### ISSUE TITLE
Download image using the cropper in modal example

### ISSUE THREAD

**Issue by Esteann** [fengyuanchen/cropper#1004]
## I'm submitting a...

<pre><code>
[- ] Feature request
</code></pre>

<pre><code>
Cropper version: v4.0.0
Browser:
- Chrome (desktop)
</code></pre>

I am trying to download an image after cropping it in the modal : 
https://github.com/fengyuanchen/cropperjs/blob/master/examples/cropper-in-modal.html

Download button code:<code><pre>
$("#download_crop").click(function () {
              var a = document.createElement('a');
              a.href = cropBoxData.toDataURL().replace("image/png", 
             "image/octet-stream");
             a.download = 'Capture.png'
             a.click();
                });
</code></pre>
But I am getting an error : <code><pre>
Error : Uncaught TypeError: cropBoxData.toDataURL is not a function
</code></pre>

**Comment by fengyuanchen** [comment]
What's the `cropBoxData`?
