### ISSUE TITLE
When I upload .png file it throw error

### ISSUE THREAD

**Issue by surajrpanchal** [fengyuanchen/cropper#1006]
When i am upload .png file it throw below error
<pre><code>
cropper.js:3271 Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at Cropper.getCroppedCanvas (file:///D:/Cropper%20image/cropper.js:3271:25)
    at HTMLButtonElement.<anonymous> (file:///D:/Cropper%20image/example.js:26:25)

<pre><code>
Cropper version: 0.8.0

</code></pre>
Browser:
- [XX] Chrome (desktop) version XX
- [XX] Edge version XX

</code></pre>

**Comment by fengyuanchen** [comment]
Why not upgrade to the latest version and try again?
