### ISSUE TITLE
Issue with Crop Area Miss Match on SET DATA

### ISSUE THREAD

**Issue by Eshwar4u** [fengyuanchen/cropper#1007]
I'm getting Issue with Crop Area Miss Match on SET DATA.

While Rotating the image in the example to 90 degrees, and zoom out to crop the shadow face of the girl. Selecting the girl's shadow face including the hat. And Now copied the GET DATA.

Released the page and paste the data in "Set data with the value" and clicked on "Set Data" it is being located on the face of the girl but not in the shadow. 

The reason might be when after reloading the page, the image is performing the zoom out operation while setting the data.

Example Data: {"x":300.63073450747316,"y":1102.2397997881947,"width":318.2800665088,"height":179.03253741120002,"rotate":90,"scaleX":1,"scaleY":1}

**Comment by fengyuanchen** [comment]
I suggest you to use both the `setCanvasData` and `setCropBoxData` method instead of `setData`.
