### ISSUE TITLE
Is it possible to set the aspect ratio for the crop box, but still allow it to be fully resizable?

### ISSUE THREAD

**Issue by onassar** [fengyuanchen/cropper#1009]
## I'm submitting a question/feature request

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[X] Documentation issue or request
</code></pre>

## Current behavior

Calling `setAspectRatio` changes the crop box dimensions, and enforces the resizing event/action to always maintain the aspect ratio.

## Expected (aka. Requested) behavior

How can I change the crop box to a specific aspect ratio, but still allow a user to resize the crop box in whatever ratio/dimensions they'd like?

## Environment
<pre><code>Cropper version: 1.4.1</code></pre>

**Comment by fengyuanchen** [comment]
Try the `initialAspectRatio` option of Cropper.js v1.4+

**Comment by cpc197c** [comment]
Hey @onassar, did you figure out a way around this? The initialAspectRatio is only settable on the initial cropper constructor. I am replacing the image and need to reset the initial aspect ratio when the user selects a file. I need this to always be free ratio, but default to the full image size and then reset to the aspect ratio when the image changes. I would greatly prefer not having to create a new cropper instance every time.

**Comment by onassar** [comment]
I unfortunately didn't. Had to adjust application logic to fit this limitation :-(

**Comment by cpc197c** [comment]
Thanks for the quick response. I've been playing around with this and I can get it to work by destroying the initial instance and creating a new one. It's ugly but works. Had to clone initial options.

Strangely that results in this (for those who may stumble on it later):
```
reader.onload = function (e) {
    cropper.destroy();
                                
    cropper = new Cropper(element, initialOptions);
    cropper.replace(e.target.result);
    $el.data('cropper', cropper);
                                
    window.setTimeout(function () {
        onCropChanged(cropper, model, viewport);
    }, 50);
};
```

**Comment by onassar** [comment]
Interesting.. yeh that could be an approach, but I was worried about destroy and re-creating multiple instances. But def a cool approach!
