### ISSUE TITLE
cropper.min.js 与 cropper.js 运行结果不一致

### ISSUE THREAD

**Issue by Barcelonao** [fengyuanchen/cropper#1013]
cropper.min.js 不是cropper.js 的压缩版本吗?

在尝试首页的demo中..如果我导入的文件是cropper.min.js 则会一直提醒我
 ```Uncaught TypeError: $image.cropper is not a function```

若是cropper.js就不会存在该问题

请问这两个文件的关系是?

**Comment by fengyuanchen** [comment]
这么多年都没遇到过这种问题，是不是你哪里弄错了？
