### ISSUE TITLE
Width always a pixel out

### ISSUE THREAD

**Issue by sambenne** [fengyuanchen/cropper#1016]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Setting the size 780 x 439 but cropped image is 779 x 439.

## Expected behavior

Should be the size that I set it to.

## What is the motivation / use case for changing the behavior?

```
$cropper.getCroppedCanvas({
                width: width,
                height: height,
                minWidth: width,
                minHeight: height,
                maxWidth: width,
                maxHeight: height,
                fillColor: '#fff',
                imageSmoothingEnabled: true,
                imageSmoothingQuality: 'high'
            })
```

## Environment

<pre><code>
Cropper version: https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.4.1/cropper.min.js

Browser:
- [x] Chrome (desktop) version 69
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by fengyuanchen** [comment]
After some transform with the image's aspect ratio, the width value `780` may become `779.99`, and after floored when cropping it will become `779` in the end. I cannot fix this in the current major version.
