### ISSUE TITLE
Save the cropped area on a local route

### ISSUE THREAD

**Issue by victorsylar** [fengyuanchen/cropper#1017]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

By clicking save pc

## Expected behavior
I require the trimmed area to be saved on a local route

## Environment

<pre><code>
Cropper version: v4.0.0

Browser:
- [x ] Chrome (desktop) version  69.0.3497.100 (Build oficial) (64 bits)
- [x ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version 62.0.3 (64-bits)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by fengyuanchen** [comment]
It seems not any browsers support your requirement at present.
