### ISSUE TITLE
Max Zoom In and Out

### ISSUE THREAD

**Issue by mpastas** [fengyuanchen/cropper#1019]
Hi guys, I'm proposing to have a maximum zoom in and out so the user experience can be enhanced. Similar to google maps zoom where the levels of zoom are restricted. 

Zoom out should be restricted so the image will fit the entire canvas of the cropper area.

**Comment by fengyuanchen** [comment]
Have you tried to control the zoom ratio with the `zoom` event?

**Comment by mpastas** [comment]
That works! thanks @fengyuanchen !
