### ISSUE TITLE
Resizing bugs

### ISSUE THREAD

**Issue by michelcve** [fengyuanchen/cropper#1020]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

There are a few problems with resizing (see provided JSFiddle):
1) When making the screen smaller, the image is not scaled down
2) When making the screen larger, the image is scaled up, but croparea doesn't size accordingly
3) When making the screen smaller then 100 pixels, and then larger again, the image gets stuck at 100 pixels (min height remains enforced, although there is ultimately more space than min height available)

Another (unrelated) observation:
- The bottom right point scales depending on screen width. Visually, I don't find that very attractive, though it seems intentional. Can you explain why this is?

## Expected behavior

Both the image, and the croparea should size according to available screen space.

## Minimal reproduction of the problem with instructions

JSFiddle: http://jsfiddle.net/michelv/31d28q5s

Step to reproduce:
- Just run the fiddle, and test the cases under 'Current behavior'

Also note that when you remove 'cropperjs' from the mix, the image scales properly.

## What is the motivation / use case for changing the behavior?

I want to use the cropper in a single page app, that can be resized.

## Environment

<pre><code>
Cropper version: 1.4.1 (latest on CDN, but also fails in 1.4.2)

Browser:
- [X] Chrome (desktop) version 68.0.3440.106
(didn't test with other browsers)
</code></pre>

**Comment by fengyuanchen** [comment]
I'm sorry. This library has been deprecated.

> PS: The bottom-right square handle is for the finger to touch, so it is bigger in small touch screen.
