### ISSUE TITLE
在微信公众号上使用,如果是安卓系统,toDataUrl和toBlob方法都不能使用怎么解决?

### ISSUE THREAD

**Issue by leesonwei** [fengyuanchen/cropper#1027]
在苹果系统打开微信公众号,使用截图都没有问题,但是再安卓下使用就一直报Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

**Comment by fengyuanchen** [comment]
图片跨域了。
