### ISSUE TITLE
Multiple Cropper Upload same time

### ISSUE THREAD

**Issue by sbabaei** [fengyuanchen/cropper#1029]
Hi, 
I have a problem with multiple cropper in same page. 
I have variable number of images and I set a cropper for each them , So I want to upload all cropped images in same time but this code does not work for me : 
`  $images.each(function(ix, ele) {
`
` var name = $(this).closest('.row').find('[data-role="inputImage"]').prop('name');`
`  $(this).cropper('getCroppedCanvas').toBlob(function (blob) {`
`   formdata.append(name, blob);`
`});`
`});`
`var xhr = new XMLHttpRequest();`
`xhr.open('POST', '@Url.Action("CreateOrUpdate", "Content", new {area = "Content"})');`
` xhr.send(formdata);`
But not any item pushing to formdata, and formdata is still empty.
I think this is related to async nature of function, How I can use this approach to upload multiple file in same time ?

**Comment by fengyuanchen** [comment]
The cropper initializing is an asynchronous process, you should call the `getCroppedCanvas` method in the `ready` hook function.
