### ISSUE TITLE
Crop box position is reset when height or width are slightly outside bounds

### ISSUE THREAD

**Issue by danielcavanagh** [fengyuanchen/cropper#1032]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

When a crop height or width is provided that scales to be slightly outside the crop box bounds (due to precision loss), the crop box is reset to the middle (despite the crop box dimensions being bound correctly)

## Expected behavior

The crop box shouldn't be reset to the middle. It should be set as closely to the original position as possible 

## Minimal reproduction of the problem with instructions

My exact test case right now is below but there are many configurations that can lead to this issue. I see it about 1 out of 5 times

True image size: 2500px × 1099px
Min crop size: 1840px × 400px
Image display size: 449.417px × 197.743px (from getImageData())

```
aspectRatio: 23 / 5
​minCropBoxWidth: 330.77091199999995 // getImageData().width * (1840 / 2500)
​minCropBoxHeight: 71.9721492265696 // getImageData().height * (400 / 1099)
data: {
  height: 87, // value is irrelevant here
  width: 400, // ditto
  x: 0, y: 0, scaleX: 1, scaleY: 1
}
```

In [renderCropBox()](https://github.com/fengyuanchen/cropperjs/blob/21e14eacd1a6873b12eb23eab3ac7dd5a881df21/src/js/render.js#L437), the crop box width is determined to be slightly too large and so top is strangely reset to the middle. This is despite both the width/height and top/left being correctly rebound using min(max())

## What is the motivation / use case for changing the behavior?

If scaling imprecision leads to slightly off values, the crop should still maintain it's original position, or as close as possible. This leads to perfectly valid crops being removed through no fault of the user or developer

## Solution

Please remove [the checks](https://github.com/fengyuanchen/cropperjs/blob/21e14eacd1a6873b12eb23eab3ac7dd5a881df21/src/js/render.js#L437) entirely. I can't see how they are at all useful for any situation

I would appreciate it if you could apply the patch to v3 too, as I'm using cropperjs through a separate package and don't have much time right now to upgrade that to the new API (nor do I think the maintainers would want to)

If you need me to do the work and submit a pull request, let me know

Cheers :)

## Environment

<pre><code>
Cropper version: All (3.1.6, 4.0.0)

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 64.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
macOS 10.14.2
</code></pre>

**Comment by fengyuanchen** [comment]
In short, `data` = `canvasData` + `cropBoxData`, so you cannot use `minCropBoxWidth/Height` to limit `data`.

**Comment by danielcavanagh** [comment]
I have no idea what you are talking about, sorry. Can you please explain?

**Comment by fengyuanchen** [comment]
The size of the crop box is limited when the `viewMode` option value is greater than `0`.

> Spec: https://github.com/fengyuanchen/cropperjs#viewmode

**Comment by fengyuanchen** [comment]
You should not use the `data` option to restore the `cropBoxData`, you should use the `setCropBoxData` method.

> Demo: https://github.com/fengyuanchen/cropperjs/blob/master/examples/cropper-in-modal.html

**Comment by danielcavanagh** [comment]
Ok, I have tested `setCropBoxData()` and the problem persists. Please reopen this issue

Image size: 5616px × 3744px
Min crop box size: 1840px × 400px

The cropper is initialised with these options:

```json
{
  "autoCropArea": 1,
  "background": false,
  "responsive": false,
  "viewMode": 1,
  "zoomable": false,
  "minContainerHeight": 133.33333333333334,
  "autoCrop": true,
  "aspectRatio": 4.6
}
```

Canvas data ends up being:

```json
{
  "left": 0,
  "top": 26.998576250000013,
  "width": 449.417,
  "height": 299.9858475,
  "naturalWidth": 400,
  "naturalHeight": 267
}
```

And image data:

```json
{
  "width": 449.417,
  "height": 97.69934782608696,
  "minWidth": 0,
  "minHeight": 0,
  "maxWidth": 449.417,
  "maxHeight": 97.69934782608696,
  "minLeft": 0,
  "minTop": 26.998576250000013,
  "maxLeft": 0,
  "maxTop": 229.28507592391304,
  "left": 0,
  "top": 128.1418260869565,
  "oldLeft": 0,
  "oldTop": 128.1418260869565
}
```

I wait for 'ready' to trigger, then set the min crop box size and restore the crop box data:

````javascript
img.on('ready', function () {
  // Set min crop box size
  var imageData = cropper.getImageData();
  cropper.options.minCropBoxWidth = imageData.width * (1840 / 5616); // = 147.24488603988604
  cropper.options.minCropBoxHeight = imageData.height * (400 / 3744); // = 32.04977003205128
  cropper.limitCropBox(true, false);

  // Restore crop box data from image-based pixel data
  // To trigger the bug, I use a max width and height
  var canvasData = cropper.getCanvasData();
  var delta = 3744 / canvasData.height; // = 12.48058877177531
  cropper.setCropBoxData({
    width: 5616 / delta, // = 449.97877124999997
    height: Math.round(5616 / 4.6) / delta + canvasData.top, // = 97.83192302283653
    left: 0 + canvasData.left,
    top: 0 + canvasData.top,
  });
});
```

After this has run, the crop box has max width and height as it should, but it's position has been reset to the middle

The crop box is not restored correctly due to [these checks on height and width](https://github.com/fengyuanchen/cropperjs/blob/21e14eacd1a6873b12eb23eab3ac7dd5a881df21/src/js/render.js#L437). I'm not sure why it changes the crop box position when it's the height/width that fail the checks, and especially when the code goes on to the bind the position (using min+max) to the crop box area anyway

Please consider removing these and instead let the binds normalise the data

Cheers!

**Comment by danielcavanagh** [comment]
If anyone else runs into this, for now I've extracted the max width/height calculation from cropper.js and using those the manually bind

```javascript
      var containerData = cropper.getContainerData();
      var canvasData = cropper.getCanvasData();
      var limited = cropper.options.viewMode === 1 || cropper.options.viewMode === 2;
      var maxCropBoxWidth = Math.min(containerData.width, limited ? canvasData.width : containerData.width);
      var maxCropBoxHeight = Math.min(containerData.height, limited ? canvasData.height : containerData.height);
      if (this.ratio) {
        if (maxCropBoxHeight * this.ratio > maxCropBoxWidth) {
          maxCropBoxHeight = maxCropBoxWidth / this.ratio;
        } else {
          maxCropBoxWidth = maxCropBoxHeight * this.ratio;
        }
      }
```

**Comment by danielcavanagh** [comment]
Can you please reopen this issue?

**Comment by njakobsen** [comment]
I have the exact same problem

**Comment by felipemuve** [comment]
I had the same issue. I fixed it subtracting one to the rounded width and height the cropper returns in the crop function parameter object:

`		   	cropImage = $('#cropImage').cropper({
		   		autoCrop: true,
		   		viewMode:1,
		  		  aspectRatio: rate,
		  		  crop: function(e) {
		  		    // Output the result data for cropping image.
		  		    yourMethodToSendToServer(Math.round(e.width-1),
                                    Math.round(e.height-1), Math.round(e.x), Math.round(e.y)) ;
		  		  },
		  		  data: newCoords, //New Coords is the server data
		  		  zoomOnWheel : false,
		  		  scalable : false
	  		});`

**Comment by Arnold-zz** [comment]
Me too and i am using setCropBoxData().
Would you mind reopening this issue?

**Comment by fabianendres** [comment]
Same here. The cropbox is always being set with left:0, top:0.137 when cropping an image with 3508x2340 pixels and aspect ratio 1,5. Expecdted left:0, top:0 when using setData() with {name: "3:2", x: 0, y: 0, width: 3508, height: 2340, …}
Would be very appreciated when you could reopen the issue.

**Comment by njakobsen** [comment]
After a deep dive, I traced my issue to the default `containerData` width and height, so this may not be exactly the same problem as the OP. In my case, I'm asking for a thumbnail url without actually rendering the cropper in the DOM. This causes the containerData to just assume a height and width https://github.com/fengyuanchen/cropperjs/blob/8fa586fd931fee9aca05451e646270bef3f6cbaf/dist/cropper.js#L1169, which ends up causing the cropbox to be repositioned https://github.com/fengyuanchen/cropperjs/blob/8fa586fd931fee9aca05451e646270bef3f6cbaf/dist/cropper.js#L1212. This only happens when an aspect ratio is provided.
