### ISSUE TITLE
How to keep the cropped size on getCroppedCanvas

### ISSUE THREAD

**Issue by zecar** [fengyuanchen/cropper#1034]
Context:

I have images 600x450 with a product in the middle and some text under product image

I'm trying to get a 500x500 image of the product without the text. So I try to crop just the product and the finished result I want it to be a 500x500 image with the cropped area exactly where it was, and the rest of the space filled with white color.

Right now when I call getCroppedCanvas i get a canvas with one side of 500px (the larger side of the cropped area) and the cropped image zoomed in to fill the canvas

my code is this:

```js
new Cropper(this.$refs.croppie, {
	viewMode: 0,
	background: true,
	minContainerWidth: 500,
	minContainerHeight: 500,
	zoomable: false,
	movable: false
})


// calling method
this.$options.cropper.getCroppedCanvas({
	width: 500,
	height: 500,
	fillColor: 'red'
})
```

**Comment by fengyuanchen** [comment]
Just set the `aspectRatio` option to `1`.

**Comment by zecar** [comment]
you did not understand my problem. aspect ratio 1 makes the cropbox to be square. I need it free to be able to put just the product in the crop area

**Comment by fengyuanchen** [comment]
Not support your requirement. Please try another tool.

**Comment by demogorgorn** [comment]
zecar, if i understand correctly your situation, do the following - crop with the sizes given from cropper (after zoom and crop), and then resize with you desidered, save.
