### ISSUE TITLE
Feature Request: Crop 2 images(background-image and image) into a single output image.

### ISSUE THREAD

**Issue by svenkatesh-nyros** [fengyuanchen/cropper#1036]
Is it possible to provide the source image in a existing background image to crop them into single image using this package.
following is the example working urls for making this feature.

http://subinsb.com/create-profile-picture-framer-web-app/

Git url: https://github.com/subins2000/profile-picture-framer

can this feature implemented in your package ?

**Comment by fengyuanchen** [comment]
Would not support this.

**Comment by fengyuanchen** [comment]
You can draw the front image into the background image with the Canvas API.
