### ISSUE TITLE
Height issue on vertical pictures

### ISSUE THREAD

**Issue by edechezelles** [fengyuanchen/cropper#1038]
Hello,

First of all, thanks to the creators for their work, and sorry if this issue has already been raised.

We use the cropper on our website Chien.com, in order to allow users to post pictures of their dogs:
https://www.chien.com/photos-chiens/ajouter-une-photo.php

Yet, if you upload a vertical picture such as the one below, the cropper window's height is too big, so basically you can't crop the picture and go on:

No problem:
(source file)
![no problem](https://user-images.githubusercontent.com/47171688/52171353-e1e97400-279e-11e9-81ce-397b78dcd86f.jpg)
(screenshot)
![no problem screenshot](https://user-images.githubusercontent.com/47171688/52171356-e6ae2800-279e-11e9-9dee-64e2f3e6ce18.png)

Problem:
(source file)
![problem](https://user-images.githubusercontent.com/47171688/52171359-f594da80-279e-11e9-821b-37b6cebe93f2.jpg)
(screenshot)
![problem screenshot](https://user-images.githubusercontent.com/47171688/52171358-f3cb1700-279e-11e9-8158-51f53316f85a.png)

I've spent hours and hours trying to find out, I'm a bit in despair...

We use an old version but we tried switching to version 4.0.0, and the problem remained.

Thank you for your valuable help,

Emmanuel

**Comment by bilihili** [comment]
maybe you can set the max-width=100%

**Comment by fengyuanchen** [comment]
```css
/* Limit image width to avoid overflow the container */
img {
  max-width: 100%; /* This rule is very important, please do not ignore this! */
}
```

**Comment by danly-liao** [comment]
#1038
