### ISSUE TITLE
when i use wechat api chose img,cropper does not work  without any error.

### ISSUE THREAD

**Issue by flysunshine** [fengyuanchen/cropper#1041]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report 
- [x] Feature request
- [x] Documentation issue or request

## Current behavior
first of all thanks for the work!
I am using WeChat API like "wx.chooseImage",the detail is following
wx.chooseImage({
count: 1, 
sizeType: ['original', 'compressed'], // 可以指定是原图还是压缩图，默认二者都有
sourceType: ['album', 'camera'], // 可以指定来源是相册还是相机，默认二者都有
success: function (res) {
var localIds = res.localIds; // 返回选定照片的本地ID列表，localId可以作为img标签的src属性显示图片
}
}); 
 I use the localIds for the cropper img, it can show in the canvas,but cropper does not show,and the canvas can not be zoomed.I have no idea what is happening. wechat give me a localId for which i can show the picture. the localId is something like 'wexin://resourceid/********(numbers)'. I guess maybe it's form doex not be supported.can you explain that ? thanks very much!

## Expected behavior
normally it should like this,it has cropper box and can zoom the image.
![image](https://user-images.githubusercontent.com/22189516/56468104-24dfed00-645a-11e9-8340-abb3db7e1ef3.png)
but now it has no cropper box and can not be cropped and zoomed
![image](https://user-images.githubusercontent.com/22189516/56468122-607ab700-645a-11e9-9946-9142c40d80e4.png)

## Environment

Cropper version: 1.5.1

### Browser:

- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by urnotzane** [comment]
me too

**Comment by flysunshine** [comment]
> me too

use wx.getLocalImgData can solve the problem. turns out that cropper has no relation with this issue
