### ISSUE TITLE
checkered background with pure css

### ISSUE THREAD

**Issue by kapouer** [fengyuanchen/cropper#1045]
Hi !
Instead of:
```
url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAAA3NCSVQICAjb4U/gAAAABlBMVEXMzMz////TjRV2AAAACXBIWXMAAArrAAAK6wGCiw1aAAAAHHRFWHRTb2Z0d2FyZQBBZG9iZSBGaXJld29ya3MgQ1M26LyyjAAAABFJREFUCJlj+M/AgBVhF/0PAH6/D/HkDxOGAAAAAElFTkSuQmCC')
```
one can do:
```
background-image: linear-gradient(45deg, #333 25%, transparent 25%), linear-gradient(-45deg, #333 25%, transparent 0), linear-gradient(45deg, transparent 75%, #333 75%), linear-gradient(-45deg, transparent 75%, #333 75%);
background-size: 14px 14px;
background-position: 0 0, 0 7px, 7px -7px, -7px 0px;
background-color: black;
```
or something similar (sorry i did not manage to get the same result, go figure).
*edit* that one now looks the same.

**Comment by amirgee007** [comment]
$("#imagen").croppie('result', { type: 'canvas',format :'jpeg', backgroundColor:'white'}).then(function(resp){ //--- your code })

**Comment by amirgee007** [comment]
$('#cropImageBtn').on('click', function(ev) {
    $uploadLogoCrop.croppie('result', {
        type: 'base64',
        format: 'jpeg',
        backgroundColor:'white',
        size: {width: 300, height: 300}
    }).then(function(resp) {
        $('#image_logo').val(resp);
        $('#item-img-output').attr('src', resp);
        $('#cropImagePop').modal('hide');
    });
});

**Comment by fengyuanchen** [comment]
@kapouer I know that solution, but `linear-gradient` is not supported in IE 9, but Cropper supports IE 9 currently. I may improve this in the next major version.
