### ISSUE TITLE
how to re-initialize cropper?

### ISSUE THREAD

**Issue by P-PATHAK** [fengyuanchen/cropper#1046]
How can I re-initialize cropper if I dynamically include a path to cropper.js with <script> .
Currently i am using this  **cropper = new Cropper(image, {**  for croping

**Comment by fengyuanchen** [comment]
Just destroy the old one and initialize a new one.

```js
// ...
cropper.destroy();
// ...
cropper = new Cropper(image, {});
// ...
```
