### ISSUE TITLE
manually set width and height  on input tag

### ISSUE THREAD

**Issue by richdenis86** [fengyuanchen/cropper#1047]
![Screenshot_1](https://user-images.githubusercontent.com/38884897/61182819-7d7deb00-a641-11e9-8d33-0d24370d95e6.png)

How to do that when entering the size of the height or width, set selection manually in the box
or by pressed enter something like this

**Comment by oskvortsov** [comment]
@richdenis86 Hello. Today I did the same task, I used the method "setData"

**Comment by richdenis86** [comment]
> @richdenis86 Hello. Today I did the same task, I used the method "setData"

I tried but I did not succeed, can you please explain how you did it? or show code snippet?

**Comment by richdenis86** [comment]
<input type="text" class="form-control" onchange="setData()"  data-method="setData" id="dataHeight" placeholder="height"> 
something, like this doesnt work :(

**Comment by oskvortsov** [comment]
@richdenis86 
`
const setFieldValue = (name, event) => {
    const value = parseFloat(event.target.value);

    if (cropper() && !isNaN(value)) {
      cropper().setData({
        ...cropper().getData(),
        ...{ [name]: value }
      });
    }
  };

<Input
                  value={cropData.width}
                  type="number"
                  onChange={value => setFieldValue("width", value)}
                />
`

**Comment by richdenis86** [comment]
may be i dont't  understand or something wrong? it doesnt work, can you send me html files pls? its very important, richdenis86@gmail.com

**Comment by oskvortsov** [comment]
@richdenis86 You can see [cropper with input](https://codesandbox.io/embed/stoic-neumann-od45c?fontsize=14)

**Comment by richdenis86** [comment]
big thank you bro, but when i 'm  transfer this code to the html page , getiing error Uncaught TypeError: $image.cropper is not a function, 
https://codepen.io/richdenis86/pen/LwZEOZ
 i installed it without npm

![Screenshot_2](https://user-images.githubusercontent.com/38884897/61821007-e5f97300-ae5e-11e9-8b6c-cb98d901d4ba.png)

**Comment by richdenis86** [comment]
solved,and finally its worked! thank you @oskvortsov !!! :)
