### ISSUE TITLE
I want crop image in different shape

### ISSUE THREAD

**Issue by rajdoshi9089** [fengyuanchen/cropper#1055]
Hi

I want to crop an image in different shapes like a pentagon, Heart shapes. Is it Possible?

**Comment by fengyuanchen** [comment]
Not support that！😂

**Comment by rajdoshi9089** [comment]
Do you have any idea for this if I want to make?

**Comment by fengyuanchen** [comment]
Here is an example of cropping a round image: https://fengyuanchen.github.io/cropperjs/examples/crop-a-round-image.html
