### ISSUE TITLE
image scrolling horizontally inside canvas container on mobile screen

### ISSUE THREAD

**Issue by MrShaikh01** [fengyuanchen/cropper#1057]
Hi need help in achieving below point.

In mobile screen lets say 360 width, my image is scrolling horizontally inside canvas container, can you help how to fit the image inside canvas container for mobile screens. For Desktop it is working properly.

In the below shared image i can scroll the image horizontally but i want it to be fit with the container.

Thanks in advance.

![mobile-screen](https://user-images.githubusercontent.com/36665887/65014802-5394bd80-d93d-11e9-9e19-065889294358.png)

**Comment by fengyuanchen** [comment]
I have not idea on this. Help yourself.
