### ISSUE TITLE
How to remove image before in canvas inside modal ?

### ISSUE THREAD

**Issue by mhendylazuardi** [fengyuanchen/cropper#1059]
i write in stackoverflow

here is the detail...

https://stackoverflow.com/questions/58212098/how-to-remove-image-on-canvas-cropper-when-you-want-change-the-image

https://youtu.be/8-dgUahd5sM
video ^

**Comment by fengyuanchen** [comment]
Maybe you are binding these events too many times. Try to use `$().once()` instead of `$().on()`.
