### ISSUE TITLE
Range for aspectRatio

### ISSUE THREAD

**Issue by eugene-g13** [fengyuanchen/cropper#1062]
First of all, thank you for great cropper!

My problem is I need cropper box have maximum and minimum constraints. Sides have to be  from 1/1 to 1/2.5 (from square to rectangle with sides 1/2.5)

I need fast solution now and good solution after)
Good solution is to have properties like aspectRatioFrom and aspectRatioTo, for example.
And now I try to event.preventDefault() in cropstart event, but I do not see width and height in event details.

I use react-cropper.

Do you have good idea?

**Comment by fengyuanchen** [comment]
https://fengyuanchen.github.io/cropperjs/examples/a-range-of-aspect-ratio.html
