### ISSUE TITLE
在个别安卓手机截图偶尔异常的问题

### ISSUE THREAD

**Issue by mwx245894** [fengyuanchen/cropper#1063]
**Describe the bug**
我的页面是在微信里访问的，在浏览器里使用都正常，只有在微信里才会出现我描述的问题，在苹果手机里截图都正常，在大部分安卓手机也没问题，当使用华为P30和三星S10截图时，偶尔会出现截图是透明图片或者纯白色图片的问题，

**To Reproduce**
完全没有规律

不知道如何解决这个问题，请问有何建议！！

**Comment by fengyuanchen** [comment]
图片如果太大，就会超出浏览器内存限制，返回空白。建议限制图片大小，或上传压缩后在裁切。
