### ISSUE TITLE
Wrong cutting position

### ISSUE THREAD

**Issue by ThissMy** [fengyuanchen/cropper#1064]
**Describe the bug**
Pixel is 1080X1440 image. When cutting, zoom the picture, drag the clipping box and move the picture. Finally, determine that the clipped image is not the desired position, but after rotating 90 degrees, repeat the above operation to achieve its purpose.

![cropper](https://user-images.githubusercontent.com/19523056/66727921-9f6f4f80-ee74-11e9-9e21-36da601c359a.jpg)
![cropperpic](https://user-images.githubusercontent.com/19523056/66727967-e65d4500-ee74-11e9-916a-4ed342ba3a41.jpg)
The final cut was not the cat, but the white cylinder next to it.

**Comment by ThissMy** [comment]
fail:
![cropperfail](https://user-images.githubusercontent.com/19523056/66728271-6fc14700-ee76-11e9-96ab-e92d8ffb0c65.jpg)

success:
![croppersuc](https://user-images.githubusercontent.com/19523056/66728272-6fc14700-ee76-11e9-9dd2-90c54b671adc.jpg)
![croppersucs](https://user-images.githubusercontent.com/19523056/66728273-7059dd80-ee76-11e9-8f9d-8b7c34deab4c.jpg)

**Comment by fengyuanchen** [comment]
I don't understand what you are meaning exactly...
