### ISSUE TITLE
文件加载不完整，等了很久还是这样

### ISSUE THREAD

**Issue by luckychenxy** [fengyuanchen/cropper#1067]
![8b68146a269c1d157b49f4e25ff4f27](https://user-images.githubusercontent.com/34885759/68557947-67a6f800-0472-11ea-8df0-02f613fb30f1.jpg)

**Comment by fengyuanchen** [comment]
系统版本？浏览器版本？Cropper 版本？一点信息都不给，我也不是神仙啊。
