### ISSUE TITLE
请问用在移动端可以很好的使用吗？

### ISSUE THREAD

**Issue by MuJinyo** [fengyuanchen/cropper#1069]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dimsco** [comment]
Hi,
More thanks for your mail; this is auto replay from DIMS deco website www.dims.ir .
Your message has been sent. 
You will receive a response as soon as possible.
Best  regard . 
DIMS.


Persian " 
سلام
ضمن تشکر از ایمل ارسالی شما . این یک پیغام اتوماتیک از طریق سایت ما میباشد . 
ایمیل شما رسید و بزودی به شما پاسخ داده خواهد شد.
با تشکر 
دایمس
"

**Comment by fengyuanchen** [comment]
应该可以。
