### ISSUE TITLE
Após cortar imagem, mandar ela para um input que está dentro de um form para enviar a imagem para o banco de dados

### ISSUE THREAD

**Issue by robson-danilo** [fengyuanchen/cropper#1070]
Eu queria que ao usuário clicar no botão escolher arquivo ele ia escolher a imagem logo após iria aparecer uma label que iria dar a opção a ele parecer redimensionar a imagem do jeito que ele, depois iria apertar um botão confirmar ai a imagem que ele editou iria para o input para poder ser enviado ao controller e de lá fazer o tratamento da imagem e mandar para o banco de dados, eu consegui fazer com que ele escolhe-se a imagem e envia ela para o banco de dados e está funcionando ele substitui a antiga, mas eu queria dar a opção ao usuário editar ela antes de enviar, se puderem me ajudar agradeço, to a 2 semanas com esse problema.

Segue o Código

---------------------------------------------------------------------------------------------------------

<?php
defined("BASEPATH") or exit("No direct script access allowed");
//print_r($id_contato);exit;
?>
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<title>Testando</title>

	<link href="/template/2.0/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
	<link href="/template/2.0/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="/template/2.0/vendors/cropper/dist/cropper.min.css" rel="stylesheet">
	<link href="/template/2.0/build/css/custom.min.css" rel="stylesheet">

	
	
	

</head>

<script src="/template/2.0/vendors/jquery/dist/jquery.min.js"></script>
<script src="/template/2.0/vendors/jquery/dist/jquery.js"></script>

<script src="/template/2.0/vendors/bootstrap/dist/js/bootstrap.min.js"></script>

<script src="/template/2.0/vendors/cropper/dist/cropper.min.js"></script>

<script src="/template/2.0/build/js/custom.min.js"></script>

<body>

	<form action="inserir" method="post">

		<input class="form-control" id="logoLab" name="logoLab" type="file" accept=".gif,.jpg,.png">
		
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#LogoModal">
			Logo Lab
		</button>

		
		<div class="modal fade" id="LogoModal" tabindex="-1" role="dialog" aria-labelledby="TituloModalCentralizado" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="TituloModalCentralizado">Testando</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">

						
						
						<div class="container cropper">
							<div class="col-md-9">
								<div class="col-md-5">
									<div class="img-container-md-5">
										<img id="image">
									</div> 
								</div>
								<div class="col-md-9">
									<div class="docs-preview clearfix">
										<div class="img-preview preview-lg"></div>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-9 docs-buttons">
									
									<div class="btn-group">
										<button type="button" class="btn btn-primary" data-method="setDragMode" data-option="Mover" title="Move">
											<span class="docs-tooltip" data-toggle="tooltip" title="Mover Imagem">
												<span class="fa fa-arrows"></span>
											</span>
										</button>
										<button type="button" class="btn btn-primary" data-method="setDragMode" data-option="Selecionar Corte" title="Crop">
											<span class="docs-tooltip" data-toggle="tooltip" title="Selecionar Área a ser Cortada">
												<span class="fa fa-crop"></span>
											</span>
										</button>
									</div>

									<div class="btn-group">
										<button type="button" class="btn btn-primary" data-method="zoom" data-option="0.1" title="Aumentar o Zoom">
											<span class="docs-tooltip" data-toggle="tooltip" title="Aumentar o Zoom">
												<span class="fa fa-search-plus"></span>
											</span>
										</button>
										<button type="button" class="btn btn-primary" data-method="zoom" data-option="-0.1" title="Reduzir o zoom">
											<span class="docs-tooltip" data-toggle="tooltip" title="Reduzir o zoom">
												<span class="fa fa-search-minus"></span>
											</span>
										</button>
									</div>

									<div class="btn-group">
										<button type="button" class="btn btn-primary" data-method="move" data-option="-10" data-second-option="0" title="Mover para a Esquerda">
											<span class="docs-tooltip" data-toggle="tooltip" title="Mover para a Esquerda">
												<span class="fa fa-arrow-left"></span>
											</span>
										</button>
										<button type="button" class="btn btn-primary" data-method="move" data-option="10" data-second-option="0" title="Mover para a Direita">
											<span class="docs-tooltip" data-toggle="tooltip" title="Mover para a Direita">
												<span class="fa fa-arrow-right"></span>
											</span>
										</button>
										<button type="button" class="btn btn-primary" data-method="move" data-option="0" data-second-option="-10" title="Mover para cima">
											<span class="docs-tooltip" data-toggle="tooltip" title="Mover para cima">
												<span class="fa fa-arrow-up"></span>
											</span>
										</button>
										<button type="button" class="btn btn-primary" data-method="move" data-option="0" data-second-option="10" title="Mover para baixo">
											<span class="docs-tooltip" data-toggle="tooltip" title="Mover para baixo">
												<span class="fa fa-arrow-down"></span>
											</span>
										</button>
									</div>

									<div class="btn-group">
										<button type="button" class="btn btn-primary" data-method="rotate" data-option="-45" title="Rotação a Esquerda">
											<span class="docs-tooltip" data-toggle="tooltip" title="Rotação a Esquerda">
												<span class="fa fa-rotate-left"></span>
											</span>
										</button>
										<button type="button" class="btn btn-primary" data-method="rotate" data-option="45" title="Rotação a Direita">
											<span class="docs-tooltip" data-toggle="tooltip" title="Rotação a Direita">
												<span class="fa fa-rotate-right"></span>
											</span>
										</button>
									</div>

									<div class="btn-group">
										<button type="button" class="btn btn-primary" data-method="scaleX" data-option="-1" title="Virar na Horizontal">
											<span class="docs-tooltip" data-toggle="tooltip" title="Virar na Horizontal">
												<span class="fa fa-arrows-h"></span>
											</span>
										</button>
										<button type="button" class="btn btn-primary" data-method="scaleY" data-option="-1" title="Virar na Vertical">
											<span class="docs-tooltip" data-toggle="tooltip" title="Virar na Vertical">
												<span class="fa fa-arrows-v"></span>
											</span>
										</button>
									</div>

									<div class="btn-group">
										<button type="button" class="btn btn-primary" data-method="crop" title="Cortar">
											<span class="docs-tooltip" data-toggle="tooltip" title="Cortar">
												<span class="fa fa-check"></span>
											</span>
										</button>
										<button type="button" class="btn btn-primary" data-method="clear" title="Limpar">
											<span class="docs-tooltip" data-toggle="tooltip" title="Limpar">
												<span class="fa fa-remove"></span>
											</span>
										</button>
									</div>

									<div class="btn-group">
										<label class="btn btn-primary btn-upload" for="inputImage" title="Upload image file">
											Upload da imagem
											<input type="file" class="sr-only" id="inputImage" name="inputImage" accept=".gif,.jpg,.png">
											<span class="docs-tooltip" data-toggle="tooltip" title="Upload imagem">
												<span class="fa fa-upload"></span>
											</span>
										</label>
									</div>

									<div class="btn-group btn-group-crop">
										<button type="button" class="btn btn-primary" data-method="getCroppedCanvas">
											<span class="docs-tooltip" data-toggle="tooltip" title="Recortar">
												Cortar e salvar imagem
											</span>
										</div>

										
										<div class="modal fade docs-cropped" id="getCroppedCanvasModal" aria-hidden="true" aria-labelledby="getCroppedCanvasTitle" role="dialog" tabindex="-1">
											<div class="modal-dialog">
												<div class="modal-content">
													<div class="modal-header">
														<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
														<h4 class="modal-title" id="getCroppedCanvasTitle">Imagem Editada</h4>
													</div>
													<div class="modal-body"></div>
													<div class="modal-footer">
														<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
														<a class="btn btn-primary" id="download" href="javascript:void(0);" download="Imagem-Editada.png">Download</a>
													</div>
												</div>
											</div>
										</div>
									</div>	
								</div>
							</div>

							

						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
							<button type="button" class="btn btn-primary">Salvar mudanças</button>
						</div>
					</div>
				</div>
			</div>   

			<div class="form-group">
				<div class="col-lg-offset-2 col-lg-2">
					<input class="btn btn-success" name="commit" value="Salvar" type="submit">
				</div>
			</div>
		</form>

	</body>

	</html>

---------------------------------------------------------------------------------------------------------

**Comment by fengyuanchen** [comment]
Please say English! And:
- [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html).
- [提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/)。
