### ISSUE TITLE
Can you add/remove an image element to cropper object?

### ISSUE THREAD

**Issue by aaflatooni** [fengyuanchen/cropper#1083]
We would like to be able to add an icon to an image element and also be able to remove it. 
I have seen documentations on multiple images but there doesn't seem to be any support for images to be added to the same cropper object and elements removed.

I am just wondering if I missed any documentations. Can someone please confirm if it is possible?

We want to be able to do something like this:

![image](https://user-images.githubusercontent.com/42128476/84680301-7241d800-af00-11ea-912f-3ffdc84ab7ae.png)

**Comment by fengyuanchen** [comment]
NOT support that. This is just a simple image cropper, not a full-featured image editor. I'm sorry.
