### ISSUE TITLE
Cropper container width and height is not equal canvas width and height 

### ISSUE THREAD

**Issue by anishjana** [fengyuanchen/cropper#1088]
![image](https://user-images.githubusercontent.com/52600343/88509707-4a658a00-cfff-11ea-999a-515a9f28edac.png)

I am creating cropper on top of a canvas whose width and height is 500 and 225 resp but the cropper container width and height is 200 and 100 respectively (image attached for ref)

![image](https://user-images.githubusercontent.com/52600343/88509873-9b757e00-cfff-11ea-8a57-92fecd9723c3.png)

Below is the initialisation:
```
var cropper = new Cropper(cropper_canvas, {
    background: false,
    aspectRatio: cropper_ratio,
    viewMode: 1,
    dragMode: "move",
    responsive: true,
    cropBoxResizable: true,
    toggleDragModeOnDblclick: false,
    rounded: true
  });
```

**Comment by fengyuanchen** [comment]
You should set size on the parent element:

```css
#crop-container {
  width: 500px;
  height: 400px;
}
```
