### ISSUE TITLE
Default values for cropper with fixed crop-box.

### ISSUE THREAD

**Issue by felixzapata** [fengyuanchen/cropper#114]
Hi, first of all, thanks for this plugin. When you use the cropper with fixed crop, can you pass default values for the image under the cropper. 

For example, I show a fix crop with an image, the users set the values for the crop (I save this values), then, when the user edit again the image, I load the image with the values that previously the user has choosen.  

I´ve seen the preview function inside your code where the image changes their margin left and top properties. But I´m not sure if this feature is in the plugin and I don´t know how to use, or maybe does not exist.

Thanks.

Thanks.

**Comment by asifjaveduk** [comment]
Hi, did you add this functionality?

**Comment by felixzapata** [comment]
hi @asifjaveduk, sorry but I did not do it.
