### ISSUE TITLE
`crossOrigin` attribute breaks functionality on non-standard ports

### ISSUE THREAD

**Issue by nchase** [fengyuanchen/cropper#119]
If I'm running a web server locally on port 3000 (or any port other than 80), and try to use cropper with an image from the web, cropper generates a 'Cross-Origin Resource Sharing policy' error. 

If I remove [the `crossOrigin` attribute code on L152](https://github.com/fengyuanchen/cropper/blob/master/src/cropper.js#L152), this error doesn't happen and the image gets appended appropriately.

Can we make the `crossOrigin` attribute optional?

**Comment by lalaBao** [comment]
It is a cross-domain image, and I need use canvas method : getDataURL ,what should I do?
