### ISSUE TITLE
Image rotation results in gray area (Chrome)

### ISSUE THREAD

**Issue by sdvg** [fengyuanchen/cropper#124]
When I use a photo taken with an iPhone and rotate it two times i get a gray area:

![2014-12-05 14-34-35](https://cloud.githubusercontent.com/assets/971072/5316447/e8f82542-7c8b-11e4-889b-65c70f00023d.jpg)

Steps to reproduce:
1. Open my [demo-page] (http://www.googledrive.com/host/0BxToYWS0fw4cSHpNZ0s3dzFYSUk/cropper-master/demos/) (I just replaced the image) in Google Chrome
2. Click "Rotate Right" twice

**Comment by fengyuanchen** [comment]
Now we use CSS3 transform3d for rotating. You can try it again.

**Comment by sdvg** [comment]
Now it works great, thank you!
