### ISSUE TITLE
Crop square displays incorrectly

### ISSUE THREAD

**Issue by zoner14** [fengyuanchen/cropper#126]
This image really tells the entire story:

![screen shot 2014-12-05 at 8 47 29 pm](https://cloud.githubusercontent.com/assets/1634953/5325667/6fd12bf2-7cc0-11e4-9913-27fdc40182aa.png)

Look at the lines of the statue and how they get distorted where the crop box is. All I did was initialize a cropper window with an aspectRatio of 1 and default settings. I'm using Chrome 39 and am able to reproduce this issue with multiple images.

**Comment by rhill45** [comment]
@zoner14  are you zooming what's inside the cropper inadvertently with a mouse wheel or a touch pad?

**Comment by zoner14** [comment]
The zoomable attribute is actually disabled on my cropper instance. I am still able to reproduce this issue in v0.7.7. 

Even though the image inside the cropper is incorrect, the client still uploads the correct image to the server; that is, it uploads what would have appeared inside the cropper had it been displaying the correct part of the image.

**Comment by fengyuanchen** [comment]
This is the same issue as #120, so I have to close this now.
