### ISSUE TITLE
zoomDelta misbehaving in FF

### ISSUE THREAD

**Issue by MonteShaffer** [fengyuanchen/cropper#128]
It appears on FF, the zoomDelta is 0.1 not 10%

behaves as expected in IE, Chrome

Ideally, it would be nice to set the zoomDelta as a potential option ... I don't know what the browser deltas are doing ...

######

wheel: function (event) {
      var e = event.originalEvent,
          msDeltaY = 117.25, // IE
          mozDelatY = 5, // Firefox
          webkitDelatY = 166.66665649414062, // Chrome, Opera
          zoomDelta = 0.1, // 10%
          delta;

      if (this.disabled) {
        return;
      }

**Comment by fengyuanchen** [comment]
I had improved this, you may try the [v0.7.8](https://github.com/fengyuanchen/cropper/releases/tag/v0.7.8) now.
