### ISSUE TITLE
slow rotation

### ISSUE THREAD

**Issue by MonteShaffer** [fengyuanchen/cropper#129]
I see the note about the slow rotation, and I am wondering why you do use CSS to rotate the image (without canvas)... I am trying to implement this on very large images, and in the viewing window/preview, I don't care that the actual image rotated, I just need to know the coordinates to I can rotate and crop on the SERVER side, which will be much more efficient.

Font Awesome does this, with a class extension as follows:

.fa-rotate-45 {
    -webkit-transform: rotate(45deg);
    -moz-transform: rotate(45deg);
    -ms-transform: rotate(45deg);
    -o-transform: rotate(45deg);
    transform: rotate(45deg);
}

Your preview could rotate the background this amount and place inside a square container, so it appears rotated, but it is not.

Anyway, Nice work.  I wouldn't be providing feedback if I didn't think your design/architecture were ADMIRABLE.

### 

In this scenario, you obviously couldn't get the dataURI since it wouldn't be available, but it would allow for "preview cropping/rotation" that could be implemented on the backend using gdlib or imagemagick

**Comment by aronica** [comment]
Rotate is still very slow with canvas, and i also found it's much faster with css3 transform, i'm new to canvas, when is it to use canvas and when is it to use css3 ?

**Comment by ppoo24** [comment]
@fengyuanchen Saw in the DarkroomJS, it use <canvas> instead of <img> to play with picture, according to @przerull , may changing to an canvas based rotation(also showing image with <canvas>) will solve this slowing

**Comment by fengyuanchen** [comment]
I'll use CSS3 Transform3d (again) for rotation in the next minor version. Thank you all~

**Comment by ryanannatuvasquez** [comment]
@fengyuanchen When is your minor version will be release referring to using CSS3 in rotate?

**Comment by fengyuanchen** [comment]
@ryanannatuvasquez Coming soon~

**Comment by ryanannatuvasquez** [comment]
actually I've been struggling using CSS3 Transform in your code the width and height of the container is not rotating only the image. Can you give me a little advice how to do that? Thank you much appreciate!

**Comment by fengyuanchen** [comment]
@ryanannatuvasquez Just add `transform: rotate(30deg)` to the image's styles.

**Comment by ryanannatuvasquez** [comment]
@fengyuanchen I can rotate the image but the container and the cropper is not rotating, if the image width is to high and you rotate it the container has gray area.

**Comment by fengyuanchen** [comment]
@ryanannatuvasquez [v0.8.0](https://github.com/fengyuanchen/cropper/releases/tag/v0.8.0) had been released.

**Comment by ryanannatuvasquez** [comment]
@fengyuanchen wow! that was fast. Thanks!
