### ISSUE TITLE
Mobile Device (safari iOS7) cropping issue

### ISSUE THREAD

**Issue by ddoonn** [fengyuanchen/cropper#131]
The plugin crops images without any problems with most desktop browsers aswell as iOS8 Safari. On Safari iOS7 mobile browser the base64 string passed generated from the 'getDataURL' seems to crop the original image in a very strange way.

Before cropping:
![before](https://cloud.githubusercontent.com/assets/494871/5359858/b7b04e8c-7fc0-11e4-9673-99ddf0201bec.jpg)
After cropping:
![after](https://cloud.githubusercontent.com/assets/494871/5359860/b9d116e2-7fc0-11e4-81ed-c86199657da9.jpg)

Any ideas to what could be causing this?

**Comment by 4kstore** [comment]
@etioun can you put an example? I have the same problem and I don't know how to deal with this
Thanks

**Comment by soutlink** [comment]
I think this is related to #120 and #159

**Comment by fengyuanchen** [comment]
Yes, it is the problem of EXIF Image Orientation in some Mac OS / iOS browsers.

**Comment by fengyuanchen** [comment]
This is the same problem as #120 .
