### ISSUE TITLE
getDataUrl throws DOMException

### ISSUE THREAD

**Issue by jamgold** [fengyuanchen/cropper#134]
Love you cropper package. I am trying to crop an image loaded from my S3 bucket. I initialize the cropper and it works perfectly with the img.src pointing to the S3 bucket URL

```
  $image = this.$(".image_container > img");
  $image.cropper({
    checkImageOrigin:false,
    aspectRatio: 1.0,
    resizable: true,
    rotatable: false,
    preview: ".img-preview",
    data: {
      x: 10,
      y: 10,
      width: 300,
      height: 300
    },
  });
```

but when I invoke the click handler of my save button

```
    var dataUrl = $image.cropper('getDataURL');
```

it throws

DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.code: 18message: "Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported."name: "SecurityError"stack: "Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

Is this supposed to work?

**Comment by checkomkar** [comment]
@jamgold 
How did you added the timestamp? I am facing the same issue. For me its works on local, but on staging and prod its giving problems.

**Comment by jamgold** [comment]
Have you tried the option `checkImageOrigin: false`? These are the options I invoke the cropper with
```
var options = {
  aspectRatio: 1.0,
  resizable: true,
  rotatable: true,
  checkImageOrigin: false,
  preview: ".img-preview",
  data: {
    x: 10,
    y: 10,
    width: 300,
    height: 300
  },
  dragend: function() {
    console.log('dragend');
  },
  built: function() {
    // this is image
    console.log('cropper built');
};
//
// initialize the cropper
//
cropimage.cropper(options);
```

**Comment by checkomkar** [comment]
Yes I tried setting checkImageOrigin: false but when I invoke 
var dataUrl = $image.cropper('getDataURL');
on a button click, I get error similar to you were getting,
"name: "SecurityError"stack: "Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

**Comment by lotas** [comment]
Can confirm that same happens to the Chrome 41/42, but works without a problem in Firefox 37

**Comment by lotas** [comment]
https://github.com/fengyuanchen/cropper/pull/271 Please see this.
Seems like in Chrome attribute order matters.
I guess `src` being applied before `crossOrigin` indicated what is that.
Funny enough, it fixed my issue for Chrome.
