### ISSUE TITLE
Cropper in modal has original image getting in way

### ISSUE THREAD

**Issue by Sammaye** [fengyuanchen/cropper#141]
I put the cropper in a bs modal but then I realised that the left of the cropper was not making the modal close when I clicked on the overlay.

After an investigation I found that the cropper-hidden image was getting in the way and preventing the cropper from closing when I clicked on the overlay to the left off the modal.

**Comment by fengyuanchen** [comment]
Do you have a demo for testing?

**Comment by Sammaye** [comment]
Sorry for the stupidly late reply, finally got round to bug fixing this and found you have already done it. It is fixed as of 0.7.7
