### ISSUE TITLE
Destroy after BS Modal close - doesn't seem to destroy completely

### ISSUE THREAD

**Issue by vasikgreif** [fengyuanchen/cropper#143]
Hi,
I'm loading cropper in Bootstrap modal, on button click.
To destroy it when the modal is closed, I added:
```javascript
    $('#crop-modal').on('hidden.bs.modal', function () {
        $("#crop-modal .bootstrap-modal-cropper img").cropper("destroy");
        console.log('modal-closed');
    })
```
When I click on the crop button again, the modal with the cropper loads correctly, but in the console I can see the `build` and `built` events are fired **twice**. When I close it again and open again, they are fired 3 times etc. 

Any idea how to fix this?

**Comment by fengyuanchen** [comment]
It seems it was the problem of your jquery selector:
```js
  $("#crop-modal .bootstrap-modal-cropper img")
```

---

Before build:
```html
<div class="bootstrap-modal-cropper">
  <img src="example.jpg"><!-- Target image (visible) -->
</div>
```

After built:
```html
<div class="bootstrap-modal-cropper">
  <img src="example.jpg"><!-- Target image (hidden) -->
  <div class="cropper-container">
    <img src="example.jpg"><!-- A clone (original, hidden) -->
    <img src="example.jpg"><!-- Another clone (may be rotated, visible) -->
    ...
  </div>
</div>
```

So, when you run `$("#crop-modal .bootstrap-modal-cropper img").cropper("destroy")`, you would get **three** image elements:
- Image 1: Already had a cropper instance, so can be destroy.
- Image 2: Didn't have a cropper instance, would build first, as it is an asynchronous process, you couldn't destroy it before it was built.
- Image 3: The same as image 2.

---

A solution:

```js
$("#crop-modal .bootstrap-modal-cropper > img").cropper("destroy"); // Add a child selector: ">"
```
