### ISSUE TITLE
Rounding issue when setting data

### ISSUE THREAD

**Issue by LeEnno** [fengyuanchen/cropper#144]
When trying to set data it may happen – probably due to rounding errors – that the crop area will be calculated as "too high" so it will fallback to something smaller. Having an image with 640x427 dimensions and setting the following data:

    width:  427,
    height: 427,
    x:      106.5,
    y:      0

with an `aspectRatio` of `1` will result in the following crop area data:

    width: 341.59999999999997
    height: 341.59999999999997
    x: 106.5
    y: 0

You can see it in action [here](http://cdn.enno-projects.de/141231_cropper/index.html). The code including a good old fiddle can be found [here](http://jsfiddle.net/zpn193hk/1/), but unfortunately I have some issues with my server, so the scripts will not execute. For looking at the code it's good enough, I think.

**Comment by fengyuanchen** [comment]
You are right! I'll fix it soon. Thank you very much!!

**Comment by LeEnno** [comment]
Thanks a lot, works now.
