### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by nchase** [fengyuanchen/cropper#145]
This project is awesome. It would be even better with tests! Have you given any thought to testing and what test framework and test runner you might like to use?

**Comment by fengyuanchen** [comment]
I think  [**Qunit**](http://qunitjs.com/) may be good for this **jQuery plugin**.
 A few months ago, I had written some simple tests for this plugin with it.

**Comment by fengyuanchen** [comment]
I had added tests in v0.8.0.

**Comment by nchase** [comment]
awesome :thumbsup:
