### ISSUE TITLE
Weird positioning of `.cropper-container` with 0.7.7b

### ISSUE THREAD

**Issue by LeEnno** [fengyuanchen/cropper#146]
This is a follow up on #144. Working width your fixed code I came across a new issue. When the `img` container is given a width, that's smaller than the `img` width, the `.cropper-container` will get weird dimensions and position properties.

Fiddle: http://jsfiddle.net/zpn193hk/4/
The red background is the `.wrap` container. The `.cropper-container` exceeds its parent's (`.wrap`) width and height' by far and has a weird `left` offset.

**Comment by fengyuanchen** [comment]
We limit the size of the image wrapper:
- minWidth: 300px
- minHeight: 150px

**Comment by LeEnno** [comment]
Ok, I see this came in [v0.7.1](https://github.com/fengyuanchen/cropper/commit/9593fe45e58440bd1d3ed8fd9f1c78aca3eaa63e), can you explain why exactly?

I'd like to turn this behavior off because I want to display thumbnails with a max-width and -height of 100px. What do you think of 2 options as in

```js
defaults = {
  containerMinWidth: 300,
  containerMinHeight: 150
}
```

I could set both of them to `0` and be just fine.

**Comment by fengyuanchen** [comment]
In order to keep the cropper visible and build it correctly. The default size come from the default size of a canvas element. Your suggestion may be fine, I will think about it. Thanks.

**Comment by LeEnno** [comment]
Thx a lot.
