### ISSUE TITLE
Smooth resizing

### ISSUE THREAD

**Issue by sclausen** [fengyuanchen/cropper#147]
If you have a big image and crop it to a relatively small area the picture gets a little noisy.
a smooth resizing algorithm would prevent this.
I found a [script](https://github.com/danschumann/limby-resize/blob/master/lib/canvas_resize.js) which resizes one canvas on another one. Its MIT, so maybe you can implement this.

**Comment by fengyuanchen** [comment]
Thank you for your suggestion!

**Comment by fengyuanchen** [comment]
In order to keep this plugin simple and lightweight, I had provided the cropped canvas in the latest version (v0.9.0), and if someone who want to get more smooth picture, then he can use a third party tool to get it with the canvas.

**Comment by jasonmcaffee** [comment]
@fengyuanchen it would be nice if you could fix this issue.  If not, it should be called out in the documentations "this library does not work well with resizing large images"
