### ISSUE TITLE
Original image fails to initialize cropper and center in avatar-wrapper

### ISSUE THREAD

**Issue by rhill45** [fengyuanchen/cropper#149]
Hi Fengyuanchen,

If the cropper it being used to say edit an already cropped image it would be useful i think for the original image to initialize the cropper. On my page, the image only sits in a corner and user must open a new image in order to initialize any cropping. Thus making cropping of the original image impossible Is this a possible feature for this example? 

You can access my page to get a better idea what I'm referring to:

    http://www.mblistings.com/members_area/add_listings.php

Should the cropper be initializing right away or is a new image always required?

for a change up, in crop-avatar.js

I'm thinking this

    this.$avatarWrapper

needs to fit into where your initialization event occurs (which I'm having trouble doing). A "guess" is near this??? idk

        initPreview: function () {
      var url = this.$avatar.attr("src");

      this.$avatarPreview.empty().html('<img src="' + url + '">');

      this.$avatarWrapper.empty().html('<img src="' + url + '">');
    },

thank you in advance!
rb

**Comment by fengyuanchen** [comment]
You may try the `data` option (or `setData` method), e.g.:
```
$('#myOriginalImage').cropper({
  data: {
    x: 100,
    y: 50,
    width: 480,
    height: 270
  }
});
```

**Comment by rhill45** [comment]
@fengyuanchen where would you put that? I've tried about a dozen places on the html and crop-avatar page. It seems to freeze it up. also, wouldn't #myOriginalImage be the same thing as .avatar-view?

**Comment by fengyuanchen** [comment]
The [Crop Avatar](https://github.com/fengyuanchen/cropper/tree/master/examples/crop-avatar) is just an example. You must understand it and custom your own page.
