### ISSUE TITLE
Missing the temporary folder message

### ISSUE THREAD

**Issue by fagnerdireito** [fengyuanchen/cropper#150]
I am uploading and then do the crop, but always gives the following error has:
Missing the temporary folder

The folder that I configured was:
private $ SRCDIR = 'img / upload';
private $ dstDir = 'img / avatar';

But always gives the error message.

**Comment by fengyuanchen** [comment]
The same code in the `examples/crop-avatar/crop-avatar.php` (line 9 and 10) is:
```
private $srcDir = 'img/upload';
private $dstDir = 'img/avatar';
```

**Comment by fagnerdireito** [comment]
Yes, but always return erro message

**Comment by fengyuanchen** [comment]
It's an issue of your php server. You can easy find a answer on [StackOverflow](http://stackoverflow.com/) or the [PHP Manual](http://php.net/manual/en/features.file-upload.errors.php).

For example: http://stackoverflow.com/questions/1811929/php-upload-err-no-tmp-dir
