### ISSUE TITLE
Allow disabling zoom by mousewheel

### ISSUE THREAD

**Issue by ghengeveld** [fengyuanchen/cropper#151]
Zooming by scrolling can be annoying when the cropper is included on a long page because it will override page scrolling. I would like to disable zooming by scrolling. Still I'd like to be able to zoom the image using `$elem.cropper('zoom', 0.1)`, so setting `zoom: false` as option is not possible.

**Comment by fengyuanchen** [comment]
Maybe we can add an `allowMouseWheelZoom` option for this case. Thank you for your suggestion.

**Comment by fengyuanchen** [comment]
I had added `mouseWheelZoom` option in v0.8.0 for this.

**Comment by chrisbjr** [comment]
According to the docs, the option is now `zoomOnWheel`
