### ISSUE TITLE
IE 10+ slow loading from file select

### ISSUE THREAD

**Issue by TomTheRock** [fengyuanchen/cropper#152]
Performance on loading a Image by clicking "upload" very slow:
1mbyte Image file 3500x1200 
Chrome 1sec
ie 5sek

2,5mbyte
Chrome 3sec
ie 30sec

maybe a bug, other cropping plugins with canvas loads much more faster...

Here i found a tut example with html5 file select and getDataURL Show as thumb loading a
2.5mbyte Picture in under 10 secs in IE
http://www.html5rocks.com/de/tutorials/file/dndfiles/

I check your code and you use the same technic new FileReader() & reader.readAsDataURL()
so it seems that anything else extremly slow down your script on IE

**Comment by fengyuanchen** [comment]
Maybe the loading time of a data-uri image it is depending of the browser and the computer memory.

**Comment by TomTheRock** [comment]
i tested it and code a simple html 5 file select and canvas crop, it work with a 6000x5000 Pixel Image(7mbyte) in IE 11 in under 3 seconds...something must be wrong in your script

**Comment by fengyuanchen** [comment]
After read the image data URL from a file input with FileReader API. Cropper will create an image element with the data URL and append it to document body. Only when the image loaded completely, Cropper woul start to build.

So there **two** asynchronous progresses here, and this will take a lot of time when upload a very large image.

**Comment by bordeux** [comment]
@TomTheRock  read files to dataURI is not very good for browsers. Source code after that is very large ( your html code + 7mb text in attribute of your image).

Best way to you is use URL.createObjectUR(fileObject) - result  is local url to file, with blob protocol. Try - your performance grow up!

**Comment by fengyuanchen** [comment]
It's super quick now since I used the Blob URLs to import image file. See the [docs](http://fengyuanchen.github.io/cropper/)

**Comment by TomTheRock** [comment]
works perfect now :)! Very good Performance...as in my example script

**Comment by blitsgoa** [comment]
Hi, Look at the image below. I have integrated the cropper , and it works well on firefox and chrome. But now when you see the image, it is from IE 11. I removed the fade class from the modal, so the modal was coming proper , but when i click on the file upload, the modal gets chopped off. Can you tell me why? 
![capture](https://cloud.githubusercontent.com/assets/5785485/6198940/c73d4e4c-b448-11e4-9f89-e9dc60a1af1b.PNG)

**Comment by kotmatpockuh** [comment]
Hello. Maybe there are any ideas, how to load small image preview (i mean get `event.target.result` and resize it with the help of canvas to smaller size) so that browser didn't need to load huge base64 code - this part i have done... but now i have question: is it real to take small preview crop data (like position, size) and crop original huge image with data, which i can get from small preview?

**Comment by fengyuanchen** [comment]
@kotmatpockuh With canvas? Before draw image into canvas, you still need to load the huge base64 image to the document, so everything is come back...

**Comment by kotmatpockuh** [comment]
@fengyuanchen  yes, but so preview is displayed much faster, and only when saving crop it will take a while - this is better then to wait until ie loads 3000*2000 image...

**Comment by kotmatpockuh** [comment]
how to do that?

**Comment by kotmatpockuh** [comment]
when i work with resized canvas - i didn't need to load into page huge base64

**Comment by kotmatpockuh** [comment]
so... maybe you have ideas how to call cropper on canvas?

**Comment by kotmatpockuh** [comment]
or maybe you have idea how to use percent sizes, like container width in percent, so that later i could use it on big image?   https://dl.dropboxusercontent.com/u/59666091/19af71228a66376d950e32cc065ff250.png  try to upload and crop such image in ie10

**Comment by kotmatpockuh** [comment]
or maybe give advice how to change image src 'on the fly', i mean to select area with small image, and when i click save: than in background change src to full base64 code and crop it with old positions... ?

**Comment by fengyuanchen** [comment]
@kotmatpockuh I suggest you don't waste time on this as you alway need to load the huge image slowly.

**Comment by kotmatpockuh** [comment]
@fengyuanchen this is not a solutuion )

not only i have such trouble, for whole community it will be a great affort to speed up png crop...

as one of solutuion: "change image src 'on the fly', i mean to select area with small image, and when i click save: than in background change src to full base64 code and crop it with old positions... ?"
