### ISSUE TITLE
About zoomable

### ISSUE THREAD

**Issue by cylinsh** [fengyuanchen/cropper#154]
my setting:
...
data: {
        x: 140,
        y: 120,
        width: 176,
        height: 68
      },     
    resizable: false,
    zoomable: true,
...
The image is wrapped in a fixed block, when I zoom in/zoom out the image, the dimensions of the cropper area is not '176 x 68' any more. 
How can I get a '176 x 68' demensions image whether if I zoom in/zoom out the orginal image in the block.

**Comment by fengyuanchen** [comment]
The properties value of `data` option base on the natural image, not the cropper container.

You can try this:
```
var $img = $('img');

$img.cropper({
  aspectRatio: 176 / 68,
  resizable: false
});

$img.cropper('getDataURL', {
  width: 176,
  height: 68
});
```
