### ISSUE TITLE
Responsive issues

### ISSUE THREAD

**Issue by seanhak** [fengyuanchen/cropper#157]
Thanks for a great plugin!

I was having issues with the responsive only working when scaling down, but never could scale back up again.

My quick solution was to change the container width to the real container however this feels wrong, and it didnt work with portrait images. Any suggestions?
```
   initContainer: function () {
      var $container = this.$container,
	  image = this.image;
	  if(image.width<image.height){	  
		this.container = {
			width: max($container.width(), 300),
			height: max($container.height(), 150)
		};
	  }else{
		this.container = {
		  width: max($container.parent().width(), 300),
		  height: max($container.parent().width()/image.aspectRatio, 150)
		};
	  }
    },
```
Attach screenshots from your modal demo to illustrate the issue (step 1 & 2 works as expected, however won't resize back to full potential on 3rd step).

![1](https://cloud.githubusercontent.com/assets/1853138/5835117/107ca73e-a165-11e4-8e15-65db358c4596.PNG)
![2](https://cloud.githubusercontent.com/assets/1853138/5835119/1081c908-a165-11e4-8125-36e83ca7b22d.PNG)
![3](https://cloud.githubusercontent.com/assets/1853138/5835118/1080c8b4-a165-11e4-8fd8-42abf2a3326f.PNG)

**Comment by fengyuanchen** [comment]
This is a good issue that I have omitted it for a long time. I will try to fix it from now.
