### ISSUE TITLE
Some Lines In Crop Area Not Visible

### ISSUE THREAD

**Issue by LeEnno** [fengyuanchen/cropper#158]
After fixing #144 I found that the upper and lower lines may be hidden:

![skitched-20150122-135932](https://cloud.githubusercontent.com/assets/2038814/5855977/e542008e-a23e-11e4-9073-9365ae5db762.png)

See [fiddle](http://jsfiddle.net/zpn193hk/6/).

This is due to `.cropper-container {overflow:hidden;}`. I don't know if *not* setting that property would leave any regressions, but at the moment I consider this behavior a bug.

What do you think?

**Comment by LeEnno** [comment]
You can also reproduce this by visiting the demo page and maxing out the crop area to the side.

![skitched-20150122-140616](https://cloud.githubusercontent.com/assets/2038814/5856074/d6082cc8-a23f-11e4-8f2d-6328bdf08784.png)

**Comment by fengyuanchen** [comment]
The blue lines are outlines, which are rendered with CSS `outline` property:
```
outline: 1px solid #69f;
```

**Comment by LeEnno** [comment]
Thx for your feedback. I know those blue lines are outlines, but in previous versions they weren't hidden when maxing out the crop area. Again have a look at the image above. Two outlines (top, left) aren't visible anymore but were visible prior to v0.7.7.

That's intentional? Since it is new behavior I thought this is a bug.

**Comment by fengyuanchen** [comment]
Since [v0.6.2](https://github.com/fengyuanchen/cropper/releases/tag/v0.6.2), the `outline-offset` rule was removed. You also can find it in [v0.6.1](https://github.com/fengyuanchen/cropper/releases/tag/v0.6.1):
```
// cropper.css
.cropper-viewer {
  ...
  outline-offset: -1px;
}
```

**Comment by LeEnno** [comment]
Is there a specific reason why?
