### ISSUE TITLE
Random image rotation and translation when using $().cropper('getDataURL')

### ISSUE THREAD

**Issue by kyle-alex-burke** [fengyuanchen/cropper#159]
I'm using the Cropper library (v0.7.7) to allow users to resize uploaded images before storing them in our server. Very occasionally, a user will upload an image on a mobile browser that doesn't crop properly.

![img_1544](https://cloud.githubusercontent.com/assets/1786323/5881443/1637a83c-a2fe-11e4-88ce-a56ac16a29ba.png)
I'm using ```$(".img-container > img").cropper('getDataURL', 'image/jpeg', 0.7);``` to capture the cropped region. However, on mobile browsers (iOS 8 Chrome and Safari) the image has been rotated by 90 degrees.
![screen shot 2015-01-23 at 12 47 54 pm](https://cloud.githubusercontent.com/assets/1786323/5881484/638504ea-a2fe-11e4-9ca2-46594d8fcb18.png)
Other times, the cropped image is translated to to the top left corner, leaving a lot of white space.
![screen shot 2015-01-23 at 12 40 11 pm](https://cloud.githubusercontent.com/assets/1786323/5881526/a69efb64-a2fe-11e4-84fc-99ea2bd3e2df.png)
When I repeat this process on a desktop browser (OSX Chrome) the cropped image renders properly. 
I'm not doing much with the library; I'm initializing the cropper with this: 
```
$(".img-container > img").cropper({
  aspectRatio: ratio,
  dashed: false,
  dragCrop: false,
  zoomable: false,
  checkImageOrigin: false
});
```
And storing the cropped region with the above line. So far, the only pictures that break in this way are ones taken with smartphone cameras (and even then, only a small portion of those). My hunch is that the removal of exif metadata with canvas.toDataURL() has something to do with it, but I don't know much about HTML5 canvases so I can't really say beyond that, nor can I identify anything in the metadata that might cause this rotation or displacement.

**Comment by fengyuanchen** [comment]
It seems to be the reason of the EXIF Image Orientation (#120).

> When draws an image with EXIF Image Orientation in to a canvas element, the iOS browser will rotate the image automatically.

**Comment by fengyuanchen** [comment]
Please see #120.
