### ISSUE TITLE
arbitrary left value on cropper-container

### ISSUE THREAD

**Issue by bluebaroncanada** [fengyuanchen/cropper#160]
Getting a left value of 9.8200899550225px on .cropper-container which is throwing things off significantly in my application.

**Comment by caiocafardo** [comment]
The same thing here!

**Comment by fengyuanchen** [comment]
You can try the new version: [v0.8.0](https://github.com/fengyuanchen/cropper/releases/tag/v0.8.0)

**Comment by kotmatpockuh** [comment]
not solved in 0.8.0...

**Comment by fengyuanchen** [comment]
@bluebaroncanada Can you show me an online demo for the unexpected left value on the `.cropper-contaner`.
