### ISSUE TITLE
Image is shown very small after init, resizes when I resize the browser window

### ISSUE THREAD

**Issue by nusoft** [fengyuanchen/cropper#161]
Hello,

When I initiate the cropper (in a Bootstrap modal), the image is shown 300px wide. When I resize the browser window for a second, it changes to the correct width. Any idea why?

See a video here: http://recordit.co/te1T5gdqxW

**Comment by fengyuanchen** [comment]
Please see #85

**Comment by nusoft** [comment]
Thank you very much, I was using:
(".modal").on("show.bs.modal", function() { })

Instead of:

(".modal").on("shown.bs.modal", function() { })

**Comment by fengyuanchen** [comment]
Ensure the image container is visible, `shown.bs.modal` is better than `show.bs.modal`.

**Comment by nusoft** [comment]
It's working now, thanks a lot, great work!

**Comment by Barzon** [comment]
Thanks! Me too

**Comment by listopadov** [comment]
Thanks!!! it's work!!!
