### ISSUE TITLE
Not able to crop images from url

### ISSUE THREAD

**Issue by MaikoHermans** [fengyuanchen/cropper#163]
I'm trying to crop images from a external url like the following:
https://www.google.nl/images/srpr/logo11w.png

however, when I try to do this it will load the image into the canvas perfectly fine but as soon as I try to get the crop information it doesn't actually crop it.

It looks like it doesn't call the javascript at all actually.
It does work perfectly fine when I use a link like images/something.png

is there a trick to making it work?

**Comment by fengyuanchen** [comment]
The Response Header of this image doesn't have a `Access-Control-Allow-Origin` property.
