### ISSUE TITLE
]Bug] You shouldn't add "timestamp" parameter to url, when URL is objectURL

### ISSUE THREAD

**Issue by bordeux** [fengyuanchen/cropper#169]
Hi!
You shuldn't add "timestamp" get parameter, when url starts with blob://  

Here is problem: 
![Problem](http://i.imgur.com/GmUxHSz.png)

1 request exist, but second with your timestamp not exsist .

Here is more info
https://developer.mozilla.org/en-US/docs/Web/API/URL.createObjectURL

**Comment by fengyuanchen** [comment]
Thank you very much! I will fix this soon.

**Comment by fengyuanchen** [comment]
A `blob` object url will not be added a "timestamp", unless the original image has a `crossOrigin` attribute.
Do you added a `crossOrigin` attribute in the original  `img` element?

**Comment by bordeux** [comment]
yes, i added crossOrign to attribute (because , one time is full url, one time is blob url , one time is data/uri url ) . But i think, plugin should detect link type before add timestamp to url. 

PS.
Very nice plugin!  Thank you for your time!

**Comment by fengyuanchen** [comment]
All right, I will try to improve it. Thanks!

**Comment by Pleasurazy** [comment]
+1

Is there have a option to setting it?

![image](https://cloud.githubusercontent.com/assets/1500206/6122360/25d6d172-b12d-11e4-9a94-48fa6011ff46.png)

**Comment by bordeux** [comment]
Set checkImageOrigin option to false

**Comment by Pleasurazy** [comment]
not work.

![image](https://cloud.githubusercontent.com/assets/1500206/6123710/f267eaec-b140-11e4-847c-7b874d7e5b02.png)


But if [this line](https://github.com/fengyuanchen/cropper/blob/master/src/cropper.js#L178) without addTimestamp, then work.

this line:
![image](https://cloud.githubusercontent.com/assets/1500206/6123697/ce92e3c4-b140-11e4-9ca2-d2b1a9a4387c.png)

**Comment by bordeux** [comment]
Your image is outside of your domain (other domain than where is script) .
Solutions
* You can add " Access-Control-Allow-Origin: *" to server, where you have images
* Wait  for @fengyuanchen to add new option. 
* Fork project and create push request to main (this) repo

**Comment by fengyuanchen** [comment]
@bordeux A blob object url with the original image has a `crossOrigin` attribute will not be added a timestamp now since v0.7.8.

@Pleasurazy A image url is also a http url, it must support search parameters too. so, I think you may improve your image server to support extra search parameters, e.g., "timestamp".

Thank you both~
