### ISSUE TITLE
Calling 'destroy' when a cropper is already destroyed (or not initalized) creates it.

### ISSUE THREAD

**Issue by peterholak** [fengyuanchen/cropper#173]
`$('#image').cropper('destroy')` creates a cropper for the image if it hasn't been created already. If this is the intended behavior, it should at least be explicitly mentioned in the documentation.

I also don't see any way to find out whether a cropper is currently attached to a certain image - there is no method that returns this information.

This means that there is no foolproof way to "destroy" a cropper regardless of its current state.

**Comment by koryteg** [comment]
I am currently doing an if statment on the image, but it is kind of buggy.

im doing:

    if $("#image").hasClass('cropper-hidden'){
        $("#image").cropper("destroy");
    }


it is not the best.

**Comment by fengyuanchen** [comment]
Destroy the cropper when it is built:

```
$('img').cropper({
  built: function () {
    // Do something
    // ...
    // Then destroy it
    $(this).cropper('destroy');
  }
});
```

**Comment by fengyuanchen** [comment]
I had improved this in the v0.7.8, you can [try it](http://fengyuanchen.github.io/cropper) now.
