### ISSUE TITLE
Cropping area is small and couldn't operate resize on it while uploading a file larger than 1M

### ISSUE THREAD

**Issue by aronica** [fengyuanchen/cropper#174]
As the title said, you great product works perfect when the image file is small , but i found it worked unnormal when the file was larger then 1m, which works fine in your demo page, i don't know why
![qq 20150204104912](https://cloud.githubusercontent.com/assets/1247104/6034258/91912a1a-ac5b-11e4-84d7-750046e65796.png)

**Comment by fengyuanchen** [comment]
Just call the `reset` method before or after replace it.

**Comment by fengyuanchen** [comment]
```
var $image = $('#myImage');

$image.cropper({
  built: function () {
    // Do something
    // ...
    // Reset and replace it
    $image.cropper('reset', true);
    $image.cropper('replace', '/path/to/another-image.jpg');
  }
});
```
