### ISSUE TITLE
Image being duplicated until it zoom to one fixed position!

### ISSUE THREAD

**Issue by damienvaz** [fengyuanchen/cropper#175]
I'm trying to implement your javascript plugin for a personal project.
But there is a problem wich i couldn't figure out ...
Why am i getting that , when i'm trying to scroll down my webpages ?
The image is being duplicated down until it will be zoomed to a fixed position and getting pixels from that images... See next picture 

![screen shot 2015-02-04 at 3 03 52 pm](https://cloud.githubusercontent.com/assets/3703782/6042748/286e7cee-ac7f-11e4-87f1-ecf4d1e94e7c.png)

I'm using bootstrap (couldn't make the modal example from your example also(doing the same effect as the picture)), using jQuery , using your js and css cropper.

This is a piece of code from my website :

```
....
<div class="row">
   <div class="col-lg-12">
      <div class="foto">
         <img src="assets/img/picture-1.jpg" style="width:100%;">
      </div> 
   </div>
</div>
.....
<script>
        $(document).ready(function() {  
            $(".foto > img").cropper({
              done: function(data) {
                // Output the result data for cropping image.
                  console.log(data);
              }
            });

        });
    </script>

```
Could you , please, help me with this problem?

**Comment by fengyuanchen** [comment]
Do you include the `cropper.css` file in your page?

**Comment by damienvaz** [comment]
It was ! I'm so dumb ! Missed to put "stylesheet" on my tag link ! Thank you again ! By the way, your plugin is really awesome ! :)

**Comment by diegopassoscosta** [comment]
Hello 

I'm having "the same issue", but I have this same behavior as damienvaz above. When I try to resize the crop area and get all area in 45° degrees the image shows kind of duplicated like a shadow.

Note: I was using the cropper CSS as fengyuanchen said.

```<link rel="stylesheet" href="~/Content/js/plugins/cropperjs/dist/cropper.min.css" />```

And CropperJS Library

```
<script type="text/javascript" src="~/Content/js/plugins/cropperjs/dist/cropper.min.js"></script>
<script type="text/javascript" src="~/Content/js/plugins/jquery-cropper/dist/jquery-cropper.min.js"></script>
```


![Picture_00](https://user-images.githubusercontent.com/2180083/67770837-eabd5c80-fa35-11e9-84b2-11583c423efc.png)
