### ISSUE TITLE
Cropper with fixed dragger problem/feature request

### ISSUE THREAD

**Issue by lucanovera** [fengyuanchen/cropper#177]
Hi! I'm really enjoying the plugin but i'm having a problem.
I need the cropper to have the size of the final cropped image and the original image to move in the background. It's the same style of croping instagram uses.

![alt text](http://cdn.cultofmac.com/wp-content/uploads/2013/06/instagrampics.jpg "Instagram cropping")

How would i do that? 

Thanks

**Comment by fengyuanchen** [comment]
We don't support this right now, but I will try to improve it in the next minor version. Thank you~

**Comment by fengyuanchen** [comment]
You can try it now:
```
$().cropper({
  autoCropArea: 1,
  movable: false,
  rezisable: false
})
```

**Comment by Hesesses** [comment]
+1

@lucanovera did you figure this out?

**Comment by lucanovera** [comment]
I ended up using http://guillotine.js.org/ interface and manual cropping and scaling with canvas.

Now this cropper supports that too, http://fengyuanchen.github.io/cropper/ ("Cropper with fixed crop box" example), but at least in that example it doesnt set the boundries for the image.
