### ISSUE TITLE
The data.x is  undefined

### ISSUE THREAD

**Issue by arieslee** [fengyuanchen/cropper#179]
var $image = $(".diy_cropper-wrapper img");
                $image.on('load',function(){
                    $('#theCropperImgLoading').hide();
                    $image.cropper({
                        aspectRatio:1,
                        preview:'',
                        done: function(data) {
                            var json = [
                                '{"x":' + data.x,
                                '"y":' + data.y,
                                '"height":' + data.height,
                                '"width":' + data.width + "}"
                            ].join();
                            $('#saveTheCropper').html(json);
                        }
                    });
                    $('#saveTheCropper').show();
                });
the #saveTheCropper html is {"x":undefined,"y":undefined,"height":273,"width":273}

**Comment by fengyuanchen** [comment]
Can you provide an online demo for this? thank you!
