### ISSUE TITLE
Unable to use cropper on a dataurl

### ISSUE THREAD

**Issue by Pyrx** [fengyuanchen/cropper#180]
I have captured a photo via webcam using GetUserMedia and have written the photo to an img tag's src attribute in data url format.  I am unable to use that data url (data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAoAAAAFoCAYAAADHMkpRAAAgAElEQVR4XsS96Y5s ... etcetera) with cropper.  Any ideas on how to resolve that?

Thanks very much!

**Comment by fengyuanchen** [comment]
The Cropper supports data uri image, just check your source code please.

**Comment by Pyrx** [comment]
The solution was a setTimeout between code segments but knowing that your code supports data uri was really helpful as I knew I could use it!  Thanks fengyuanchen!!

**Comment by g-akshay** [comment]
@Pyrx @fengyuanchen I tried with source its working, but not working with data urls ;(

**Comment by rwwagner90** [comment]
This just refuses to work with a base64 image for me. Can you guys help me out? My image shows up, but the cropping box does not.

**Comment by Pyrx** [comment]
Hey @rwwagner90 as per my comment above, a timeout is required when you initialise the cropper.  The line I used in my code was:

window.setTimeout(cropper(photoTag), 200); 

that calls a function that starts as below

function cropper(photoTag) {
        var $image = $(photoTag);

        $image.cropper({
            aspectRatio: 330 / 420,
           etc...
