### ISSUE TITLE
Min and max aspect ratio.

### ISSUE THREAD

**Issue by airtwister** [fengyuanchen/cropper#182]
Hello! 
Thank you for your great plugin!

I'm using cropper.js for cover and avatar image cropping.
Users can upload cover image with fixed width(928px) and non-fixed height. But height of cropped image must be from 100px to 800px. So my question is: how can I assign to cropper min aspectratio as 928/100 and max aspectratio as 928/800.

Thank you in advance.

**Comment by fengyuanchen** [comment]
I'm sorry, we don't support this right now.

**Comment by romaincointepas** [comment]
+1, I would really love this to be possible as well (for http://www.twitshot.com)

**Comment by airtwister** [comment]
@romaincointepas Hi! 
May be it will be heplful for you.
I solved it (for now) by adding this to cropper.js options:
```javascript
done: function (data) {
    var ratio = data.width/928,
          height = data.height/ratio,
          min_height = ratio * 100,
          max_height = ratio * 800;

    if( h < 100 ) $('#my_img').cropper('setData', {height: min_height});
    if( h > 800 ) $('#my_img').cropper('setData', {height: max_height});
}
```
Here we simply don't allow the cropping area to be out of ratio sizes by setting it to needed value. So aspect ratio will be minimum of 928/100 and maximum of 928/800.

**Comment by climberwoodi** [comment]
+1

**Comment by jgliesman** [comment]
+1

**Comment by ashishsinghyopmail** [comment]
I want to upload and crop images in two different size 60*40 and 130*100
Please suggest anyone how to do this ..using this plugin
Thanks for any suggestion....

**Comment by ashishsinghyopmail** [comment]
if i want to fix size of crop box selector area on image before cropping any idea if....suggest
Thanks

**Comment by fengyuanchen** [comment]
Here is a solution with `cropmove` event:

```html
<div>
  <img id="image" src="/path/to/picture.jpg">
</div>
```
```js
$(function () {
  var $image = $('#image');
  var minAspectRatio = 1;
  var maxAspectRatio = 2;

  $image.cropper({
    cropmove: function (e) {
      var cropBoxData = $image.cropper('getCropBoxData');
      var cropBoxWidth = cropBoxData.width;
      var aspectRatio = cropBoxWidth / cropBoxData.height;
      var lessThan = aspectRatio < minAspectRatio;

      if (lessThan || aspectRatio > maxAspectRatio) {

        // Stop the current move
        e.preventDefault();

        // Trim the crop box size
        $image.cropper('setCropBoxData', {
          height: cropBoxWidth / (lessThan ? minAspectRatio : maxAspectRatio)
        });
      }
    }
  });
});
```
