### ISSUE TITLE
getDataUrl after ajax request and showing cropper in modalbox returns The operation is insecure...

### ISSUE THREAD

**Issue by pimduijst** [fengyuanchen/cropper#183]
Hi,

I run into an issue using your top notch plugin. The problem occurs as follows: 

I upload an image using ajax, when the image dimensions of the uploaded img do not match a predefined set of dimensions the croptool is triggered in a modalbox. So far so good. I make a selection of the area I want to crop and click on the crop button. The cropbutton fires the 'getDataUrl' with 'image/jpeg'.

But for some reason I get The operation is insecure as a result. My code is as follows:
//below renders the modal and the cropper function

```js
$('#cropForm').modal('show');
cropper();

function cropper(){
    var image = $('.img-container > img');
    var originalData = {};
    var dataX = $('#dataX');
    var dataY = $('#dataY');
    var dataHeight = $('#dataHeight');
    var dataWidth = $('#dataWidth');
    var dataURLView = $('#dataURLView');

    $('#cropForm').on('shown.bs.modal', function() {
        image.cropper({
        preview: '.preview',
        done: function (data) {
            dataX.val(Math.round(data.x));
            dataY.val(Math.round(data.y));
            dataHeight.val(Math.round(data.height));
            dataWidth.val(Math.round(data.width));
            }
        });
        $('#crop').click(function(){
            crop(image);
        });
      
    }).on('hidden.bs.modal', function() {
      originalData = image.cropper('getData');
      image.cropper('destroy');
    });

}

function crop(img){
    //var image = $('.img-container > img');
    var dataURL = img.cropper('getDataURL', 'image/jpeg');
    //console.log(dataURL);
    //$dataURLInto.text(dataURL);
    dataURLView.html('<img src="' + dataURL + '">');
}
```

Can you please help me out? What am I doing wrong? Let me know if you need more detailed info.

p.s. I upload the image to the same server (as I read that this issue seemed to occure on crossdomain images) as where the plugin is hosted on.

Kind regards,

Pim

**Comment by pimduijst** [comment]
I have already figured out that the error message is caused by the following line:

e.toDataURL(a, b);

in function getDataUrl

**Comment by fengyuanchen** [comment]
The `SecurityError: The operation is insecure` error means the image crosses origin. I need your uploaded image url to check if it is a cross origin image.

**Comment by pimduijst** [comment]
True, I think I already figured out a workaround

**Comment by pimduijst** [comment]
Got a workaround!
