### ISSUE TITLE
working in a database with rails.

### ISSUE THREAD

**Issue by TomGroombridge** [fengyuanchen/cropper#184]
Hi, 

I am using this in my rails application so i can create a user with a avatar.  I have all the code working fine but I am at a loss as to how to replace the image uploaded with the cropped image. How can I add the cropped image to the database?

**Comment by fengyuanchen** [comment]
Just uploads the cropped image to server and stores it to database..

**Comment by koryteg** [comment]
how are you handling the image processing? are you using carrierwave or paperclip?
I am sending the x, y, w, h up to the server as virtual attributes of the model that the image is attached to. and then running a crop method on the image processor( in my case carrierwave.)

**Comment by ruchanb** [comment]
you get the cropped data in Base64 string from $([selector]).cropper('getDataURL'); then send it to your server... on server you might need to replace the data:image... part from the string to save as image

**Comment by fengyuanchen** [comment]
@TomGroombridge You can store the dataURL to database directly. 

If you just want to store a image path to database, maybe you need to transfer the dataURL to blob, and upload the blob as a file to server and save it in hard disk.

Here is a thirk party project for transfering dataURL to blob, you may try it: https://github.com/blueimp/JavaScript-Canvas-to-Blob

---

For example:

Includes files:

```html
<script src="js/canvas-to-blob.min.js"></script>
```

JavaScript:
```js
var dataURL = $('#myImage').cropper('getDataURL'),
    formData,
    blob;

if (window.dataURLtoBlob) {
  blob = dataURLtoBlob(dataURL);
  formData = new FormData(); https://developer.mozilla.org/en-US/docs/Web/API/FormData
  formData.append('file', blob, fileName);

  // Then send the formData with XMLHttpRequest to server
  // On the server-side, you can get the upload file, for example, with PHP: $_FILES['file']
}
```
