### ISSUE TITLE
minWidth & minHeight not respected when zooming

### ISSUE THREAD

**Issue by BjornEngelen** [fengyuanchen/cropper#185]
Hi,

1) set a minimum size for the cropped area, say 200x200 pixels
2) load an image, and resize the dragger as small as it will go
3) then, zoom in.The dragger's size on the canvas will remain the same. Therefor the cropped area will be smaller than 200x200 pixels.
4) verify by saving the resulting image

**Comment by fengyuanchen** [comment]
You are right, thank you!

**Comment by fengyuanchen** [comment]
[v0.8.0](https://github.com/fengyuanchen/cropper/releases/tag/v0.8.0) had been released. I removed the `minWidth` and `minHeight` options, and added `minCropBoxWidth` and `minCropBoxHeight` options.
