### ISSUE TITLE
if crop area takes whole container should switch to movable to false.

### ISSUE THREAD

**Issue by koryteg** [fengyuanchen/cropper#186]
so I have a cropper that is movable and zoomable but not resizable. if when the cropper loads, the crop area takes the whole image area and then I zoom, I cannot move the image behind the crop area.
it would be nice if the cropper listened to this case and changed movable to false so when you click on the area when you are zoomed it will move the image.

![amplo_advancement](https://cloud.githubusercontent.com/assets/777967/6155613/86fb868e-b1e9-11e4-85a5-c8e77dc2e5e5.png)

**Comment by fengyuanchen** [comment]
It's done. Thank you!

**Comment by koryteg** [comment]
wow thanks for the quick response and fix!

**Comment by ruchanb** [comment]
Is this on 0.7.8? I don't see this change on this version.

**Comment by koryteg** [comment]
actually this isnt working for me either. fyi.

**Comment by ruchanb** [comment]
Oh i got the settings wrong... it is working... I however would love to see the moving of image with the dragging of cropper on movable:true

**Comment by fengyuanchen** [comment]
I fixed this in `src/cropper.js`, but not yet release.

**Comment by ruchanb** [comment]
one concern about this... you are making the image movable when the cropper takes the whole container... When cropper only takes part of the container then it is hard to move the image around to fit in the cropper. I would suggest a movable image while moving the cropper on the edges.
See the issue below:
![cropperissue](https://cloud.githubusercontent.com/assets/11032047/6224062/a3b17a96-b69d-11e4-9f09-b7ede29c2636.png)
