### ISSUE TITLE
Moving zoomed Image with moving of Cropper window on corners  - feature request

### ISSUE THREAD

**Issue by ruchanb** [fengyuanchen/cropper#190]
It would be a good feature to move the Zoomed Image when cropper window is dragged to corners and edges. This currently only happens (0.7.8) when the cropper window covers the whole image container.

**Comment by fengyuanchen** [comment]
Then how do you drag it back to the centre?

**Comment by ruchanb** [comment]
i don't think it is required to be moved back to center for movable:true

**Comment by ruchanb** [comment]
it will be useful when the cropper area is only leaving a small portion(which can be hard, sometimes un-selectable) backdrop image to drag around.

**Comment by fengyuanchen** [comment]
I think it is not a good idea to do this. Sorry!
