### ISSUE TITLE
Zooming out/Fit image upto cropper window when autoCropArea<1.0 / feature request

### ISSUE THREAD

**Issue by ruchanb** [fengyuanchen/cropper#191]
Currently if we want to crop a 400 X 200 image to 200 X 200 window we need to set the autoCropArea=1. By setting the autoCropArea <1, the cropped image will be less than 200 X 200 size, because we cannot zoom out to the cropping window.

It is necessary feature to have the image be zoomed out to match the cropper window.

**Comment by fengyuanchen** [comment]
Please try [v0.8.0](https://github.com/fengyuanchen/cropper/releases/tag/v0.8.0). Thanks~

**Comment by ruchanb** [comment]
Great update. :+1: 
Here are some suggestions around it:
1. When zooming out or dragging backdrop image around the cropper window, limit the movement to the cropper window edges. This will fix the blank image data which is not necessary while getting cropped image.
see facebook image cropper or http://scottcheng.github.io/cropit/
2. Don't let to start new cropper window from empty background.
