### ISSUE TITLE
Do not show crop by default

### ISSUE THREAD

**Issue by navneetccna** [fengyuanchen/cropper#194]
Can it possible that we do now crop by default. If user click on crop button than only crop will start

**Comment by soutlink** [comment]
Do you mean autoCropArea: 0??

**Comment by navneetccna** [comment]
no i don't want to initialize crop first time. i want crop only on when i click on crop button than crop will start

**Comment by fengyuanchen** [comment]
The crop button is just for changing the drag mode. After click on the crop button, you can drag on the image to create a new crop box.

**Comment by navneetccna** [comment]
so is there any way to start crop on a button click ?

**Comment by fengyuanchen** [comment]
Initialize a cropper when click a button:
```
$('#startCropBtn').click(function () {
  $('#myCropImg').cropper();
});
```

**Comment by navneetccna** [comment]
i want to initialize cropper on page load so user can zoom or rotate image but do not crop till click on crop button

**Comment by fengyuanchen** [comment]
```
// Extent it
$.fn.cropper.Constructor.prototype.crop = function () {
  if (!this.disabled) {
    this.options.modal && this.$canvas.addClass(CLASS_MODAL);
    this.$cropBox.removeClass(CLASS_HIDDEN);
    this.cropped = true;
    this.renderCropBox();
  }
}

// Call it
var $image = $('#myImage');

$image.cropper({
  autoCrop: false
});

$('#startCropBtn').click(function () {
  $image.cropper('crop');
});
```

**Comment by navneetccna** [comment]
still cropping is enable :(

**Comment by navneetccna** [comment]
still i am able to click on canvas and crop image
showing cross hair icon and can able drag crop to crop image

**Comment by fengyuanchen** [comment]
```
...
$image.cropper({
  autoCrop: false,
  dragCrop: false
});
...
```

**Comment by help-me-help-you** [comment]
...
$image.cropper({
  autoCrop: false,
  dragCrop: false
});
Xie Xie fengyuanchen

**Comment by help-me-help-you** [comment]
http://mafestival.be/blicsm/plugins/cropper-master/docs/

A good reference cheatsheet for using your plugin.
