### ISSUE TITLE
Default crop data

### ISSUE THREAD

**Issue by Leftyx** [fengyuanchen/cropper#195]
Hello,

compliments for your great job.

I was using Cropper v0.7.8. Today I decided to upgrade to v0.8.0.
I was initializing my cropper passing data fetched from database

EX:

```javascript
Projects.CropSize = {
    height: 190.6
    width: 190.6
    x: 613.2
    y: 12.7
}
```

```javascript
var $cropper = $('#image-tools-image').cropper({
	multiple: false,
	modal: true,
	autoCrop: true,
	zoomable: true,
	aspectRatio: 1/1,
	data: Projects.CropSize || Projects.CropDefaults,
	preview: ".tool-img-preview",
	done: function (data) {
	    // console.log(data);
	    modal.find('.label-x').text('X: ' + Math.round(data.x));
	    modal.find('.label-y').text('Y: ' + Math.round(data.y));
	    modal.find('.label-width').text('Width: ' + Math.round(data.width));
	    modal.find('.label-height').text('Height: ' + Math.round(data.height));
	}
});
```
Now it does not seem to work anymore.

How should I initialize a cropper with my setting for a specific image?

Thanks.

**Comment by fengyuanchen** [comment]
[v0.8.0](https://github.com/fengyuanchen/cropper/releases/tag/v0.8.0) changed many options. If you don't want to change your code, you can still use v0.7.x
