### ISSUE TITLE
Does not work in shadow DOM

### ISSUE THREAD

**Issue by lerayne** [fengyuanchen/cropper#196]
On stript init and when ``.cropper()`` is called, the script adresses the body element (cropper.js, line 234 is the first meaningful info in error stack). As I understand - that is why it does not work in shadow DOM, which is widely used by Polymer.js

From my experience - there is no ultimate nessecity to address the body to build such a thing

**Comment by fengyuanchen** [comment]
You may try to fix it:

Replace line 234 of the `cropper.js` 
```
$clone.addClass(CLASS_HIDE).prependTo('body');
```
with
```
$clone.addClass(CLASS_HIDE).insertAfter($this);
```
