### ISSUE TITLE
Destroy Fails. 

### ISSUE THREAD

**Issue by TheFilmGod** [fengyuanchen/cropper#197]
$().cropper('destroy');

Does not work properly. When calling destroy() - the html source is not removed from the DOM and any attempt to create a new cropper afterwards fails. Internal handlers are most certainly not removed.

The use case is very code heavy - all uploads and image rotation is done server side. So unfortunatley, I can not post a full code example. However, here is the general process:

1) user uploads image. Server upload.
2) image preview is shown from server.
3) Cropper is created
4) Users clicks on "rotate" image
5) Request is sent to the server that performs the rotation. Image is rotated on the SAME uploaded file.
6) Cropper is replaced. Replace fails too! So we do: cropper-> destroy -> and then, create

Results:

Cropper is not destroyed and such, any subsequent call to create a new cropper creates not 1 but 3 crop containers. (since dom elements).

Here is a partial hack to get a semi-clean destroy to take place:

    // Destroy cropper
    $().cropper('destroy');
    //			$('#popup.upload .cropper-container').remove();
    //			$('#popup.upload img.cropper-hidden').removeClass('cropper-hidden');
    //			$('#popup.upload .preview img').remove();

Creating a new cropper completely fails at this point. Even with the "hacked" attempt.

**Comment by TheFilmGod** [comment]
Update. We were able to make a clean destroy by calling destroy and deleting the cropper's parent container from the dom. The entire parent container was recreated into the dom and a new cropper initialized.

Hopefully, a fix can be implemented to prevent such a work around though. Thanks!!

**Comment by fengyuanchen** [comment]
If you call the `replace` method with the same image url, it will not word. You can add a time stamp or any other search parameters to the image url to let it work.

**Comment by TheFilmGod** [comment]
Good point. But a timestamp WAS added to revalidate the cache. 

Nevertheless, this does not solve the issue with the destroy method completely not working properly.

**Comment by fengyuanchen** [comment]
What is the version you are using? 
We improved the `destroy` method in the v0.7.8.
