### ISSUE TITLE
Please add a `.cropper('getBlob', cb, ...)` method

### ISSUE THREAD

**Issue by dantman** [fengyuanchen/cropper#198]
I'm working with cropper with the intent of uploading the cropped images via XHR2 as a Blob.

Canvas elements have a [toBlob](https://html.spec.whatwg.org/multipage/scripting.html#dom-canvas-toblob) method that sends a Blob to a callback instead of a data URI. It's not universally supported (Firefox has it but not Chrome) however it can [be pollyfilled](https://github.com/blueimp/JavaScript-Canvas-to-Blob).

I'm not suggesting that cropper incorporate the pollyfill. But I would like to have a `getBlob` method that behaves the same as the `getDataURL` method, where the browser supports `canvas.toBlob`.

Then anyone who wants to use `getBlob` across browsers can just include the pollyfill.

**Comment by dantman** [comment]
((Note that the cropper I linked to doesn't actually work because it uses the dropped BlobBuilder. But it is still possible to pollyfill toBlob))

**Comment by dantman** [comment]
I implemented this in #200.

**Comment by fengyuanchen** [comment]
Thank you!
You can include a polyfill project (e.g., [canvas-toBlob](https://github.com/eligrey/canvas-toBlob.js)) before call `toBlob` if the browser does not support it, and then get blob like this:
```
$().cropper('getCroppedCanvas').toBlob();
```

**Comment by dantman** [comment]
Note that lack of toBlob means blob users need to implement the `image/jpeg set fillColor: #fff` handling themselves.
