### ISSUE TITLE
Set and limit the Image Preview size

### ISSUE THREAD

**Issue by Abdeljabar** [fengyuanchen/cropper#199]
I looked into the whole documentation and couldn't figure out how to set the image preview size. Any way to do that?

**Comment by fengyuanchen** [comment]
Preview size depends on the initial size of the preview element. If you set an `aspectRatio`, be sure to set the same aspect ratio to the preview element.

**Comment by Abdeljabar** [comment]
Actually the preview image does weird things. It doesn't really catch the real cropped image and it gets bigger when it should get smaller and vice-versa. Can I post the code here?

**Comment by ajibarra** [comment]
I am having problems also with the preview. When the image is cropped, it creates the img node for the preview with the whole image (data from whole image) and also width = 0 and height = 0

**Comment by fengyuanchen** [comment]
@ajibarra I'm sorry for this, I don't know how you use it.
