### ISSUE TITLE
Set min. Image size to Container or Cropper size

### ISSUE THREAD

**Issue by tilocgn** [fengyuanchen/cropper#201]
First of all I want to thank you for the awesome tool you created!! The update to version v0.8.0 came very handy and solved a lot of problems handling the image and made it a lot faster!

One problem I'm facing now is that the image can be zoomed smaller than the cropper itself. Is there a way to set the minimum image size to the size of the container so it won't be possible to use the cropper outside the image itself? It used to be that way before the update i think.

**Comment by fengyuanchen** [comment]
I know that you want some options like `minImageWidth` and `minImageHeight`. I will try to add them. Thank you~

**Comment by tilocgn** [comment]
Thanks for the quick reply. Do you have any idea when you will be able to add them? Or is there some kind of workaround for this like a small hack to realize that already? Thank you!

**Comment by gerrod** [comment]
@tilocgn - I've submitted a PR which adds this functionality, if you're interested.

https://github.com/fengyuanchen/cropper/pull/209

**Comment by tilocgn** [comment]
Thanks again @gerrod This worked for me!

**Comment by fengyuanchen** [comment]
@tilocgn You can try v0.9.0 now.

**Comment by tilocgn** [comment]
@fengyuanchen I will! Thank you again so much for updating your project and listening to the problems that people are having!! That's not to be taken for granted.
