### ISSUE TITLE
Unable to get data after rotate if crop is cleared

### ISSUE THREAD

**Issue by navneetccna** [fengyuanchen/cropper#202]
clear crop than rotate working but unable to get image data

**Comment by fengyuanchen** [comment]
`getData` or `getImageData`?

**Comment by navneetccna** [comment]
i am talking about "Get Data URL"

**Comment by fengyuanchen** [comment]
Of course you can't get Data URL after cleared, because it is not cropped any more.

**Comment by navneetccna** [comment]
but it is not right i want to only rotate image and get rotated data i dont want to crop

**Comment by navneetccna** [comment]
can we do this ?

if (support.canvas) {
        data = this.getData();
        var source = getSourceCanvas(this.$clone[0], this.image);

        if(data.width == 0) {
          data.width = source.width;
        }
        if(data.height == 0) {
          data.height = source.height;
        }

**Comment by fengyuanchen** [comment]
This is an image cropping plugin...

**Comment by navneetccna** [comment]
i know but why limiting it to only cropping when we can do lots of thing with that ?
