### ISSUE TITLE
Cropper gets wider and adjusts itself about 20px to the right after it loads (bootstrap modal, small size)

### ISSUE THREAD

**Issue by jaredreich** [fengyuanchen/cropper#203]
I believe this only occurs on small-width bootstrap modals. Try it for yourself on a mobile device in portrait mode on the bootstrap modal example on your demo page.

Notice the blank canvas on the left side, and the overflow on the right side.

![2015-02-23 12 34 02](https://cloud.githubusercontent.com/assets/8563847/6335374/5f1bd5a6-bb58-11e4-913a-6d8b2d1be6b9.png)

**Comment by fengyuanchen** [comment]
Because of the default value of the `minContainerWidth` option is `300`px.
