### ISSUE TITLE
Zoom on mobile is too sensitive

### ISSUE THREAD

**Issue by ravemir** [fengyuanchen/cropper#206]
Hello,

First of all, let me get this out of the way: great plugin! It's amazing how we had a couple of different use cases for an app we are building and in a couple of days we were able to make it work to near perfection. Keep at it!

Now, on to the problem: whenever I end up using the cropper on mobile devices, the zoom function is too sensitive, meaning the user has to pinch really carefully not to overshoot the intended zoom.

Heres the troublesome part: whenever this happens, there's a change we will zoom out beyond being able to zoom in. [Here](http://screencast.com/t/75O95Kul)'s a video that describes the issue and the [page](https://appsdev.outsystems.net/CropperSandbox/FixedCrop.aspx) that reproduces it.

I am going to workaround this by overriding the zoom function to stop zooming, should the size of the resulting image go below a certain size. May I suggest an option that allows us to configure this? Such as 'maxZoomOutLevel' or 'minZoomWidth/Height'?

**Comment by ravemir** [comment]
For reference, here is the edit directly on the cropper.js file:

```javascript
...
    zoom: function (delta) {
      var image = this.image,
          width,
          height;

      delta = num(delta);

      if (delta && this.built && !this.disabled && this.options.zoomable) {
        delta = delta <= -1 ? 1 / (1 - delta) : delta <= 1 ? (1 + delta) : delta;
        // Fix to stop infinite zoom in (only allow zoom out up to 15%)
        if(image.width * delta > 0.15*image.naturalWidth || image.height * delta > 0.15*image.naturalHeight) {
          width = image.width * delta;
          height = image.height * delta;
          image.left -= (width - image.width) / 2;
          image.top -= (height - image.height) / 2;
          image.width = width;
          image.height = height;
          this.renderImage(true);
          this.setDragMode('move');
        }
      }
    },
...
```

**Comment by fengyuanchen** [comment]
I had improved it in `src/js/change.js`, and it will be released soon.

**Comment by ravemir** [comment]
Awesome! Thanks!

**Comment by ravemir** [comment]
I'm sorry to reopen this, but I mistakenly

**Comment by fengyuanchen** [comment]
Every thing will be fine in next version.

**Comment by ravemir** [comment]
Got it! I'll fork your repo in the meanwhile, and stay updated with your pushes.

Thanks for the hard work!

**Comment by tilocgn** [comment]
@fengyuanchen Has this been fixed? In the demo of v0.9 you can still zoom so far out that the image disapears and it still is too sensitive on mobile.

**Comment by fengyuanchen** [comment]
@tilocgn Maybe something is wrong, I will try to fix it again.

**Comment by uxtx** [comment]
Thanks for knocking this out! Gonna pull down the update and use it in an angular directive I've created for cropper. Looking to open source it very soon.

**Comment by DAS-STIG** [comment]
Any update on this? It is still happening.

**Comment by elmogallen** [comment]
Still happening in December 2019

**Comment by elmogallen** [comment]
To clarify, the sensitivity is not an issue for me. Now it's just that it allows you to keep zooming, even though I set the viewMode: 1, so it should not allow zooming out further when the image fits in the container. (If I understand the setting correctly.)
