### ISSUE TITLE
Image cropping boundary limits?

### ISSUE THREAD

**Issue by toolsmith** [fengyuanchen/cropper#207]
In older versions the crop box was limited to the width and height of the photo.  In the latest version this no longer seems to be the case.  Any idea how I can restrict the crop box to the inside bounds of the image itself? I don't want users accidentally cropping outside of the image.

Thanks for a great script :)

**Comment by ravemir** [comment]
I second this. I believe there might be a way using the 'dragMove' option, but it's not clear what we can do even then.

An option seems to make sense.

**Comment by pineapple-thief** [comment]
Yeah, really miss this behaviour after upgrading

**Comment by harm-less** [comment]
I was searching for a similar functionality as well

**Comment by pineapple-thief** [comment]
I've solved issue for myself by writing custom event handler and assigning it to cropper built, dragmove, dragend events.
https://gist.github.com/pineapple-thief/5544b836fec4d05dae6f#file-gistfile1-txt

**Comment by tilocgn** [comment]
@pineapple-thief What version of the script are you using? It seems to me, that you are using an version below 0.8.

**Comment by pineapple-thief** [comment]
No, I'm on v0.8.0

2015-03-03 18:38 GMT+10:00 tilocgn <notifications@github.com>:

**Comment by toolsmith** [comment]
I'm on version 0.8.0 (Cropper v0.8.0)

Thanks,
-Paul

**Comment by jaredrada** [comment]
I'm also on v0.8 and it'd be great if we could fix this issue (without writing custom handlers).

**Comment by fengyuanchen** [comment]
Hi, all, I will try to limit it in the next version (coming soon).

**Comment by fengyuanchen** [comment]
Now you can try v0.9.0.

**Comment by toolsmith** [comment]
Thanks, I've updated to v0.9.0 but I receive this error now:

Uncaught TypeError: Cannot read property 'width' of undefined line (line
492 in cropper.js)

I've set the width and height of my image container...

Any thoughts?

Thanks,
-Paul
