### ISSUE TITLE
Zoom out with mouse issue

### ISSUE THREAD

**Issue by kotmatpockuh** [fengyuanchen/cropper#210]
Hello.

In my app i try to zoom in and out as in your demo, but i could only encrease my image: decrease i could not. I use angularJS, but this didn't mind: i'v created plunker without angularJS logic.

http://plnkr.co/edit/aeKdQZ8fmAh4UwsQtdRU?p=preview (use wheel, also you could try to use links)

`<script>
  $(document).ready(function() {
    $('.myimg').cropper();
  });
</script>`

could you please take a look? why i could not get my image smaller, only bigger with mouse scroll?
thank you

**Comment by kotmatpockuh** [comment]
hello.... please reply...

**Comment by hacfi** [comment]
@kotmatpockuh Keep in my this is an open-source project and peope do this for free. I don’t understand your issue. What do you mean by you can’t make the image smaller, only bigger? This library is for cropping images - that means cutting out a part of an image. It provides zooming in on the image. It doesn’t include zooming out (which doesn’t make much sense) if that is what you mean.

**Comment by hacfi** [comment]
If you just mean zooming out:
you’re using an older version of cropper: http://plnkr.co/edit/ea4r9mNfW18wiEF81Hle?p=preview

Please close the issue or explain in more detail what your issue is.

**Comment by kotmatpockuh** [comment]
great, thank you

**Comment by kotmatpockuh** [comment]
@hacfi one last question: could i somehow set background color of zoomed out image not to transparent, but let's say to #cecece ?

**Comment by hacfi** [comment]
@kotmatpockuh http://plnkr.co/edit/ea4r9mNfW18wiEF81Hle?p=preview You should learn how to use the Chrome Developer Toolbar or Firebug if you use Firefox.

```css
.cropper-modal {
  background: #cecece;
}
```

but your styles have to be AFTER cropper.css

**Comment by kotmatpockuh** [comment]
@hacfi before i tried that, but result cropped image was with cropper default background... will think deeper....

**Comment by kotmatpockuh** [comment]
Are you sure that zoom out works in 0.9.1 version?

**Comment by fengyuanchen** [comment]
Just disable the strict mode.

**Comment by kotmatpockuh** [comment]
@fengyuanchen it is not a solution...
