### ISSUE TITLE
How can I save Data URI to png file

### ISSUE THREAD

**Issue by rockers123** [fengyuanchen/cropper#212]
Firstly thank you for the awesome plugin. 

I have save the cropped data uri codes to an input feild. How can I save this as a png file using php?

Regards,
Rushenn

**Comment by hacfi** [comment]
@rockers123 Have a look at the example:
https://github.com/fengyuanchen/cropper/blob/master/examples/crop-avatar/index.html#L27-79
https://github.com/fengyuanchen/cropper/blob/master/examples/crop-avatar/crop.php

The crop.php provided in the example directory should work as long as you use the same fields as the example (https://github.com/fengyuanchen/cropper/blob/master/examples/crop-avatar/index.html#L37-40). And don’t forget `enctype="multipart/form-data"` on the `<form>` tag.

**Comment by fengyuanchen** [comment]
@rockers123 Your can transfer DataURI to Blob and upload with FormData, see #184.
