### ISSUE TITLE
minCropBoxWidth/Height should support scaled down/up images

### ISSUE THREAD

**Issue by romaincointepas** [fengyuanchen/cropper#213]
When original image used with cropper is being scaled up/down (ex: with a max-width:500px for an image with an original width of 1000px), cropper should take this into account: minCropBoxWidth/Height should reflect actual cropped zone dimensions, not the cropper size on screen.

PS: minWidth/Height worked as intented in previous versions.

**Comment by fengyuanchen** [comment]
`minWidth` / `minHeight` had been removed, and the `minCropBoxWidth` / `minCropBoxHeight` are not the same as them.

**Comment by romaincointepas** [comment]
Yep, the minWidth/minHeight behavior was really useful in my case though. (http://www.twitshot.com)

**Comment by fengyuanchen** [comment]
Sorry, we don't support  minWidth / minHeight any more. You can try the strict mode in v0.9.0.
