### ISSUE TITLE
请问下如何动态设置容器的尺寸

### ISSUE THREAD

**Issue by bjdgyc** [fengyuanchen/cropper#214]
你好，请问下如何动态设置容器的尺寸，我在初始完成后动态设置cropper-container的宽高，并不会起作用。
现在做一个裁切头像的应用，但是如果使用图片缩放功能，很容易出现黑边的问题。
如果设置成容器和图片比例相同，并且禁用图片缩放功能，正常情况下可以裁切，
但是在图片旋转后，容器尺寸与旋转后的图片就没法吻合，
请问能够在旋转图片后对容器尺寸进行动态修改吗，还是我的思路错了。
希望能够得到回复，谢谢。

**Comment by fengyuanchen** [comment]
限制图片缩放和平移，已经有很多人提这个问题了

**Comment by bjdgyc** [comment]
你好，不太明白你说的，可以给个简单代码示例吗，谢谢

**Comment by fengyuanchen** [comment]
容器是固定的，如果要改变，请注销后在重新初始化。
