### ISSUE TITLE
Problem with portrait pictures on mobile phones (android and iPhone)

### ISSUE THREAD

**Issue by JyTy** [fengyuanchen/cropper#216]
I'm having a huge issue with cropping portrait photos on mobile phones. both pictures have exif orientation equal to 6. But the problem is that if I upload a photo through iPhone it is displayed in portrait mode inside preview in cropper. So I rotate it inside the CropAvatar.php file and the crop is great...
But if I upload a photo through android phone it gets rotated for 90 degrees in preview mode for cropping, so it is displayed in landscape... The crop parameters I get (x, y) are reversed and the crop is not OK.

Anyone had the same problem? Any help would really be appreciated!

**Comment by fengyuanchen** [comment]
We cannot handle the EXIF Orientation right now.

**Comment by fengyuanchen** [comment]
As it is the same as #120, I have to close this.
