### ISSUE TITLE
Destroy freezes all other cropper instances on same page.

### ISSUE THREAD

**Issue by oceanwap** [fengyuanchen/cropper#217]
I have several croppers on same page and if I destroy anyone cropper instance area selector in all other instance freeze and i can't move area selector for them while zoom,destroy are working on other cropper instances.

**Comment by fengyuanchen** [comment]
What's the version?

**Comment by oceanwap** [comment]
Cropper v0.7.6

**Comment by oceanwap** [comment]
It looks like issue is fixed in latest version but can't use it because minHeight, maxHeight, minWidth, maxWidth are removed from new version. I would like to see it again in next version because it's really useful that you can only fix width and height may be flexible and also it was perfectly working.

Can you help me with the issue because I can't switch to latest because of missing feature minHeight, maxHeight, minWidth, maxWidth ? I don't want to waste your time on an old version but I would really appreciate your help.

**Comment by fengyuanchen** [comment]
Try [v0.7.9](https://github.com/fengyuanchen/cropper/releases/tag/v0.7.9). Here is the [docs](http://fengyuanchen.github.io/cropper/0.7.9/).

**Comment by oceanwap** [comment]
Thanks for help. It seems working now. 
I have seen latest version and it's rotation is better than earlier and also it's more optimized. I will use it in some other project but I will really appreciate if you implement those feature in latest version too, which you implemented in earlier version.
Thanks again.
