### ISSUE TITLE
Crop box can be moved outside image

### ISSUE THREAD

**Issue by max-mykhailenko** [fengyuanchen/cropper#218]
getImageData returns (it's correct)
```
height: 250
left: 34.64173640167364
top: 0
width: 240.71652719665272
```
getCropBoxData returns (it's correct)
```
height: 93
left: 9
top: 136
width: 93
```
But crop box is outside image (it's bug)
![screen shot 2015-03-04 at 4 59 19 pm](https://cloud.githubusercontent.com/assets/1213198/6485933/f4fa6ad6-c28f-11e4-9a2b-d7bd87ee3d6c.png)

**Comment by fengyuanchen** [comment]
It's the cause of EXIF Orientation, see #120.

**Comment by maiaz** [comment]
I have same issue with images without any EXIF data. basically, with any image it is possible for cropbox go out of picture boundaries... does any possibility exists to prevent this?

**Comment by MikeMatusz** [comment]
Also seeing the same thing after updating to the latest version.  It's nice that you can click outside the image boundary to start your selection, which wasn't possible in the older version, but the crop box itself should still be confined to the boundaries of the image.

**Comment by rossbearman** [comment]
This is the same issue as mentioned in #207. It makes the latest version of Cropper much more difficult to use for a lot of common use cases.

**Comment by max-mykhailenko** [comment]
`getCropBoxData` returns incorrect `left` parameter. `left` in example above must be minus ~`-20`

**Comment by fengyuanchen** [comment]
I had improved this in the v0.9.0.
