### ISSUE TITLE
Drag events don't distinguish between move/resize

### ISSUE THREAD

**Issue by MikeMatusz** [fengyuanchen/cropper#219]
Would it be possible to add an indicator to the drag events that would indicate what type of operation is being performed?  Right now there's no way to distinguish between whether the user is moving the cropbox, moving the image behind the cropbox, or dragging one of the handles to resize the cropbox.  I was trying to handle the dragmove event, but need to respond differently depending on whether they are resizing the crop area or moving it, but can't find any way to determine which is the case.  My event handler was attempting to work around the issue in #218, so if that gets fixed this may not be necessary for me, but would still probably be a helpful addition to your API.

**Comment by fengyuanchen** [comment]
You are right, maybe we can improve this next.

**Comment by fengyuanchen** [comment]
Hi, I had added "event.dragType" property to drag events in the latest version (v0.9.0).
