### ISSUE TITLE
cannot setCropbox Data when cropper loaded

### ISSUE THREAD

**Issue by faizytech** [fengyuanchen/cropper#221]
i want to load cropbox data automatically when cropper loaded.
tell me how to set cropbox data in the below code 

$dataX = $('#dataX'),
        $dataY = $('#dataY'),
        $dataHeight = $('#dataHeight'),
        $dataWidth = $('#dataWidth'),
        $dataRotate = $('#dataRotate'),
		$image = $('.img-container > img');
    	$image.cropper({
      guides: false,
      highlight: false,
      dragCrop: false,
      movable: false,
      resizable: false,
	  crop: function (data) {
            $dataX.val(Math.round(data.x));
            $dataY.val(Math.round(data.y));
            $dataHeight.val(Math.round(data.height));
            $dataWidth.val(Math.round(data.width));
            $dataRotate.val(Math.round(data.rotate));
			$('#cropvalueurl').val($image.cropper("getDataURL", {
  width: 268,
  height: 195
},"image/jpeg"));
          },		  
    });

**Comment by fengyuanchen** [comment]
```js
$image.cropper({
  ...
  build: function () {
    $image.cropper('setCropBoxData', {
      ...
    });
  }
});
```

**Comment by dvreed77** [comment]
I needed to set built, not build

```
$image.cropper({
  ...
  built: function () {
    $image.cropper('setCropBoxData', {
      ...
    });
  }
});
```

**Comment by fengyuanchen** [comment]
It is my mistake. It should be `built`.
