### ISSUE TITLE
How to start the cropper...

### ISSUE THREAD

**Issue by AntonTrapp** [fengyuanchen/cropper#223]
As there is no support forum, or anything like that I can't make sure if this is a major bug or the documentation is wrong or I am just stuipid:

```
<div id="cropperDiv">
  <img data-ng-src="http://s3.amazonaws.com/******.png?*****" src="http://s3.amazonaws.com/*****.png?*****">
</div>
```
waiting for the image to load. Opening Firebug console (so that I can be sure that everything is really finished for this test):

```
$('#cropperDiv > img').cropper({aspectRatio: 16 / 9, crop: function(data) { console.log("*****CROP*****"); } });
```

The image exists - $('#cropperDiv > img') is working - so no typo. But the cropper call does nothing at all. How do I start the cropping process? According to the documentation I should not need to do anything else, right?

bower installation (cropper#0.8.0 with jquery#2.1.1).

Tried ngCropper too, does nothing at all too.

**Comment by peterchibunna** [comment]
Did you try setting the `autoCrop` property to `true`?
```
$('#cropperDiv > img').cropper({aspectRatio: 16 / 9, autoCrop: true, crop: function(data) { console.log("*****CROP*****"); } });
```

**Comment by AntonTrapp** [comment]
No. Should be true by default.

**Comment by claaslange** [comment]
I've had a similiar problem today. In my case there was a problem with cross-origin policies. After I enabled ``Access-Control-Allow-Origin`` on the server the cropper started working as it should.

**Comment by peterchibunna** [comment]
@AntonTrapp, can you open the developer console and check for errors?

**Comment by AntonTrapp** [comment]
empty. Switched to another cropper as I needed to continue my work. But claaslange could be right, the image came from a different location. Maybe it is possible to update that in the docs with a big blinking warning if this happens more often (amazon S3, ...) - could be helpful to new users.

**Comment by fengyuanchen** [comment]
@AntonTrapp All right, I will add a cross-origin image using notice to the document.

**Comment by AntonTrapp** [comment]
Sounds great!
