### ISSUE TITLE
convert the pre-loaded images into base64 to reuse

### ISSUE THREAD

**Issue by chennamadhu** [fengyuanchen/cropper#224]
In my application after saving the original image and cropped image area, and again after refresh, i will be pre-loading the saved original image and show the cropped area that was saved, so here when the original image is pre-loaded i want the image to be in base64 to reuse to apply cropper.

can you please help me on this.

**Comment by fengyuanchen** [comment]
I am sorry, I don't really understand it.

If you want to restore a cropper, you should save both of the image data and the crop box data, and then:
```
$image.cropper({
  built: function () {
    $image.cropper('setImageData', savedImageData);
    $image.cropper('setCropBoxData', savedCropBoxData);
  }
});
```

**Comment by chennamadhu** [comment]
yes for the restore a cropper am doing the same thing, but when I preload the saved original image then the image am getting it as URL format, but for the cropper it should be base64 dataURL format na, so when pre-loading the saved original image how to convert the image URL to base64 dataURL.

**Comment by fengyuanchen** [comment]
You can search for a third party tool to do this.

**Comment by lucaspanik** [comment]
If your intention is get the Base64, use:
```javascript
$image.cropper('getCroppedCanvas').toDataURL("image/jpeg", 0.9);
```
Example:
```javascript
var $image = $(".image-crop > img");
$($image).cropper({
   crop: function(e) {
      var canvas = $image.cropper('getCroppedCanvas');
      var dataURL = canvas.toDataURL("image/jpeg", 0.9);
      console.log(dataURL); // or  window.open(dataURL);
   }
});
```
