### ISSUE TITLE
Crop area shouldn't be bigger than the image

### ISSUE THREAD

**Issue by garygreen** [fengyuanchen/cropper#225]
I think when the image is resized, the croppable area should resize itself to match the width/height of the image IF the image becomes smaller than the crop box. With the current method, it causes issues:

1. Your not really cropping anything at all in the image below, it shouldn't technically be allowed.
2. Introducing a blank area around the image
3. It causes issues on mobile -- try using the "Cropper with fixed crop box" on the demo site on your mobile, making the image smaller. You'll eventually lose the image and won't be able to get it back again.

![capture](https://cloud.githubusercontent.com/assets/1702638/6579792/6844334c-c744-11e4-82d4-d93b7608745d.PNG)

I can try and create a PR to this, if your open to the idea?

**Comment by tilocgn** [comment]
Please do! That would help a lot because there are many people asking for this very issue! 

The min-width or min-height of the image should be the height or width of the image container depending which one is shorter. The cropper should not be able to be moved outside this area.

This would also fix the problem on mobile which was already partly fixed by @gerrod in #209. His code helped on a static image container but on a responsive container there are still problems.

**Comment by gerrod** [comment]
I'm only using a static crop box (it's all we need for our project), but I've made some other modifications that may be of interest too:

1. Don't allow the image to be zoomed out such that it's smaller than the crop box
2. Don't allow the image to be dragged beyond the bounds of the crop box

This means that the user _cannot_ crop the image with any "whitespace" - i.e. the resulting image is always the right aspect ratio. Here's a screenshot; this is the smallest that the image can be zoomed, and it cannot be dragged left or right any further (as it would be violate the aspect ratio):

![2015-03-11_1958](https://cloud.githubusercontent.com/assets/865932/6594037/46ad299c-c829-11e4-9bac-a2b969899830.png)

If there's any interest, I'll tidy up the code a bit and put together another PR.

**Comment by tilocgn** [comment]
Yes, please share your code so maybe I can adapt some of it. It might be kind of tricky because you are working with a static cropper but maybe it's possible to change the min-width to the size of the image container. Thanks @gerrod!

**Comment by gerrod** [comment]
OK no worries; I'll try and put something together for a PR but if you just want the crux of the code, here's how I achieved the above by overriding the `zoom` and `renderImage` methods of cropbox:

    function overrideZoomAndRender() {
        // Adjust the zoom method so that the cropper can't zoom out to be smaller than the minimum image size.
        cropper.zoom = function(delta) {
            var image = this.image,
                width,
                height,
                maxDeltaWidth,
                maxDeltaHeight;

            delta = parseFloat(delta);

            if (delta && this.built && !this.disabled && this.options.zoomable) {
                delta = delta <= -1 ? 1 / (1 - delta) : delta <= 1 ? (1 + delta) : delta;

                // If we're zooming out, make sure the image doesn't get smaller than the cropbox
                if (delta < 1) {
                    var cropBoxData = this.getData();
                    maxDeltaWidth = cropBoxData.width / image.naturalWidth;
                    maxDeltaHeight = cropBoxData.height / image.naturalHeight;

                    delta = Math.max(delta, Math.max(maxDeltaWidth, maxDeltaHeight));
                }

                width = image.width * delta;
                height = image.height * delta;

                image.left -= (width - image.width) / 2;
                image.top -= (height - image.height) / 2;
                image.width = width;
                image.height = height;
                this.renderImage(true);
                this.setDragMode("move");
            }
        };

        // Don't allow dragging outside the boundaries of the image
        var originalRenderImage = cropper.renderImage;

        cropper.renderImage = function (changed) {
            if (changed) {
                var cropBoxData = this.getCropBoxData();
                var image = this.image;

                image.left = Math.min(image.left, cropBoxData.left);
                image.top = Math.min(image.top, cropBoxData.top);

                var cropBoxRight = cropBoxData.left + cropBoxData.width;
                var cropBoxBottom = cropBoxData.top + cropBoxData.height;

                if (image.left + image.width < cropBoxRight) {
                    image.left = cropBoxRight - image.width;
                }

                if (image.top + image.height < cropBoxBottom) {
                    image.top = cropBoxBottom - image.height;
                }
            }

            originalRenderImage.call(this, changed);
        };
    }

**Comment by garygreen** [comment]
Awesome @gerrod. I would definitely like to see a PR for that

**Comment by fengyuanchen** [comment]
Please try the new strict mode in the v0.9.0.
