### ISSUE TITLE
fillColor does not appear to fill up the background color of the image

### ISSUE THREAD

**Issue by geekyme** [fengyuanchen/cropper#226]
When I write the code as shown to grab the image and filling ```fillColor```

![image](https://cloud.githubusercontent.com/assets/977460/6592960/6de05892-c80e-11e4-8825-4d57958d5c78.png)

The generated image does not appear to have the stated background. Instead, it shows a transparent background.

**Comment by geekyme** [comment]
![image](https://cloud.githubusercontent.com/assets/977460/6593001/f6f90e30-c80e-11e4-9288-ff524187d085.png)

**Comment by fengyuanchen** [comment]
I am sorry, the `fillColor` option had added to the `src/js/methods.js` file, but hasn't been released yet.

**Comment by fengyuanchen** [comment]
v0.9.0 had released.

**Comment by tilocgn** [comment]
The fillColor is not showing up in my cropped image. I use v0.9 and strict-mode. When I rotate the image and get the cropped canvas the background is black. I use the following code:

```javascript
$().cropper('getCroppedCanvas', { fillColor: '#FFFFFF' });
```

**Comment by fengyuanchen** [comment]
@tilocgn I works.

**Comment by tilocgn** [comment]
@fengyuanchen Thanks a lot for the update to v0.9.1. Now besides the zoom and the the reset function, the fillColor work as well! All my problems are fixed :+1: Love it!

**Comment by PavanMadala** [comment]
@fengyuanchen Is there any way to generate the image with brightness control. ? I am in the requirement of adding brightness control option to the image. 
Please help.

**Comment by fengyuanchen** [comment]
@PavanMadala See #585.

**Comment by PavanMadala** [comment]
Thank you so much for the reply fengyuanchen.

But, I am unable to use both the cropper and CamanJS together. Either one is working other one is not yet all working.
Please find the attached zip file contains my source code.
It would be very great full if you can apply the brightness here.

Thanks in advance.

-PavanMadala.

**Comment by jonathanleemc** [comment]
Hi yuanchen, if I'm working on a later version of cropperJS, can I still somehow change the fill color of an cropped image?

**Comment by fengyuanchen** [comment]
@jonathanleemc You can set `fillColor` in the `getCroppedCanvas` method. read the doc for more detail.

**Comment by nirav-panchal** [comment]
For me fillcolor property is not working. i am using 1.0.0 - rc version

**Comment by fengyuanchen** [comment]
@nirav-panchal As of v0.9.0, the `getDataURL` had been removed, please `getCroppedCanvas` instead.
