### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by garygreen** [fengyuanchen/cropper#227]
Let's say your img has a native resolution of 1000x1000 but you don't want to actually display the cropper at 1000x1000 as it's quite a big cropper, so you want only 500x500. You change your code like below:

```html
<div class="image-container" style="width: 500px; height: 500px;">
   <img src="my-1000x1000-image.jpg"/>
</div>
```

Now all your cropping values are based on 500x500 when you call functions like `$().cropper('getData')` -- there should be an option to allow you to have values calculated based on the original true scale of the image, not what's actually being displayed in the browser.

This is one major thing that's stopping me from using this awesome plugin. Coincidentally, another similar plugin JCrop uses the concept of [true image size](http://deepliquid.com/content/Jcrop_Sizing_Issues.html) which makes sense. Maybe I'm missing something here and cropper does already support this?

**Comment by fengyuanchen** [comment]
The output cropped data is computed with the natural image size all the time, please read the document carefully or check the demo carefully.

**Comment by garygreen** [comment]
I just checked my code again and I think it's because I'm setting a `width` and `height` on my `<img` tag which isn't the natural width and height of the image.... How does cropper decide what the 'natural' side is for the image?

**Comment by garygreen** [comment]
Yep, glad I missed something. It is calculating the right scales. One thing that isn't working quite right though is calling `$('img').cropper('getData')` in my really [simple example version](https://github.com/garygreen/cropper-test). I get an error in console:

    Uncaught TypeError: Cannot read property 'rotate' of undefined

**Comment by fengyuanchen** [comment]
I had tested your demo, it is okey, not any error.

**Comment by leo4all** [comment]
I had the same issue, with this snippet but locally.

http://bootsnipp.com/user/snippets/oPy2n

**Comment by woprrr** [comment]
We have an similar error only with 2.3 version of cropper on ImageWidgetCrop integration for Drupal 8.
![capture d ecran 2017-03-22 a 11 59 22](https://cloud.githubusercontent.com/assets/8972139/24194621/0791974a-0ef7-11e7-8768-eba4e31885b8.png)

**Comment by alejandroiglesias** [comment]
I'm having the same error: `Cannot read property 'rotate' of undefined` when trying to call `cropper.rotate(-90)`. @garygreen @leo4all @woprrr did you solve the issue? How?
