### ISSUE TITLE
Image is rotated at the backend but no effect on preview

### ISSUE THREAD

**Issue by fawadahmad** [fengyuanchen/cropper#228]
Hi,
Ive found this plugin few days earlier as an awesome solution to my requirement of uploading image with crop, rotate and zoom options. Its working alright on desktop. But on mobile (android chrome and native browser), when I try to rotate the image, there is no effect on selection pane and preview, but when image is saved, its rotated. Means rotation is working at the backend but not updating frontend for user. Hence cropping a false selection.
Can anyone help please....
Thanks.

**Comment by fengyuanchen** [comment]
Does your browser support CSS3 [Transforms3d](http://caniuse.com/transforms3d)?

**Comment by fawadahmad** [comment]
Thanks for the quick suggestion. Updating chrome on android and now its fine.
