### ISSUE TITLE
crop: data crops more than CropBoxData specifies

### ISSUE THREAD

**Issue by dfherr** [fengyuanchen/cropper#231]
When i'm using setCropBoxData my crop: function(data) methods data object returns 10 less x value than the getDropxBoxData method returns.

How is that happening? As i want to hide/show my cropper and reopen it with the previous cropBox this causes it to jump 10 to the left each time.

**Comment by fengyuanchen** [comment]
The crop box data is actual, bases on the container, but the cropped data bases on the original image size.
