### ISSUE TITLE
setCropBoxData does not work with fixed aspectRatio

### ISSUE THREAD

**Issue by dfherr** [fengyuanchen/cropper#232]
I can not move the CropBoxData when a aspectRatio is set.

Setting the aspectRatio after specifying the CropBoxData resets the crop box to default area with given aspect ratio...

a moveCropBox method would solve this issue pretty easily.

**Comment by fengyuanchen** [comment]
The aspect ratio of a provided crop box data must be the same as the set aspect ratio.

**Comment by dfherr** [comment]
couldn't you make it, it still works but simply uses x + width and then calculates the appropriate y + height if the given cropboxdata is off the set aspect ratio? It's really not obvious whats going wrong there, as it doesn't work because of small rounding errors (e.g. aspect ratio 4/5 with 200 width / 251 height won't work).

**Comment by fengyuanchen** [comment]
I can't reproduce this. It's fine in my demo.
