### ISSUE TITLE
Problems with strict mode

### ISSUE THREAD

**Issue by AlexRieger** [fengyuanchen/cropper#242]
I'm having Problems with the strict mode.

When I set the strict mode to true then Images that do not fit in the aspect ratio of the canvas are resized to fill the canvas but then leaving out parts of the image.
Simple example: If you try to upload a square image into a rectangle canvas the image fills the width of the canvas but top and bottom part of the image are cut off.
Similar is happening when rotating. I have buttons that rotate the image by 90 degrees. If you rotate a landscape image in a landscape canvas the image becomes portrait and the same thing as with the square image happens: width fits canvas, top and bottom p art are cut off.

If I set strict to false the image isn't automatically fit to the width of the canvas, so I have - stick with the square image in the rectangle canvas - left and right of the image the blank background. So far so good. But what now happens is, that the user can select blank space which I do not want. Another issue in this setup is the following: I save the position of the crop area (getData function) so if the user wants to change the cropped area he can start where he left last time. This works well in mode strict. With mode strict and my favorite example - square image, rectangle canvas - the left part of the position is miscalculated as it starts from the canvas and not from the image.

What I need is sort of a combination of strict and non-strict. Actually strict would do, if the images would not be refitted and cut off.

Besides from that it is a very, very great plugin and I hope I am making any sense here, I've been writing this after 3hrs of debugging tries and my head is a little dizzy right now.

**Comment by boustanihani** [comment]
I think your issue is somehow related to mine, check: https://github.com/fengyuanchen/cropper/issues/238

would be glad to hear your feedback...

**Comment by fengyuanchen** [comment]
Nothing is almighty. If you don't go forward, you still can use [v0.7.9](http://fengyuanchen.github.io/cropper/0.7.9/) for your case.
