### ISSUE TITLE
'options.minContainerHeight' test fails

### ISSUE THREAD

**Issue by filipp-qoma** [fengyuanchen/cropper#243]
Hi!
I tried to build Cropper with grunt, and 'options.minContainerHeight' has failed. I checked properties of container and figured, that in
```
assert.ok(Math.round(container.height) === minContainerHeight);
```
container.height equals to 221. 
I think checking as 'greater-or-equal' will be more correct. Some thing like this (I'm not an expert of QUnit):
```
assert.ok(Math.round(container.height) >= minContainerHeight);
```
The same thing in 'options.minContainerWidth' test.
Thank you for your attention.

**Comment by fengyuanchen** [comment]
It's my fault. Thanks!

**Comment by filipp-qoma** [comment]
Oops, I was wrong in my suggestion.. Sorry. I figured the reason of test only now xD
Good work!
