### ISSUE TITLE
Functionality to prevent dragging image beyond the cropbox borders

### ISSUE THREAD

**Issue by marcolz** [fengyuanchen/cropper#244]
Currently it's possible to drag the image (or the cropbox, based on `movable` config) beyond the cropbox borders; hence allowing for cut/partial images to be generated.

Is there an option to avoid that from happening? I tried them all unsuccessfully.

**Comment by filipp-qoma** [comment]
Did you try strict mode?

**Comment by StragelX** [comment]
Same problem, is there a posibility to make an image, non-dragable?

**Comment by marcolz** [comment]
@filipp-qoma I tried, but I actually had to rollback to 0.8, as 0.9 was stretching the cropbox to a full width oval. - I'll try again later today and keep you posted. Thanks for now!

**Comment by marcolz** [comment]
Essentially same issue described #245
