### ISSUE TITLE
Reset does not rotate image to original position

### ISSUE THREAD

**Issue by t-marxi** [fengyuanchen/cropper#246]
Hi, the lib is great, but I found some issue - for me If I pressed reset, I will want to rotate image original position.
For fix I suggest next code to add to 'reset' function before calling "this.renderCanvas();":
"     his.image.rotate = 0;
      this.rotated = true;"
It fixed this problem.

**Comment by tilocgn** [comment]
Thank you, works like a charm! I was missing this feature in v0.9 too. You have a little typo in your code, here is the corrected version:

```javascript
this.image.rotate = 0;
this.rotated = true;
```

**Comment by fengyuanchen** [comment]
It's my fault. Thank you very much!
