### ISSUE TITLE
Data corrupted pm getDataURL with mime type

### ISSUE THREAD

**Issue by navneetccna** [fengyuanchen/cropper#250]
This is my code
var image_cropper = $('img.cropper');
image_cropper.cropper("rotate", 90);
image_cropper.cropper("getDataURL",image_mime_type);

After rotation i want image data and when i am doing that image corrupted some time it is happening randomly

**Comment by navneetccna** [comment]
And this is only happening in Mozilla i checked in chrome its working fine

**Comment by filipp-qoma** [comment]
Hi @navneetccna, could you please provide some screenshots of your results?

**Comment by fengyuanchen** [comment]
Call the methods after built:
```
var image_cropper = $('img.cropper');

image_cropper.cropper({
  built: function () {
    image_cropper.cropper("rotate", 90);
    image_cropper.cropper("getDataURL",image_mime_type);
  }
});
```

**Comment by navneetccna** [comment]
My original image like this
![test0](https://cloud.githubusercontent.com/assets/210475/6840814/ad366836-d3a5-11e4-89f6-42ca0d253d08.png)
After 2-3 rotation in mozilla it become like this
![test1](https://cloud.githubusercontent.com/assets/210475/6840819/be318dc8-d3a5-11e4-875f-d927ce65070d.png)

**Comment by navneetccna** [comment]
@fengyuanchen already tried this but same issue in mozilla

**Comment by fengyuanchen** [comment]
@navneetccna What's the version of your browser/system?

**Comment by navneetccna** [comment]
Firefox 34.0 Ubuntu

**Comment by fengyuanchen** [comment]
That may be the problem of the browser's canvas.
