### ISSUE TITLE
Make default zoom step configurable

### ISSUE THREAD

**Issue by jakuub** [fengyuanchen/cropper#251]
If I understand correctly, then this is the place, where the zoom on scrool is made: 
https://github.com/fengyuanchen/cropper/blob/master/src/js/handlers.js#L59

Is it possible to create configuration for the default zoom step, which is now 0.1? It will be very helpful for us, because we need smoother zoom in our project. 

I know, it is possible to implement it by ourself, and also make smoother zoom by buttons or other custom calls of the zoom method, but I think, this is a good to have it configurable in general.

Thank you :-)

**Comment by anik786** [comment]
+1 . I was just going to make a post on this. For the time being how can you do this manually anyway.

**Comment by jakuub** [comment]
One possibility is maybe to listen to the same mouse wheel event and call zoom function manually. 

I didn't try that and maybe the easiest solution for us will be to remove cropper from bower dependences and include it directly into the repository and edit it directly in the code, because we are working on the project, which will be running only during the april, and then will be over. 

But if we are working on long-term project which should be more maintainable, we will go the way with custom event listener, or create pullrequest for the cropper library.

**Comment by arne-slabbinck** [comment]
I have the same problem. This is the way i dirty-quick-fixed it in cropper.js in following code:

    zoom: function (delta) {
        .....

        if (zoomEvent.isDefaultPrevented()) {
          return;
        }

        delta = delta / 2 ;

        delta = delta <= -1 ? 1 / (1 - delta) : delta <= 1 ? (1 + delta) : delta;

        .......
    },

I divided delta by 2 to decrease the zoom sensitivity, you can devide it by more/less to adjust.
Again, dirty & quick cause things had to go fast.

**Comment by fengyuanchen** [comment]
As of v0.11.0, a new option `wheelZoomRatio` has been added. Thank you all!
