### ISSUE TITLE
PARSERERROR (what doing wrong?)

### ISSUE THREAD

**Issue by nywuctuk** [fengyuanchen/cropper#252]
Examples work good. But after i moved code to my project, something PARSERERROR appeared when I try use it (on click save button).
How i use it:
1) require_once html body code from '/cropper/examples/crop-avatar/index.html'); 

2)I moved css and js files in my folders and loaded it:

	< link href="css/cropper/bootstrap.min.css" rel="stylesheet">
	< link href="css/cropper/cropper.min.css" rel="stylesheet">
	< link href="css/cropper/main.css" rel="stylesheet">

	<script type="text/javascript" src="js/cropper/jquery.min.js"></script>
	<script type="text/javascript" src="js/cropper/bootstrap.min.js"></script>
	<script type="text/javascript" src="js/cropper/cropper.min.js"></script>
	<script type="text/javascript" src="js/cropper/main.js"></script>

screenshoot: http://pixs.ru/showimage/Screenshot_8282159_16699130.jpg

**Comment by fengyuanchen** [comment]
It may be a problem of your PHP code...

**Comment by nywuctuk** [comment]
Its not.
I use  Yii, in profile's view a have this php code
<?php require_once(dirname(__FILE__).'/cropper/examples/crop-avatar/index2.html'); ?>
And it work successful.

I need know what is mean this error (paresererror)?

**Comment by fengyuanchen** [comment]
The response content must be JSON, if not, jQuery will throw a pareser error.
