### ISSUE TITLE
strict:false croparea shift

### ISSUE THREAD

**Issue by OlegsKlujs** [fengyuanchen/cropper#255]
v0.9.1
When setting **strict:false**, the coordinates of the cropbox shift:

![preview](https://cloud.githubusercontent.com/assets/11734310/6915796/93c61e64-d797-11e4-9d71-d9a39b18931f.png)
```javascript 
cdata: Object
  height: 37
  left: 223.5
  top: 93.625
  width: 58
```
which theoreticly could be adjusted, i.e. :
```javascript 
var canvasData2 = $image.cropper('getCanvasData');
var cropBoxData2 = $image.cropper('getCropBoxData');

var x1=cropBoxData2.left-canvasData2.left
var y1=cropBoxData2.top-canvasData2.top
```
this helps with small pictures, but if the picture is larger then the container, this fix fails.

**Comment by fengyuanchen** [comment]
Why don't you just use the strict mode?

**Comment by OlegsKlujs** [comment]
Because then the picture is zoomed then. See https://github.com/fengyuanchen/cropper/issues/245.
The issue isn't closed.
