### ISSUE TITLE
What is left and top in Get Image Data result?

### ISSUE THREAD

**Issue by radoslavius** [fengyuanchen/cropper#256]
Hello,

If rotate is 0, left and top are 0 too. But if rotate != 0, for example, if I set up in demo rotate=45, then left is 40.... and top is 208.... I don't understand.

I use this plugin for rotating and cropping photos for a graphical editor that rotates according to the upper left corner, so I need to perform certain calculations. In version 0.8.0 me it worked correctly in this conversion - http://www.stofko.cz/rotace, but if I download the newer version, so it generates different data.

Thanks for explanation

**Comment by fengyuanchen** [comment]
The left/top of the image is relative to the canvas (image wrapper). Just ignore them.
