### ISSUE TITLE
Can't use percentage instead of pixel for the position of the crop box with setCropBoxData

### ISSUE THREAD

**Issue by KhaledElAnsari** [fengyuanchen/cropper#258]
I'm trying make the crop box position a little bit responsive by adding a percentage value instead of pixel to it's position using the setCropBoxData but it's not working.

Any idea how to make it responsive? and if there's not can you please make it possible in the next update?

**Comment by fengyuanchen** [comment]
As the crop box moves by pixel, it  **cannot accept** any percentage value.
