### ISSUE TITLE
PARSE ERROR

### ISSUE THREAD

**Issue by larsklein** [fengyuanchen/cropper#260]
Hi Feng,

no matter what I do, its giving me the following error:

XHR finished loading: POST "XXX/crop.php".
index.php parsererror...SyntaxError: Unexpected token <...[object Object]

I can't see any further details. I'm using your original code of "crop-avatar". CHMOD is set to 777 for testing usage.
What could the problem be or how can I enable more detailed error reporting?

Looking for help...

**Comment by nywuctuk** [comment]
https://github.com/fengyuanchen/cropper/issues/252 
(parsererror, but another situation - no solution yet)

**Comment by larsklein** [comment]
@nywuctuk Mine looks same but after XHR comes the parseError

XHR finished loading: POST "###/user.file.crop.php".
index.php:2836 
parsererror...SyntaxError: Unexpected token <...[object Object]

**Comment by fengyuanchen** [comment]
@larsklein The "crop.php" should return valid JSON only.

**Comment by larsklein** [comment]
@fengyuanchen I uploaded your whole git, set chmod to 777 for crop.php and the image directories, it doesn't work. Do I need any other CHMOD to 777? Anything else what I need to notice? I haven't changed anyhting!

**Comment by fengyuanchen** [comment]
@larsklein Check your PHP version / HTTP server.

**Comment by fengyuanchen** [comment]
Maybe you don't have permission to create folder in you PHP server, you can try the v0.9.2.
