### ISSUE TITLE
setting initial crop value

### ISSUE THREAD

**Issue by jpalach** [fengyuanchen/cropper#261]
Hi, I want to set initial crop data (related to original image) but there is no longer support for setData() function. I am doing as follow:

						//initCrop - my crop data to set

						var imgData = $imageToCrop.cropper('getImageData');
						var canvasData = $imageToCrop.cropper('getCanvasData');
						
						var cropBox = {
								left : (imgData.width / imgData.naturalWidth) * initCrop.left + canvasData.left,
								top : (imgData.width / imgData.naturalWidth) * initCrop.top + canvasData.top,
								width : initCrop.width * imgData.width / imgData.naturalWidth, 
								height : initCrop.height * imgData.height / imgData.naturalHeight
							} 
						$imageToCrop.cropper('setCropBoxData', cropBox);

but, it works well only with rotate = 0. Shouldn't be function like this built in cropper?

**Comment by choxy** [comment]
I just updated from 0.6.0 version and I am a bit confused that setData() is not there anymore. I have stored data from getData() and need to edit previous crop - so what is the meant way of setting initial crop (based on previous getData()) ?

**Comment by fengyuanchen** [comment]
@choxy You can try this:

```js
var $image = $('img');

$image.cropper({
  built: function () {
    var cropData = previousCropData, // Get by "getData" method
        scaled = {},
        scaledRatio,
        imageData,
        canvasData;

    if ($.isPlainObject(cropData)) {
      imageData = $image.cropper('getImageData');
      canvasData = $image.cropper('getCanvasData');
      scaledRatio = imageData.width / imageData.naturalWidth;

      $.each(cropData, function (key, val) {
        scaled[key] = val * scaledRatio;
      });

      $image.cropper('setCropBoxData', {
        left: scaled.x + canvasData.left,
        top: scaled.y + canvasData.top,
        width: scaled.width,
        height: scaled.height
      });
    }
  }
});
```
