### ISSUE TITLE
Image does not zoom out enough to crop full image

### ISSUE THREAD

**Issue by anik786** [fengyuanchen/cropper#263]
There is a major issue with the current  image cropper plugin as it is as shown in: http://fengyuanchen.github.io/cropper/

When you try to crop most images, you will not be able to crop the full image.

For example lets take this image as an example:
http://www.online-image-editor.com//styles/2014/images/example_image.png

If I zoom out as much as I can, and make the crop box as big as you can also, you will get something like this:
![cropper](https://cloud.githubusercontent.com/assets/5897460/7032783/fb82f6f0-dd6c-11e4-938c-21a1a901c506.png)

But note that I should be able to crop this image further as there is space at the bottom right corner and there is more to the image as demonstrated by dragging the image up:

![cropper 1](https://cloud.githubusercontent.com/assets/5897460/7032867/9970f092-dd6d-11e4-8b06-1cdb9f61e02e.png)

A potential solution is to put "strict mode off" but that means the user can crop beyond the image, which I don't want.

The only way I have found to fix this is if you specify the width and the height of the image as the same aspect ratio as the original image. (In this case 475x360 or any image with aspect ratio 475/360)

However you website design can break, especially if you have large images or a responsive layout.

What the dev teams need to do is change the strict mode of the cropper to match the appearance of the non-strict mode (so you can zoom out as much as you can), but still maintain the strict behaviour ( i.e. no cropping beyond the crop box)
 
Can you please fix this issue as soon as possible!!! Or if anyone has any solutions please post them.

Thanks!

**Comment by fengyuanchen** [comment]
The strict mode had been improved in v0.9.2.

**Comment by anik786** [comment]
Thanks I'll check it out :-)!
