### ISSUE TITLE
Mac OS Safari: cropper didn't called 100% times

### ISSUE THREAD

**Issue by kotmatpockuh** [fengyuanchen/cropper#265]
Hello. I have strange bug. Only in mac os in safari cropper sometimes didn't work.
Sometimes works, sometimes no. (also, i use angularjs):
```
        element.bind('load', function() {
          $image = undefined;
          $timeout(function() {
            $image = element;
            originalData = {};
            $image.cropper({
              multiple: true,
              aspectRatio: attrs.aspectRatioVal,
              data: originalData
            });
          }, 500);
        });
```

**Comment by fengyuanchen** [comment]
Please update to the latest version (the `multiple` and `data` options had been removed).

**Comment by kotmatpockuh** [comment]
@fengyuanchen 

https://github.com/fengyuanchen/cropper/issues/210#issuecomment-89206860

i do not want to do that... why? read in link above...
zoom didn't work

also new version still didn't work always in safari

**Comment by BigCatStuff** [comment]
Hi, I have also run into a similar issue with Cropper v0.9.1 and Safari 7.1.5 on Mac OS, where Cropper would not load with a "Cross-origin image load denied by Cross-Origin Resource Sharing policy" error shown in the console. I verified that my CORS settings were correct on Amazon S3, and the exact same code worked on both Chrome and Firefox.

From the code that @kotmatpockuh provided it seems that they ran into the same issue that I had, where I was loading an image by XHR and then initializing Cropper on the loaded image (bound to the load event). It seems that Safari might mishandle the handling of 'crossorigin' attributes on img tags, even if CORS headers allow it.

To workaround the issue for Safari, I prevented Cropper from adding the 'crossorigin' attribute to the image with some code like this in cropper.js:

```
 217       if (!isSafari()) {
 218         crossOrigin = ' crossOrigin'; // crossOrigin="anonymous"
 219       }
```

I hope this information helps you.

**Comment by kotmatpockuh** [comment]
@BigCatStuff  `Cross-origin image load denied by Cross-Origin Resource Sharing policy`

**Comment by kotmatpockuh** [comment]
http://stackoverflow.com/questions/29793005/angularjs-and-element-load-bug-in-safari

seems that something with angular load event...

**Comment by thebucknerlife** [comment]
@kotmatpockuh any luck with solving this? @fengyuanchen I'm having the same issue - crossOrigin does not work in Safari but works in other browsers.

**Comment by thebucknerlife** [comment]
I was able to figure it out - I was using 9.1 instead of 9.2 which had fixes for crossOrigin.

@fengyuanchen The CDN suggested is one version old. Might be worth noting it isn't always up to date - would have saved me 4-5 hours of debugging.

**Comment by thebucknerlife** [comment]
Thanks!

**Comment by fengyuanchen** [comment]
This had been fixed (#271) in `src/js/load.js` and will be released soon.

**Comment by kotmatpockuh** [comment]
@fengyuanchen when you ~ plan to make release?

**Comment by fengyuanchen** [comment]
[v0.9.3](https://github.com/fengyuanchen/cropper/releases/tag/v0.9.3) has released!
