### ISSUE TITLE
How to get the zoom amount?

### ISSUE THREAD

**Issue by zilions** [fengyuanchen/cropper#266]
The function `getData()` can get everything about the image besides its current zoom level. 
Is it possible to get this?

**Comment by fengyuanchen** [comment]
Use `getImageData` method:
```
var image = $('img').cropper('getImageData');

image.zoomLevel = image.width / image.naturalWidth;
```

**Comment by zilions** [comment]
@fengyuanchen - I'm getting the zoom level (using your above method( and then using the same number to set the zoom using `zoom()`. Unfortunately this is not setting the zoom level as it originally was?

**Comment by fengyuanchen** [comment]
···
var image = $('img').cropper('getImageData');

$('img').cropper('zoom', (image.naturalWidth - image.width) / image.width);
···
