### ISSUE TITLE
Scaling Issue

### ISSUE THREAD

**Issue by ilovecoffee** [fengyuanchen/cropper#27]
It would be a great addition if you implement a solution for very large image inside a fixed container. See [Jcrop's box sizing method](http://deepliquid.com/content/Jcrop_Sizing_Issues.html).

Use case:
Let's say a user uploads a file to the server. Once uploaded, you open up the modal and display the image inside the modal so the user can select desired cropping selection.

**Comment by jessicamarx** [comment]
I can verify that this behavior is not happening for me.

When I load an image larger than the cropper, it reports irregular cropping boundaries.

**Comment by beezee** [comment]
Yeah I don't see this working either. minCropBoxHeight > container height does not appear to recognize scaling.
