### ISSUE TITLE
Javascript error when destroying "empty image" cropper

### ISSUE THREAD

**Issue by tinpont** [fengyuanchen/cropper#272]
I'm using bootstrap modal to crop image.

```html
                <div id="cropper-container">
                    <img class="img-responsive" src="">
                </div>
```

```javascript
var cropperImage = $('#cropper-container > img');
modal.on('show.bs.modal', function (e) {
                cropperImage.cropper({
                    aspectRatio: 1,
                    autoCropArea: 1,
                    dragCrop: true,
                    zoomable: false,
                })
}).on('hidden.bs.modal', function () {
                cropperImage.cropper('destroy').removeAttr('src');
})
```

When user open modal and close without upload anything, it will show javascript error 
`Uncaught TypeError: Cannot read property 'off' of undefined    cropper.js:1089`

BTW, sometimes if you fast enough, scroll image when cropper initializing, `zoomable` parameter will lose effectiveness.

**Comment by johnbacon** [comment]
It appears that this fix has not yet been built into the dist files. See: https://github.com/fengyuanchen/cropper/blob/ee684d92bee2cc8ac9255f3998fcbdb9dcce93db/dist/cropper.js#L1089

I have run into the same issue, and adding the fix to the dist file fixes it as expected.

**Comment by fengyuanchen** [comment]
@johnbacon Yes, it's not released, but you can build it yourself with Grunt .
