### ISSUE TITLE
[Request] Making crop area movable without making the image movable

### ISSUE THREAD

**Issue by hasandogu** [fengyuanchen/cropper#273]
First things first, great work with the plugin!

I need to create a cropper where the image will not be zoomable and movable but the crop area will need to be movable and resizeable. However, I don't want to create a new crop area when clicked outside the current one.

So, I enabled strict, disabled dragCrop and zoomable but I can still move the image. Is there a way to keep the image position locked while keeping the crop area movable?

Thanks a lot

**Comment by filipp-qoma** [comment]
Hi @hasandogu!
Did you try to prevent dragMove event with dragType == 'move'?

**Comment by hasandogu** [comment]
Thanks @filipp-qoma,

That was exactly what I needed. In my options, I defined the following 

    dragmove: function (event) {
        if (event.dragType == 'move') {
            event.preventDefault();
        }
    },

For your other note:

I just tested on the demo page again without zooming or rotating the image without the following options and I can move both the image and the cropper area.

![image](https://cloud.githubusercontent.com/assets/10977151/7279095/48917b8a-e8ce-11e4-83c2-82b20f2da96c.png)
