### ISSUE TITLE
Non-movable cropbox is moved on aspect ratio change if zoomed/rotated

### ISSUE THREAD

**Issue by hasandogu** [fengyuanchen/cropper#276]
I am using the plugin in a mobile app and implementing the option to crop the image using different aspect ratios like in the demo page. I am using strict mode with zoomable and rotatable enabled and dragCrop, movable and resizable disabled.

Switching between aspect ratios changes the cropbox position if the image is zoomed or rotated.
Is it possible to implement an option to make it so that the cropbox is always centered (at a fixed relative maximumsize) in the container and the image behind is moved/scaled instead of the cropbox?

**Comment by fengyuanchen** [comment]
Call `reset` first before call `setAspectRatio` method.
