### ISSUE TITLE
Bug: Unexpected cropbox size change with corner point movement in 'free' aspect ratio

### ISSUE THREAD

**Issue by hasandogu** [fengyuanchen/cropper#277]
I could only reproduce this with the 'free' aspect ratio

On the demo page:
1. Set the aspect ratio to 'Free'
2. Move the cropbox to the bottom left of the image
3. Pull the SW or NW corner towards left, observe the width of the cropbox increase.

I have seen this with the other corners changing the height of the image as well.

**Comment by hasandogu** [comment]
Seems like this can be the range checks were missing minTop and minLeft.

     @@ -146,7 +146,7 @@
          }

          if (range.y <= 0) {
    <<<            if (top > 0) {
    >>>            if (top > minTop) {
              height -= range.y;
              top += range.y;
            }
    @@ -183,7 +183,7 @@
          left += range.X;
        } else {
          if (range.x <= 0) {
    <<<            if (left > 0) {
    >>>            if (left > minLeft) {
              width -= range.x;
              left += range.x;
            } else if (range.y <= 0 && top <= minTop) {
    @@ -195,7 +195,7 @@
          }

          if (range.y <= 0) {
    <<<            if (top > 0) {
    >>>            if (top > minTop) {
              height -= range.y;
              top += range.y;
            }
    @@ -231,7 +231,7 @@
          height = width / aspectRatio;
        } else {
          if (range.x <= 0) {
    <<<            if (left > 0) {
            if (left > minLeft) {
              width -= range.x;
              left += range.x;
            } else if (range.y >= 0 && bottom >= maxHeight) {

**Comment by fengyuanchen** [comment]
Awesome! It is my mistake, I will fix it soon. Thank you very much!
