### ISSUE TITLE
Crop image behavior with transparent background images. 

### ISSUE THREAD

**Issue by ShankarKadam** [fengyuanchen/cropper#278]
Hello! 
Thank you for your great cropper plugin!
I am facing some problem with transparent images. Cropper tool is taking white background by default for images. If any logo is consist of while letters with no background/ transparent background  then logo is taking white background. In case of white letters like 'ii_logo_white.png' images is displaying completely white. I think transparent images should take transparent background instead of white while cropping it into your plugin. For more details please try to upload attached images.

Thanks,
Shankar Kadam 

![ii_logo_white](https://cloud.githubusercontent.com/assets/5096757/7294305/9c082344-e9c9-11e4-972a-37831365d8c5.png)
![logo-without-the-background-transparent](https://cloud.githubusercontent.com/assets/5096757/7294318/bf4eb138-e9c9-11e4-8429-012d11b09aa3.jpg)

**Comment by ShankarKadam** [comment]
Adding one more transparent image..
![chinmay](https://cloud.githubusercontent.com/assets/5096757/7294793/11bde598-e9ce-11e4-9235-938f56e5bc9f.png)

**Comment by fengyuanchen** [comment]
What is the cropper version you are using?

With latest version, if the image is a background transparent png image, then the cropped image is the same too.
```js
var croppedCanvas = $('img').cropper('getCroppedCanvas');
var croppedImage = croppedCanvas.toDataURL(); // png
```

**Comment by ShankarKadam** [comment]
I am using Cropper v0.8.0...
