### ISSUE TITLE
Strict Mode Bug

### ISSUE THREAD

**Issue by anik786** [fengyuanchen/cropper#280]
There is a bug with the strict mode. 

If you zoom in and make the box really big, then zoom out the crop box can go over the image.

![cropper-bug-1](https://cloud.githubusercontent.com/assets/5897460/7310256/fb48c1f4-ea20-11e4-9ca0-b35552d97d44.png)
![cropper bug 2](https://cloud.githubusercontent.com/assets/5897460/7310257/fb4bdb64-ea20-11e4-9341-b77c77fb5743.png)

**Comment by fengyuanchen** [comment]
Thank you!
