### ISSUE TITLE
setData for restore cropper positions (without workarounds)

### ISSUE THREAD

**Issue by estudiogenius** [fengyuanchen/cropper#281]

**Comment by fengyuanchen** [comment]
`setCanvasData` + `setCropBoxData` = `setData`

**Comment by fengyuanchen** [comment]
Or, `getImageData` + `getCropBoxData` + `setCropBoxData` = `setData`, see #261.

**Comment by fengyuanchen** [comment]
[v0.9.3](https://github.com/fengyuanchen/cropper/releases/tag/v0.9.3) implements `setData` now.

**Comment by estudiogenius** [comment]
Aewwwww yeahhh!!
