### ISSUE TITLE
Is it possible to disable the drag?

### ISSUE THREAD

**Issue by juliandormon** [fengyuanchen/cropper#282]
Thanks for your great plug-in!

I was hoping it was possible to disable the drag event. When on a small mobile device, scrolling the page is interrupted if you accidentally swipe over an image with the cropper applied.

I would like to show the crop boundaries when the page loads but lock all of the functions until the user specifically unlocks an element to begin cropping. This would prevent scrolling conflicts.

I am able to stop the drag by using e.preventDefault(); but that bubbles up to the window and also prevents the page from scrolling.

It would be great if this was another option like, movable: false.

Thanks for your help.

**Comment by fengyuanchen** [comment]
Use the `disable` and `enable` methods:

```js
$('#img').cropper({
  built: function () {
    $(this).cropper('disable');
  }
});

$('#btn').click(function () {
  $('#img').cropper('enable');
});
```

**Comment by juliandormon** [comment]
Awesome! Thanks. I just saw that. Don't know how I missed that in the docs.
