### ISSUE TITLE
Zoom Out wont go beyond size of cropBox

### ISSUE THREAD

**Issue by araskin** [fengyuanchen/cropper#283]
I am using the mouse wheel to zoom in and out. I have noticed that once the cropbox width is equal to the width of the image it wont continue to zoom out. This makes it impossible to fit the image inside of the cropBox. Perhaps there is a settings I need to set to allow this?

This is how i init my cropper
```js
$image.cropper({
  aspectRatio: 4 / 3,
  //autoCropArea: 0.5,
  responsive: true,
  highlight: true,
  resizable: true,
  zoomable: true,
  crop: function(data){
    menuModel.imageUpload.cropBoxData = data;
  }
});
```

Any thoughts?

**Comment by fengyuanchen** [comment]
Set the `strict` option with `false`:

```js
$image.cropper({
  aspectRatio: 4 / 3,
  strict: false,
  crop: function(data){
    menuModel.imageUpload.cropBoxData = data;
  }
});
```

**Comment by araskin** [comment]
Thank you.
