### ISSUE TITLE
Changing Preview container

### ISSUE THREAD

**Issue by tlemmons** [fengyuanchen/cropper#285]
I have setup different div's to handle different aspect ratios.  When I change aspect in script I also try to change preview location.  The change in aspect works great, however the change to the class name for preview does not.  Here is my code.  Am I doing it wrong?

       mine.cropper({
            aspectRatio: 16 / 9,
            strict: false,
            autoCropArea: 1,
            dragCrop: false,
            background: true,
            preview:'.L1080',
            fillColor: "#010010",
            crop: function (data) {
                // Output the result data for cropping image.
            }
        });

I pass 'P1080' or 'L1080' which matches my two div's class.
       function setFrame(ratio,preview) {
            mine.cropper("setAspectRatio", ratio);
            mine.cropper("preview", preview);
            return false;
        }

The preview starts out in the L1080 div correctly but then does not change.

**Comment by fengyuanchen** [comment]
The `preview` is not a method..

**Comment by tlemmons** [comment]
Is it possible to change its destination at all?

-Tom

**Comment by fengyuanchen** [comment]
I'm afraid not.

**Comment by Getitdan** [comment]
Is there any workaround to change the preview location? I must do it too.
I want to "freeze" one preview and start another one. I would appreciate any solution. By the way, thanks for this amazing plugin!

**Comment by tlemmons** [comment]
That is exactly what I wanted to do also.

**Comment by fengyuanchen** [comment]
You can try to customize your own preview by using `change.cropper` event in v0.10.0.
