### ISSUE TITLE
IE issue: IE9 file select 

### ISSUE THREAD

**Issue by istvanskeri** [fengyuanchen/cropper#287]
When i'm on this page http://fengyuanchen.github.io/cropper/ and i upload a file using IE9 the image appears almost instantaneously without making an ajax call. 

I also downloaded the https://github.com/fengyuanchen/cropper/tree/master/examples/crop-avatar example and when I upload an image it has to submit the form to crop.php and only then does the image appear. 

Can you explain why these two are different? Thanks

**Comment by fengyuanchen** [comment]
Are you sure you can find the upload button on the [demo](http://fengyuanchen.github.io/cropper/) page with IE9? Because only [IE10+ support Blob URLs](http://caniuse.com/#search=Blob%20URLs).

**Comment by istvanskeri** [comment]
You are correct. My mistake. I am on IE10 now and the cropper example still doesn't allow Blob URLs. 

in main.js at init i do:

alert("file list:"+this.support.fileList);
alert("blob url:"+this.support.blobURLs);

both return false

**Comment by istvanskeri** [comment]
I'm also experiencing the same issue on safari, yet when i go to http://fengyuanchen.github.io/cropper/  i see the upload

**Comment by fengyuanchen** [comment]
Only [Safari 7+ support Blob URLs](http://caniuse.com/#search=Blob%20URLs).
