### ISSUE TITLE
crossOrigin 'anonymous' doesn't work in minified code on Safari

### ISSUE THREAD

**Issue by thebucknerlife** [fengyuanchen/cropper#288]
I discovered today that the `crossOrigin = 'anaonymous'` support for img tag CORS doesn't work in the minified version of the cropper (9.2).

When I use the unminified version it works. No other difference. Breaks in Safari.

**Comment by fengyuanchen** [comment]
Because #271 changed the `dist/cropper.js`, but I have not release the update.

**Comment by thebucknerlife** [comment]
@fengyuanchen Thank you
