### ISSUE TITLE
Plugin not working in certain cases

### ISSUE THREAD

**Issue by elizardi** [fengyuanchen/cropper#289]
Hi!

I started working a couple of days ago with Cropper but I have a particular problem.  

If I initialize the plug in between "script"  tags (outside any function) it works as intended but if I put inside a jQuery or JavaScript event/function(  $("#element").click or <button onclick="">  for example ) I get "$(...).cropper is not a function"  error.  

What can it be the problem?

Thanks in advance and congratulations for this amazing plug in!

Eneko.

**Comment by fengyuanchen** [comment]
Can you paste a few code of your deno here?

**Comment by elizardi** [comment]
I've been reviewing my code and I've found the error.  

I'm working in a Rails app and apparently it auto-imports Javascript and CSS files but what didn't notice is that someone has put another <script type="text/javascript" src=jquery.min.js> line at the bottom of some pages.  

After removing it works fine.  Thanks for Cropper and your help!
