### ISSUE TITLE
Can read crop data with getData; but there's no setData?

### ISSUE THREAD

**Issue by DanTup** [fengyuanchen/cropper#290]
(Edit: see next comment, this was slightly incorrect!)

I don't believe scaling is being handled correctly. I load an image that is 640x200 into the cropper (where the container is deliberately different, so the image is scaled) and then set the crop box to 320x100 (a quarter of the image area), but the crop box is incorrectly drawn at the equivilent of 409x128 on the image.

It appears that setCropBoxData is assuming the values are screen/canvas pixels, and not image pixels. This seems wonky to me, and the README even says:

> The outputing cropped data bases on the original image size, so you can use them to crop the image directly.

I've tried various methods, and cannot find any that give the correct coordinates. I'm sure I'm doing something wrong; because others seem to be using this without issue (and if this is a bug, it seems quite serious); but I'm unable to figure out what.

JSFiddle here:
http://jsfiddle.net/kd0omk3b/1/

![Screenshot](https://cloud.githubusercontent.com/assets/1078012/7474065/fa429c48-f336-11e4-8801-bc2800ef239f.jpg)

**Comment by DanTup** [comment]
So; I just noticed that there's a getData as well as getCropBoxData. This returns the coordinates I want.

However, I cannot find an equivalent set method. If I want to switch between some different types of crops; how can I feed data back from getData back into the cropper to restore a set of data?
(I do not have the ability to store other types of data, as we store only the image pixel coords/size in the database).

**Comment by fengyuanchen** [comment]
v0.9.3 implements `setData` now.
