### ISSUE TITLE
Chance of supporting without jQuery?

### ISSUE THREAD

**Issue by geekyme** [fengyuanchen/cropper#291]
This is by far the best frontend image cropping tool, however it depends on jQuery which adds significant weight to a page bundle. I was wondering if there are efforts to make free cropper of its jQuery dependency?

**Comment by nchase** [comment]
I'd love to see this too.

I opened #111 on the same topic a long time ago.

I think the work is doable, particularly now that  the repo has a bunch of tests to help detect regressions. :smile_cat:

I would open a pull request proposing a changeset myself if I had time to do the work.

**Comment by geekyme** [comment]
Yep. Being framework agnostic helps to improve this tool even more! People can use it without fearing the extra overheads. @fengyuanchen

**Comment by fengyuanchen** [comment]
Thank you both! I will try it if I have more time.

**Comment by vinnymac** [comment]
I found this tool to be the best option as well. However my site does not use jQuery and I would love to use this if it did not depend on it. Seeing as this tool has tests, and is available on many package managers I think the community would embrace it even more if it dropped jQuery. Thanks for considering it @fengyuanchen

**Comment by vinnymac** [comment]
For anyone interested, I made some progress with removing jQuery. Take a look at [the fork here](https://github.com/vinnymac/cropper/tree/rm-j).

**Comment by vinnymac** [comment]
I removed jQuery from the source, and have all the tests passing. There is still work that can be done to clean up, and the tests could have jQuery removed from them as well. I also cleaned up the demo page, to make this fork useable. No documentation yet, but it should be pretty self explanatory if you understand how to use this plugin already.

```javascript
// original
$image.cropper('getCanvasData');

// becomes

// fork
var cropper = new Cropper(image);
cropper.getCanvasData();
```

So if anyone needs a jQuery free version give my fork a shot.

**Comment by hellier** [comment]
@vinnymac could you update the demo as well (from the jQuery dependency). Took me a while to figure out you hadn't done so.

**Comment by vinnymac** [comment]
@hellier I mention this in the comment above yours. I have a work in progress branch for the demo where jQuery is barely used. It will be merged in soon. However the demo has bootstrap as a dependency, jQuery cannot be entirely removed without removing bootstrap as well.

**Comment by hellier** [comment]
@vinnymac Is the bootstrap dependency just a bunch of CSS?

**Comment by vinnymac** [comment]
@hellier nope, it is also a jQuery plugin. Check the bottom of the index file where the bootstrap script tag is found. I have merged in my changes and now jQuery is only being used to display the modals and the tooltips. Otherwise everything is native.

Next I will be looking into upgrading from 0.9.3.

**Comment by vinnymac** [comment]
Added all changes from v0.10.0 to the fork.

**Comment by fengyuanchen** [comment]
@vinnymac Good work. What about the browser support? BTW, You also need to update your documentation and examples.

**Comment by geekyme** [comment]
Bumping this thread. I noticed there wasn't any follow up for removing jquery dependency.

**Comment by fengyuanchen** [comment]
[CropperJS](https://github.com/fengyuanchen/cropperjs) is available for this.

**Comment by geekyme** [comment]
Yay!! Looks like u did a rewrite of the code without jquery
