### ISSUE TITLE
cropBox.maxWidth and cropBox.maxHeight doesn't get updated

### ISSUE THREAD

**Issue by tquensen** [fengyuanchen/cropper#293]
calling setCropBoxData fails when the dimensions are larger the the maxWidth/maxHeight values that were calculated in initCropBox.

Those values dont get updated/recalculated.

In my situation, the maxHeight was limited by the canvas height. After zooming in, the canvas height is larger, but the maxHeight from cropbox stays too low.

Changing this.limitCropBox(false, true); in render.js line 346 to this.limitCropBox(true, true); and move it to line 334 fixed this for me

**Comment by fengyuanchen** [comment]
In strict mode, the maxWidth/Height of the crop box depends on the canvas's size.
