### ISSUE TITLE
Blank image on mobile with canvas.toDataUrl()

### ISSUE THREAD

**Issue by geekyme** [fengyuanchen/cropper#294]
I am using getCroppedCanvas in the following manner: 

```
var canvas = this.cropper.cropper('getCroppedCanvas', {
        width: 160,
        height: 160
      });


var image = canvas.toDataURL("image/jpeg");

$image.attr('src', image)
```

However, all i'm seeing is a empty 160x160 data url image. Am I doing something wrongly?

The problem only exists on mobile with pictures taken from my iPhone 6 camera (high megapixels). Desktop works perfectly fine.

**Comment by jonnylevy** [comment]
I am having the exact same issue. I get a blank image on my iPhone 5 in Safari. Strangely it works with the front-facing camera (albeit rotated incorrectly but im aware of the exif issue) but when I try with the back-facing camera, I just get a blank image at the correct dimensions. 

It works absolutely fine on the iPhone when using photos from my photo library and also fine on desktop.

What is causing this and is there a solution?

Thanks

**Comment by jonnylevy** [comment]
I'm on iOS 8.1 btw

**Comment by geekyme** [comment]
OMG lol. U are right it works on front facing camera but failed on back facing! I am using the same iPhone.

**Comment by geekyme** [comment]
Sorry I am on iPhone 6. iOS V 8.3. 
The same behavior happen on both mobile chrome and safari; back facing camera failed, front works. Lmfao

**Comment by tareqlol** [comment]
I faced this issue with iOS devices has limited memory issue , when you are cropping an large Image ( IPhone camera resolution) a canvas will be generated with the dimensions of the crop area and then it will generate an image with the given cropped dimensions. 

during this process the browser crash. 

All you have to do is to resize the image (something below 1000px wide) before you apply the cropper on it. 

https://developer.apple.com/library/mac/documentation/AppleApplications/Reference/SafariWebContent/CreatingContentforSafarioniPhone/CreatingContentforSafarioniPhone.html

**Comment by jonnylevy** [comment]
Thank you @tareqlol . You are absolutely right, great solution!

FYI, I used this library: https://github.com/gokercebeci/canvasResize to resize the original photo and then applied the cropper and now it works!

**Comment by tareqlol** [comment]
(y) , canvas resize can cause losing image quality , i used a php resizer :) , good thing that it works now :D

**Comment by tilocgn** [comment]
Thank you for the research and coming up with a solution! This will help a lot since I was facing the same problem and had no clue where to start. @tareqlol, would you mind sharing your code here? That would really kickstart my efforts in solving this!

**Comment by tilocgn** [comment]
@jonnylevy @tareqlol It would be great if ou could share some of your code or give some more insights in how you solved the problem. That would be really appcreciated! :thumbsup:

**Comment by tareqlol** [comment]
All you have to do is to check if you are on mobile to send the image to an action to resize it. 

Check if the width of the image is larger 1000 or the height is larger than 1000 and also you are

```javascript
if($(window).width < 768 && ($(image).height() > 1000 || $(image).width() > 1000)){
// send the image to backend to resize it. 
// once it is ready get it from the backend and apply the cropper on it 
}
```
backend resize:
http://php.net/manual/de/imagick.resizeimage.php

**Comment by geekyme** [comment]
Create 1 level of indirection by drawing the image on a small canvas. Then extract the image and apply it to cropper.

**Comment by tareqlol** [comment]
@geekyme  it is a good solution but larger images on the iphone would break if you are using canvas resizing.

**Comment by goldnuggets24** [comment]
You guys rock! I'm having this exact same issue. So it sounds like re-sizing below 1000px prior to cropping is the best solution here. Much appreciated!

**Comment by marvambi** [comment]
Hello guys.
Please I'd love to see a full script that works fine.
Just started front-end design.
Thanks

**Comment by tilocgn** [comment]
How do you guys feel about checking if it is an iOS system in addition to checking the image size and if on mobile. This way you dont need to lower the quality if not really needed.

```javascript
if ( (/iP(hone|od|ad)/).test(window.navigator.platform) && ($(window).width < 768 && ($(image).height() > 1000 || $(image).width() > 1000)) ) {
	// send the image to backend to resize it. 
}
```

**Comment by crown-cc** [comment]
Thank you for your sharing. I want to ask if there are any other ways.
 canvas resize can cause losing image quality

**Comment by tareqlol** [comment]
@crown-cc  : you can use a php image re-sizer instead. http://www.imagemagick.org/script/index.php
