### ISSUE TITLE
CropBox gets resized if image aspectRatio is wider than canvas aspect ratio

### ISSUE THREAD

**Issue by tquensen** [fengyuanchen/cropper#295]
I am using the following settings:
autoCropArea: 1,
modal: false,
guides: false,
highlight: false,
background: false,
movable: false,
resizable: false,
rotatable: false,
aspectRatio: 3,
minCropBoxWidth: 1200,
minCropBoxHeight: 400,
minContainerWidth: 1200,
minContainerHeight: 400,
minCanvasWidth: 1200,
minCanvasHeight: 400

When loading an image, the image is zoomed in/out to fill the full width of the container.

If the aspect ration of the image is wider than the AR of the canvas, the image doesn't completely fill the canvas. If strict mode is active, this behaviour will resize the cropBox.

If the image AR is wider than the canvas AR, the image should be zoomed to 100% of the container HEIGHT instead of WIDTH to fill the container, so that the canvas and cropbox can stay at full size

I couldn't completely figure out where this behaviour is defined... probably somewhere in renderCanvas and/or limitCanvas

I tried to work around this issue by manually zooming in inside the built callback and then setting the cropBox to full size, but this doesn't work as intendes (as described in #293)

**Comment by fengyuanchen** [comment]
Thanks! There is an error when computes the canvas.minWidth/Height sizes.

**Comment by tquensen** [comment]
Thanks, looks good now
