### ISSUE TITLE
Can't get the preview rendered

### ISSUE THREAD

**Issue by dstollie** [fengyuanchen/cropper#298]
For some reason the preview is not getting rendered, all the other things work as espected so I dont understand what im doing wrong.

These are my cropper options:

```javascript
cropperOptions: {
		aspectRatio: 1,
		preview: ".img-preview",
		autoCropArea: 0.65,
		strict: false,
		guides: false,
		highlight: false,
		dragCrop: false,
		movable: false,
		resizable: false
	}
```

and this is the html

```html

    <!-- Wrap the image or canvas with a block element -->
    <div class="image-crap-container">
        <img src="">
    </div>

    <div class="img-preview preview-md"></div>

```

**Comment by dan-leech** [comment]
initPreview on lines 744-748
data takes before img sets, and data.height = 0
move set data sizes after html() setting

**Comment by dstollie** [comment]
@dan-leech do you mean i have to switch the img-preview div with the image-crap-container div.. like this: 

```html

   <!-- Wrap the image or canvas with a block element -->
    <div class="image-crap-container">
        <img src="">
    </div>

    <div class="img-preview preview-md"></div>
```

**Comment by dan-leech** [comment]
no
it's in source of plugin. The cropper plugin don't get img size correctly.

**Comment by dan-leech** [comment]
my correction is:
 var html = $this.html();
            $this.html('<img src="' + url + '" style="display:block;width:100%;min-width:0!important;min-height:0!important;max-width:none!important;max-height:none!important;image-orientation: 0deg!important">')
            .data(CROPPER_PREVIEW, {
                width: $this.width(),
                height: $this.height(),
                original: html
            });

**Comment by metalcro** [comment]
I tried what @dan-leech posted, but to no avail. @dstollie , any luck?

**Comment by fengyuanchen** [comment]
You should set width and height to the preview container:
```css
.preview {
  width: 200px;
  height: 200px;
}
```
