### ISSUE TITLE
Option to disable double click from switching crop mode and move mode

### ISSUE THREAD

**Issue by stephanegigandet** [fengyuanchen/cropper#299]
Hello,
Would it be possible to add an option to disable double click?
If would like users to always stay in crop mode.
Thanks!

**Comment by fengyuanchen** [comment]
v0.10.0 supports this, see the `doubleClickToggle` option. Thanks!

**Comment by stephanegigandet** [comment]
Wonderful, thank you very much!

**Comment by scotticus** [comment]
Can this be re-enabled? I don't see this option in the current version, and it would be very useful.

**Comment by fengyuanchen** [comment]
@scotticus See the `toggleDragModeOnDblclick` option.

**Comment by nop33** [comment]
I set the `toggleDragModeOnDblclick` option to `false` but it still switches from drag to crop mode on double click.
