### ISSUE TITLE
Initiating a drag and drop inside a not movable crop area should create a new area

### ISSUE THREAD

**Issue by stephanegigandet** [fengyuanchen/cropper#300]
If the movable option is set to false, starting a drag and drop inside an already defined crop area moves the image below (even when we are in crop mode). I would expect a new drag and drop area to be created instead.

**Comment by fengyuanchen** [comment]
Awesome!  We will support it in next version.Thank you!

**Comment by stephanegigandet** [comment]
Great, thank you!
