### ISSUE TITLE
Option to disable movable image

### ISSUE THREAD

**Issue by rafalp** [fengyuanchen/cropper#302]
I would like cropbox to be only movable element in my crop interface, but it seems like there's no setting for that currently?

**Comment by gfpacheco** [comment]
Hi, I too would like to have this option. I'll try to open a pull request for it

**Comment by gfpacheco** [comment]
I opened #306 but I'm not sure if it's the best way to do it or even if it's working in all cases.
I asked for feedback to improve the PR and I hope we could add this to the master soon

**Comment by shawou** [comment]
I'm very interested by this option too !
As a possible workaround while this is being dealt with :
Comment line 1823 to 1826 of cropper.js

**Comment by M3kH** [comment]
:+1:

**Comment by fengyuanchen** [comment]
The `movable` is only available for image now. and `cropBoxMovable` just for crop box. see v0.10.0.
