### ISSUE TITLE
How change style of class=preview-sm

### ISSUE THREAD

**Issue by nywuctuk** [fengyuanchen/cropper#303]
Trying change css - help only at start. When i start add new img - start work the startCropper function (193 line in main.js) and img changes to blob and  style of 'preview-sm' changes too. It depended from aspectRatio but i want different sizes for big and small previews.
If i add code like this: 
<pre>$( "div.avatar-preview.preview-sm" ).css({
				"width": "50px",
				"height": "50px",
			}).each(function(){
				console.log('it work!');
			});</pre>
in the end of startCropper function, it work but partly. Sizes of 'preview-sm' stil wrong...

**Comment by nchase** [comment]
this is an entirely different issue from the one you originally opened. it's a better practice (and easier for maintainer to understand if you make a new unique issue for each question/concern you have.

**Comment by fengyuanchen** [comment]
We don't support this, but you may custom the preview by yourself with the events.

**Comment by nywuctuk** [comment]
<b>solution:</b>
This code added in the cropper.js in the end of function prototype.preview (line 677)
