### ISSUE TITLE
Cropped image is not showing before page reload in bs modal. It saves first opened image does not destroy the old image and not showing the cropped on.

### ISSUE THREAD

**Issue by muradhassan** [fengyuanchen/cropper#308]
I have used fengyuanchen/cropper v0.9.2 for image crop and rotation in bootstrap modal. It's working fine for both crop and rotation but problem is that it saves the first image in modal even after crop, suppose I have opened an image in modal, crop it, save it(from the server) and dismiss the modal. Then if I open the image again it is showing the old image not the cropped one. But if I reload the page then it is showing cropped one. Below is some code that I have used.

 $(document).on('click', '.original_image_show', function() { //click on the image 
var data_original = $(this).find('img').attr('data-original');/ //get the src to to crop
 // #originalImageShow is the modal div's id.
$("#originalImageShow").find(".bootstrap-modal-cropper img").attr('src', data_original); //set the src of bootstrap modal from clicked image's src.

var $image = $('.bootstrap-modal-cropper > img');
$('#originalImageShow').on('shown.bs.modal', function() {
      //-----cropping code here-----
        }).on('hidden.bs.modal', function() {
    $image.cropper('destroy');//I have used this code to destroy the modal.
 });

**Comment by alefbetta** [comment]
muradhassan , do u save img like in DEMO example? how u pass the data to php file for saving ??

**Comment by muradhassan** [comment]
Hi alefbetta, thank you for your reply. I have solved the problem. It was for caching of image. When I click the image first, then browser cached the image and next it shows the old image from cache not the cropped one.

var data_original = $(this).find('img').attr('data-original');  //get the src to to crop
var data_original = data_original+ '?'+Math.random()*Math.random();
 // #originalImageShow is the modal div's id.
$("#originalImageShow").find(".bootstrap-modal-cropper img").attr('src', data_original); //set the src of bootstrap modal from clicked image's src.

I did not save image like DEMO example, I have used <b>ThumbHandler</b> php library, but modified the class because existing class has no rotation option.

**Comment by alefbetta** [comment]
muradhassan thanks for reply. 
The problem is that i cannot send data to php file using DEMO example.  i get parseerror.
It would be useful if cropper Creator just update the DEMO example with PHP file for saving the cropped image. Then we will see a proper sample of how it should be...

**Comment by muradhassan** [comment]
Hi alefbetta,
You can try this:
----------------------------------------
          aspectRatio: 16 / 9,
          preview: '.img-preview',
          crop: function (data) {
           cropImgData = data; // save returned data to cropImgData.
           console.log(cropImgData);   cropImgData is the returned data from cropper
           
}
------------------------------------------------------

Now you can use cropImgData in any event to pass the data to your server side file.
suppose use this
$(document).on('click', '#saveCroppedBtn', function(){
    var url ='your_ajax_page_url.php';
    $.ajax({
        type: "POST",
        url: url,
        data: cropImgData,
        success: function(res) {
          //do something.  
          }
});

**Comment by alefbetta** [comment]
muradhassan you are right and i went the same way, i used this

$(document).on('click', '#saveCroppedBtn', 
    function(){
    var url ='crop.php';
    $.ajax({
    type: "POST",
    url: url,
    data: **here is my data**,
    success: function(res) { 
      console.log(cropImgData);         
    }
    });
});

But data must be sent in a proper way to crop.php file ...  so that'a the problem.. i need to gather all information encode it with jason and send to CROP.php file like  it goes in AVATAR Example

**Comment by fengyuanchen** [comment]
This is not a issue. Please understand the example! Don't just copy the code...
