### ISSUE TITLE
Save preloaded img without using avatar modal window

### ISSUE THREAD

**Issue by alefbetta** [fengyuanchen/cropper#309]
Want to understand one simple issue.
I use simple div with img in it 

after that go different buttons

so it's the same like in DEMO folder.... 

1- We open the page - see the image right away that we have in our div container
2- We change the image as we like and want to save it
3 - HOW DO WE SAVE OUR CHANGES On the current image?????  

i saw the example with avatar but i don't need any modal windows, buttons to UPLOAD image and so on... i just want to save the image that i see after opening a browser page.. i don't see any SAVE buttons that send data to PHP file for saving it... i just see GET CROPPED CANVAS button but as i underrstand it's just a view of my changes ...  SO how to save current img after all changes in you DEMO folder example ?

**Comment by fengyuanchen** [comment]
Why don't you send the cropped data to server-side with AJAX and crop the image there and then return the image URL to replace the old one?

**Comment by marvambi** [comment]
@fengyuanchen How can we send the cropped data to server side without using the ajaxUpload method?
In my case, I just removed the form tag and used a section element instead. This is because I'm using it within another form tag and don't want the form to submit.

**Comment by fengyuanchen** [comment]
Sorry, I can do nothing for this.

**Comment by marvambi** [comment]
Thanks. Bn able to integrate the tool onto a profile update view that
already had a form.
