### ISSUE TITLE
Bad cropped canvas size when aspect ratio isn't round

### ISSUE THREAD

**Issue by gfpacheco** [fengyuanchen/cropper#310]
When I ask for a cropped canvas with size 160x60 (for example), the calculated aspect ratio of 2.66... makes the canvas 160 pixels wide by 59 pixels tall (59.99...)

**Comment by gfpacheco** [comment]
Fix proposed on #311

**Comment by fengyuanchen** [comment]
I think it is not a problem. 59.99... ≈ 60, not 59.

**Comment by gfpacheco** [comment]
59.99... is indeed almost 60, but when I invoke getCroppedCanvas and call its `.toDataURL("image/png")` the returned png is 59px tall (there's no such thing as png 59.99...px tall)

**Comment by fengyuanchen** [comment]
After test it, the result height is still 60px:

```js
$().cropper({
  aspectRatio: 160 / 60,
  built: function () {
    var canvas = $(this).cropper('getCroppedCanvas', {
          width: 160,
          height: 160
        }),
        $image = $('<img>').attr('src', canvas.toDataURL('image/jpeg')).appendTo('body');

    console.log(canvas); // <canvas width="160" height="60"></canvas>
    console.log($image.width()); // 160
    console.log($image.height()); // 60
  }
});

**Comment by BrendonKoz** [comment]
I'm having a similar issue with my results (height of 99px instead of 100px). Is it how I've handled the export, or is it potentially the rounding issue as well? I'm using Firefox Developer Edition (v48.0a2 2016-05-24).

```js
$('#image').cropper({
	aspectRatio: 143 / 100,
	preview: '.preview-image',
	movable: false,
	scalable: false
});
$('.cropper--get-data-button').click(function(){
	$('#image').cropper('')
	var myCanvas = $('#image').cropper('getCroppedCanvas', {
		width:143,
		height:100,
		fillColor:'#000'
	});
	console.log(myCanvas.toDataURL());
});
