### ISSUE TITLE
Ability to specify rounded crop box data

### ISSUE THREAD

**Issue by ilovecoffee** [fengyuanchen/cropper#312]
At the moment, the crop box returns decimal values. It would be nice add an option to round off these values (x, y, width, height). For example, I am initializing cropper with following options:

minimum width: 960
minium height: 540
aspect ratio: 16/9

I am using api where server throws an error since server is expecting x, y, width and height as integers.

Is there anyway I can round the values (in any callback) while keeping the above requirements (min. width, height, and aspect ratio)?

Thanks.

**Comment by fengyuanchen** [comment]
Why don't you call the `Math.round` for each value before send to server?
