### ISSUE TITLE
Remove Origin rules?

### ISSUE THREAD

**Issue by mathiassen1990** [fengyuanchen/cropper#314]
Hi is it possible to remove the origin control on images?
The image i get is from an amazon server given by adobe, and i cant change the origin headers.
witch meen i can't use the plugin.

Any ideas?

**Comment by fengyuanchen** [comment]
You cann't use the `getCroppedCanvas`, but you can send the cropped data to server-side and crop the image there:

```js
$().cropper({
  checkImageOrigin: false,
  crop: function(data) {
    // Send the data to server-side and then crop the image 
  }
});
```
