### ISSUE TITLE
Fixed crop area

### ISSUE THREAD

**Issue by vladimirsbudkins** [fengyuanchen/cropper#316]
Hi, how to fix crop area to make it working only in image area. Like you have in the example. Currently crop area (image below) is out of image area.

Thanks

![cropper](https://cloud.githubusercontent.com/assets/6427274/7726885/ea38e6ee-ff0d-11e4-90e8-481867b6db1e.png)

**Comment by axyxnz** [comment]
Set the ```strict``` option to ```true```

```
$('.container > img').cropper({
  strict: true // Prevents the crop box from going outside of the canvas
});
```

**Comment by vladimirsbudkins** [comment]
I need to prevent the crop box from going outside of the image

**Comment by axyxnz** [comment]
It seems like the cropper's container (```div.cropper-container```) is bleeding out of your modal's content div. Inspect and compare ```div.cropper-container``` and its parent's width and position.

**Comment by fengyuanchen** [comment]
Just set the `strict` option to `true` as @axyxnz said!

**Comment by vladimirsbudkins** [comment]
dot work with strict:true !!!

**Comment by fengyuanchen** [comment]
@vladimirsbudkins What is the version you are using?

**Comment by ClleaR** [comment]
i have a similar problem on v9.3 vs strict:true. 
![screen shot 2015-06-01 at 11 05 57](https://cloud.githubusercontent.com/assets/5529620/7908527/6a145c10-084e-11e5-9fa5-43185993f302.jpg)
i have this gray areas on the sides, and they increase selected area 
cropbox => Object {left: 34, top: 0, width: 610, height: 149.82456140456017}
but left must be 0
I don`t have this bug in v9.0 but in v9.3 i have wrong crop parameters

**Comment by fengyuanchen** [comment]
@ClleaR For your case, only `getData`'s `x` will be 0:
getCanvasData => data.left = 34
getCropBoxData => data.left = 34
getData => data.x = 0

**Comment by notflip** [comment]
Ohmygod! Been looking for this for so long.
I was using getCropBoxData, it's just the getData.

Thanks so much!
(wtf is that picture btw haha)

**Comment by mahendrakharvi** [comment]
Hi 
  i am getting small white rectangle in the cropped image can anyone suggest what could be the issue?
![signature (55)](https://user-images.githubusercontent.com/54401242/63667636-35cab180-c7f2-11e9-8938-3126881f9946.png)

**Comment by mahendrakharvi** [comment]
please help ...

**Comment by mahendrakharvi** [comment]
@fengyuanchen please help..
