### ISSUE TITLE
Method to 'autoCrop' right after loading source

### ISSUE THREAD

**Issue by Rvanlaak** [fengyuanchen/cropper#318]
We disabled 'autoCrop' because when there is no image, we put a placeholder on the canvas. When we load an image onto the canvas, we want to call a method to get the same effect as the `autoCrop` setting does.

Tried to find it around [this line in the README](https://github.com/fengyuanchen/cropper#methods) but couldn't make a conclusion out of it:
> As there is a asynchronous process when load the iamge, you should call most of the methods after built, except "setAspectRatio", "replace" and "destroy".

So, is there a method to automatically make a centered optimal crop after loading an image asynchronously?

**Comment by fengyuanchen** [comment]
Try the `crop` method:

```js
$().cropper({
  autoCrop: false,
  built: function () {
    // Do something here
    // ...
    // And then:
    $(this).cropper('crop');
  }
});
```

**Comment by Rvanlaak** [comment]
This does work for the image that is initially loaded, but in not in the script I've found somewhere to load a local image into the canvas:

```js
var $inputImage = $('#form_file'),
$inputImage.change(function () {
    var files = this.files,
    file;

    if (files && files.length) {
        file = files[0];

        if (/^image\/\w+$/.test(file.type)) {
            blobURL = URL.createObjectURL(file);
            $image.one('built.cropper', function () {
                URL.revokeObjectURL(blobURL); // Revoke when load complete
             }).cropper('reset').cropper('clear').cropper('replace', blobURL).cropper('crop');

         } else {
            sweetAlert('Please choose an image file.');
         }
     }
});
```
Also tried:
```js
// ..
}).cropper('reset').cropper('clear').cropper('crop').cropper('replace', blobURL);
// ..
```

Cropping does work for the first image, but does not seem to work for the image that was loaded via this script.

**Comment by fengyuanchen** [comment]
Why don't you destroy the cropper first?
