### ISSUE TITLE
Aspect Ratio Issue

### ISSUE THREAD

**Issue by shivagoogel** [fengyuanchen/cropper#321]
Hi Thanks for nice plugin.

I am integrating this plugin in my application.

Say I have image of size 1600X400 PX and set my crop-box aspect-ratio as 1:1.

Currently it is 'original image container' aspect ratio is not same as original image. 
I have noticed that the croper-canvas is maintaining the aspect-ratio of image but not the image which being displayed, So when the crop-box aspect-ratio to 1:1 then the crop-box will appear as 1:1 but this is covers   width-1200px and height-400px of original image, It is not scaling properly.

Is it mandatory to set widthXheight for 'original image container' as same aspect ratio of original image?

Please suggest me how to resolve this.

**Comment by fengyuanchen** [comment]
I don't understand what you mean...

**Comment by shivagoogel** [comment]
I had issue because of minWidth and minHeight values has been set to 200X100px
![hydrangeas](https://cloud.githubusercontent.com/assets/12619795/8028127/0ab67bc4-0dc4-11e5-9ee8-3474618eafab.jpg)
.
After modifying this to 1X1px the scaling issues has been resolved.

**Comment by shivagoogel** [comment]
dfgd
