### ISSUE TITLE
The minimum size of the crop leads to an error in the preset width and length of the field crop.

### ISSUE THREAD

**Issue by borisovdmitry** [fengyuanchen/cropper#323]
options = {
           data: {
             x: 0,
             y: 0,
             width: 120,
             height: 150
           },
          // strict: false,
          // responsive: false,
          // checkImageOrigin: false

          // modal: false,
          // guides: false,
          // highlight: false,
          // background: false,

          // autoCrop: false,
          // autoCropArea: 0.5,
          // dragCrop: false,
          // movable: false,
          // resizable: false,
          // rotatable: false,
          // zoomable: false,
          // touchDragZoom: false,
          // mouseWheelZoom: false,

           minCanvasWidth: 120,
           minCanvasHeight: 150,
           minCropBoxWidth: 120,
           minCropBoxHeight: 150,
           minContainerWidth: 120,
           minContainerHeight: 150,

          // build: null,
          // built: null,
          // dragstart: null,
          // dragmove: null,
          // dragend: null,
          // zoomin: null,
          // zoomout: null,

          // aspectRatio: 16 / 9,
          preview: '.img-preview',
          crop: function (data) {
            $dataX.val(Math.round(data.x));
            $dataY.val(Math.round(data.y));
            $dataHeight.val(Math.round(data.height));
            $dataWidth.val(Math.round(data.width));
            $dataRotate.val(Math.round(data.rotate));
          }
        };
With these parameters, width and height is 120 and not 150 pixels, and 185 and 232 pixels.
![1](https://cloud.githubusercontent.com/assets/7840293/7881181/1dcc9672-05f8-11e5-8a3f-7b643eb6bc3b.png)

**Comment by fengyuanchen** [comment]
You should know that the data values are computed with the natural image sizes, not equal to the crop box's.

```js
data: {
  x: 0,
  y: 0,
  width: 120, // transfers to crop box width will be 185, large than `minCropBoxWidth: 120`
  height: 150 // transfers to crop box height will be 232, large than `minCropBoxWidth: 150`
}
```
