### ISSUE TITLE
Proper way to destroy a cropper when using a form to upload and crop more than once?

### ISSUE THREAD

**Issue by lamoni** [fengyuanchen/cropper#324]
I'm running into an issue (image attached) where, if I use the same form more than once to crop different photos, the FIRST photo shows up inside of the cropbox still. I've tried calling .cropper('destroy') on the instance, but to no avail

![screen shot 2015-05-29 at 11 41 56 pm](https://cloud.githubusercontent.com/assets/5675626/7895451/61b073fe-065c-11e5-8dde-193818f40792.png)

**Comment by fengyuanchen** [comment]
Maybe you don't use it correctly.
