### ISSUE TITLE
Are numbers proportional?

### ISSUE THREAD

**Issue by zackperdue** [fengyuanchen/cropper#333]
Are the x, y, width, height numbers proportional to the image thats being cropped?

For example... my original image is 1000 wide by 500 high

but on my crop box the image is being cropped and displayed at 500 wide and 250.

I think the numbers that the cropper gives me are proportional to the current image size. Is there a way to get the correct numbers?

**Comment by fengyuanchen** [comment]
They are the correct numbers already.

**Comment by zackperdue** [comment]
Ahhh you're right.

My app was using coordinates from previous crop operation to crop current photo.
