### ISSUE TITLE
moveable:false still moveable when using dragCrop:false

### ISSUE THREAD

**Issue by peterbode1989** [fengyuanchen/cropper#335]
Hi, first of all great plugin, love it already!

But i encoutered a problem (if i didn't make any mistakes). When i set dragCrop and moveable both to false. I can still move the image. Is this a know bug or is it a scripting-failure from my side?

Here is my code:

```javascript
$(function(){
	$('.cropper > img').cropper({
		guides: false,
		dragCrop: false,
		movable: false,
		rotatable: false,
		zoomable: false,
		mouseWheelZoom: false,
		touchDragZoom: false,
		doubleClickToggle: false,
		crop: function(data) {
			$("#dataX").val(Math.round(data.x));
			$("#dataY").val(Math.round(data.y));
			$("#dataHeight").val(Math.round(data.height));
			$("#dataWidth").val(Math.round(data.width));
		}
	});
});
```

Thanks in advance,
Peter B.

Ps. i'm not English so sorry for the typos (if there are any)!

**Comment by fengyuanchen** [comment]
`moveable` => `movable`

**Comment by peterbode1989** [comment]
Ah that was stupid. Thnx and i updated the code above with the correct one!
