### ISSUE TITLE
How to make minCropBoxWidth/minCropBoxHeight relative to image size?

### ISSUE THREAD

**Issue by endelwar** [fengyuanchen/cropper#339]
Using cropper on a image bigger than the container (e.g. `max-width:500px` on an image 2500px width) is it possible to deny a crop smaller than a defined size?

I'd like to have images cropped to 16/9 aspectRatio and with a minimum width of 960px.

I've tried `minCropBoxWidth` but it's not relative to image real size.

**Comment by fengyuanchen** [comment]
Please just set the `aspectRatio` option and resize the cropped image with `getCroppedCanvas` or crop the image on the server side.

**Comment by endelwar** [comment]
It's not a problem of crop, that part server side works great, I would like to make impossible to narrow too much the crop rectangle, like it was possible on version 0.7.*

**Comment by fengyuanchen** [comment]
Sorry! We don't support it now as we want to show the whole image by default when initialized.

**Comment by pixxelfriend** [comment]
@endelwar i got the same problem yesterday. My cropped images must not be smaller than 250px in width and height. I found this JSFiddle, this should help you:  http://jsfiddle.net/dekkard/9r6czo65/12/

**Comment by endelwar** [comment]
Yes @pixxelfriend that's what I'd like to achieve, many thanks!

**Comment by ADmad** [comment]
Would be great if the functionality implemented in example provided by @pixxelfriend was inbuilt in the plugin.

**Comment by endelwar** [comment]
:thumbsup:

**Comment by fengyuanchen** [comment]
I think it is unnecessary to implement this.

**Comment by ADmad** [comment]
:disappointed:

**Comment by FoxWhite** [comment]
Also had to implement this 'unnecessary' feature myself today. Cheers @pixxelfriend :)

**Comment by messerbill** [comment]
this is really kind of strange...so many people wanna use this feature (like myself). It would be very kind to make this feature 'necessary' :)

**Comment by ADmad** [comment]
@fengyuanchen Please rethink your stance on this. It's clearly not "unnecessary" when so many people are requesting it.
