### ISSUE TITLE
I have issue uploading image in ajax loaded page

### ISSUE THREAD

**Issue by ravi3592** [fengyuanchen/cropper#341]
change: function () 
Is not working, since the modal is loaded in ajax. i need document.on(change). How to change here?

**Comment by fengyuanchen** [comment]
I don't really understand. The `change.cropper` event is fired when the cropping area changes.

**Comment by ravi3592** [comment]
I loaded a page as ajax content. So change.cropper event is not triggering. What should i do to make it work. 
It works good when normal page is loaded(Not ajax content).

**Comment by fengyuanchen** [comment]
Please initialize the cropper only when the remote page is loaded completely!
