### ISSUE TITLE
Download cropped image?

### ISSUE THREAD

**Issue by howardhee** [fengyuanchen/cropper#344]
i modified below code in cropper\js\main.js to download the cropped image:

                result = $image.cropper(data.method, data.option);
                if (data.method === 'getCroppedCanvas') {
                    $('#getCroppedCanvasModal').modal().find('.modal-body').html(result);

                    $("#saveImage").click(function () {
                        var dt = result.toDataURL('image/png');
                        this.href = dt;
                    });
                }

But why the downloaded cropped image size is bigger than original image, any idea? Thanks

**Comment by fengyuanchen** [comment]
You should not bind `click` event handler inner another `click` event handler ...

**Comment by howardhee** [comment]
I bind click event inside is because i want user click preview first then only the download button visible, and then click the download button to download the image. The image can download successful, but the size is much more bigger, i crop a 2MB image, the download size is 11MB. Am I pass wrong data?
