### ISSUE TITLE
Cropper Canvas isn't staying within the the container div

### ISSUE THREAD

**Issue by StuckSimon** [fengyuanchen/cropper#346]
I can't seem to make the image aspect fit inside my container div. The only way for me to have gotten it to fit is by setting strict to false, but then users can select transparent areas.

my code looks like:

    <div class="image-preview-container">
       <img src="http://whateverimageurl" id="image-preview" />
    </div>

and I have CSS on the container.

Here's what it looks like with the strict setting as true and false respectively

![cropper comparison](https://cloud.githubusercontent.com/assets/940257/8198593/e93e86e4-1476-11e5-9f32-12dcca2b100d.jpg)

**Comment by renatorib** [comment]
If you are using code of cdnjs, it's an old version (v0.9.1). 
Download and use the current version v0.10.0

I know that feel bro.

**Comment by StuckSimon** [comment]
This fixed my problem, thank you!

**Comment by renatorib** [comment]
@fengyuanchen can you update cdnjs source or ask someone to do it?

**Comment by fengyuanchen** [comment]
@renatorib OK! Thanks!
