### ISSUE TITLE
Allow cropper to grow vertically

### ISSUE THREAD

**Issue by dantman** [fengyuanchen/cropper#350]
I'd like to have my (non-zoomable) cropper grow to fit the image (possibly up to a maximum size based on the viewport).

Like so.
![screen shot 2015-06-21 at 12 55 36 pm](https://cloud.githubusercontent.com/assets/53399/8273158/5fa0e1c8-1815-11e5-9e6d-a8974c7f7cfe.png)

This sort of works fine if the image is visible before Cropper is loaded. As it uses the container height that has been extended by the visible image as a base.

However if the image was `display: none;`ed such as by react-cropper or simply by someone not wanting to show an unstyled flash of the image without the cropper. This happens.
![screen shot 2015-06-21 at 12 59 17 pm](https://cloud.githubusercontent.com/assets/53399/8273159/5fa1429e-1815-11e5-8fd3-d5e187c881f6.png)

I think the ideal would be to have an option like `growContainerVertical: true` (and perhaps a `maxContainerHeight`). This way not only would it handle images that have been hidden, but it would also allow the height of the container to be recalculated 

As an extra possibility perhaps `maxContainerHeight` could be permitted to be a function. In which case it would be re-run when Cropper's _resize handler is triggered.

**Comment by fengyuanchen** [comment]
I think you can set the container's size base on the image's size before start a cropper.

**Comment by dantman** [comment]
@fengyuanchen Yes. However some people might want to avoid the `Min height box` -> `Loaded image` -> `Cropper` and go straight from the (hidden) image to the cropper.

Also, that only applies when you first load the cropper. If you use `replace` it wouldn't inherit new heights from the image.

**Comment by dantman** [comment]
I also ended up with my cropper recently unexpectedly working different. `opacity: 0` was being used so the cropper would inherit the image height. Before it inherited the height. Now it doesn't.

Which makes me think that it is much better for cropper to be responsible for sizes of things instead of relying on a context that allows potential race conditions and/or browser inconsistencies.

**Comment by fengyuanchen** [comment]
After a few tests, I found this is a bug of the `replace` method left over by history. Thank you very much. I will improve it soon.
