### ISSUE TITLE
Initiate cropper in bootstrap dialog box with existing image

### ISSUE THREAD

**Issue by anieshjoseph** [fengyuanchen/cropper#351]
Need a help on this complete PHP example on this page: 

https://github.com/fengyuanchen/cropper/tree/master/examples/crop-avatar

Click on the "Change Avatar" initially will open the dialog box but the main image area is empty. But I can see small images on right side. When upload an image, it suddenly shows the image in main area.

Is it possible to display the existing image used in the parent page to be opened and available in the main area to start cropping immediately ?

One more point is, I have opened the "Dialog Box" automatically when the page loads (using the settings you mentioned in the main.js)  So I couldn't see the right side preview images.

**Comment by fengyuanchen** [comment]
It is easy to custom your own cropper application, try to do it yourself.
