### ISSUE TITLE
Crop Box Fixed Not Working

### ISSUE THREAD

**Issue by boblikesoup** [fengyuanchen/cropper#352]
Hi I got your plugin working except fixed cropper isn't working like in the demo with all the same attributes. The aspect ratio is working but all the dragging/moveable/resizable aren't.

$('.cropper-example-1 > img').cropper({
aspectRatio: 16 / 9,
autoCropArea: 0.65,
strict: false,
guides: false,
highlight: false,
dragCrop: false,
cropBoxMovable: false,
cropBoxResizable: false
});

**Comment by nathanjamal** [comment]
What was the solution here @boblikesoup ?
