### ISSUE TITLE
Multiple cropper

### ISSUE THREAD

**Issue by yukarlo** [fengyuanchen/cropper#353]
I've read that this supports multiple cropper, how do I do that? Cant find it in your documentation. Thanks

**Comment by phpdev82** [comment]
Check this question: https://github.com/fengyuanchen/cropper/issues/247

**Comment by yukarlo** [comment]
Thanks for that. How about on multiple image area selection, do you have any idea on how I am going to achieve that?

**Comment by anieshjoseph** [comment]
Did you mean to select multiple area in a single image ?  I have read it in the issues section (either closed or opened). Somebody asked about this but I didn't record the url or remember the answer. Please check and find it.

**Comment by yukarlo** [comment]
Yes I meant multiple area selection. Will check in the issues section. Thank you.

**Comment by fengyuanchen** [comment]
As a simple image cropping plugin, we don't support to crop multiple areas on one image at the same time, and I think it is not really useful for most people.

**Comment by mrloop** [comment]
@yukarlo I've used [jcrop](https://github.com/tapmodo/Jcrop) for multiple selection on a single image, have documented [here](https://github.com/tapmodo/Jcrop/pull/157/files).
