### ISSUE TITLE
Support for PHP 5.3.3

### ISSUE THREAD

**Issue by tahertechs** [fengyuanchen/cropper#354]
I want to integrate the example project (crop-avatar) in my project but mine is running on PHP 5.3.3 , Trying to load the project it did work on 5.5 but not 5.3.3 . What should I have to change to make it work? Thanks

**Comment by dalves82** [comment]
I think I have the same problem.
Works fine on PHP 5.5.12, but doesn't on PHP 5.4.

I get "NetworkError: 500 Internal Server Error" on crop.php

Any help?

**Comment by fengyuanchen** [comment]
Just an example, please try to custom it yourself base on the example.
