### ISSUE TITLE
Bug with max zoom

### ISSUE THREAD

**Issue by Steinmar** [fengyuanchen/cropper#356]
If you will increase your zoom you can see background instead of your image. You can see this bug on example [page](http://fengyuanchen.github.io/cropper/). May be it's necessary create max zoom value? It can be const or based on image size.

Max zoom value:

![333](https://cloud.githubusercontent.com/assets/1280914/8331555/b82357bc-1a91-11e5-8bd7-e473450a2cd6.png)

Max zoom + 1 value:

![333](https://cloud.githubusercontent.com/assets/1280914/8331562/c320a1ce-1a91-11e5-82ee-1daef5d9f205.png)

**Comment by fengyuanchen** [comment]
What's your browser and version?
I still can see the image after zoom in a lot.

**Comment by vinnymac** [comment]
Using the latest version of Chrome (v43) I got this to happen on the demo page after around ~120 calls to zoom in. (Also tried this on my forked non-jquery version and it had the same result)

**Comment by Steinmar** [comment]
I use Chrome v43 (Windows OS). And although I has this bug on Firefox v38 (Windows OS). I didn't test cropper on other browsers and other versions of Chrome and Firefox.

**Comment by fengyuanchen** [comment]
This is not a bug, you should limit the zoom in level as zoom in too much will break the image rendering.

```js
$().cropper({
  zoomin: function (e) {
    var imageData = $(this).cropper('getImageData');

    if (imageData.width / imageData.naturalWidth > 100) {
      e.preventDefault(); // Prevent zoom in again
    }
  }
});
```

**Comment by Steinmar** [comment]
thanks
