### ISSUE TITLE
How i can set max image width, height for zoom/crop

### ISSUE THREAD

**Issue by MikeBazhenov** [fengyuanchen/cropper#357]
Hi!

```
$('.div > img').cropper({
  aspectRatio: 1.7,
  crop: function(data) {
   //data.width, data.height
  }
});
```
In result `data` image width and height need to be bigger than 1920x1080px or equal, how i can implement
minCropImageWidth and minCropImageHeight?

**Comment by fengyuanchen** [comment]
Try `zoomin` event.
