### ISSUE TITLE
Calling getCroppedCanvas without cropping

### ISSUE THREAD

**Issue by mattparlane** [fengyuanchen/cropper#358]
I'm trying to use cropper to create an image editing tool which supports cropping, rotating and resizing. I've found that if all I want to do is rotate an image, I can't call getCroppedCanvas because the image has not been cropped. That means I can't get the blob for my rotated image.

I'm happy to write a patch myself, but I wanted some feedback on whether you think that's a good idea or not. If you'd be happy to accept a patch, I'll write one.

Thanks!

**Comment by fengyuanchen** [comment]
As an image cropping plugin, we don't support you case. I'm sorry for this. You can fork one and try to custom it.
