### ISSUE TITLE
Get Cropped image 

### ISSUE THREAD

**Issue by chamnab** [fengyuanchen/cropper#359]
How can i get cropped image to display in img ? Can u give sample code.

Thank You.

**Comment by renatorib** [comment]
```js
$('img').cropper('getCroppedCanvas');
```
or
```
$('img').cropper('getCroppedCanvas', {width: 100, height: 100);
```

**Comment by chamnab** [comment]
it only return : 
```html
<canvas width="200" height="200"></canvas>
```
it don't show image.

**Comment by renatorib** [comment]
It return the Canvas element. With canvas you can extract the image data with toDataURL() method.
Do this test:
```js
var imageData = $('img').cropper('getCroppedCanvas').toDataURL();
$('<img>')
    .attr('src', imageData)
    .appendTo('body');
```

**Comment by abdulrauf618** [comment]
I was facing an issue when I was ruing code as an html file, issue was

`cropper-in-modal-Rauf.html:110 Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
`
![image](https://user-images.githubusercontent.com/12670040/36058899-1892df84-0e4e-11e8-8193-a99e3594c94c.png)



Found solution here:
[https://stackoverflow.com/a/22716873/2114413](url)

Now I can show results in preview image

![image](https://user-images.githubusercontent.com/12670040/36058913-474f39d0-0e4e-11e8-9e67-2c5400c423f2.png)
