### ISSUE TITLE
Problems with PHP 5.4

### ISSUE THREAD

**Issue by dalves82** [fengyuanchen/cropper#362]
Hi, I have a project on wamp server with PHP 5.5.12, works fine.
But the server where I have to host my app works with PHP 5.4, and I gets "NetworkError: 500 Internal Server Error" on crop.php
Any help?
Thanks

**Comment by fengyuanchen** [comment]
Easy to debug: Chrome -> Developer Tools -> Networks -> crop.php -> Response
