### ISSUE TITLE
Avatar Example - Close Modal

### ISSUE THREAD

**Issue by kitarafrei** [fengyuanchen/cropper#363]
Hello,

First of all, thank you so much for your plugin.

I installed with success the demo avatar you provide and it works great. I only have one problem with it. When I close the modal, without uploading the image, it doesn't reset the wrapper of the image, it does reset the preview images, but the wrapper never resets which causes a problem where if I open again the modal it will show the new image previously selected on the wrapper with the original previews. How can I just clear the canvas?

Thanks!

**Comment by DavidSunny** [comment]
+1

**Comment by fengyuanchen** [comment]
I have fixed it. Thank you!
