### ISSUE TITLE
Full width in Foundation framework grid? (After window resize it does work)

### ISSUE THREAD

**Issue by Silvester20** [fengyuanchen/cropper#365]
Hello, first thanks for the amazing plugin!

I am using Zurb Foundation framework and placed a image to crop in a modal. The image to crop is in a grid of 7 columns, and the preview is in a grid of 5 columns.

But for a unkown reason the grid of 7 columns isn't filed with to image. In other words, the red area is empty in the fiddle. But the stange thing is after a window resize, the empty area is filled! (So after browser window resize it works like a charm).

Here is a fiddle to show you what I mean

http://jsfiddle.net/0am73z3o/

**Comment by fengyuanchen** [comment]
You should start the cropper only when the modal has been shown completely.

**Comment by Silvester20** [comment]
I started the cropper in the 'open'-event of the reveal modal, but unfortunately the same error appears

**Comment by fengyuanchen** [comment]
Is there an "opened" event?

**Comment by Silvester20** [comment]
Sure there is, just like this

$(document).on('open.fndtn.reveal', '[data-reveal]', function () {
  var modal = $(this);
 alert('You opened the ' + modal + ' reveal modal');
});

**Comment by fengyuanchen** [comment]
I don't know how Foundation framework work, so I suggest you to find help on [StackOverflow](http://stackoverflow.com).
