### ISSUE TITLE
master-cropper in rtl language site

### ISSUE THREAD

**Issue by anafasama** [fengyuanchen/cropper#366]
Hi everybody!
My site's language is right to left (Persian) & master-cropper doesn't work properly but change language of site to English, it work.
I know the problem is in file:
cropper-master\dist\cropper.min.js
But I don't know how to change it to work properly.

**Comment by fengyuanchen** [comment]
The RTL support had been added (#317, #342), and will be released soon.

**Comment by anafasama** [comment]
div#crop-avatar > * {direction: ltr !important;}
I add this line to this file: 
cropper-master\examples\crop-avatar\css\main.css

Thank you vvvvvvvvvvvvvvvvvvvvvvvvvvvery match fengyuanchen!

**Comment by anafasama** [comment]
How can I get name of crop image?
Within each file put this:
echo $_FILES['avatar_file'];
but not work.
I was really frustrated!

**Comment by fengyuanchen** [comment]
Anything about PHP you can ask on StackOverflow.com.

**Comment by anafasama** [comment]
Ok. thanks.

**Comment by fengyuanchen** [comment]
The new  version which supports RTL had been released ((v0.10.1).

**Comment by vahidalvandi** [comment]
just need add
dir="ltr"
in div
