### ISSUE TITLE
Center indicator

### ISSUE THREAD

**Issue by Vashiru** [fengyuanchen/cropper#367]
The cropper has a lot of different functionalities but I've stumbled upon something I'm missing. There's no way to show an indicator that represents the center of the cropped area. Having the rule of thirds grid overlay the image while cropping is already a great way to align pictures, but sometimes you just want something centered after cropping. Would it be possible to add a center indicator?

**Comment by fengyuanchen** [comment]
Good idea!!!

**Comment by Vashiru** [comment]
Glad you like it, thanks for updating the cropper! I'd suggest making the cross a little bigger for the default setting, but of course people can always do that themselves in the CSS. I immediately updated the project I"m working on to include the new version. :)

**Comment by fengyuanchen** [comment]
@Vashiru You are right. The cross is too small, I will enlarge it for 1 ~ 2 px. Thanks!
