### ISSUE TITLE
[BUG] Double image cropper 

### ISSUE THREAD

**Issue by BowgartField** [fengyuanchen/cropper#368]
Hello, 

I have a probleme when I load the cropper plugin, he loads two cropper area and two images.

![bug](https://cloud.githubusercontent.com/assets/13118844/8431242/6777761c-1f38-11e5-9f9e-39b6dc217a83.png)

For informations, I charging image in a dialog box of jquery (it's the problem ?)

Thank you,

**Comment by BowgartField** [comment]
UP !!

**Comment by fengyuanchen** [comment]
You may start cropper on two images. 
Try `$('.container > img').cropper()` instead of `$('.container img').cropper()`

**Comment by BowgartField** [comment]
I just want one cropper !! :


               var dimension;

                $('#upload-image-data > img').cropper({
                    aspectRatio: 140 / 140,
                    autoCropArea: 0.65,
                    strict: true,
                    guides: false,
                    highlight: false,
                    dragCrop: false,
                    movable: false,
                    resizable: false,
                    background:false,
                    global:false,
                    crop: function(data) {
                        dimension = data;
                    }

            });

**Comment by fengyuanchen** [comment]
I think you don't use the cropper correct!!!

**Comment by BowgartField** [comment]
Ok ? How I have to use it ?
thanx,

**Comment by diegopassoscosta** [comment]
Hello,

I'm having the "same issue", but I have this same behavior as BowgartField above. When I try to resize the crop area and get all area at 45°  degrees (just in 45°) the image shows kind of duplicated like a shadow.

Note: I was using the cropper CSS as fengyuanchen said in issue 175
(https://github.com/fengyuanchen/cropper/issues/175)

<link rel="stylesheet" href="~/Content/js/plugins/cropperjs/dist/cropper.min.css" />

And CropperJS Library

<script type="text/javascript" src="~/Content/js/plugins/cropperjs/dist/cropper.min.js"></script>
<script type="text/javascript" src="~/Content/js/plugins/jquery-cropper/dist/jquery-cropper.min.


Ps: this is the libraries that I have here in the project that I'im working for.

Bootstrap      v3.0.3
jQuery         v1.11.1
Cropper.js     v1.5.5
jQuery Cropper v1.0.0

And they declared are following order

1  bootstrap.min.css
2  bootstrap.min.js
3  jquery.min.js
4  cropper.min.css
5  cropper.min.js
6  jquery-cropper.min.js

Thank you
Best Regards Diego

**Comment by diegopassoscosta** [comment]
Hello, Again, 

Manipulating here I saw that this issue occurs with me when you try to use the crop outside the canvas area
![pic_02](https://user-images.githubusercontent.com/2180083/67971659-f2266680-fbeb-11e9-8d70-1b6e76ad3c7e.png)
.
