### ISSUE TITLE
Feature: Integrated uploader

### ISSUE THREAD

**Issue by nilssolanki** [fengyuanchen/cropper#369]
Since this library is geared towards manipulating images, in a lot of the cases these images will be user uploaded. So I was wondering if you were thinking of adding some kind of uploader (drag&drop + fallback).

I know this would not exactly be a core feature of this library, but maybe this could be a plugin?

**Comment by arahansen** [comment]
Or, at the very least, do you have a recommended plugin/library to use with cropper?

**Comment by fengyuanchen** [comment]
I suggest you to use a upload plugin directly. For example: https://github.com/fengyuanchen/uploader
