### ISSUE TITLE
Bootstrap modal is not working properly without reload the page. Need a complete solution for bootstrap modal.

### ISSUE THREAD

**Issue by muradhassan** [fengyuanchen/cropper#371]
Please visit <a href="ourbazaar.net/cropperTest.html">ourbazaar.net/cropperTest.html</a> click on an image, rotate it. it's working fine but if you close the modal open another image and try to rotate again it will rotate twice in one click, close the modal and open another modal by clicking an image try to rotate it will rotate three times, same case for zoom in and zoom out. I think the problem is for bs-modal. you can get the code from <a href="https://gist.github.com/muradhassan/1693f614e72ac015d6fd">https://gist.github.com/muradhassan/1693f614e72ac015d6fd</a>. I can't use jsfiddle because Cross-Origin Resource problem is occurring for image.

**Comment by fengyuanchen** [comment]
I think you had bound too much click events on the same button...

**Comment by muradhassan** [comment]
Thank you,
I also think so. But could you please help me out. I have tried a lot to solve the problem but couldn't. Please check the small jquery code from <a href='https://gist.github.com/muradhassan/1693f614e72ac015d6fd'>https://gist.github.com/muradhassan/1693f614e72ac015d6fd</a>, if you can give me any suggesstion.
