### ISSUE TITLE
unable to save crop

### ISSUE THREAD

**Issue by cinek2000** [fengyuanchen/cropper#376]
For some reason after I uploaded this to my website, and changed the directory for uploads from imgs/ to ../avs it does not save the cropped image. It only saves the original. There are no errors. Console output looks like this:
Object {state: 200, message: null, result: "../avs/1_2_original.jpeg"}

I've only modified the crop.php file, not sure if there's anything else I should change?

private function setDst($accountID, $userID=1) {
    $this -> dst = '../avs/' . $accountID . '_' . $userID . '.png';

 private function setFile($file, $accountID, $userID=1) {
    $errorCode = $file['error'];

    if ($errorCode === UPLOAD_ERR_OK) {
      $type = exif_imagetype($file['tmp_name']);

      if ($type) {
        $extension = image_type_to_extension($type);
        $src = '../avs/' . $accountID . '_' . $userID . '_original' . $extension;

**Comment by fengyuanchen** [comment]
Why don't you just debug this with Developer Tools of your browser?
