### ISSUE TITLE
Cropper not working with ie10

### ISSUE THREAD

**Issue by minhtien1502** [fengyuanchen/cropper#377]
Please help me.
Cropper not working with ie10

**Comment by fengyuanchen** [comment]
Please provide more details about your problem...

**Comment by minhtien1502** [comment]
When I console.log (e) in function dragstart() on IE10. I don't see attributes pageX and pageY. Do not get the coordinates. thanks

**Comment by minhtien1502** [comment]
Hi all. 
With ie10 change:
 - e.pageX   to  e.originalEvent.pageX;
 - e.pageY   to  e.originalEvent.pageY;

**Comment by fengyuanchen** [comment]
As it is a custom event, it does not provide `pageX` and `pageY` properties, but you can find them on the `originalEvent` property.

**Comment by bbrooks** [comment]
Any reason not to incorporate that into the current version?

**Comment by billsliu** [comment]
After I change e.pageX to e.originalEvent.pageX;
IE 10 works, I can move crop, but it is broken in ios devices.
e.pageX works on every platform except IE10
e.originalEvent.pageX works on every platform except IOS

**Comment by billsliu** [comment]
Change  e.pageX to e.pageX || e.originalEvent.pageX
              e.pageY to e.pageY || e.originalEvent.pageY
works on all platform

**Comment by fengyuanchen** [comment]
The new version (v0.11.0) had fixed this. Thanks!
