### ISSUE TITLE
strict: true is not working when image is rotated

### ISSUE THREAD

**Issue by vizo** [fengyuanchen/cropper#380]
When you rotate image in strict mode, image can get smaller than crop box.

**Comment by fengyuanchen** [comment]
Are you sure? Can you provide a demo for this issue?

**Comment by vizo** [comment]
You can try it on http://fengyuanchen.github.io/cropper/. Rotate image and you will see, borders of crop are outside of image.

**Comment by fengyuanchen** [comment]
What strict mode limits is just the canvas (the wrapper of the image).
