### ISSUE TITLE
Is it possible the upload of cropped image ?

### ISSUE THREAD

**Issue by fluctuate** [fengyuanchen/cropper#381]
I knew that  you cannot change tag &lt;input&gt; "type='file'" data (due to security reasons).
In fact after i have cropped the image, i would have to set my &lt;input name="fileupload" type="file"&gt; with cropped image -> but it's not possible.

But i can read here in "cropper" docs: 
https://github.com/fengyuanchen/cropper/blob/master/README.md#user-content-getcroppedcanvasoptions

I've read that:
"After then, you can display the canvas as an image directly, or use canvas.toDataURL to get a Data URL, or use canvas.toBlob to get a blob and upload it to server with FormData if the browser supports these APIs."

How can realize cropped image upload with "FormData" feature/object ?

Thank you,
   F

**Comment by fengyuanchen** [comment]
See #325

**Comment by fluctuate** [comment]
Thank you very much and excuse me for my blindness.
