### ISSUE TITLE
Crop Circles...

### ISSUE THREAD

**Issue by ballenjr** [fengyuanchen/cropper#382]
Hello,

Let me start by saying how awesomely complete this plugin is. Its great. There is just one minor thing that I had to look elsewhere for. A Circle shape for the cropper. It would be very nice to have to further round out this otherwise thorough plugin. 

I looked into modifying myself but I didn't expect you to be using spans the way that you did. It kinda threw me off. So I am not sure how to get it in there. I could only come up with a CSS hack that doesn't really look good:
```
span.cropper-face.cropper-move::after {
  content: '';
  height: 100%;
  width: 100%;
  position: relative;
  top: 0px;
  bottom: 0px;
  left: 0px;
  right: 0px;
  display: block;
  border-radius: 100%;
  background-color: white;
  mix-blend-mode: soft-light;
}

span.cropper-face.cropper-move{
    background-color: transparent;
    opacity:1;
}
```

What I am really hoping for is something like this: [ngImgCrop](https://github.com/alexk111/ngImgCrop)

Unfortunately this one has a bug that I cant figure out. When I apply a data: image from another canvas, for some reason the img-crop canvas dimensions are set to 0. Can't figure out why. Oh, and the canvas is being generated by html2canvas. But I don't think that should matter.

I know that he is making more use of the canvas to get a cleaner look. But I'm hoping that since you are more familiar with your code you would have a better idea on how to do this.

**Comment by fengyuanchen** [comment]
You can try to reset this class:

```css
.cropper-view-box {
  border-radius: 50%;
}
```

**Comment by ballenjr** [comment]
Yes, that does look better. Still wish I had a way to either ditch those spans or manipulate them so that the rectangle is not visible at all and only the circle is.

**Comment by ballenjr** [comment]
Btw, thanks for clueing me in on that class. I will use this and hide the .cropper-line's and unwanted .point's:

```
.point-w, .point-e, .point-s, 
.point-n, .point-ne, .point-nw, .point-sw{
	outline-color: transparent;
}

.cropper-view-box {
  border-radius: 100%;
  outline-color: transparent;
}
```

Sure would be nice to flip a flag in the options to apply these and maybe even repostion .point-se::before to line up with the new circle border.

**Comment by ballenjr** [comment]
Here is what I used to reposition the handle and scale up the crosshairs:

```
.cropper-center {
	-webkit-transform: scale(3.5);
}

.cropper-point.point-se {
  right: 12%;
  bottom: 12%;
  -webkit-transform: translate(100%, 100%);
}
```
