### ISSUE TITLE
How can I set the fixed cropbox to a specific size?

### ISSUE THREAD

**Issue by smoke-along** [fengyuanchen/cropper#383]
How can I setup the fixed cropbox to have a specific size? 

I've tried with the following code, but it doesn't work for me

    $(function() {

	var $toCrop = $('.img-container > img');

	$toCrop.cropper({
          aspectRatio: 16 / 9,
          autoCropArea: 0,
	  strict: false,
	  guides: false,
	  highlight: false,
	  dragCrop: false,
	  cropBoxMovable: false,
	  cropBoxResizable: false
	});

	$toCrop.cropper("setCropBoxData", { width: "100", height: "50" });

    });

**Comment by fengyuanchen** [comment]
> As there is an asynchronous process when load the image, you should call most of the methods after built, except "setAspectRatio", "replace" and "destroy".
> -- https://github.com/fengyuanchen/cropper#methods

So you code should be: 

```js
$(function() {
  var $toCrop = $('.img-container > img');

  $toCrop.cropper({
    aspectRatio: 16 / 9,
    autoCropArea: 0,
    strict: false,
    guides: false,
    highlight: false,
    dragCrop: false,
    cropBoxMovable: false,
    cropBoxResizable: false,
    built: function () {
      $toCrop.cropper("setCropBoxData", { width: "100", height: "50" });
    }
  });
});
```

**Comment by smoke-along** [comment]
This still doesn't work for me. It's like it keeps it default settings. I tried with setting autoCropArea to: false and 0. But no reaction.

If I change the value of autoCropArea, I do get some reaction, but that's in percentages... (Which is currently not what I'm looking for).

Any suggestions?

**Comment by asherman1986** [comment]
I don't see what relevance this has to "toBlob is not a function" in the referenced issue

**Comment by pdiniz13** [comment]
i also dont see how this is relevant to the toBlob issue

**Comment by fengyuanchen** [comment]
> As there is an asynchronous process when load the image, you should call most of the methods after built, except "setAspectRatio", "replace" and "destroy".
> -- https://github.com/fengyuanchen/cropper#methods

So you should call `getCroppedCanvas` method after built: 

```js
$().cropper({
  built: function () {
    $(this).cropper('getCroppedCanvas').toBlob(function (blob) {
      // Handle the blob
      // ...
    });
  }
});
```

**Comment by Yahshoua** [comment]
how to call a function build ? 

when i write
``
const cropper = $(elem).cropper({
  built: function () {
    $(this).cropper('getCroppedCanvas').toBlob(function (blob) {
      // Handle the blob
      // ...
    });
  }
});

cropper.build() ???  //no work
``
Help me

**Comment by Yahshoua** [comment]
`
const cropper = $(elem).cropper({
built: function () {
$(this).cropper('getCroppedCanvas').toBlob(function (blob) {
// Handle the blob
// ...
});
}
});
`

**Comment by fengyuanchen** [comment]
@Yahshoua 
1. The `built` hook function had been rename to `ready`.
2. Are you sure there is a method named `build`?

**Comment by ashrafali-v** [comment]
this.angularCropper.cropper.getCroppedCanvas() is return null on firefox appreciate any help. Thank you.

**Comment by finladder** [comment]
instead of build use ready function

**Comment by jarridlima** [comment]
> this.angularCropper.cropper.getCroppedCanvas() is return null on firefox appreciate any help. Thank you.

Me too... same problem in Firefox.

**Comment by mohamed351** [comment]
I can't make cropbox has a specific size (width and height)
`let ImageFile = a.srcElement.files[0];

                let reader = new FileReader();
                reader.readAsDataURL(ImageFile);
                reader.onload = function (a) {

                    $("#image").attr("src", a.currentTarget.result);
                    $("#image").css({ "display": "inline-block" });

                    let myImage = document.getElementById("image");
                    let croper = new Cropper(myImage, {
                        aspectRatio: 16 / 9,
                        autoCropArea: 0,
                        strict: false,
                        guides: false,
                        highlight: false,
                        dragCrop: false,
                        zoomable: false,
                        zoomOnTouch: false,
                        zoomOnWheel: false,
                        viewMode:3,
                        minContainerHeight: 150,
                        minContainerWidth:150,
                        dragMode:3,
                        //cropBoxResizable: false,
                        setCropBoxData: {
                            width: 100,
                            height: 50
                        },
                        ready: function (a) {
                            console.log(a);
                           
                         
                            console.log(myImage);
                           
                            
                        },
                      
                        crop(event) {
                        
                            myImage.cropper("setCropBoxData", { width: "100", height: "50" });

                            $("#x").val(event.detail.x);
                            $("#y").val(event.detail.y);
                            $("#Width").val(event.detail.width);
                            $("#Height").val(event.detail.height);

                         

                        }
                     
                    });
                    
                }
            }`

**Comment by mohamed351** [comment]
Now it is Working With Width 250px  and  Height 250px or very close to them !
```
<script src="~/js/cropper.js"></script>
    <script src="~/js/jquery-cropper.min.js"></script>
<scrript> 
  var $toCrop = $('#image');
                    $toCrop.cropper({
                        strict: true,
                        cropBoxResizable:false,
                        autoCropArea: 0,
                        resize:false,
                        strict: false,
                       
                        highlight: false,
                        dragCrop: false,
                        zoomable: false,
                        zoomOnTouch: false,
                        zoomOnWheel: false,
                        viewMode: 3,
                       
                        dragMode: 3,
                     
                    
                        ready: function () {
                            $toCrop.cropper("setCropBoxData", { width: 250, height: 250 });
                        },
                        crop: function (event) {
                           
                            console.log(event.detail);
                            $("#x").val(event.detail.x);
                            $("#y").val(event.detail.y);
                            $("#Width").val(event.detail.width);
                            $("#Height").val(event.detail.height);
                          
                        }
                             
                    });
</script>

```
