### ISSUE TITLE
GetCroppedCanvas Method does not work

### ISSUE THREAD

**Issue by sferoze** [fengyuanchen/cropper#384]
Here I initialize the cropper

```
$('.crop-image-container > img').cropper
    aspectRatio: 1 / 1,
    #autoCropArea: 0.65,
    strict: false,
    guides: false,
    highlight: false,
    dragCrop: false,
    cropBoxMovable: false,
    cropBoxResizable: false
    autoCropArea: 0.75
```

Now when I want to get the canvas to get the data URL I do:

```
$('.crop-image-container > img').cropper('getCroppedCanvas').toBlob (blob) ->
      console.log blob
```

It says that toBlob is not a function. I have tried a bunch of other variations but just cannot get the cropped canvas. Please help.

**Comment by fengyuanchen** [comment]
See #383

**Comment by pdiniz13** [comment]
this question wanst answered on #383

**Comment by fengyuanchen** [comment]
> As there is an asynchronous process when load the image, you should call most of the methods after built, except "setAspectRatio", "replace" and "destroy".
> -- https://github.com/fengyuanchen/cropper#methods

So you code should be: 

```js
$().cropper({
  built: function () {
    $(this).cropper('getCroppedCanvas').toBlob(function (blob) {
      // Handle the blob
      // ...
    });
  }
});
```

**Comment by vanjor** [comment]
I also meet this issue, and finally resolve by myself by import a js file : canvas-to-blob.min.js

**Comment by fengyuanchen** [comment]
Only Firefox 25+ supports [canvas.toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) right now.

**Comment by TomaIvanovTomov** [comment]
> canvas-to-blob.min.js

Where did you import it ? A little more information please.
