### ISSUE TITLE
minCropBoxHeight/Weidth and autoCropArea conflict

### ISSUE THREAD

**Issue by gurkov** [fengyuanchen/cropper#387]
I'm trying initialize cropper by next code:
```
$image.cropper({
                    resizable: false,
                    zoomable: false,
                    dragCrop: false,
                    responsive: false,
                    rotatable: false,
                    movable: false,
                    cropBoxResizable: false,
                    minCanvasWidth: 400,
                    minCanvasHeight: 400,
                    minCropBoxWidth: 400,
                    minCropBoxHeight: 267
                });
```
Real size of image: 400*400. And I'm expecting that cropBox will be 400x267, but... I'm getting 400x320. My investigation: 400 (image size) * 0.8 (autoCropArea default) = 320. May be you need to add cropBoxWidth and cropBoxHeight options for exactly crop area sizes if this issue not a bug?

**Comment by fengyuanchen** [comment]
```js
$image.cropper({
  dragCrop: false,
  responsive: false,
  movable: false,
  zoomable: false,
  rotatable: false,
  cropBoxResizable: false,
  minCanvasWidth: 400,
  minCanvasHeight: 400,
  minCropBoxWidth: 400,
  minCropBoxHeight: 267,
  built: function () {
    $(this).cropper('setCropBoxData', {
      width: 400,
      height: 267
    });
  }
});
```

**Comment by fabianrios** [comment]
can you please complement this example to make it work if the img container is smaller than the required cropbox for example setCropBoxData to width 700 when the container is only 484, is that possible?
<img width="1018" alt="screenshot 2018-07-16 09 09 42" src="https://user-images.githubusercontent.com/1442115/42746619-f899444c-88d8-11e8-96ea-05c1b3ef0c81.png">
