### ISSUE TITLE
Destroy cropper & relaunch it

### ISSUE THREAD

**Issue by fluctuate** [fengyuanchen/cropper#390]
Hi,

in my JS app i need to destroy $(mycanvas).cropper Object and recreate it from scratch without page refresh.

I do in this way:

var app = $(mycanvas).cropper({...

Destroy app:
app = undefined; // or null

Rebuild app:
var app = $(mycanvas).cropper({...

But now new JS app doesn't work properly, why ?
Is there a way/method to reset previous.cropper app ?

**Comment by fengyuanchen** [comment]
```js
$().cropper('destroy');
```
