### ISSUE TITLE
Changing minCropBoxWidth and micCropBoxHeight on already initialized cropper doesn't work.

### ISSUE THREAD

**Issue by Sebruck** [fengyuanchen/cropper#396]
Hi,

I need to change minCropBoxWidth/minCropBoxHeight dynamically, after the cropbox is already initialized, which doesn't work. I tried this:

```javascript
var settings = { /* ... some settings, but no minCropBox* setting .. */ }
$element.cropper( settings );

// later in the code

// I tried this
$element.cropper( 'minCropBoxWidth' , 50 );
$element.cropper( 'minCropBoxHeight' , 50 );

// and also this (this just initializes another cropper...)
$element.cropper( {
  minCropBoxWidth: 50,
  minCropBoxHeight: 50
} );
```

Is there any possibility to change this option after the cropper is initialized?

**Comment by fengyuanchen** [comment]
Sorry, we don't support this. I suggest just set an aspect ratio and resize the image to what you want on the server side.

**Comment by onassar** [comment]
Would be great to see this.
