### ISSUE TITLE
 If we upload same file more than one time, element rendered inside the parent Element i.e.  "cropper-container cropper-bg"  

### ISSUE THREAD

**Issue by razazaidisd** [fengyuanchen/cropper#400]
When we upload same file more than one time, "cropper-container cropper-bg" again rendered in the element. Please see the screenshot.
Problem: If we upload a picture and again we browse another photo and click choose, element rendered inside the parent Element. 

Please let me know if you have any question.

![problem](https://cloud.githubusercontent.com/assets/6624130/8926490/239131a0-3521-11e5-8596-0096a47d81f3.png)

**Comment by fengyuanchen** [comment]
You don't use the plugin correctly!

I guess you used some code like `$('.container img').cropper()`, you should transfer it to `$('.container > img').cropper()`. The `>` is very important!
