### ISSUE TITLE
Small container width results in huge container height

### ISSUE THREAD

**Issue by ErikWitt** [fengyuanchen/cropper#402]
Hey,

I have a cropper with a given width (25% of the screen). If i load an image that is wider than the width of the cropper, the height of the container is way too large. It seems that the width of the container is bounded, but the height is derived from original image.

This image shows the problem. 
![bad](https://cloud.githubusercontent.com/assets/2457248/8933475/49906674-3543-11e5-864c-87c0e425bfa2.png)

This image shows the expected behaviour.
![good](https://cloud.githubusercontent.com/assets/2457248/8933479/4db01ce0-3543-11e5-9ed4-56b378ec3bb9.png)

Best regards!

**Comment by fengyuanchen** [comment]
```css
.img-container > img {
  max-width: 100%;
}
```

**Comment by andr0man** [comment]
thanks it worked
