### ISSUE TITLE
Zooming inconsistent between + and - values

### ISSUE THREAD

**Issue by vpillinger** [fengyuanchen/cropper#403]
So I was trying to do manual zooming on images in the cropper. Looking into the code for the zoom function took me to this line.

delta = delta <= -1 ? 1 / (1 - delta) : delta <= 1 ? (1 + delta) : delta;

The output of this code on a positive 2 is a 2X zoom in. The output of this code on a -2 is a 3X zoom out (multiplies by 1/3). The output of negative values seem like they should map 1-1 with the relative positive values (except zooming out instead of in).

**Comment by fengyuanchen** [comment]
Thank you!
