### ISSUE TITLE
Responsive viewports causing image to stretch 

### ISSUE THREAD

**Issue by jgliesman** [fengyuanchen/cropper#406]
Hello and thank you for this awesome plugin.

If you scale your browser window down, ultimately cycling through the different responsive viewports, the image that is being cropped becomes skewed. While using a custom image (300x300) if you size down to mobile, the image scales accordingly, but height of the crop area does not change. In your demo it does. When you scale back up from mobile to desktop, the image now stretches beyond the cropping area. It is an awkward experience. Hitting the 'reset' helps but doesn't solve the root issue.

Strangely enough, this is working in Safari but there is a slight cut off in Chrome and and even bigger cut off in Firefox.

![1](https://cloud.githubusercontent.com/assets/4631506/9015561/bd7482d6-3797-11e5-8afa-b089bffcd00e.png)
![2](https://cloud.githubusercontent.com/assets/4631506/9015560/bd73245e-3797-11e5-9e92-81762f5e5d39.png)

Any idea on what's causing this? 
Thanks again!

**Comment by fengyuanchen** [comment]
Because I set a fixed height to the main demo. Why don't you try the third example?
