### ISSUE TITLE
Automatically fix image size/position after rotation

### ISSUE THREAD

**Issue by DaimonPl** [fengyuanchen/cropper#408]
I'm using cropper with {zoomable : false} setting (this ideally adjusts image to container size at the beginning).

However there's problem after rotating image (calling $(...).cropper('rotate', 90); several times) if both image and container are rectangles - image sometimes gets mispositioned and "cut" by container.

Is there a way to readjust image after rotation (i.e. automatically adjust it's width/height if it does not fit in container after rotation)?

(same problem happens here: http://fengyuanchen.github.io/cropper/)

**Comment by fengyuanchen** [comment]
The only way is set `strict` option to `false`.

**Comment by DaimonPl** [comment]
After setting strict to false image is being positioned correctly but now cropping mask can be set completely incorrectly.

Is there a way to achieve both (proper image positioning/sizing after rotation AND strict cropping mask)?
