### ISSUE TITLE
method toBlob results in wrong type being sent to server

### ISSUE THREAD

**Issue by r3wt** [fengyuanchen/cropper#410]
it always sends as type `png` no matter. when i try to upload this file to server it has problems working.

I am tryign to upload the image to php then upload it from php to zimg, with no success.

here is full code in javascript

```js
	var $image = $('#cropper').cropper({
	  aspectRatio: 1,
	  minCropBoxHeight: 120,
	  minCropBoxWidth: 120,
	  crop: function(data) {
		// Output the result data for cropping image.
		console.log(data);
	  }
	});
	
	$("#edit-image").on('change',function(e){
		if ( this.files && this.files[0] ) {
			var FR = new FileReader();
			FR.readAsDataURL( this.files[0] );
			FR.onload = function(e) {
				$image.cropper('replace', e.target.result )
				$('#cropper').attr("src", e.target.result )
				.show();
			};       
		}
	});
	
	
	$('button[type="submit"]:not(disabled)').on('click',function(e){
		e.preventDefault();
		var _t = $(this);
		_t.addClass('m-progress').prop('disabled',true);
		$image.cropper('getCroppedCanvas').toBlob(function (blob) {
			var formData = new FormData();
			blob.lastModifiedDate = new Date();
			blob.name = $('#edit-image')[0].files[0].name;
			blob.type = $('#edit-image')[0].files[0].name.split('.').pop().toLowerCase();
			formData.append('userfile', blob);
			$.ajax({
				xhr: function(){
					var xhr = new window.XMLHttpRequest();
					xhr.upload.addEventListener("progress", function(evt){
						if (evt.lengthComputable) {
							sk.progress.update( Math.round( (evt.loaded / evt.total) * 100 ) , true );
						}
					}, false);
					return xhr;
				},
				beforeSend: function (){
					sk.progress.start($('.container'));
				},
				url: window.location.origin + '/api/change_avatar',
				type: "POST",
				data:  formData,
				contentType: false,
				cache: false,
				processData:false,
				success: function(data){
					console.log(data);
					var data = JSON.parse(data);
					if(data.error == 0){
						$('.thumb > img').attr('src',data.message);
						sk.alert('Avatar Updated','success');
					}else{
						sk.alert(data.message,'error');
					}
				},
				error: function(jqXHR, textStatus, errorThrown ){
					sk.alert('Server Error','error');
				} 	        
			}).always(function(){
				_t.removeClass('m-progress').prop('disabled',false);
				sk.progress.done();
			});
		});
		e.stopPropagation();
		return false;
	});
```

**Comment by agungyuliaji** [comment]
same problem here...
btw @r3wt you opened this issue and then close this?

**Comment by r3wt** [comment]
@agungyuliaji it was obvious that @fengyuanchen was not going to respond to my request, so i worked around the issue in some other way. i'll try and dig that up for you in a bit.

**Comment by r3wt** [comment]
the way i worked it was to stop sending the type and instead reading the image in with `imagecreatefromstring()` after reading the file with `file_get_contents()`

**Comment by IrisZhang** [comment]
The method of HTMLCanvasElement.toBlob() has three parameters, if you don't set the value of type, the default type is "image/png".
https://developer.mozilla.org/en-US/docs/Web/API/DOMString

**Comment by kpomservices** [comment]
I solved saving the cropped image by
// client side
    var cropcanvas = $('#imagetocrop').cropper('getCroppedCanvas');
    var croppng = cropcanvas.toDataURL("image/png");
	
    $.ajax({
        type: 'POST',
        url: 'savecropimage.php',
        data: {
            pngimageData: croppng,
            filename: 'test.png'
        },
        success: function(output) {
        }
    })
-------
//server side php
	$filename = $_POST['filename'];	
	$img = $_POST['pngimageData'];
	$img = str_replace('data:image/png;base64,', '', $img);
	$img = str_replace(' ', '+', $img);
	$data = base64_decode($img);
	file_put_contents($filename, $data);
