### ISSUE TITLE
When I rotate photo, photo expands.

### ISSUE THREAD

**Issue by kspacja** [fengyuanchen/cropper#412]
When I rotate about 90 degres, photo expands and goes out of canvas.

**Comment by fengyuanchen** [comment]
Set `strict` option to `false`.

**Comment by kspacja** [comment]
But still image is out of bound after rotation..

**Comment by jaredrada** [comment]
@kspacja is correct. after rotating an image portions of the image are beyond the bounds of the canvas. you are unable to see the top and bottom of the image. @fengyuanchen can you reopen and look into this problem?
