### ISSUE TITLE
When I rotate about 90 degres, image goes out of canvas.

### ISSUE THREAD

**Issue by kspacja** [fengyuanchen/cropper#414]

**Comment by fengyuanchen** [comment]
I can't reproduce it.

**Comment by asuran** [comment]
I think I have the same problem. 
Original image
![image](https://cloud.githubusercontent.com/assets/1727336/9376810/7e532958-471a-11e5-97e0-591fc520065a.png)
After rotate 45 it shows only part of the image
![image](https://cloud.githubusercontent.com/assets/1727336/9376853/2b90286e-471b-11e5-9d6b-5dadd93514d1.png)
Same image after 4 clicks "rotate 45". After rotate 360 I expect to see the original image like first screenshot, but the image was zoomed.
![image](https://cloud.githubusercontent.com/assets/1727336/9376814/93b948a4-471a-11e5-83a6-1b61cc1b4d2b.png)
After that you can rotate the image as much as you want - the image stay the same size.
![image](https://cloud.githubusercontent.com/assets/1727336/9376906/c9f2aa5e-471b-11e5-9fa4-c29868ed3313.png)
![image](https://cloud.githubusercontent.com/assets/1727336/9376907/d291c302-471b-11e5-9185-208d4b5c3337.png)

Hope I explained clearly :) By the way, thank you for the awesome plugin! Please fix this problem or tell me, how to get rotate behaviour like in desktop app editors or, for example, in this plugin http://mattketmo.github.io/darkroomjs/

**Comment by fengyuanchen** [comment]
The only way to avoid this problem is set the `strict` option with `false`.

**Comment by asuran** [comment]
Then the crop box can be outside of the canvas. Is it posible to add option to limit it?

**Comment by fengyuanchen** [comment]
I'm afraid not. But you can zoom in to make the image large enough than the crop box before rotate or disable the rotation function.
