### ISSUE TITLE
Color changes post crop?

### ISSUE THREAD

**Issue by wesleyradcliffe** [fengyuanchen/cropper#415]
Hi, i've implemented your cropper class in our new content platform, and its an amazing library, but our photo editors have noticed certain photos get washed out. 

1. Images that don't get processed through cropper.js still have the same gamma/darkness levels as the source images:
http://ugc.vivalastatic.com/gen/crop/240/150/80/2015/08/03/20/6y/0k/phu4ppn58o2qbwe.jpg

2. Images that are processed through cropper.js are much lighter
http://ugc.vivalastatic.com/gen/constrain/300/300/65/2015/08/03/20/b1/2p/po3ji7e48wb.png

I've gotten through a lot of bug testing, and things have come down to just things that are processed through cropper.js. Any insight on your end on how this could be happening? The images are obviously heavily processed through photoshop before being added to our CMS, could that be causing any issues? 

Thank you so much for any insight!

**Comment by fengyuanchen** [comment]
1. If you call the `getCroppedCanvas` method, then the cropped image is processed by [HTMLCanvasElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement).

2. If you cropped the image on server-side, then may be the problem of your server-side code.
