### ISSUE TITLE
Set Default Crop Area?

### ISSUE THREAD

**Issue by ojraqueno** [fengyuanchen/cropper#417]
I have the cropper area set to a square. When the original image is also a square, by default the cropping area covers the entire image, and it's hard to see the crop handles on the sides and corners. It's hard to know that the app is in "crop" mode.

Is it possible to reduce the size of the default cropping area?

**Comment by l4u** [comment]
Not sure if it works, but try with the `autoCropArea` option.

**Comment by ojraqueno** [comment]
Yes that's it, thanks. There was also another configuration setting called "maximize" which I removed.
