### ISSUE TITLE
Documentation for getImageData() is out of date!

### ISSUE THREAD

**Issue by DS-Matt** [fengyuanchen/cropper#419]
Hi,

I just wanted to start off by saying that I love cropper.

I noticed that the documentation of the getImageData() method is out of date. The documentation states that the method returns an object with the following properties:
- left
- top
- width
- height

The method actually returns much more:
- aspectRatio
- height
- left
- naturalHeight
- naturalWidth
- rotate
- top
- width

**Comment by fengyuanchen** [comment]
Updated! Thanks!
