### ISSUE TITLE
getCroppedCanvas wrong return value?

### ISSUE THREAD

**Issue by mathishuettl** [fengyuanchen/cropper#420]
Hello,

i used the following code to show the cropping-area in a modal and when i click the save-button the function "cropImage" is called. but when i alert my the cropper("getCroppedCanvas") return value then i get an <img /> element... 

        var showCropper = function(elem) {
		$("#crop img").attr("src", $(elem).attr("data-url"));
		var $image = $("#crop img"), cropBoxData, canvasData;
		$("#crop").modal("show");
		
		$("#crop").on("shown.bs.modal", function() {
			$image.cropper({
				aspectRatio: 16 / 9,
				autoCropArea: 0.65,
				strict: false,
				guides: false,
				highlight: false,
				dragCrop: false,
				cropBoxMovable: false,
				cropBoxResizable: false,
				built: function() {
					$image.cropper('setCropBoxData', cropBoxData);
					$image.cropper('setCanvasData', canvasData);
				}
			});
		}).on("hidden.bs.modal", function() {
			cropBoxData = $image.cropper("getCropBoxData");
			canvasData = $image.cropper("getCanvasData").toBlob();
			$image.cropper("destroy");
		});
	}
	
	var cropImage = function() {
		$image = $("#crop img");
		var canvas = $image.cropper("getCroppedCanvas");
		alert(canvas.prop("tagName"));
	}

**Comment by fengyuanchen** [comment]
Please read the documentation about how to call the methods carefully!!!
