### ISSUE TITLE
Reset Preview

### ISSUE THREAD

**Issue by moderith** [fengyuanchen/cropper#421]
Is it posible to reset / rebuild the preview box to new constraints? For example in a mobile sized screen I have 1 size on a desktop sized screen I have a version twice as large. When I initiate the cropper it works fine in whatever size I started in, but when I hit the breakpoint to shrink or enlarge the preview box the preview does not change size. I figure if it can build it it can hopefully reset it. I found a function in the source for prevewReset(), but can't figure out how to leverage it.

Any help would be appriciated!

![screen shot 2015-08-10 at 5 52 04 pm](https://cloud.githubusercontent.com/assets/197101/9187712/63acfc6c-3f88-11e5-8f6d-cadc929fda6c.png)
![screen shot 2015-08-10 at 5 52 53 pm](https://cloud.githubusercontent.com/assets/197101/9187711/63ad131e-3f88-11e5-8d0d-5ee69ea670a5.png)

**Comment by hakubo** [comment]
+1

**Comment by vforge** [comment]
Hey, we have exactly same issue - we're having cropper set up on 100% width and height and when switching orientation of the screen it's not resized.

So +1 from me

**Comment by fengyuanchen** [comment]
1. Customize preview with `crop.cropper` event.
2. Restart the cropper when resize the window.

**Comment by vforge** [comment]
@fengyuanchen works as a charm, thanks!

**Comment by moderith** [comment]
Thanks for the response @fengyuanchen . I have tried both $().cropper('destroy').cropper(), and $().cropper({preview: '.img-preview'}). Still seems to do the same thing.

What will do it is if I change the aspect ratio. Then the preview resets fully.

**Comment by vforge** [comment]
@moderith `$().cropper('destroy').cropper()` didn't work for me, but ```
$(element).cropper('destroy');
$(element).cropper(settings);
``` worked fine.

**Comment by fengyuanchen** [comment]
I have added an example for customizing preview: https://github.com/fengyuanchen/cropper/blob/master/examples/customize-preview.html
