### ISSUE TITLE
The following version of the iOS8.4 can't be used to preview and cut the photos

### ISSUE THREAD

**Issue by jobyang** [fengyuanchen/cropper#423]
Hi Fengyuanchen,

I need you help.thank you very much!
I made a photo of a cell phone to the end of the cutting tool.
The following version of the iOS8.4 can't be used to preview and cut the photos.

**Comment by fengyuanchen** [comment]
Any more detail?

**Comment by jobyang** [comment]
您好！
       我这边边遇到的问题是，我在使用该插件进行手机端的照片上传、剪裁。Android是完全支持的，但是iOS8.4以下的版本无法使用照片的剪裁和上传功 能。ISO8.4以下的版本点击照片上传会出现白屏和卡顿现象，剪裁照片时也会出现白屏现象。我主要使用过ISO8.3，ISO7.0，ISO7.0.1 等版本进行测试，发现都无法使用照片的剪裁和上传。这个问题我不知道是我在错误使用插件造成的还是插件的兼容性有问题，插件的代码我已经认真核对多遍，没 有发现异常的参数传递或者是代码错误。因此得向您这位技术大拿请教，非常感谢。

**Comment by jobyang** [comment]
英文不是很流利，所以使用中文，敬请谅解，谢谢

**Comment by fengyuanchen** [comment]
See #294
