### ISSUE TITLE
php not croping

### ISSUE THREAD

**Issue by illinoisbdr529** [fengyuanchen/cropper#424]
hi thanks a lot for your work is just what i need.
unfortunatelly i do have a problem:
the file in original size is saved in the img folder... the cropped file no...
the php file is just the original one... is probably a noob question... 
can u help me?

**Comment by illinoisbdr529** [comment]
the log it give is just "error"

**Comment by illinoisbdr529** [comment]
i just intalled the example page not changing anything ... and is still having errors
http://www.fanta-trade.eu/fanta-trade-3/cropper-master/examples/crop-avatar/index.php
in the browser console is showing a 500 (Internal Server Error) on the crop.php file

**Comment by fengyuanchen** [comment]
Please check your **php_error.log** file.

**Comment by illinoisbdr529** [comment]
hi man thanks... but no error are showing...

**Comment by fengyuanchen** [comment]
What's your php version?

**Comment by illinoisbdr529** [comment]
5.3.10

**Comment by fengyuanchen** [comment]
Requires PHP 5.5+
https://github.com/fengyuanchen/cropper/blob/master/examples/crop-avatar/README.md

**Comment by illinoisbdr529** [comment]
i see
i try to install the 5.5 
sorry
