### ISSUE TITLE
Some time magic bug !! 

### ISSUE THREAD

**Issue by Soroush-Co** [fengyuanchen/cropper#425]
See the attachments screenShot

if in change src of img tag change to wrong file (not photo) cropper output show olden image and style buggy!!

confige
$('#imageCropper > img').cropper({
					aspectRatio       : 1,
					dragCrop          : false,
					minContainerWidth : 768,
					minContainerHeight: 400
				});

on change input:
url = URL.createObjectURL(this.file);
$('#imageCropper > img').cropper('replace', url);

ScreenShot
<img width="1440" alt="screen shot 2015-08-17 at 2 11 57 pm" src="https://cloud.githubusercontent.com/assets/12074104/9302230/442c2af4-44ea-11e5-8bd1-466f677c3362.png">

**Comment by fengyuanchen** [comment]
Why don't you filter the input file first?

**Comment by Soroush-Co** [comment]
after finde him filter this but this is a BUG if remove or replice empty path in src image cropper must be die

**Comment by fengyuanchen** [comment]
If you intend to change the src of a image, please destroy the cropper first.
