### ISSUE TITLE
Some Time dublicat crope area

### ISSUE THREAD

**Issue by Soroush-Co** [fengyuanchen/cropper#426]
See the Screen Shot

<img width="764" alt="screen shot 2015-08-17 at 2 50 07 pm" src="https://cloud.githubusercontent.com/assets/12074104/9302979/103c50f6-44f0-11e5-8e8b-5049792d7268.png">

**Comment by fengyuanchen** [comment]
Just check your own code to find out the problem.

**Comment by Soroush-Co** [comment]
I find :dart: after change

**Comment by Soroush-Co** [comment]
this Bug not valid! problem whit bacbone :dango: 
if 3time set config cropper and select image show 3 crop area !!
