### ISSUE TITLE
can we have first browse button and then allow crop ?? 

### ISSUE THREAD

**Issue by Raju21** [fengyuanchen/cropper#43]
I have used model example.where i need first browse image then model will appear with crop image option.I did practice and worked well except crome and safari browser.issue getting default image dimension as approximate 180*210 px.
![crop-issue](https://cloud.githubusercontent.com/assets/7448978/3654485/fbc7a31e-116a-11e4-8896-a5d71315180d.png)

**Comment by mrmarktyy** [comment]
Hi @fengyuanchen , i loved your cropperjs, it works great. However I had some problems with IE11(win7) and 搜狗browser when use the image from local machine ( eg "access is denied" or "cross orgin" issues). I found that the steps I used were quite close to those in your comments above. 

Would you provide some suggestions what i did wrong ? or any workarounds? thank you!
