### ISSUE TITLE
minWidth minHeight (cropbox) not working for photos like panorama

### ISSUE THREAD

**Issue by sangyoo91** [fengyuanchen/cropper#430]
Just like the title says,

sometimes, the cropbox min width and minheight is ignored.

How do I make it so that the image overflows everything and so that cropbox min width and height work ?

**Comment by fengyuanchen** [comment]
You may need to understand that `minCropBoxWidth` not means `minCroppedWidth`.

**Comment by sangyoo91** [comment]
What I meant was that when cropbox is set to for example, width: `100px` loading some images will cause the `cropbox width` to go below `100px`

**Comment by fengyuanchen** [comment]
You are right! Thanks!
