### ISSUE TITLE
when I crop and upload from iphone 4 it rotates 90deg to the left

### ISSUE THREAD

**Issue by wordnesia** [fengyuanchen/cropper#431]
when I crop and upload from iphone 4 it rotates 90deg to the left, how to solve it?

**Comment by tilocgn** [comment]
Its a know issue on iOS. See https://github.com/fengyuanchen/cropper#known-issues and https://github.com/fengyuanchen/cropper/issues/120

**Comment by wordnesia** [comment]
thank you for your reply, really appreciate it.
this is a great plugin, really nice work
