### ISSUE TITLE
Multitabs and upload button on IE9

### ISSUE THREAD

**Issue by nanoarts** [fengyuanchen/cropper#432]
Hi , really good job your cropper , i try to use him but i have two problem 

i need tabs and in every tabs i need your "cropper generator" ( make multi crop from multi img ) 
and i can't just cut and copy your html container in the same html...( that duplicate the img on every tabs)

 have you an idea ?  ( i try with iframe on tab and it's ok ..but i don't like use iframe ) 

second question the button import img (import img with blobs url ) don't appear on IE9..
 (after try: this is because the id="inputImage" in input type="file" ) ... without this id impossible to import img in the container no ?
 i has try with the "avatar" example, i have the button "import" on iE9 but nothing appear in the container ..( i hate iE9 :-1:  ) any idea ?

last question how to having a save button ?

that's a loot of question i know ^^"  thk if you can help me

**Comment by fengyuanchen** [comment]
IE9 does not support [Blob URLs](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL), so I hide the import button.

I can't help you for other problems as they are not about cropper.
