### ISSUE TITLE
Destroying cropper still keeps imageData somewhere?

### ISSUE THREAD

**Issue by grofit** [fengyuanchen/cropper#434]
I am using knockout and cropper together and I noticed some weird behaviour when I am updating an images src attribute with cropper.

The process is:
- An image is dropped on the page
- The image is read in and output as base64
- The base64 content gets set to the src of the image used for editing
- A modal is loaded which contains the image to be cropped
- The cropper is created for this image
- The modal is closed
- The cropper is destroyed (`$(imageElement).cropper("destroy");`)
- Repeated from start

So currently in the above process once an image has been dragged in and loaded in the cropper, every time it is created again regardless of what was in the image when it is re-created it always shows the first image that it was told to crop.

To prove this is the case I added a step in after the cropper is destroyed to empty the base64 string from the image, and if I go into the html source I can see the `src=""`. So the knockout binding is definitely feeding the image the correct image data, it just seems that even though the cropper is destroyed, somewhere it is leaving behind a cache of what image it was last looking at then just re-loading that, rather than getting the latest image src data.

So was just wondering if there is a way around this? I know there are a few `imageData` properties I could possibly hook into on creation of the cropper to manually pass the data in, but I wasnt sure if this was correct behaviour or a bug, before I go writing more code to try and solve the problem.

**Comment by fengyuanchen** [comment]
Maybe it because of that the plugin restore the original src to the image after destroyed.

**Comment by grofit** [comment]
Do you mean knockout? I can create a quick code pen showing this behaviour without knockout if it would help.

**Comment by fengyuanchen** [comment]
Maybe the cropper's problem. Please use `gulp release` to build a new `cropper.js` and try again.

**Comment by grofit** [comment]
Will do, thanks for the quick response.

**Comment by grofit** [comment]
Yep works as expected, thanks again.
