### ISSUE TITLE
when updating 0.11.0 to 0.11.1 cropper uses minContainer width/height

### ISSUE THREAD

**Issue by dfherr** [fengyuanchen/cropper#436]
after updating from 0.11.0 to 0.11.1 the cropper uses the minContainer width and height instead of the image width/height. I'm using in the cropper in a jquery modal, if that could be related.

It's working correctly with 0.11.0

here are two screenshots:

![with0.11.0](https://cloud.githubusercontent.com/assets/6793674/9496484/d8621e4a-4c10-11e5-8f39-ec33179c6074.png)

![with0.11.1](https://cloud.githubusercontent.com/assets/6793674/9496497/e38548f6-4c10-11e5-9e18-cf586e0845c7.png)

**Comment by fengyuanchen** [comment]
Maybe you don't use it correctly (see #85).

**Comment by dfherr** [comment]
i'm setting up my modal settings on `$(window).load()` to make sure the image is correctly loaded. The modal size is also dynamically modified in relation to my image size (using js tmp =  Image.new(), to draw width/height).

The cropper never gets initiated without the modal beeing open.

```
        function openCropper(){
            dialog.dialog('open');
            if(cropperEnabled) {
                showPreview();
            }else{
                 startCropper();
            }
        }
``` 

i also made sure, my startCropper() function isn't called twice, so closing the modal just hides the cropper and reopens it at the same state, which is working correctly.

**Comment by fengyuanchen** [comment]
window loaded does not means image loaded. 

v0.11.1 improve the starting of cropper (start the cropper immediately when the target image load completely)

**Comment by dfherr** [comment]
thats probably the issue. but its weird because i dont start the cropper before opening the modal. And the modal uses the dimensions of the same image for its size, which is still working.

Additonally i even get some ajax data of a previously cropped area before initiating the cropper via startCropper(), which is used to set the initial cropbox. The ajax request is also fired on $(window).load, so there is even more time for everything to setup correctly.

**Comment by dfherr** [comment]
My original image is loaded hidden though, thats why i have to do the work around with the temporary image. Hidden images dont return the correct width and height in many browsers.

Could it be you encountered the same issue with your new way of loading the image?

**Comment by fengyuanchen** [comment]
If the image is hidden, you should show it (or copy to a visible area) before start the cropper.

**Comment by dfherr** [comment]
sorry you see it that way. it's bad design on your end you don't support this, especially since you did support it up to 11.0. 

Needing to show the image just to start the cropper will result in weird user experience. Really dislike that.
