### ISSUE TITLE
Feature: image can't be zoomed smaller than container and moved out of container

### ISSUE THREAD

**Issue by dfherr** [fengyuanchen/cropper#437]
it would be nice to have an option to prevent the user from making his image smaller than the container and to prevent him from moving it out of the container.

strict mode does that already for the crop box, but unfortunately not for the container.

the following images illustrates what should be prevented:

![image-smaller-than-container](https://cloud.githubusercontent.com/assets/6793674/9496847/9cb7267c-4c12-11e5-8e17-df6045d65a72.png)

![image-moved-out-of-container](https://cloud.githubusercontent.com/assets/6793674/9496980/3542b460-4c13-11e5-9dfb-689b364a66a5.png)

**Comment by anthonyav** [comment]
i'm looking for the same feature

**Comment by anthonyav** [comment]
i'm looking for the same feature

**Comment by fengyuanchen** [comment]
Maybe what you need is someting like the third example: [Cropper with responsive container](http://fengyuanchen.github.io/cropper/).

**Comment by dfherr** [comment]
well it's close, but not exactly what i would like to have.

Moving and zooming is fine, as long as the image does not leave the visible area. The example blocks zooming and moving completly.

**Comment by genmacg** [comment]
I'm not sure if that's the exact use case you're looking for but make the crop box the same size as the container and disable cropBoxMoveable and cropBoxResizable.

**Comment by fengyuanchen** [comment]
You can try to set the `viewMode` option to `3` to get it on the latest v2.0.0 now.
