### ISSUE TITLE
canvas.toDataURL not a function

### ISSUE THREAD

**Issue by longpham91** [fengyuanchen/cropper#441]
Hi there,

First of all, thanks for the work here! I love this tool.

Second, I've been running into this problem recently, when I can't get the CanvasData by using toDataURL(). I took a peek at the result returned after running GetCroppedCanvas, and it looked like this:

<img width="808" alt="2015-08-28_11-36-32" src="https://cloud.githubusercontent.com/assets/2569884/9550438/484f22a2-4d79-11e5-9b12-13603207c662.png">

That doesn't look like a canvas element, which is probably why my code is failing. I've upgraded Cropper to latest version, and confirmed that this occurs in my project for multiple browsers. Running this from my dev box, so no Chrome/Firefox extensions. I saw another issue related to toDataURL also, but that happened on iOS environment, so probably doesn't have anything to do with this. Also, I'm pretty sure this is a Cropper issue, since I saw in the documentation that CanvasData can be retrieved by simply calling toDataURL() function.

Please assist!

Best regards,

Leo

**Comment by fengyuanchen** [comment]
Please my documentation about how to call a method carefully! 
https://github.com/fengyuanchen/cropper#methods

**Comment by longpham91** [comment]
Oh yeah was gonna reply that I found the culprit. It's something I added to data-method, without realizing that I'd also have to add the method to source code. My apologies.
