### ISSUE TITLE
Choose file -> cancel issue

### ISSUE THREAD

**Issue by douglasrhiner** [fengyuanchen/cropper#443]
I'm working with a slightly customized version of the cropAvatar example and have found a scenario where this.$avatarInput.val() is emptied causing the UI to "break".
Example:
If I click "choose file", find an image and then click "open" an image is loaded and the cropper starts as expected. However, if I try to select yet another image by again clicking "choose file" for a second time ( prior to clicking "crop & upload ) but then clicking "cancel" instead of "open" and then clicking "crop & upload" nothing happens. From my analysis,  this.$avatarInput.val() is empty/null and submit: returns false.
From a UX/UI view, what should happen is that the cropper state should revert to the state prior to clicking "choose file" the second time. This would be a simple modification in principal but since you can not programmatically set the value of <input type="file"> this becomes a bit more interesting.

Do you have any thoughts about this?

**Comment by fengyuanchen** [comment]
Maybe the file you chosen has been cleared after you click the `cancel` button.

**Comment by milivojsa** [comment]
I have the same issue. 

The reason for this is because `$("input:file").change(function() {...});` is executed again even if no file is selected.

I don't know if there is some option to check for the cancel action.
