### ISSUE TITLE
Trouble with npm install

### ISSUE THREAD

**Issue by rygim** [fengyuanchen/cropper#444]
I just ran npm install and I am having trouble with some of the dependencies for cropper:

> npm install
npm http GET https://registry.npmjs.org/cropper
npm http 304 https://registry.npmjs.org/cropper
npm http GET https://registry.npmjs.org/fengyuanchen/tooltip/0.0.2
npm http 404 https://registry.npmjs.org/fengyuanchen/tooltip/0.0.2
npm ERR! 404 'fengyuanchen' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url

Is something not published or do I need to do something else?  The relevant part of my package.json is as follows:

  "dependencies": {
    "body-parser": "~1.13.3",
    "cookie-parser": "~1.3.5",
    "cropper": "^0.11.1",

Thanks in advance.

**Comment by fengyuanchen** [comment]
Please update your NPM.

**Comment by rygim** [comment]
Wow, you are absolutely right.  I was at 1.3.6.  

That fixed it, thanks.

**Comment by amirashurov** [comment]
Hi! I have problem when an image resolution is so big, can you help me
