### ISSUE TITLE
Zoom not centered to crop-area

### ISSUE THREAD

**Issue by sendele** [fengyuanchen/cropper#446]
Can be reproduced on the demo page: When zooming in/out (no matter if mouse wheel or buttons are used) the center of the image stays at the same place, but if the crop-box is not centered on the image, it "moves around" on the image.

I think it would be more intuitive if the center of the crop-box was fixed to where it is placed on the image at the moment.

Use case: One places the drop-box on a certain part of the image (say the right eye of Emma Watson), then he decides to take a closer clip and zooms in. As a results he has to re-position the crop-box, as the eye is eventually not even within the crop-box.

Maybe an option to activate this behavior would be good.

Another possibility might be to center the cavas or the contained while zooming.

Btw: This is the best JS image cropping tool that can be found on the web!

**Comment by marcoo** [comment]
+1

**Comment by fengyuanchen** [comment]
I think it is unnecessary to do this.

**Comment by 2Owy** [comment]
Hi.
So if I understand correct there is no possibility to keep the canvas centred when you zoom in/out and you move the mouse arround it.

**Comment by fengyuanchen** [comment]
@2Owy You can disable wheel zoom and zoom with the `zoom` and `zoomTo` methods.
