### ISSUE TITLE
Error with scaled Image and minCropBox Settings

### ISSUE THREAD

**Issue by zf2timo** [fengyuanchen/cropper#449]
When the image is down-scaled by HTML/CSS, the minCropBoxWith and minCropBoxHeight are not respected correctly.
See [this Example](https://jsfiddle.net/exchange/07xwk6vw/), for a better understanding of the Problem.

I'd expected the values in width and height are never less than 1200px and 500px, but as you can see they are 1183px and 492px.
My assumption is there are errors with different image sizes. The original image has a height of 1067, which are down-scaled to 274px but the image copy created by Cropper has 278px.

I just started yesterday to use this plugin, so i am not experienced enough to created a PR with a fix.

**Comment by fengyuanchen** [comment]
I don't understand. You example isn't available.
