### ISSUE TITLE
base64 format

### ISSUE THREAD

**Issue by Serhiosnic** [fengyuanchen/cropper#45]
Could you add the ability to use your cropper when the image source is represent as in base64 format?

e.g.

div
img class="cropper" scr="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQE...">
/div

Or it is impossible?

**Comment by zpbd** [comment]
Hi Fengyuan, great plugin.

I'm struggling with this a bit. What I'm trying to do is crop an image **without ever uploading it to the server filesystem** (I have important privacy reasons for doing so). So I'm using this:

```
<img id="image"> /*Image which will get the base64 src*/
<input type="file" id="imageUpload" accept="image/*"> /*Our image upload input*/
```

```
function readURL(e) {
    if (this.files && this.files[0]) {
        var reader = new FileReader();
        $(reader).load(function(e) { $('#image').attr('src', e.target.result); });
        reader.readAsDataURL(this.files[0]);

        $('#cropper-image').cropper(); //invoke the cropper
    }
}
$("#imageUpload").change(readURL);
```

I have looked at your Crop Avatar example, but I can't quite figure out what's going on. I think your example has a fallback for when the browser doesn't support the FileReader api but I don't understand what I need to do differently to invoke the cropper on my image with a base64 src.

Could you point me in the right direction?

**Comment by zpbd** [comment]
Ah, it turns out that I was invoking cropper too soon, as the `readAsDataURL` method happens asynchronously. 

The solution was to use the FileReader `onloadend` event:

```
function readURL(e) {
    if (this.files && this.files[0]) {
        var reader = new FileReader();
        $(reader).load(function (e) { $('#image').attr('src', e.target.result); });
        reader.readAsDataURL(this.files[0]);

        reader.onloadend = (function () {
            $('#cropper-image').cropper();
        });
    }
}
```
