### ISSUE TITLE
cropstart event on zoom

### ISSUE THREAD

**Issue by tlemmons** [fengyuanchen/cropper#450]
This is probably a foolish question but I cans seem to figure it out.  I am using cropstart to set some stuff on the page but it does not fire when using the mouse wheel to just zoom the image.  Is there a way to get it to hit then also or does another event work better.

**Comment by fengyuanchen** [comment]
You can trigger `cropstart` manually, but I suggest you avoid to do this:
```js
$('img').on('zoom.cropper', function () {
  $(this).trigger('cropstart.cropper');
});
```
