### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by kartagis** [fengyuanchen/cropper#451]
Hi,

I've tried hard with the plugin and did exactly as described, but couldn't even make it work. I even took your example as is, but couldn't make that work either. Please could you take a look at http://jsfiddle.net/kartagis/8qbdkw23/1/ and tell me what I'm doing wrong?

Thanks,

**Comment by fengyuanchen** [comment]
Are you include the Cropper's script and style file?

**Comment by kartagis** [comment]
Yes, I include them. If you look at the fiddle, you can see it.

**Comment by kartagis** [comment]
Sorry, not directly. I added them as external resources.

**Comment by kartagis** [comment]
I fixed it. I realised I src'd the wrong file and uploaded the right one with the same name, and didn't realise jsfiddle cached the old one.
