### ISSUE TITLE
Window is not defined in node environment

### ISSUE THREAD

**Issue by nbwar** [fengyuanchen/cropper#453]
In my case i'm doing server side rendering of components for use in react. The component is include via require() so it executes on the server even if it isn't used for server side rendering.

A module in npm should be guarded correctly in order to be requirable in node environments and used in Server Side Rendering.

```
$ node
> require('react-cropper')
ReferenceError: window is not defined
```

**Comment by fengyuanchen** [comment]
This is not a issue. Cropper requires a window with a document.

**Comment by jamaica474** [comment]
I am having similar problem. What happens is - most of my application is rendered on server side. For parts that cannot be rendered on server I use { (typeof window != 'undefined' && window.document)} conditional.
The very fact that your library requires window right then I do the import makes it unusable(there are no dynamic modules import in es6).

I believe cropped should fail with this message when I try to actually use it on server, not just import it.
