### ISSUE TITLE
CropBox Fixed 

### ISSUE THREAD

**Issue by Darshkore** [fengyuanchen/cropper#454]
Hi, I would like to fix the cropbox size despite of any resolution/size the image is. 

I have a fixed banner size of 668 x 226 so i want users to crop the image in that size itself. can you help me in getting this result please ? 

Thanks.

**Comment by fengyuanchen** [comment]
Try this config:

```js
$().cropper({
  strict: false,
  cropBoxMovable: false,
  cropBoxResizable: false,
  built: function () {
    var container = $(this).cropper('getContainerData');
    var cropBoxWidth = 668;
    var cropBoxHeight = 226;

    $(this).cropper('setCropBoxData', {
      width: cropBoxWidth,
      height: cropBoxHeight,
      left: (container.width - cropBoxWidth) / 2,
      top: (container.height - cropBoxHeight) / 2
    });
  }
});
```

**Comment by Darshkore** [comment]
Heyy, thanks a lot, it works well. the only problem im facing on it is when I upload vertical image like with larger height then the width, the image loads off to the cropbox. 

![image](https://cloud.githubusercontent.com/assets/2732393/9981021/4554958a-5fcd-11e5-9be6-7b8ee26f9444.png)


		 	strict: false,
			cropBoxResizable: false,
			cropBoxMovable: false,
			highlight: false,	
		    guides: false,
			modal:true,
			checkImageOrigin:true,
			minCanvasWidth:678,
			maxCanvasHeight:226,
			dragCrop: false,  
	        preview: '.img-preview',
		   built: function () {
    var container = $(this).cropper('getContainerData');
    var cropBoxWidth = 678;
    var cropBoxHeight = 226;
    $(this).cropper('setCropBoxData', {
      width: cropBoxWidth,
      height: cropBoxHeight,
      left: (container.width - cropBoxWidth) / 2,
      top: (container.height - cropBoxHeight) / 2,
    });
  }

**Comment by nandanself** [comment]
How Can I fix the cropBoxSize in ember.The addon is present in ember ? https://github.com/mhretab/ember-cli-image-cropper
