### ISSUE TITLE
Max image and canvas size

### ISSUE THREAD

**Issue by jzahka** [fengyuanchen/cropper#455]
Hi!

First, thank you for creating such an excellent cropping tool! Your source code is beautiful. My question: Is there an easy way to set the max width and height of the image to crop? When a large file is uploaded the cropper modal becomes too large for the screen.

John

**Comment by amirashurov** [comment]
I have same problem

**Comment by amirashurov** [comment]
i found the solution, you must set for container height 
 <div id="cropper-example-2" class="edit-photo-container">
         <img id="cropperImg" src="~/Content/images/no-photo.jpg" alt="Picture">
 </div>
.edit-photo-container {
    height: 600px;
}

**Comment by jzahka** [comment]
That doesn't quite do it for me. I'm using the modal format very close to the example https://github.com/fengyuanchen/cropper/tree/master/examples/crop-avatar

**Comment by fengyuanchen** [comment]
Just limit the size of the image width...
