### ISSUE TITLE
Cropping images with blob URLs

### ISSUE THREAD

**Issue by bgreeley** [fengyuanchen/cropper#457]
I'm currently using the ng-file-upload plugin and I'm using the ngf-src attribute to preview the image before I upload it. The image src attribute of the preview is a blob URL. Can I use cropper with a blob URL? I've tried doing so - instantiating the cropper after the image is selected, but haven't had any luck. 

```html
<div class="col-md-12" id="photo-preview-crop-container">
    <img ngf-src="file">
</div>
```

```javascript
$scope.selected = function() {

    // Show cropper tools
    $('#photo-preview-crop-container > img').cropper({
        aspectRatio: 4 / 3,
        zoomable: false,
        crop: function(e) {
            console.log(e);
        }
    });
};
```

Is this even possible? I can just upload the image and have my API return the uploaded file path on the server, but I'd prefer to not have to do that because the application will have two POSTs per image: one to submit and get a URL and then the other to submit the cropped version.

**Comment by fengyuanchen** [comment]
Blob URL is available for Cropper.

**Comment by daominhsangvn** [comment]
Hi @fengyuanchen , I'm trying to integrate the filter plugin (http://camanjs.com/) along with your cropper. The camanjs return the base64 image data after apply the filter, I tried to use cropper replace method but no succeed. Is the cropper support base64 image? I also tried to convert to blob URL, but the image never render.

**Comment by fengyuanchen** [comment]
HTTP, HTTPS, File URLs, Data URLs and Blob URLs are all available for Cropper. Just check your own code!

**Comment by Activee** [comment]
An example for external url would be welcome. I'm having trouble as the image doesn't display itself even though it appears in the src attribute.
    	    	     $imageCrop.cropper('replace','http://cdn.homeshopping.pk/product_images/uploaded_images/Dish-TV-Packages.jpg');

**Comment by fengyuanchen** [comment]
@Activee For cross-origin images, read the [notes](https://github.com/fengyuanchen/cropper#notes) please.

**Comment by Activee** [comment]
sorry just found out about it. I was about to delete my comment but you are too fast.
