### ISSUE TITLE
setData function doesn't set up Flips

### ISSUE THREAD

**Issue by zem-aleks** [fengyuanchen/cropper#459]
How to reproduce:
1. Flip the image by horizontal axe (scaleX parameter will be -1). 
2. Apply getData function to the cropper and remember result to the variable. For example, data = $().cropper('getData', true);
3. Again flip the image (scaleX will be 1). 
4. set Data using parameters from the variable $('setData', data)
 Image won't be flipped back.

**Comment by fengyuanchen** [comment]
Already [fixed](https://github.com/fengyuanchen/cropper/commit/5ef211c5825cbf51fb0714c8d19181da5a4ee39a), will be released soon. Thanks.

**Comment by zem-aleks** [comment]
Thanks for the quick response!
