### ISSUE TITLE
GetData not updating object after crop.cropper event fires twice.

### ISSUE THREAD

**Issue by sant123** [fengyuanchen/cropper#460]
Hi, as the title says when the crop.cropper fires it gives me the correct object for example this:
```javascript
{
    "x": 0,
    "y": 0,
    "width": 500,
    "height": 485,
    "rotate": 0,
    "scaleX": 1,
    "scaleY": 1
}
```
But when I change the image (using the method replace and I also use it in the first step) the result object is:

```javascript
{
    "x": 0,
    "y": 0,
    "width": 0,
    "height": 0,
    "rotate": 0,
    "scaleX": 1,
    "scaleY": 1
}
```

Also instead of using the parameter from the method, I have invoked the method in the callback phase ```$( "#image1").cropper("getData"); ``` but it gives me the same result. But if I invoke the previous method in the console, it works! 

So I think every time the image changes it should give the object filled and not empty. (Ignoring scaleX and scaleY).

Thank you!.

**Comment by fengyuanchen** [comment]
If you call the `replace` method, it will rebuild the cropper, so you should call the other methods after built.

**Comment by sant123** [comment]
Yes I did it, but the crop.cropper event execute twice as well. I just used a setTimeout in order to get the data from the cropper and it works. But it should give me the object data without using replace or setTimeout or other methods.
