### ISSUE TITLE
 Index or size is negative or greater than the allowed amount

### ISSUE THREAD

**Issue by DanielVC** [fengyuanchen/cropper#461]
When trying to use Cropper with an large image we get the following error:

 "Index or size is negative or greater than the allowed amount"

The dimension of the image used is: 3954 x 710

**Comment by fengyuanchen** [comment]
What's the browser and version?

**Comment by DanielVC** [comment]
Firefox
40.0.3

**Comment by fengyuanchen** [comment]
I test this with the following conditions, and everything is fine:
- Windows 10
- Firefox 41
- A huge image with 5600 × 3600 (px)
