### ISSUE TITLE
图片截取不对，问题bug请求大神？

### ISSUE THREAD

**Issue by liuwenfeng554** [fengyuanchen/cropper#462]
设置width和height，通过“Get Cropped Canvas”获取图片尺寸不对，截取的尺寸都会多好几个像素，这是为什么？是插件本身存在的算法bug吗？

**Comment by fengyuanchen** [comment]
参数的宽高比必须与裁切框的宽高比保持一致（你也可以只传递一个width或一个height，让插件根据裁切比例自动计算另一个值）。当然，`canvas`元素会将结果四舍五入，所以可能会出现最多1px左右的偏差。

**Comment by liuwenfeng554** [comment]
如果300X350的图片想截取600X200的这样插件可以支持吗？

**Comment by liuwenfeng554** [comment]
如果300X350的图片想截取600X200的这样插件可以支持吗？@fengyuanchen
