### ISSUE TITLE
Blob Image not showing on Mozilla Firefox 41.0

### ISSUE THREAD

**Issue by gmisa** [fengyuanchen/cropper#466]
It is working for me on all major browsers except Firefox 41.0 where I am getting this error on the console whenever I select an image:

Content Security Policy: The page's settings blocked the loading of a resource at blob:https://mydomain.com/6ad83048-3dfc-5b45-aedc-4d414e817580 ("img-src *").

I added this on the head tag of my html:

< meta http-equiv="Content-Security-Policy" content="img-src 'self' data: blob:"   / >

but still doesn't work.  Image does not show up.

**Comment by fengyuanchen** [comment]
Are you sure this is an issue of Cropper?

**Comment by fengyuanchen** [comment]
Are you sure Firefox 41 supports `Content-Security-Policy`?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#Browser_compatibility

**Comment by gmisa** [comment]
We can close this issue.  I realized that Firefox actually supports Content-Security-Policy while the other browsers ignore this policy.  Our server had restrictions with img-src to 'self'.  When i set security.csp.enable to false in Firefox, the cropper worked perfectly.

**Comment by arist0tl3** [comment]
@gmisa Just wanted to say thank you for posting that meta tag. This had me scratching my head for a while today!
