### ISSUE TITLE
Set boundaries when moving crop box

### ISSUE THREAD

**Issue by Lilian-Chen** [fengyuanchen/cropper#469]
Hi everyone, 

I have encountered some difficulties, hope to get some help here. 

I am working on a project which allows users to upload an image and then crop the selected area to save into file. The minimum crop area has been defined which does not allow to crop less than a specific value. However, users may upload image size less than the minimum crop area. I have to set strict to be false to display original image without stretch it to the same size as crop box. Users should not move the crop box out of image height and width, as container is much bigger than uploaded image size. Is there any way to set the boundaries when moving crop box?
![image crop](https://cloud.githubusercontent.com/assets/14883744/10155497/83d27960-66d2-11e5-8d99-3f45a5f7070c.png)

Thank you in advance for your time and support!

**Comment by fengyuanchen** [comment]
Try `cropmove` event:
```js
$().cropper({
  cropmove: function (e) {
    var canvasData = $(this).cropper('getCanvasData');
    var cropBoxData = $(this).cropper('getCropBoxData');

    if (
      cropBoxData.left < canvasData.left || 
      cropBoxData.top  < canvasData.top  || 
      cropBoxData.left + cropBoxData.width > canvasData.width + canvasData.left || 
      cropBoxData.top + cropBoxData.height > canvasData.height + canvasData.top
    ) {
      e.preventDefault();
    }
  }
})
```

**Comment by Lilian-Chen** [comment]
e.preventDefault(); will totally stop the crop box from moving. In the situation I described, users should be able to move the crop box but only horizontally or vertically.
![vertical image example](https://cloud.githubusercontent.com/assets/14883744/10351042/e18e5b8c-6da3-11e5-8cae-d3de8c94ffd2.png)

**Comment by EsmaeilMazahery** [comment]
use viewMode Option
