### ISSUE TITLE
Responsive issue

### ISSUE THREAD

**Issue by Lilian-Chen** [fengyuanchen/cropper#470]
Set the strict to be true, and uploaded a image smaller than container. Resized the browser window to be smallest, the image still could be displayed inside of container. However, when resized the browser window to maximum, image canvas appeared out of container boundaries. Only when set strict to be false, then image would be responsive correctly. I need to set strict to be true because I do not want users to crop out of canvas.
![original image view](https://cloud.githubusercontent.com/assets/14883744/10186039/49cde78a-67aa-11e5-83cc-07d3571d48a2.png)
![shrink browser window size](https://cloud.githubusercontent.com/assets/14883744/10186043/508ad60a-67aa-11e5-8daa-81cfbc7d0dc7.png)
![maximise browser window again](https://cloud.githubusercontent.com/assets/14883744/10186049/5dc070c8-67aa-11e5-8ee1-79887de9e63c.png)

**Comment by ThemisB** [comment]
I have exactly the same problem

**Comment by fengyuanchen** [comment]
Don't limit the height of the container, see example 3: [Cropper with responsive container](http://fengyuanchen.github.io/cropper/#examples).
