### ISSUE TITLE
Image zoom increaset when rotate image

### ISSUE THREAD

**Issue by navneetccna** [fengyuanchen/cropper#474]
Step
1) Clear crop
2) Rotate image 2 times in any direction

**Comment by marcoo** [comment]
#445

**Comment by stylefieber** [comment]
Hey there, I fixed it for my own needs. The basic idea is (for strict mode), to manipulate the cropbox dimensions before rotating, then rotate the image, set it to the right position and then manipulate the cropbox dimension back.

I just have a button which rotates an image in 90° steps. My fix has not been tested for other purposes.

And here some code: http://stackoverflow.com/a/32938693/2689455
