### ISSUE TITLE
Cropper adds a line to image if it's too big

### ISSUE THREAD

**Issue by nachoargentina** [fengyuanchen/cropper#476]
Hi!
I'm facing an issue with big images. And I mean big in pixels, not necessarily big on size.
I have for example this sunset image which is 5472 x 3648px and weights about 581kb.
When I upload it to the cropper, it looks good:

![image](https://cloud.githubusercontent.com/assets/6412598/10273326/322be7b8-6b05-11e5-99bc-c290322678b7.png)

I make a little zoom, move it around a bit and click on the "get cropped canvas" button on the demo page for the cropper, and I end up with the cropped image with a weird line. Some times is vertical, some times it's horizontal:

![image](https://cloud.githubusercontent.com/assets/6412598/10273339/75197428-6b05-11e5-929b-1c4385465039.png)

Do you guys know anything about this and how to avoid it?

**Comment by tilocgn** [comment]
I'm having the same problem! Thanks for reporting the issue :thumbsup:

**Comment by fengyuanchen** [comment]
What's the browser and system?

**Comment by nachoargentina** [comment]
I apologize for the delay fengyuanchen! I've been out of town.
The browser is Chrome Versión 46.0.2490.71 m and the system is Windows 8.1

**Comment by nachoargentina** [comment]
If you want I can send you the specific image I'm having issues with also! but any big image in terms of resolution is having the same problem on my end. I've even tried it on a Mac and Safari (don't know version here as it was a firend's computer) and was getting the same issue.

**Comment by fengyuanchen** [comment]
Send me the specific image please as I found that everything is fine on Chrome 46 and Windows 10 in my computer.

**Comment by nachoargentina** [comment]
Here's the image. Please note that the problem shows after you crop the image (after running getCroppedCanvas)

![masai-mara-sunset](https://cloud.githubusercontent.com/assets/6412598/10580774/829b21ea-7655-11e5-8c25-08e4edf4638b.jpg)

**Comment by fengyuanchen** [comment]
It seems to be an issue of the [CanvasRenderingContext2D.drawImage](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) API, and it only occurs when the dimensions of the image large than some threshold values (e.g. 5400 × 3600 px).

**Comment by nachoargentina** [comment]
Ok...so then this is not a an issue with the cropper, is just that the API is like that. Can you think of any workaround that doesn't involve re-sizing the image to a lower res? or we are stuck with this API issue?
I'll look around to see if there's anything that can be done about it.

**Comment by fengyuanchen** [comment]
**Passed browsers**:
- Firefox 41
- Internet Explorer 11
- Windows Edge

**Failed browsers**:
- Chrome 46
- Opera 32
- Safari (lastest?)

So, this may be a bug of the Webkit or Chromium?

**Comment by hppycoder** [comment]
You could run this through a pre-renderer first to crop the image back. We use BlueImp's Javascript Load Image and set the max-width to: 1500

```
var file = evt.target.files[0];
loadImage(
                    file,
                    function (canvas) {
                      // inner manipulation of a canvas
                    },
                    {
                      maxWidth: 1500,
                      orientation: orientation,
                      canvas: true
                    }
                  );
```

**Comment by stephanpaquet** [comment]
We've got the same issue here on Windows / Chome.

I tried a lot of time with Ubuntu / Chrome and never succeed to reproduce it, with the same picture. The picture is (10 109 x 4 542 px)

**Comment by ctomoshekamer** [comment]
Hi @hppycoder ,
Where did you put this code?
Thanks,

**Comment by nachoargentina** [comment]
Hi @hppycoder! I'm already using that for mobile cropping, as the memory there is an issue with big images.
I wanted to use full resolution images for desktop though, but having this issue, I see no way out of it for now, so that might be the only solution...
I believe the problem comes with the native drawImage method, which does a subsample of the image and in that process it adds the lines

**Comment by ctomoshekamer** [comment]
Hi,
In file: cropper.js, in line:2444.
replace: args.push(dstX, dstY, dstWidth, dstHeight); 
to: args.push(Math.floor(srcX), Math.floor(srcY), Math.floor(srcWidth), Math.floor(srcHeight));

It's need to resolve the problem.

**Comment by fengyuanchen** [comment]
@ctomoshekamer I just try your solution, It really resolves the problem. You are so awesome!!! :+1:

**Comment by nachoargentina** [comment]
Sorry for the late comment, but I couldn't leave the opportunity to say thank you!! This is great!!
