### ISSUE TITLE
Prevent canvas of getting smaller than the container

### ISSUE THREAD

**Issue by tilocgn** [fengyuanchen/cropper#478]
Hi,
I'm migrating the cropper from v0.9.1 to the recent version and I'm am wondering if there is a way to prevent the canvas of getting smaller than the container. Actually its not a problem of size rather the canvas should always fill out the complete container. 

In strict mode I'm using right now the image can be moved to the boundaries of the cropper but i would like to expand this behaviour to the container. 

In v0.9.1 it was the normal behaviour if I'm not mistaking.

Thank you!

**Comment by fengyuanchen** [comment]
Try this:
```html
<div id="container">
  <img id="image" src="/path/to/picture.jpg">
</div>
```
```js
var $container = $('#container');

$('#image').cropper({
  minCanvasWidth: $container.width(),
  minCanvasHeight: $container.height()
});
```

**Comment by tilocgn** [comment]
Thanks, thats a step in the right direction. But i can still move the image so far that i can see the checkered background. I never want to be able to do that. 

It should always look like the first one and never like the second:

![cropper](https://cloud.githubusercontent.com/assets/11157110/10348575/14c276c4-6d3a-11e5-8644-eeea83b32ddd.jpg)

I think i'll somehow need to check the coordinates too and prevent it to happen with the help of the cropmove.cropper event.

**Comment by tilocgn** [comment]
@fengyuanchen Any thoughts on this? I would really appreciate some input!

**Comment by fengyuanchen** [comment]
As you say, you can use `cropmove.cropper` event, why not try it?

**Comment by AbrahamGreyson** [comment]
@fengyuanchen  great work! man.

**Comment by tilocgn** [comment]
I'm having a hard time finding a good result. I'm having a couple of problems, maybe you some input on that.

1. Setting minCanvasWidth and minCanvasHeight does not work as expected. Instead of setting the exact width and height, it always shows the full picture.  If the image is landscape it will take the width as minCanvasWidth and doesnt respect the minCanvasHeight and vice versa.

2. The use of the cropmove.cropper and the zoom.cropper events to prevent from the image from moving out of focus is working but have a really bad user expericence. 

```javascript
        'cropmove.cropper': function (e) {

            var CanvasData = $(this).cropper('getCanvasData');
            var DeltaWidth = $container.width() - Math.round(CanvasData.width) ;
            var DeltaHeight = $container.height() - Math.round(CanvasData.height);
           
            if (Math.round(CanvasData.top) >= 0) {
                CanvasData.top = 0;
                $(e.target).cropper('setCanvasData', CanvasData);
            } 

            if ( Math.round(CanvasData.left) >= 0 ) {
                CanvasData.left = 0;
                $(e.target).cropper('setCanvasData', CanvasData);
            } 
            
            if (Math.round(CanvasData.top) <= DeltaHeight ) {
                CanvasData.top = DeltaHeight;
                $(e.target).cropper('setCanvasData', CanvasData);                
            } 
            
            if (Math.round(CanvasData.left) <= DeltaWidth) {
                CanvasData.left = DeltaWidth;                
                $(e.target).cropper('setCanvasData', CanvasData);
            }            
            
        }          
```
I made a fiddle for that http://jsfiddle.net/tilocgn/u28b2xfd/3/

**Comment by fengyuanchen** [comment]
@tilocgn 

1. Why not use the `e.preventDefault`?
2. Can you just call the `setCanvasData` method once in each event handler rather than several times?
3. What is this: `CanvasData.left <= DeltaWidth`(left < width)?!
4. Are you sure use `>=` and `<=` is fine? Why not `>` and `<`?

**Comment by tilocgn** [comment]
Thank you for your reply. e.preventDefault() does not work because after it is set once the canvas and cropper stops moving. But of course you should only use setCanvasData once, you are right! 

CanvasData.left <= DeltaWidth is the maximum offset the image should be able to moved to if it is bigger than the canvas. It works like this but not very good. When you try to move the image away from the canvas it starts shaking and oddly enough when you pull the image fast enough you can create a space between image and canvas.

Do you have any other idea what i could do here? And do you have a suggestion about the other problem i had: 

"Setting minCanvasWidth and minCanvasHeight does not work as expected. Instead of setting the exact width and height, it always shows the full picture. If the image is landscape it will take the width as minCanvasWidth and doesnt respect the minCanvasHeight and vice versa."

Thanks again for your help and the awesome tool you built!
