### ISSUE TITLE
Fixed size cropBox does not rescale on built

### ISSUE THREAD

**Issue by intellisense** [fengyuanchen/cropper#480]
So I set the crop area to 400x300 because I want fixed size crop area:

```
$cropImage.cropper({
        dragCrop: false,
        background: false,
        cropBoxResizable: false,
        movable: false,
        guides: false,
        highlight: false,
        built: function () {
          // Strict mode: set crop box data first
          var container = $(this).cropper('getContainerData');
          $(this).cropper('setCropBoxData', {
            width: 400,
            height: 300,
            left: (container.width - cropBoxWidth) / 2,
            top: (container.height - cropBoxHeight) / 2
          });
        }
      });
```

When page is loaded on desktop and resized to narrow window the crop box area adjust itself. But when the page is loaded in a mobile view (320 view port) the crop box area does not re-scale based on container and image resolution. Any help?

**Comment by fengyuanchen** [comment]
The crop box should **within** the container! 
when the width of the container is 320 pixels, how can you set the width of the crop box to 400 pixels which great than 320 pixels?
