### ISSUE TITLE
Rotation Origin

### ISSUE THREAD

**Issue by ascottmccauley** [fengyuanchen/cropper#481]
I've come up empty while looking into changing the origin of the `.rotate` function to rotate around the center of the  crop box instead of the center of the image. Does anybody have any idea how best to adapt that. 
Also, I just wanted to check how difficult it might be to create `rotateTo` and `scaleTo` functions?

**Comment by fengyuanchen** [comment]
The rotation function is supported by CSS3 2D Transforms. When you rotate the image, it always rotate around the center of the image, you can't change this.  So, the only way is keeping the center of the image and crop box at the same point.

**Comment by fengyuanchen** [comment]
About the second question, the following methods already added to the source code, and will be released in the next version:
- `moveTo`
- `zoomTo`
- `rotateTo`
- `scaleX`
- `scaleY`

**Comment by fengyuanchen** [comment]
The new v2.0.0 with these new methods had been released.

**Comment by ArnonSpam** [comment]
Hi,

it can be solved by implementing a rotation matrix into the
rotate: function (degree)


            if (degree && this.built && !this.disabled && this.options.rotatable) {
                image.rotate = (image.rotate + degree) % 360;
                this.rotated = true;

               ////////////////////////////////////////////////////////////////////////////////////////////////////////////
                // Calculate the delta created by rotating around arbitrary axis
                var x = (this.cropBox.left + this.cropBox.width / 2) - (this.canvas.left + this.canvas.width / 2);
                var y = (this.cropBox.top + this.cropBox.height / 2) - (this.canvas.top + this.canvas.height / 2);
                var rad = degree * Math.PI / 180;
                var deltaX = x - (x * Math.cos(rad) - y * Math.sin(rad));
                var deltaY = y - (x * Math.sin(rad) + y * Math.cos(rad));
                // add the delta pre rendering
                this.canvas.left += deltaX;
                this.canvas.top += deltaY;
             /////////////////////////////////////////////////////////////////////////////////////////////////////////////

                this.renderCanvas(true);
            }


Arnon Mathias
