### ISSUE TITLE
Cropper.js cropper('getCroppedCanvas') toBlob Work on firefox error in safari, chrome

### ISSUE THREAD

**Issue by map1975** [fengyuanchen/cropper#483]
I try to post cropped image like a function in documentation fengyuanchen/cropper

    <div class="container">
      <div class="cropper-example-1">
        <img src="../assets/img/503601019.jpg" alt="Picture">
      </div>
    </div>

    $(function () {
        $('.cropper-example-1 > img').cropper({
          aspectRatio: 16 / 6,
          autoCropArea: 0.65,
          strict: false,
          guides: false,
          highlight: false,
          dragCrop: false,
          cropBoxMovable: false,
          cropBoxResizable: false,
    
        });
    
        $('.cropper-example-1 > img').cropper('getCroppedCanvas').toBlob(function (blob) {
          var formData = new FormData();
    
          formData.append('croppedImage', blob);
    
          $.ajax('upload.php', {
            method: "POST",
            data: formData,
            processData: false,
            contentType: false,
            success: function () {
              console.log('Upload success');
            },
            error: function () {
              console.log('Upload error');
            }
          });
        });
    
      });

The script works with Firefox . 
But with Safari and Chrome have this error : 

TypeError : undefined is not a function ( evaluating ' $ ( ' . Cropper -example - 1 > img ' ) . Cropper ( ' getCroppedCanvas ' ) . ToBlob ' )

How can I fix ?

**Comment by fengyuanchen** [comment]
Please read the documentation about how to call a method carefully!
https://github.com/fengyuanchen/cropper#methods

**Comment by ZacWolf** [comment]
The link provided doesn't explain anything having to do with toBlob throwing an error in Chrome/IE, but not Firefox.  You're own example code throws the same error in Chrome and IE...

**Comment by ZacWolf** [comment]
Here is a link that explains that toBlob is currently only supported in Firefox, but provides a workaround prototype based on dataUrl: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob
