### ISSUE TITLE
setCropBoxData and iFrame

### ISSUE THREAD

**Issue by erdoesa** [fengyuanchen/cropper#484]
Hi,

I am facing an issue where setCropBoxData does not render cropbox correctly when opening image for cropping in an iFrame (fancybox - type iframe). Initially the size of the cropbox is wrong (I guess some default), when reloading iFrame content, the size is correct! It is always correct when opening iFrame URL directly in browser...

Any ideas what causes the problem on first load?

Regards,
Arthur

**Comment by fengyuanchen** [comment]
Did your `cropBoxData` come from the cropper in the iframe? Would you mind to provide an online demo?

**Comment by erdoesa** [comment]
Thx for the quick reply!

Yes, the cropBoxData come from the cropper in the iframe. I set up exactly my scenario for you here:
http://cropper-demo.s3-website.eu-central-1.amazonaws.com

You can get the iframe (with correct box size) directly using iframe content URL:
http://cropper-demo.s3-website.eu-central-1.amazonaws.com/iframe.html

**Comment by erdoesa** [comment]
Just figured out that the problem only occurs when loading the image to crop from other (sub)domain

**Comment by fengyuanchen** [comment]
If the image load from other (sub)domain, then it is cross origin, you may try to set `checkImageOrigin` option to `false`.

**Comment by erdoesa** [comment]
That does not work either and causes unexpected behaviour (cropper not initialized correctly when reloading image). Anyway, works like a charm with cross origin images without lightbox/iframe.
