### ISSUE TITLE
setCanvasData and setCropBoxData in strict model

### ISSUE THREAD

**Issue by elaijuh** [fengyuanchen/cropper#485]
So I want to initialise the canvas and cropBox with the stored data since last crop. But it turns out that the position is not as expected, given the cropBox is inside the canvas with strict mode.  I am assuming there is default initial canvas and cropBox and then the built functino will adjust them, there is some tricky parts here...

**Comment by fengyuanchen** [comment]
You should call the `setCropBoxData` before `setCanvasData` in strict mode:

```js
$().cropper({
  built: function () {
    // Strict mode: set crop box data first
    $image.cropper('setCropBoxData', storedCropBoxData);
    $image.cropper('setCanvasData', storedCanvasData);
  }
});
```

**Comment by elaijuh** [comment]
I did exactly what you suggested, but sometimes the cropbox and the canvas are not in the position defined in the data. Is that because you have an initialisation of canvas and cropbox position, and then the setCropBoxData and setCanvasData will have restrict on that in strict mode? I just find `limitCropBox`  and `limitCanvas` function in source code.

**Comment by fengyuanchen** [comment]
Yes, the Strict Mode has many limitations.

**Comment by elaijuh** [comment]
But if the data set by `setCropBoxData` and `setCanvasData` doesn' t break the limitation, the canvas and the cropbox should be finally put to the right place.

**Comment by fengyuanchen** [comment]
You can reference to the second example on the demo page: http://fengyuanchen.github.io/cropper/#examples

**Comment by elaijuh** [comment]
Right, because the canvas(image) occupies the full container, so the cropBox is free to set. But in most cases, the canvas is not the same as container.

**Comment by fengyuanchen** [comment]
You can try this:
```js
// Sotre
var storedData = $().cropper('getData');

// Resotre
$().cropper({
  data: storedData
});
```

**Comment by elaijuh** [comment]
that doesn't set the canvas position.
finally i end up adjusting the position manually for both canvas and cropbox..
