### ISSUE TITLE
Problem when resizing window

### ISSUE THREAD

**Issue by Hyleeh** [fengyuanchen/cropper#488]
I instantiate the plugin just as in the responsive example
But there is the issue, the image does not follow the scaling, it is inconsistent
Here are some snapshots from when I am scaling the window

![screen shot 2015-10-23 at 15 17 58](https://cloud.githubusercontent.com/assets/5340560/10692354/ab58c7f8-7999-11e5-97c8-ae2928821325.png)
![screen shot 2015-10-23 at 15 18 08](https://cloud.githubusercontent.com/assets/5340560/10692357/ac3f129e-7999-11e5-911b-4cff45034fc8.png)
![screen shot 2015-10-23 at 15 18 35](https://cloud.githubusercontent.com/assets/5340560/10692356/abfdad40-7999-11e5-90e5-c67312398bec.png)

And here is the snippet for instantiation that I use

```javascript
$(function () {
    // Init cropper
    $('.document-edit-image > img').cropper({
        movable: false,
        zoomable: false,
        rotatable: false,
        scalable: false,
        autoCrop: false,
        autoCropArea: 1
    });
});
```

The cropbox gets smaller and smaller when I scale but not correctly
It gets smaller twice as fast than the image

And when I scale up there is sometimes the empty background where there should not be

There is no additional CSS on the container nor image:
```css
.document-edit-image
    width: 100%
    img
        max-width: 100%
```

I am not sure what causes the problem though, do you have any suggestions?

**Comment by Hyleeh** [comment]
One thing I have noticed is that the .cropper-container height does not change and stays the same all the time whether I resize the window or not

**Comment by shaneparsons** [comment]
+1 for the `.cropper-container` window not resizing. If scaling is turned off, as it is with me, the image gets cut off on the top and bottom.

**Comment by shaneparsons** [comment]
@Hyleeh are you using bootstrap? if so adding the class `img-responsive` to the image may help with the initial sizing.

**Comment by fengyuanchen** [comment]
https://github.com/fengyuanchen/cropper/blob/master/examples/responsive-container.html

**Comment by fengyuanchen** [comment]
As of v2.1.0, you can set the new `restore` option to `false` to avoid this problem.
