### ISSUE TITLE
Data option with autoCrop

### ISSUE THREAD

**Issue by bardt** [fengyuanchen/cropper#491]
I use autoCrop because I want to drag and zoom image instead of cropper area. After the crop finishes, I save crop data to be able to come back to cropper and start from the same state I left it. 

So, on initialisation I pass `data` in options among with `autoCrop = true` and `autoCropArea = 0.5` for  example. I expect crop area to be fixed, but image to come to the same zoom and position I left it. 

What I get is crop area set to `data` and fixed, ignoring autoCropArea. What am I doing wrong? Is there a way to achieve what I want with different settings?

**Comment by fengyuanchen** [comment]
The `autoCropArea` option will be overrided by the `data` option.

In other words, this

```js
$().cropper({
  autoCrop: true,
  autoCropArea: 0.5,
  data: previousData
});
```

is the same as

```js
$().cropper({
  autoCrop: true,
  autoCropArea: 0.5,
  built: function () {
    $(this).cropper('setData', previousData);
  }
});
```

**Comment by bardt** [comment]
@fengyuanchen are where any methods that could help me restore crop with cropbox fixed in the centre? Looks like I need to calculate image position and zoom based on current copper container size and data saved from previous crop.

**Comment by fengyuanchen** [comment]
You might try to store the canvas data only:

```js
// Cache
var oldCanvasData = $().cropper('getCanvasData');

// Restore
$().cropper({
  built: function () {
    $(this).cropper('setCanvasData', oldCanvasData);
  }
});
```
