### ISSUE TITLE
cropper is not initlialized when called from modal.on shown event

### ISSUE THREAD

**Issue by snimavat** [fengyuanchen/cropper#495]
```
 $('#crop-modal').on('shown', function() {
                                initCropper($element);
  });

 function initCropper($element) {
                var $cropper = $(".eg-wrapper > img")
                $cropper.cropper({
                    movable:false,
                    rotatable:false,
                    scalable:true,
                    zoomable:false,
                    mouseWheelZoom:false,
                    touchDragZoom:false,
                    doubleClickToggle:false,
                    responsive:true,
                    //modal: false,

                    preview: ".preview",
                  
                });
            }
        }
```

However when initCropper is moved outside of shown event, it works, and cropper is initialized properly, but then it doesnt calculate width of the cropper properly, and cropper-container and cropper-canvas width is not 100% even if my .eg-wrapper has width 100%. resizing windows fixes this and image looks good.

**Comment by snimavat** [comment]
<img width="896" alt="2015-10-29_2236" src="https://cloud.githubusercontent.com/assets/623295/10825998/9748ae2e-7e8d-11e5-941f-6f14ddd6799f.png">

**Comment by snimavat** [comment]
Okay, looks like it was another issue, but still that canvas width issue shown in image is there

**Comment by fengyuanchen** [comment]
1. Initialize the cropper when the modal is shown completely!
2. Destroy the cropper when the modal is hidden completely!
