### ISSUE TITLE
How to destroy and initialize cropper again after closing modal?

### ISSUE THREAD

**Issue by praveen5566** [fengyuanchen/cropper#496]
Hi,

I wanted to know how to re-initialize the entire cropper to accept new images when the user cancels the modal. Below is the code I am using to destroy the cropper on close function of the modal. Kindly help me with the initialization of cropper. Thanks

```js
var $image = $(".img-container");

$(".modal-branding-logo").on("click", function(){
    $("#brandingLogoModalDialog").modalWindow();
    $("#brandingLogoModalDialog").dialog({
        height:588,
        width:500,
        close:function () {
            $image.cropper("destroy");
            //initialize and build cropper again
        }
    });
    $("#brandingLogoModalDialog").dialog("open");
});
```

**Comment by fengyuanchen** [comment]
1. Initialize the cropper when the modal is shown completely!
2. Destroy the cropper when the modal is hidden completely!

**Comment by maiaurkya** [comment]
![fireshot capture 013 - cropper - http___localhost_cropper-test_](https://user-images.githubusercontent.com/16760623/30478375-6caa6ca2-9a2e-11e7-99d6-386b4f3f877d.jpg)

Hi fengyuanchen,
It is very great plugin and i m love to use this
I have three different images to crop and rotate.
Whenever i rotate or zoom one image and click on reset from another image toolbar it reset all three images .

Please help me to resolve this prolem

**Comment by fengyuanchen** [comment]
@maiaurkya It is the problem of your own code, not cropper.

**Comment by DataZhenTech** [comment]
code:
$image.cropper('destroy').cropper(options);
From official code and path is docs\v3.1.6\js\main.js, row number 104, Hope you help! .

**Comment by fengyuanchen** [comment]
@DataZhenTech Do you try the latest version?

**Comment by DataZhenTech** [comment]
Cropper v4.0.0!




| |
丁青青
邮箱：lm_master@163.com
|

签名由 网易邮箱大师 定制

On 10/24/2018 21:58, Fengyuan Chen wrote:

@DataZhenTech Do you try the latest version?

**Comment by Prince-254** [comment]
> code:
> $image.cropper('destroy').cropper(options);
> From official code and path is docs\v3.1.6\js\main.js, row number 104, Hope you help! .

I did $image.cropper('destroy');  
and it worked for me as if e latest version of Jquery Cropper
