### ISSUE TITLE
Cropper with multer

### ISSUE THREAD

**Issue by Marsiou** [fengyuanchen/cropper#497]
Hello,

Your cropper is great, i would like to use it for my site in nodejs.
You have a lot of features with documentations, it's great but i can't find a function that push the data from the crop and the image with or without the crop client? did i miss something?

I would like to combine your product  with multer(1.0.6) for security reasons. I want to crop the image from the client and send the image cropper  to my server.
 
Thanks.
Sorry for my english

**Comment by fengyuanchen** [comment]
The Cropper requires a `window` with a `document`.

**Comment by syuilo** [comment]
I think that there is a need to use the library, such as [gm](https://github.com/aheckmann/gm) separately Node.js side.

Sorry for my english too

**Comment by fengyuanchen** [comment]
I think gm only needs a path to an image.
