### ISSUE TITLE
Orientation wrong

### ISSUE THREAD

**Issue by artvel** [fengyuanchen/cropper#504]
Hello

The orientation seems to be wrong when a file is selected that was rotated by the default windows photo viewer.
The following image is shown in portrait in the most reliable viewers but with the cropper it is on landscape(Its even here on github wrong shown. I think this default windows tool is doing something wrong with the rotation but the cropper should have a fallback for that):
![imgres](https://cloud.githubusercontent.com/assets/6398539/10992928/3130d7f4-846b-11e5-907c-375b41dacbb6.jpg)

Can be easy reproduced by your demo here:
https://fengyuanchen.github.io/cropper/

Thx for any help.

**Comment by tilocgn** [comment]
Its a known issue. See https://github.com/fengyuanchen/cropper#known-issues and https://github.com/fengyuanchen/cropper/issues/120

**Comment by artvel** [comment]
@tilocgn thx
impl. workaround with:
https://github.com/fengyuanchen/cropper/issues/120#issuecomment-120552620

**Comment by fengyuanchen** [comment]
See #120.
