### ISSUE TITLE
Responsive: Container width stops adapting itself under an arbitrary size

### ISSUE THREAD

**Issue by infosaurus** [fengyuanchen/cropper#505]
Hi,

I instantiate Cropper with the responsive option :

    $imgTarget.cropper({
        aspectRatio: 1,
        autoCropArea: 0.8,
        strict: false, 
        dragCrop: false,
        minCropBoxWidth: 300,
        minCropBoxHeight: 300,
        cropBoxResizable: false,
        responsive: true
    });

The container div adapts itself well at all resolutions until we reach xtra small (<768px), under which it remains stuck at 570px wide or so. It does so even with a very small image (<300px wide), even if the crop box size is set to only 300px as you can see above. Setting *minContainerWidth* (which defaults at 200px) doesn't seem to help either.

The result is, under 768px we start seeing scrollbars appear, which is not user friendly and not really responsive any more.

Container div size seems to be set to arbitrary values calculated by Cropper... What is the rationale behind that calculation ? Why does the container div stop shrinking under a certain size ? Have I missed something ?

**Comment by fengyuanchen** [comment]
1. `minCropBoxWidth/Height` should less than `minContainerWidth/Height`.
2. It is not necessary to set `minCropBoxWidth/Height` as you can resize the cropped image on the server side or with `getCroppedCanvas` method:
```js
$().cropper('getCroppedCanvas', {
  width: 300,
  height: 300
}).toDataURL(); // Output an image with 300 px with and 300 px height
```

**Comment by infosaurus** [comment]
Hi fengyuanchen,

The reported problem remains no matter if `minCropBoxWidth/Height` is greater than `minContainerWidth/Height`, lower than it, or not set.

What we want to achieve by hardcoding cropbox width and height is giving the user a faithful preview of what the final image will be. It don't believe this is possible without specifying a crop box size, right ?

**Comment by fengyuanchen** [comment]
Please check if you had set some `min-width` styles to the image's parent elements.
