### ISSUE TITLE
Top and Left properties from getImageData() always zero

### ISSUE THREAD

**Issue by manng** [fengyuanchen/cropper#508]
This is a great plugin and I would like to use it in a picture cropping application I am writing, but this issue is blocking me.

I notice that the top and left properties from the getImageData() return object are always zero, no matter what the size and position of the image.  This applies to the demo examples (set viewMode to 0, move and resize the image and keep checking "left" and "top" from Get Image Data).

My application requires me to know the difference between the top-left positions of the crop box and the image, so I need the correct values for these image properties.

**Comment by fengyuanchen** [comment]
You should use the `getCanvasData` method (the canvas is the wrapper of the image), see the schematic diagram:

![layers](https://cloud.githubusercontent.com/assets/3456749/11084054/90fad9c8-8871-11e5-98ce-a53c560d52bf.jpg)
