### ISSUE TITLE
Shouldn't maximum height/width of the cropper be the maximum height/width of image rather than that of preview container

### ISSUE THREAD

**Issue by ahmedtabrez** [fengyuanchen/cropper#510]
According to the documentation:
>  - The maximum width is the initial width of preview container.
>  - The maximum height is the initial height of preview container.

Sometimes the height of the image may differ than that of the container. In such cases, the cropped image may result in empty pixels in one or more sides of the cropped image.

If not default, it should at least be configurable like the  `minCropBoxHeight` and `minCropBoxWidth`. Doesn't it?

**Comment by fengyuanchen** [comment]
Sorry, I don't really understand this. If you don't want the default preview behaviour, you can customize it, see the example: https://github.com/fengyuanchen/cropper/blob/master/examples/customize-preview.html

**Comment by ahmedtabrez** [comment]
@fengyuanchen , I thought we could limit the crop area from being extended beyond the actual image pixels so that we can avoid the empty pixels (transparent in png and black in jpg) like in the below screenshot![download](https://cloud.githubusercontent.com/assets/5443412/11161712/9251b1f8-8aaa-11e5-91c6-b212be59679a.jpg)

**Comment by fengyuanchen** [comment]
You can set `viewMode` option to `3` to limit it.

**Comment by ahmedtabrez** [comment]
Did you mean `viewMode = 2`? That solved it.....

**Comment by fengyuanchen** [comment]
`viewMode: 1`, `viewMode: 2` and `viewMode: 3` all works.
