### ISSUE TITLE
Flexible aspect ratio

### ISSUE THREAD

**Issue by JustMikey** [fengyuanchen/cropper#511]
Is there a way to make the aspect ratio flexible? In my case I want it to be >= 0.7 and <= 1 but I can't find a way to implement it. I tried a function from one of the previous issues where was recommended to use `cropmove` but I didn't manage to make it work properly.

**Comment by fengyuanchen** [comment]
Please see the issue #182.

**Comment by JustMikey** [comment]
Thank you for the reply but as I mentioned in my first comment, that function does not work.

When the cropper gets built, the cropbox usually has a ratio that is out of the range, so you end up not being able to change it. So I had to add something like this to set its initial size.

    built: function(e) {
        $image.cropper('setCropBoxData', {
            height: 250,
            width: 250
        });
     }

but it's one thing, the other is that when I minimaze the cropbox, its ratio, for some reason, goes lower than the minimum (it gets like 6.9 when the minimum is 0.7) and again, I end up not being able to change the cropbox size.

**Comment by fengyuanchen** [comment]
Example: https://github.com/fengyuanchen/cropper/blob/master/examples/a-range-of-aspect-ratio.html

**Comment by JustMikey** [comment]
Thank you very much for your help and such an amazing plugin. You should probably consider the idea of adding some info regarding donation so grateful users could buy you a beer :)
