### ISSUE TITLE
Minimal crop area width

### ISSUE THREAD

**Issue by SempaChoo** [fengyuanchen/cropper#512]
I would like know if there is any option or workaround to set minimal width of croped area ? I am not tallking about minCropBoxWidth because I am not getting wanted result. Thx

**Comment by fengyuanchen** [comment]
You can get the actual data with the `getData` method, and then you can control the crop box resizing with the `cropmove` event.

**Comment by fengyuanchen** [comment]
```js
$().cropper({
  cropmove: function () {
    var $this = $(this);
    var data = $this.cropper('getData');
    var cropBoxData;

    if (data.width < 480) {
      cropBoxData = $this.cropper('getCropBoxData');

      $this.cropper('setCropBoxData', {
        width: 480 * (cropBoxData.width / data.width)
      });
    }
  }
});
```

**Comment by SempaChoo** [comment]
@fengyuanchen Thankk youu soo muchhh !! This is just what I needed.
