### ISSUE TITLE
Reload original cropped image with saved data?

### ISSUE THREAD

**Issue by refringe** [fengyuanchen/cropper#515]
I'm creating an online image library and using cropper. When an image is cropped using cropper the original image is left untouched so it can be loaded back into cropper and adjusted at a later date. I'm unsure what data I need to get, save, and later re-set to have the image re-load into cropper and display just as it was cropped last time.

I can see there's three methods available:
```
setData
setCanvasData
setCropBoxData
```

Do all of these need to be saved and set? Is there a specific order that they need to be set?

**Comment by fengyuanchen** [comment]
You can only use the `data` option to restore the cropper:
```js
var savedData = $().cropper('getData');

$().cropper({
  data: savedData
});
```

**Comment by fengyuanchen** [comment]
You also can use `setCanvasData` and `setCropBoxData` just as the example: https://github.com/fengyuanchen/cropper/blob/master/examples/cropper-in-modal.html

**Comment by refringe** [comment]
So either just use the `data` method, or both the `CanvasData` and `CropBoxData` methods. What are the differences between these two ways?

**Comment by fengyuanchen** [comment]
The second way can restore the zoom level of the canvas.

**Comment by refringe** [comment]
Many thanks!

**Comment by HiYellowC** [comment]
Can you tell me the difference of getData and getCropBoxData?
thanks~
