### ISSUE TITLE
Unable to initialize cropper

### ISSUE THREAD

**Issue by sbsomya** [fengyuanchen/cropper#516]
Hi I have put the cropper.js and cropper.css in the head of the html
and trying 
```js
var $ele = $("#image");

$ele.cropper({
    aspectRatio: 4 / 3,
    crop: function (data) {

    },
    zoomable : false,
    scalable : false,
    movable : false,
    background : true,
    viewMode : 2,
    built : function(){
        $(this).cropper('getCroppedCanvas').toBlob(function (blob) {
            console.log("ENtereedddd");
            var formData = new FormData();
            formData.append('croppedImage', blob);
            console.log(formData);
        });
    }
});
```

It says .cropper is not defined 

I checked the demo it is written with different initialization

**Comment by sbsomya** [comment]
CODE :: 

var $ele = $("#image");
$ele.cropper({
	aspectRatio: 4 / 3,
    crop: function (data) {
    },
    zoomable : false,
    scalable : false,
    movable : false,
    background : true,
    viewMode : 2,
    built : function(){
		$(this).cropper('getCroppedCanvas').toBlob(function (blob) {
			console.log("ENtereedddd");
			var formData = new FormData();
			formData.append('croppedImage', blob);
			console.log(formData);
		});
	}
});

**Comment by fengyuanchen** [comment]
Apply Cropper when window loaded:
```html
<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<link  href="https://cdn.rawgit.com/fengyuanchen/cropper/v2.0.1/dist/cropper.min.css" rel="stylesheet">
<script src="https://cdn.rawgit.com/fengyuanchen/cropper/v2.0.1/dist/cropper.min.js"></script>
<script>
  $(function () {
    var $ele = $("#image");

    $ele.cropper({
        aspectRatio: 4 / 3,
        crop: function (data) {

        },
        zoomable : false,
        scalable : false,
        movable : false,
        background : true,
        viewMode : 2,
        built : function(){
            $(this).cropper('getCroppedCanvas').toBlob(function (blob) {
                console.log("ENtereedddd");
                var formData = new FormData();
                formData.append('croppedImage', blob);
                console.log(formData);
            });
        }
    });
  });
</script>
```

**Comment by sbsomya** [comment]
Hi thanks the above thing worked probably i was using different cropper.js and jquery.js files

But got stuck in toBlob is not a function

Uncaught TypeError: $(...).cropper(...).toBlob is not a function

Error is coming up

**Comment by sbsomya** [comment]
Sorry working in firefox but not in chrome

**Comment by fengyuanchen** [comment]
Chrome does not support toBlob, but there a low performance polyfill based on toDataURL. See the document: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

**Comment by sbsomya** [comment]
Used this 
https://github.com/eligrey/canvas-toBlob.js/
