### ISSUE TITLE
How to set aspect ratio for each modal?

### ISSUE THREAD

**Issue by JayWelsh** [fengyuanchen/cropper#519]
Cropper opens in two different modals, each with a different image. How do we change only the aspect ratio? We are using the main.js and when we set the aspect ratio like this, it causes the canvas data to stop being shown.

< script >
            $('#img-container-pp > img').cropper({
                aspectRatio: 1 / 1,
            });
            $('#img-container-cvr > img').cropper({
                aspectRatio: 16 / 9,
            });
</ script >

What would be the best way to only adjust the aspect ratio while keeping the rest of the settings we have made? We can use IDs if need be.

**Comment by fengyuanchen** [comment]
You should initialize a cropper only when the outer modal shown completely.

**Comment by JayWelsh** [comment]
Found the solution, thanks :)
