### ISSUE TITLE
setData not setting properly

### ISSUE THREAD

**Issue by causztic** [fengyuanchen/cropper#520]
I have a cropped image's dimensions stored in my database, and sometimes it does not set the cropping properly on the **built()** function when either the width or height are set exactly to the rendered dimensions of the  **cropper-canvas** class.

I had to 
<code>$(this).cropper("setData", {x: x, y: y, height: height - 1, width: width - 1 });</code>

to give the illusion that the cropper rendered correctly.

Any ideas why?

**Comment by fengyuanchen** [comment]
Please check if the stored data was still the same as the data get by `getData` method.

**Comment by fengyuanchen** [comment]
And I suggest you to apply the stored data with the `data` option:
```js
$().cropper({
  data: storedData
});
```

**Comment by causztic** [comment]
the stored data is 1 higher than <code>getData</code> because it is stored as a integer in the database after rounding off. Could we have an option to set the crop to max instead of failing if the values inputted are larger than the <code>getData</code> size?

**Comment by causztic** [comment]
I tried using 
<code>
$().cropper({
  data: storedData
});
</code>
like you suggested and it didnt work, but the old method does.

**Comment by fengyuanchen** [comment]
For integer values, you can get the data like this: `var storedData = $().cropper('getData', true)`.

**Comment by fengyuanchen** [comment]
```js
$().cropper({
  data: storedData
});
```
is a shortcut of 
```js
$().cropper({
  built: function() {
    $(this).cropper('setData', storedData)
  }
});
```

**Comment by causztic** [comment]
when <code>storedData.width</code> is larger than <code>$().cropper('getData', true).width</code>, the cropper resets. Is this intended?

**Comment by fengyuanchen** [comment]
Sorry, I don't really understand that...

**Comment by causztic** [comment]
I had an image with a height of something like 227.5078125px after cropping to a ratio (The user uploaded a portrait image while we needed a landscape one). I stored it in the database as an integer after rounding, which resulted in a height of 228px.

So when I attempted to set the cropper with

```
$().cropper({
  data: { x: x, y: y, height: 228px, width: width }
});
```

It does not work. I had to set with <code> height: 227.5078125px </code> obtained from <code>getData</code>! 

Hope this helps

**Comment by fengyuanchen** [comment]
Sorry, I can't reproduce this case, can you provide a demo?

**Comment by jayked** [comment]
I'm still having this issue. I'm using 2.3.0 of Cropper. Anyone got a solution?

**Comment by frutality** [comment]
Hello @fengyuanchen !
Had same bug, but can't reproduce at jsfiddle :/

Here is code https://jsfiddle.net/39tqomwp/ - it seems fine, but read my comments.
And here is how it seems at my local demo http://imgur.com/7kPgtYM

Crop area get's centered because cropper thinks height and width are 1199.9999999999998px, not 1200. IDK why that happens only at my local demo.
