### ISSUE TITLE
Cropping outside the image boundaries - Firefox issue

### ISSUE THREAD

**Issue by SPapaioannou** [fengyuanchen/cropper#523]
Hi i'm using strict false in my cropper options and i am having an issue with firefox. 
I'm getting this error:

<code>Error: Index or size is negative or greater than the allowed amount</code>

If i use strict true then it's fine. I found some posts in stackoverflow and i tried a couple of things but they don't seem to work. Any suggestions ?

**Comment by fengyuanchen** [comment]
I cannot reproduce this case on Firefox 41, Window 10. What's you system or any detail?

**Comment by SPapaioannou** [comment]
Hi sorry i was using and angular module that i found on github that is using ur cropper and something was wrong with that that's why i was getting the error. I changed it now to directly call the getCroppedCanvas and it works fine ! Thanks for replying
