### ISSUE TITLE
Revise .cropper-bg background-image url string

### ISSUE THREAD

**Issue by shaneparsons** [fengyuanchen/cropper#527]
The base64 string below causes me issues when minimizing my css, more in particular the part around the middle with `////`.
```
.cropper-bg {
    background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAAA3NCSVQICAjb4U/gAAAABlBMVEXMzMz////TjRV2AAAACXBIWXMAAArrAAAK6wGCiw1aAAAAHHRFWHRTb2Z0d2FyZQBBZG9iZSBGaXJld29ya3MgQ1M26LyyjAAAABFJREFUCJlj+M/AgBVhF/0PAH6/D/HkDxOGAAAAAElFTkSuQmCC");
}
```
The process that minimizes my SASS and CSS sees the `//` as a comment, and since it strips out comments in my stylesheets, it breaks the css at that point.

Please fix this.

**Comment by shaneparsons** [comment]
After trying just about everything, I even created an entirely new graphic, the only thing that fixed it was swapping the two lines `.cropper-bg...` and `.cropper-invisible...` like so:
```
.cropper-invisible {
  filter: alpha(opacity=0);
  opacity: 0;
}

.cropper-bg {
  background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAAA3NCSVQICAjb4U/gAAAABlBMVEXMzMz////TjRV2AAAACXBIWXMAAArrAAAK6wGCiw1aAAAAHHRFWHRTb2Z0d2FyZQBBZG9iZSBGaXJld29ya3MgQ1M26LyyjAAAABFJREFUCJlj+M/AgBVhF/0PAH6/D/HkDxOGAAAAAElFTkSuQmCC");
}
```

**Comment by fengyuanchen** [comment]
You can use the original image directly: `src/img/bg.png`
