### ISSUE TITLE
min height/width when zooming in/out

### ISSUE THREAD

**Issue by huglester** [fengyuanchen/cropper#528]
Hello,

For example I want my croped image to be of sizes min at: 800x400. (aspectRation: 2)

But when I zoom in the image, I can zoom it and have a container like  100x50. How do I make it minimum @ 800x400?
```
        minContainerWidth: 800,
        minContainerHeight: 400,
```

does not help. Any idea?

Also:
```
            console.log(e.scaleX);
            console.log(e.scaleY);
```
this one always return 1 and 1, does not matter when I zoom in or zoom out. or I do not understand the `scale` correct?

**Comment by fengyuanchen** [comment]
Please resize the cropped image on server side or use:
```js
$().cropper('getCroppedCanvas', {
  width: 800,
  height: 400
});
```

About the second issue, please read the doc about [that](https://github.com/fengyuanchen/cropper#scalexscalex)
