### ISSUE TITLE
请问Jquery版本的怎样作为CommonJS模块引入呢？

### ISSUE THREAD

**Issue by edwardnevermind** [fengyuanchen/cropper#529]
RT.

**Comment by fengyuanchen** [comment]
```js
const Cropper = require('cropper');
```

**Comment by edwardnevermind** [comment]
$ = require("jquery")
    Cropper = require("cropper")

    $(document).ready ->
	    $(".book-new-ico").cropper({
		    aspectRatio: 1
	    })

但是这样不行啊。

**Comment by edwardnevermind** [comment]
ok了，3ks so much
