### ISSUE TITLE
Feature - AspectRatio - getCroppedCanvas

### ISSUE THREAD

**Issue by graphefruit** [fengyuanchen/cropper#530]
Hello!

First of all, thanks for this realy great plugin! Works awesome, easy to handle and well documented!

##### I would have a little feature request:
Would it be possible to provide a param by method "getCroppedCanvas" to ignore the aspect ratio?
e.g.:
```
$("#image").cropper("getCroppedCanvas", {aspectRatio:"ignore", width: 100, height: 100 })
```
If I crop the canvas I need exact the same width and height, ignore the aspect ratio.
So on most images/crops the image needs to be crunched or strechted.

In your current demo, the cropped-canvas would be "100x56" after executing the js above.
With aspect:
![with_aspect](https://cloud.githubusercontent.com/assets/6260244/11470719/5b1c2584-9760-11e5-90e1-46a4ad804ee0.png)

Without aspect (feature)
![without_aspect](https://cloud.githubusercontent.com/assets/6260244/11470720/5ea8b4ce-9760-11e5-847f-dcc9123e71be.png)

Thanks in advance
Graphefruit

**Comment by fengyuanchen** [comment]
I suggest you to use the cropper like this:
```js
$().cropper({
  aspectRatio: 1,
  data: {
    scaleY: 2
  },
  built: function () {
    // Get the stretched canvas what you need
    var canvas = $(this).cropper('getCroppedCanvas');
  }
});
```

**Comment by fengyuanchen** [comment]
Or, you can get the default cropped canvas, and then translate the canvas to what you want with the [CanvasRenderingContext2D.translate](https://developer.mozilla.org/zh-CN/docs/Web/API/CanvasRenderingContext2D/translate) API.

**Comment by graphefruit** [comment]
Hi,
Thanks for reply.
If I insert this into the "built" function, how shall I trigger this after the user has cropped and clicked a button?
Related to the documentation the built is fired asynchron if everything is **set up**
Greetings

**Comment by fengyuanchen** [comment]
```js
var $image = $('#image');
var ready = false;

$image.cropper({
  built: function () {
    ready = true;
  }
});

$('#button').on('click', function () {
  var canvas;

  if (!ready) {
    return;
  }

  canvas = $image.cropper('getCroppedCanvas');
  // Handle the canvas...
  // ...
});
```

**Comment by graphefruit** [comment]
Understood. Thanks, thats the way I already did it, for the rest:
```
function cropImage{             
	var croppedCanvas = $("#crop").cropper('getCroppedCanvas');
	var ctx = croppedCanvas.getContext("2d");
	var image = new Image();
	image.onload = function () {
		croppedCanvas.height = 200;
		croppedCanvas.width = 200;
		ctx.drawImage(image, 0, 200,200);
		var dataURL = croppedCanvas.toDataURL();
		//... do what you want
	};
	image.src = croppedCanvas.toDataURL();
};
```
