### ISSUE TITLE
Mac touchpad scroll without intentio

### ISSUE THREAD

**Issue by kiwi1342** [fengyuanchen/cropper#532]
On a Mac and using Chrome latest version, if positioning two fingers on the touchpad, the plugin intercept this call as a scroll event and decrease the background size. This causes continuos unintentional zoom-out. This happens only on Chrome and I'm using a Mac. Not sure if this happens on Win as well.

**Comment by fengyuanchen** [comment]
two fingers touch will trigger a wheel event. I will limit the wheel speed in next version.
