### ISSUE TITLE
Image sometimes rotates 180º instead of 90º

### ISSUE THREAD

**Issue by shaneparsons** [fengyuanchen/cropper#533]
This is kind of hard to re-produce, as it doesn't happen all the time, but every once in a while when I click my button to rotate the image 90º it rotates the image 180º instead and doesn't ever use 90º increments unless restarting the cropper.

Below is the code I'm using for rotating the image left / right:

```
// Rotate Left
$('#rotate-left').on('click', function () {
    image.cropper('rotate', -90);
});

// Rotate Right
$('#rotate-right').on('click', function () {
    image.cropper('rotate', 90);
});
```

If anyone's had this problem before, or has any ideas on how to prevent it, any feedback would be greatly appreciated.

**Comment by fengyuanchen** [comment]
The only thing I can think of is that you might triggered the **click event handler** twice some times.

**Comment by shaneparsons** [comment]
By the way it's happening I can tell that's definitely not the case.. I'll try to throw up an example on jsfiddle or something when I get a chance.
