### ISSUE TITLE
Rotating Image in viewMode: 1 is causing image to change zoom

### ISSUE THREAD

**Issue by guptamitesh** [fengyuanchen/cropper#537]
Steps to reproduce:
1. Go to Demo url of the tool. 
2. Select view mode 1. 
3. Rotate image 90 degrees by clicking on rotate 45 button twice.
4. Observe that zoom level of the image changes.
5. Rotate image -90 degrees by clicking on rotate -45 button twice again to get original image on canvas back.
6. Observe that original image is zoomed in and does not remain same.
![screen shot initial image](https://cloud.githubusercontent.com/assets/13232814/11626805/b88dcd98-9d0b-11e5-9086-f96f6503a757.png)
![screen shot image rotated by 90 degrees](https://cloud.githubusercontent.com/assets/13232814/11626810/be7985d0-9d0b-11e5-8509-e7cd9ce9f5d8.png)
![screen shot image rorated by -90 degrees](https://cloud.githubusercontent.com/assets/13232814/11626815/c1f4e8a8-9d0b-11e5-9b84-9ed41361c435.png)

**Comment by fengyuanchen** [comment]
Once you rotate the image, the size of the image enlarged to fit the crop box.

**Comment by makc** [comment]
yes but doesn't it make more sense to make smaller selection instead?

**Comment by guptamitesh** [comment]
You can adjust zoom through mouse wheel rotation or through touchpad two
finger motion. If not try making box smaller and try to adjust zoom again.

**Comment by fengyuanchen** [comment]
This is not a bug. If you call the `$().cropper('rotate', 180)` directly, you will find it works as what you expect.
