### ISSUE TITLE
Cropper / modal initializes poorly - Firefox

### ISSUE THREAD

**Issue by shaneparsons** [fengyuanchen/cropper#538]
When I launch my cropper model in Firefox, it resizes the initial image, which is very ugly.
Both Safari and Chrome don't do this.

**Safari / Chrome (good)**
![screen shot 2015-12-07 at 3 02 47 pm](https://cloud.githubusercontent.com/assets/5495493/11638233/d57a7662-9cf3-11e5-906c-15dc4e69bb3e.png)

**Firefox (horrible)**
![screen shot 2015-12-07 at 3 02 58 pm](https://cloud.githubusercontent.com/assets/5495493/11638235/d6fbfa2e-9cf3-11e5-8573-a1726cbfdc15.png)

I tried my best to illustrate this issue in jsfiddle, but because jsfiddle doesn't like the image, the cropper never initializes in the first place.. You'll likely have to put this code elsewhere to reproduce it.

http://jsfiddle.net/bs9c8ct5/12/

**Comment by fengyuanchen** [comment]
You might need to set the style like this:
```css
.modal-body img {
  width: 100%;
}
```

**Comment by shaneparsons** [comment]
Didn't work unfortunately. I tried many other variations of that, along with `.cropper-container` as well.

**Comment by fengyuanchen** [comment]
Please follow the existing example: https://github.com/fengyuanchen/cropper/blob/master/examples/cropper-in-modal.html

**Comment by shaneparsons** [comment]
I did follow that example.. even look at the JSFiddle above.
This issue isn't resolved and shouldn't have been closed.

**Comment by fengyuanchen** [comment]
So, when I open the jsfiddle demo in Firefox 42, everything seems fine.
> Requires to set the `checkCrossOrigin` option to `false` in order to load the image correctly.

**Comment by shaneparsons** [comment]
Thanks, setting `checkCrossOrigin` to `false` fixed it!

I don't believe the docs mention anything about adding that in though.

**Comment by shaneparsons** [comment]
Actually scratch that last message.

It only appeared to work in the jsfiddle, because cropper never initializes in the jsfiddle to begin with.
I'll see if i can get it to work in codebin or jsbin.

In the meantime, copying the code exactly from jsfiddle and pasting it elsewhere will show you exactly what my problem is.

**Comment by shaneparsons** [comment]
Sorry for all the back and forth.
It seems to work in the codepen http://codepen.io/anon/pen/obzvQq so something in my project must be clashing with it. I'll figure it out from here on.

Thanks for all the help!

**Comment by shaneparsons** [comment]
Alright I've finally come to the conclusion the the problem was coming from me using an svg as the initial image. I'm still not sure why this only happens in firefox, but if I use a png it doesn't happen.. Any ideas?
