### ISSUE TITLE
Set Crop ratio based on real picture

### ISSUE THREAD

**Issue by endrureza** [fengyuanchen/cropper#539]
Well, i am a little bit confused. 

I have Container with 500px width, My real picture solution is 2560 x  1080 but i want aspect ratio exactly 4:3 but based on real picture. Not based on container. let's say, i want min crop 640 x 640. Now, that min crop just based on container right ? 

any solution ? ty.

**Comment by fengyuanchen** [comment]
See #522 or #528.

**Comment by endrureza** [comment]
well, that doesn't answer actually. 

Here is my issue,

i have a picture with resolution 2560 x 1280

but i just want the crop box reach for the least 1110 x 311, it can be larger but cannot be less. What i'm confused is, the percentage of crop box is not 1110 x 311 based on real picture. Beside that, i set my container only 500 so that cropping container is not too big. I'm afraid this crop box follows the container size not the picture. 

here is my setting

```
$(section).cropper({
	aspectRatio: 1110/311,
	viewMode:3,
	zoomable:false,
	dragMode:'none',
	background:false,
	minCropBoxWidth:1110,
	minCropBoxHeight:311
});
```

those mincropbox thing doesn't relate to real picture. That's what i'm confused at. Is there any solution ?

**Comment by fengyuanchen** [comment]
The `minCropBoxWidth/Height` should not large than the `containerWidth/Height`. Why? Just think about it!
