### ISSUE TITLE
Cross Origin issue 

### ISSUE THREAD

**Issue by SPapaioannou** [fengyuanchen/cropper#540]
Hi,
when i load the cropper with a url from aws i get the cross origin error.
I tried setting the below CORS settings to amazon and i still get the error. 

        AllowedOrigin 'our dev site'
        AllowedMethod GET
        AllowedHeader *

I also tried setting this "checkImageOrigin" to false and true but didn't made any difference. I tried to follow that: https://github.com/fengyuanchen/cropper/issues/148 but it looks like u already done that in the new cropper version.

Can u please help me with this issue?  Do i have something wrong in my setup? 

Thanks

**Comment by fengyuanchen** [comment]
You need to set the response header `Access-Control-Allow-Origin: *`.

**Comment by fengyuanchen** [comment]
Or just set the `checkOrientation` option to `false` (v2.2.0).

**Comment by mrmarktyy** [comment]
Hi @fengyuanchen , i loved your cropperjs, it works great. However I had some problems with IE11(win7) and 搜狗browser when use the image from local machine ( eg "access is denied" or "cross orgin" issues). I found that the steps I used were quite close to those in your comments above. 

IE11:
> Error: Access is denied. 
>  at load (http://cdn.yoocc.com/agar/vendors/cropper.min.js:10:6778)
>  at init (http://cdn.yoocc.com/agar/vendors/cropper.min.js:10:6566)

搜狗:
> XMLHttpRequest cannot load data:image/jpeg;base64,/9j/4QA2RXhpZgAASUkqAAgAAAABAJiCAgASAAAAGgAAAAAAAAAy…Uvb7PGiRyAWVnAFvT4daZMiytHFGSFs3S3+dCQ9oIpdpgOW3h8qClaSNNKsI0ADHb4UoE2f//Z. Received an invalid response. Origin 'http://www.example.com' is therefore not allowed access. 

Would you provide some suggestions what i did wrong ? or any workarounds? thank you!

**Comment by mrmarktyy** [comment]
`checkOrientation`, sure ?

**Comment by mrmarktyy** [comment]
@fengyuanchen Sorry, I think the problems were sorted out after i bump the cropperjs to v2.2.0

Thanks, Sorry for the noise.

**Comment by fengyuanchen** [comment]
@mrmarktyy You can try a Blob URL (created by `URL.createObjectURL(file)`).

**Comment by fengyuanchen** [comment]
@mrmarktyy After test in IE 11, a Data URL don't work, but a Blob URL works.
