### ISSUE TITLE
How to change shape from square to circle in crop area?

### ISSUE THREAD

**Issue by shahbaz-gaxon** [fengyuanchen/cropper#545]
![image](https://cloud.githubusercontent.com/assets/13620572/11760481/7edaedb8-a0c3-11e5-88d9-17a8178592a5.png)
Hello,

i want to change shape from selecting area to square to circle.

which property should i use?

Please suggest me solution.

**Comment by fengyuanchen** [comment]
The Cropper does not support circle crop box, but you can customize it by yourself.

**Comment by shahbaz-gaxon** [comment]
how can i customize to convert it circle box?

any suggestion or fiddle it?

**Comment by fengyuanchen** [comment]
Override the relative classes as `.cropper-crop-box` and `.cropper-view-box`.

**Comment by shahbaz-gaxon** [comment]
ok sir i will try it i have no clue to done it.because i am newbie to using this plugin?

**Comment by schuma7** [comment]
Hi,

I have been looking to achieve the same thing. Please note that you need to make use of the box-shadow property to create a rounded stroke, as outline currently doesn't follow the border-radius property in a cross-browser way.

I ended up using the following styles:

.cropper-crop-box, .cropper-view-box {
	border-radius: 50%;
}

.cropper-view-box {
	box-shadow: 0 0 0 1px #39f;
	outline: 0;
}

Tested in Safari, Chrome and Firefox on Mac OS, if you want to support IE8 you should consider resetting the outline for that browser, as it doesn't support border-radius and box-shadow.

I also had to set highlight: false when initializing cropper.

**Comment by shahbaz-gaxon** [comment]
Hii , schuma7 

i have using your code..

.cropper-crop-box, .cropper-view-box {
border-radius: 50%;
}

.cropper-view-box {
box-shadow: 0 0 0 1px #39f;
outline: 0;
}

It does seems good. i want something like that round shape. good work.

Thanks  schuma7

**Comment by Sandeepwal** [comment]
Hi Guys i'm also looking for this, where we need to change above css?

**Comment by fengyuanchen** [comment]
@Sandeepwal  Here is [an example from Cropper.js](https://github.com/fengyuanchen/cropperjs/blob/master/examples/crop-a-round-image.html).

**Comment by Siva-Ganesh-VR** [comment]
Hey all by doing some css work we can make image crop into circle

```

.cropper-crop-box, .cropper-view-box {
    border-radius: 50%;
}

.cropper-view-box {
    box-shadow: 0 0 0 1px #39f;
    outline: 0;
}

.cropper-face {
  background-color:inherit !important;
}

.cropper-dashed, .cropper-point.point-se, .cropper-point.point-sw, .cropper-point.point-nw,   .cropper-point.point-ne, .cropper-line {
  display:none !important;
}

.cropper-view-box {
  outline:inherit !important;
}
```
![git](https://user-images.githubusercontent.com/47774640/60948378-6a50df80-a310-11e9-84e4-2ec6b8962d15.png)

**Comment by power-media** [comment]
As rectangular outer shape with handles might be easier to use, also most users are familiar with it more than circle (UX), I have another solution: Round internal plus rectangular outer shape as below:

![cropperjs-circle-in-square](https://user-images.githubusercontent.com/8167541/64539578-a3103380-d316-11e9-837a-dee095deb970.png)

Very little CSS to add to make it like this:

```
.cropper-view-box {
	box-shadow: 0 0 0 1px #39f;
	border-radius: 50%;
	outline: 0;
}
.cropper-face {
	background-color:inherit !important;
}
.cropper-view-box {
	outline:inherit !important;
}
```

**Comment by XmelesX** [comment]
Have nice result with css from @Siva-Ganesh-VR  and some magic from me)
![Screenshot_20190919_133200](https://user-images.githubusercontent.com/16750139/65236755-e9694d80-dae1-11e9-9848-980531af9f8f.png)
css:

```
.cropper-crop-box, .cropper-view-box {
    border-radius: 50%;
}
.cropper-view-box {
    box-shadow: 0 0 0 1px #39f;
    outline: 0;
}
.cropper-face {
  background-color:inherit !important;
}

.cropper-dashed, .cropper-line {
  display:none !important;
}
.cropper-view-box {
  outline:inherit !important;
}

.cropper-point.point-se {
  top: calc(85% + 1px);
  right: 14%;
}
.cropper-point.point-sw {
  top: calc(85% + 1px);
  left: 14%;
}
.cropper-point.point-nw {
  top: calc(15% - 5px);
  left: 14%;
}
.cropper-point.point-ne {
  top: calc(15% - 5px);
  right: 14%;
}
```

**Comment by GiangTruong-afk** [comment]
any example about  rectangle shape

**Comment by rinogo** [comment]
Here's another solution, derived from the one by [the one from @power-media](https://github.com/fengyuanchen/cropper/issues/545#issuecomment-529503784).

In my application, I think it makes more sense to retain the blue border around the rectangle since that's the most "traditional" UI. Our users respond poorly to non-traditional implementations. The semi-opaque circular area is just an indication to the user regarding how the resulting image will be used (it will be enclosed within a circle). After all, there's no such thing as a circular image.

![image](https://user-images.githubusercontent.com/3732514/81826362-ed286500-94f4-11ea-848f-fccde4df4e4e.png)

The CSS is surprisingly quite simple! 🎉🥳

```
.cropper-view-box {
	border-radius: 50%;
}
.cropper-face {
	background-color:inherit !important;
}
```

If you'd like to remove the dashed lines (like I have in the screenshot above), that CSS is also quite simple:

```
.cropper-dashed {
	display: none;
}
```

**Comment by AxelBriche** [comment]
How can I change the black transparent background for a white background without transparency please?

**Comment by rinogo** [comment]
@AxelBriche It's all CSS - just inspect the elements and apply some CSS to make the changes. If you need more info, you may want to open a new issue.
