### ISSUE TITLE
I am newbie to use this plugin. how to limit the select area of image

### ISSUE THREAD

**Issue by shahbaz-gaxon** [fengyuanchen/cropper#546]
![area](https://cloud.githubusercontent.com/assets/13620572/11775181/96566206-a262-11e5-80b7-43108900669a.png)

![area-1](https://cloud.githubusercontent.com/assets/13620572/11777062/d3c5ef3a-a271-11e5-9d95-2613788fc815.png)

My question is - User cannot select area from out of image. so i can limit the select area into image only.

I want that user can zoom full image and user can zoom out this picture until transparent image is not showing.. understand my question..

Sorry for my poor english..

Which property should i use?

**Comment by SPapaioannou** [comment]
in the cropper options set strict to true.

**Comment by shahbaz-gaxon** [comment]
i have set viewMode to 3.

my task has been completed.

Thanks,

SPapaioannou

**Comment by shahbaz-gaxon** [comment]
Thanks,

fengyuanchen

for great plugin. keep it up ..

**Comment by fengyuanchen** [comment]
@SPapaioannou Thank you for the answer. BTW, the `strict` option had been removed since v.2.0.0.
@shahbaz-gaxon Thanks. Enjoy it.
