### ISSUE TITLE
Crop box can't be move or resized with base64 image in angular modal on Mobile

### ISSUE THREAD

**Issue by JoMas971** [fengyuanchen/cropper#548]
Hello,

I'm using the latest **2.2.1** version of your jQuery plugin with an angular app running on Mobile. (both cordova and Mobile browser).

I've an issue with the crop box. I can load the picture, and the crop box, but i just can't move or resize the box when i am on Mobile (it's working like a charm on Desktop Browsers).

I have seen your [known issues](https://github.com/fengyuanchen/cropper/#known-issues) with iOS, and i'm resizing my pictures to fetch 400px max (square) so **no heavy picture anymore**.

As i said, I can load the *picture*, *the cropper* and *previews*, but i can't move/resize the crop box on **mobile**.

Also, i'm using a **base64 image** as src.

There is my init function, called after the picture is completely loaded :

    $('#cropper').load(function() {
      $('#cropper').cropper({
        aspectRatio: 1 / 1,
        preview: '.preview',
        strict: true,
        autoCrop: true,
        movable: false,
        cropBoxMovable: true,
        cropBoxResizable: true,
        zoomOnTouch: false,
        zoomOnWheel: false
      });
    });

Do you have any ideas of what's happening there ?

Thanks.

**Comment by fengyuanchen** [comment]
I'm sorry, I have not idea about this, you may need to check it by yourself. By the way,  the `strict` option had been removed since [v2.0.0](https://github.com/fengyuanchen/cropper/releases/tag/v2.0.0).

**Comment by JoMas971** [comment]
Thank you for the tip with the `strict` option. I've removed it, but nothing change... 
That's weird then, this plugin is supposed to work with mobile isn't it ? Do i need a special option to enable the plugin on Mobile Phone or best practices to do ?
Anyone has already tested this plugin with cordova ?

Thanks for the Help :-).
