### ISSUE TITLE
Fixed width but flex height

### ISSUE THREAD

**Issue by Chinmay85** [fengyuanchen/cropper#549]
Hello there!
First of all this plugin is amazing. Thanks for creating it.

Now, we have a requirement where we want to have a fixed width for a crop box but allowing flexible height. So i tried restricting it under "crop: function (e) { ... .... }" by checking and setting  setCropBoxData if width is not same as fixedWidthValue  "$cropbox.cropper("setCropBoxData", { width: fixedWidthValue});" 

The needful is working but it's taking a very bad performance hit.
Do you have any recommendation for the same or any hack which do not take a toll on performance.

And it would be amazing if you add this functionality where user can set fixed width or fixed height but flexible height or width respectively.

Cheers

**Comment by fengyuanchen** [comment]
You can reference this example: [Cropper with a range of aspect ratio](https://github.com/fengyuanchen/cropper/blob/master/examples/a-range-of-aspect-ratio.html).
