### ISSUE TITLE
cropper inside TD tag

### ISSUE THREAD

**Issue by zahaaurel** [fengyuanchen/cropper#550]
Hi,

Just noticed when the cropper is used inside a TD tag, pay attention to the align property of TD tag. If it is aligned to center, when zooming out the image the 2 overlays of the cropper get a gap between them. I personally changed to align: left and it solved the problem.

regards
Aurelian

**Comment by fengyuanchen** [comment]
Wrap the image with a block element:

```html
...
<td>
  <div class="cropper">
    <img src="/path/to/picture.jpg">
  </div>
</td>
...
```

```css
.cropper {
  overflow: hidden;
}
```

**Comment by zahaaurel** [comment]
Thank you for the reply, but in my case, I am not allowed to add elements inside the table.

regards
Aurelian

**Comment by fengyuanchen** [comment]
All right. then I have to suggest that don't use Cropper inner a table.

**Comment by zahaaurel** [comment]
Just needed to set TD align to left and it works perfect. Thanks for the great library, really great job!
