### ISSUE TITLE
Initial size in responsive mode.

### ISSUE THREAD

**Issue by maxikSP** [fengyuanchen/cropper#555]
How to set size correctly? It works after window resizing only. Example, just open tool in browser.
https://drive.google.com/file/d/0B5oADJvHHxPzSkFWQ19GVVJlYnM/view?usp=drivesdk
https://drive.google.com/file/d/0B5oADJvHHxPzS1QtUFZTcDRaaGc/view?usp=drivesdk

**Comment by maxikSP** [comment]
Can some one help? I rely don't know why I have such strange view. I tried all ways from plugin docs and   nothing helped

**Comment by fengyuanchen** [comment]
I can open your links...Why don't you just upload them?

**Comment by maxikSP** [comment]
![meetrip - account - change bank card](https://cloud.githubusercontent.com/assets/2980628/11979635/a02deb68-a99d-11e5-805c-6d068eca126c.png)

![meetrip - account - change bank card 1](https://cloud.githubusercontent.com/assets/2980628/11979644/b3fd5836-a99d-11e5-9005-ee3744d08374.png)

Sorry :(

**Comment by fengyuanchen** [comment]
```css
.modal-body img {
  width: 100%;
}
```

**Comment by maxikSP** [comment]
Thanks :) Now all working properly.
