### ISSUE TITLE
display issue with cross origin image

### ISSUE THREAD

**Issue by flyfj** [fengyuanchen/cropper#557]
i'm recently using cropper on cross origin images fetched from an image url via a cross-origin server. The image element is like this:

    <div>
        <img id="sel-img" style="width:100%" crossOrigin src="...">
    </div>

and cropper is added as below:
   
    $('#sel-img').cropper({
                        scalable: false,
                        zoomable: false,
                        movable: false,
                        rotatable: false,
                        crop: function(e) {
                               ...
                        }
                    }); 

the result shows with a gray mask above the whole image with a invalid icon at top left corner:
![eg](https://cloud.githubusercontent.com/assets/2397970/11890152/49048978-a51f-11e5-9520-a6cff874777c.png)

in the chrome console, there is a error stating: 
![err](https://cloud.githubusercontent.com/assets/2397970/11890181/8ece7d10-a51f-11e5-82e7-a6ede8aa0567.png)

if i don't add cropper, everything works ok without error.
really struggling with this, hope for help.

**Comment by fengyuanchen** [comment]
Two options for you:
1. Search the issues history for "cross origin" to find the resolution.
2. Set both the `checkCrossOrigin` and `checkOrientation` options to `false`.

**Comment by flyfj** [comment]
setting `checkCrossOrigin` to `false` solves the issue. thanks for help.
