### ISSUE TITLE
How to take the image / thumbnail name and insert it in the database

### ISSUE THREAD

**Issue by orexutzu** [fengyuanchen/cropper#559]
Hello guys.. I'm struggling to take the name in order to upload it in the database as in my example below:
$sql = mysql_query("INSERT INTO user (Fname, Lname, ProfileImage)Values('{$FName}', '{$LName}',  '{$UploadName}')") or die(mysql_error());

could you please give me some hints?  Thanks a lot!

<?php
	if(isset($_FILES['UploadFileField'])){
		$UploadName = $_FILES['UploadFileField']['name'];
		$UploadName = mt_rand(100000, 999999).$UploadName;
		$UploadTmp = $_FILES['UploadFileField']['tmp_name'];
		$UploadType = $_FILES['UploadFileField']['type'];
		$FileSize = $_FILES['UploadFileField']['size'];
		$UploadName = preg_replace("#[^a-z0-9.]#i", "", $UploadName);
		session_start();
		$_SESSION["ProfilePicName"] = $UploadName; 
		
		if(($FileSize > 5250000)){
			
			die("File to big");
		
		}		
		
		if(!$UploadTmp){
			die("No file selected");
			}else{
				move_uploaded_file($UploadTmp, "Upload/$UploadName");
			}
	}

?>

**Comment by fengyuanchen** [comment]
Any questions about how to use PHP, I suggest to ask for help on StackOverflow.com
