### ISSUE TITLE
Image distortion on iOS

### ISSUE THREAD

**Issue by aemdy** [fengyuanchen/cropper#561]
I have upgraded cropper from 2.0.1 to 2.2.1. I noticed fixes of various bugs, but there is one problem which is new.

On iOS it seems that width/height dimensions are mixed (the glass is actually much higher):
![img_0079](https://cloud.githubusercontent.com/assets/1015018/11929069/c2dbb2d0-a7e0-11e5-99ca-5a4c2a24b107.jpg)

I tried various values of `checkOrientation` setting, but it didn't help.

**Comment by fengyuanchen** [comment]
I still have not idea about this (the same issue as #509).
