### ISSUE TITLE
low quality

### ISSUE THREAD

**Issue by rooholah** [fengyuanchen/cropper#563]
how to crop high quality by cropper.js ?

**Comment by fengyuanchen** [comment]
Reference the [HTMLCanvasElement.toDataURL](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL):
```js
$().cropper('getCroppedCanvas').toDataURL('image/jpeg', 1);
```

**Comment by rooholah** [comment]
hello. My problem was not solved. continues to be very low-quality images and colors together.

**Comment by rooholah** [comment]
![crop](https://cloud.githubusercontent.com/assets/5820932/11948541/413b3034-a88a-11e5-846c-149ededc4a10.jpg)

**Comment by rooholah** [comment]
![001](https://cloud.githubusercontent.com/assets/5820932/11948545/56d909fc-a88a-11e5-8a36-ccdfccf5b6f2.jpg)
