### ISSUE TITLE
PHP Requirements

### ISSUE THREAD

**Issue by gauravmak** [fengyuanchen/cropper#566]
Does this example require exif and mbstring both?
-> https://github.com/fengyuanchen/cropper/tree/master/examples/crop-avatar

**Comment by gauravmak** [comment]
And will it run with both installed on php 5.4?

**Comment by fengyuanchen** [comment]
1. Not need Exif
2 . What's the mbstring?
3. I don't test it on PHP 5.4, just PHP 5.5.

**Comment by fengyuanchen** [comment]
It is just an example, you can customize it by yourself.

**Comment by gauravmak** [comment]
1) I asked because exif function is being used in the file and that line is throwing an error.
https://github.com/fengyuanchen/cropper/blob/master/examples/crop-avatar/crop.php#L19

2) I had read in stackoverflow that mbstring would be needed as well so. Though its needed for windows only (I just found that) - http://stackoverflow.com/a/20409917

3) No problem. Thank you.

**Comment by fengyuanchen** [comment]
Okay~ I didn't understand your exif as I have a repo named [Exif](https://github.com/fengyuanchen/exif).

**Comment by gauravmak** [comment]
That example just worked well with php 5.4.45
