### ISSUE TITLE
Subpixel issues

### ISSUE THREAD

**Issue by hypeJunction** [fengyuanchen/cropper#569]
I'm seeing issues with large images that are downsized to fit the container width. As you can see below, I am trying to crop a large image in a smaller container. Container height is 438px, but the image height is 433.58px, which leaves 2px gap before and after the image. If I resize the crop area to the container size, I am unable to perform the crop server side, as the calculated coordinates are outside of the original image.

![croparea](https://cloud.githubusercontent.com/assets/1202761/12033793/cbd8bef8-ae27-11e5-8ca6-cc0d39366ab8.png)

**Comment by cyberwolfru** [comment]
Have you tried to change viewMode option? 
For example, viewMode: 2

**Comment by hypeJunction** [comment]
2 didn't help, but 3 works. Thanks.
