### ISSUE TITLE
why my cropper area is so small

### ISSUE THREAD

**Issue by zhangwei900808** [fengyuanchen/cropper#571]
![qq 20160103094838](https://cloud.githubusercontent.com/assets/4385154/12076948/48bf7990-b1ff-11e5-97ca-df0d8706ca0d.png)
![qq 20160103094915](https://cloud.githubusercontent.com/assets/4385154/12076949/578c7bda-b1ff-11e5-9520-3ca342224bb5.png)

**Comment by fengyuanchen** [comment]
Keep the container has 100% width:
```css
.modal-body img {
  width: 100%;
}
```

**Comment by zhangwei900808** [comment]
还是不行，不过奇怪的是，当我点击f12的时候它就变大了，这是为什么
![qq 20160103094838](https://cloud.githubusercontent.com/assets/4385154/12077089/b9824d10-b209-11e5-94d1-0f09e6b168fb.png)
![qq 20160103110253](https://cloud.githubusercontent.com/assets/4385154/12077088/abeca3b2-b209-11e5-9562-b69891b5bf2d.png)

**Comment by zhangwei900808** [comment]
大神，1576410833我qq，如果你方便的话我们qq联系可以吗

**Comment by fengyuanchen** [comment]
Please use the `shown.bs.modal` rather than `show.bs.modal`.

**Comment by zhangwei900808** [comment]
一开始我就是用shown的，可是不行才改成show的

**Comment by zhangwei900808** [comment]
一开始我就是用shown的，可是不行才改成show的

**Comment by fengyuanchen** [comment]
Refer this example please: https://github.com/fengyuanchen/cropper/blob/master/examples/cropper-in-modal.html

**Comment by zhangwei900808** [comment]
我就是看的这个例子做的，但是出现这样的问题，

**Comment by zhangwei900808** [comment]
大神，还有个地方非常奇怪，当我使用网络图片，它显示是正常的，但是我上传本地图片就出现这样的问题

**Comment by zhangwei900808** [comment]
$('#inputImage').change(function () {

        var $image = $('#avatorImg');
        var cropBoxData;
        var canvasData;
        var files = this.files;
        var file;

        if (files && files.length) {
            file = files[0];
            var reader = new FileReader();
            reader.onload = function () {
                // 通过 reader.result 来访问生成的 DataURL
                var url = reader.result;
                //setImageURL(url);
            };
            if (/^image\/\w+$/.test(file.type)) {
                blobURL = URL.createObjectURL(file);

                $image.one('built.cropper', function () {
                    // Revoke when load complete
                    URL.revokeObjectURL(blobURL);
                }).cropper('reset').cropper('replace', blobURL);

            } else {
                window.alert('Please choose an image file.');
            }
        }
        $('#myModal').modal('show');
        $('#myModal').on('shown.bs.modal', function () {
            $image.cropper({
                autoCropArea: 0.5,
                zoomable:false,
                zoomOnWheel:false,
                wheelZoomRatio:false,
                movable: false,
                built: function () {
                    $image.cropper('setCanvasData', canvasData);
                    $image.cropper('setCropBoxData', cropBoxData);
                }
            });
        }).on('hidden.bs.modal', function () {
            cropBoxData = $image.cropper('getCropBoxData');
            canvasData = $image.cropper('getCanvasData');
            $image.cropper('destroy');
        });


    });

**Comment by fengyuanchen** [comment]
```js
$(function () {
    var $image = $('#avatorImg');
    var $modal = $('#myModal');
    var cropBoxData;
    var canvasData;

    $('#inputImage').change(function () {
        var files = this.files;
        var file;

        if (files && files.length) {
            file = files[0];

            if (/^image\/\w+$/.test(file.type)) {
                blobURL = URL.createObjectURL(file);
                
                $image.one('built.cropper', function () {
                  // Revoke when load complete
                  URL.revokeObjectURL(blobURL);
                });

                $image.attr('src', blobURL);
            } else {
                window.alert('Please choose an image file.');
            }
        }

        $modal.on('shown.bs.modal', function () {
            $image.cropper({
                autoCropArea: 0.5,
                zoomable:false,
                zoomOnWheel:false,
                wheelZoomRatio:false,
                movable: false,
                built: function () {
                    $image.cropper('setCanvasData', canvasData);
                    $image.cropper('setCropBoxData', cropBoxData);
                }
            });
        }).on('hidden.bs.modal', function () {
            cropBoxData = $image.cropper('getCropBoxData');
            canvasData = $image.cropper('getCanvasData');
            $image.cropper('destroy');
        });

        // Call the `show` method after bound events
        $modal.modal('show');
    });
});
```

**Comment by zhangwei900808** [comment]
好的，我试试

**Comment by zhangwei900808** [comment]
可以了(为什么？？？)，大神，不过为什么显示这么大啊？
![qq 20160103112905](https://cloud.githubusercontent.com/assets/4385154/12077140/41f8441c-b20d-11e5-8f32-4bf1cd7d4558.png)

**Comment by fengyuanchen** [comment]
```js
$(function () {
    var $image = $('#avatorImg');
    var $modal = $('#myModal');
    var cropBoxData;
    var canvasData;

    // Bind events first
    $modal.on('shown.bs.modal', function () {
        $image.cropper({
            autoCropArea: 0.5,
            zoomable:false,
            zoomOnWheel:false,
            wheelZoomRatio:false,
            movable: false,
            built: function () {
                $image.cropper('setCanvasData', canvasData);
                $image.cropper('setCropBoxData', cropBoxData);
            }
        });
    }).on('hidden.bs.modal', function () {
        cropBoxData = $image.cropper('getCropBoxData');
        canvasData = $image.cropper('getCanvasData');
        $image.cropper('destroy');
    });

    $('#inputImage').change(function () {
        var files = this.files;
        var file;

        if (files && files.length) {
            file = files[0];

            if (/^image\/\w+$/.test(file.type)) {
                blobURL = URL.createObjectURL(file);

                $image.one('built.cropper', function () {
                  // Revoke when load complete
                  URL.revokeObjectURL(blobURL);
                });

                $image.attr('src', blobURL);
            } else {
                window.alert('Please choose an image file.');
            }
        }

        // Don't bind events in another event

        $modal.modal('show');
    });
});
```

**Comment by zhangwei900808** [comment]
不行，试了，还是好大，我要不要设置宽度什么的，要不然显示好大啊

**Comment by fengyuanchen** [comment]
初始化的图片尺寸取决于容器尺寸（超小图片自动拉伸，超大图片自动收缩）
