### ISSUE TITLE
Uncaught TypeError: $image.cropper(...).toBlob is not a function

### ISSUE THREAD

**Issue by zhangwei900808** [fengyuanchen/cropper#572]
![qq 20160103150128](https://cloud.githubusercontent.com/assets/4385154/12077663/0b751fb4-b22b-11e5-8feb-e7174f0f82a1.png)

**Comment by fengyuanchen** [comment]
Only Firefox support `toBlob` currently: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

**Comment by zhangwei900808** [comment]
哦哦，那我想把图片数据用java后台保存，这个怎么操作啊

**Comment by fengyuanchen** [comment]
There is a polyfill in the documentation of [toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) API.

Or use this library: https://github.com/eligrey/canvas-toBlob.js

**Comment by fengyuanchen** [comment]
You can also refer to #325, #489.

**Comment by zhangwei900808** [comment]
我到现在都还不知道怎么用java获取

**Comment by zhangwei900808** [comment]
找到解决方法了：
 var $image = $('#avatorImg');
    $image.cropper('getCroppedCanvas').toBlob(function (blob) {

        var formData = new FormData();

        formData.append('croppedImage', blob);
        $.ajax('/json/uploadAvatar.json', {
            method: "POST",
            data: formData,
            processData: false,
            contentType: false,
            success: function () {
                console.log('Upload success');
            },
            error: function () {
                console.log('Upload error');
            }
        });

后台：

@RequestMapping(value = "/json/uploadAvatar.json", method = RequestMethod.POST)
    @ResponseBody
    public String uploadAvatar(@RequestParam("croppedImage") MultipartFile file) {
        try {
            InputStream content = file.getInputStream();
            String properties = "aliyun-oss.properties";
            String filepath = userSitesService.uploadAvatar(properties, content);
        } catch (Exception ex) {

        }
        return null;
    }

配置文件：

    <bean id="multipartResolver" class="org.springframework.web.multipart.commons.CommonsMultipartResolver"/>
