### ISSUE TITLE
Would a pull request that adds a `zoomend` event be accepted?

### ISSUE THREAD

**Issue by brynnb** [fengyuanchen/cropper#574]
Right now there's no way I know to listen for when zoom event ends. The use case for me is testing whether the resulting image after the zoom is larger than a minimum width/height. 

I store the contents of `getData()` in a `tempData` variable on the `zoom.cropper` event or `cropstart.cropper` event, then check at `cropend.cropper` whether it's the minimum height/width. If not, it `setData()` back to `tempData`. I need a `zoomend.cropper` in order to know when the zoom is done to perform this same test.

Let me know if there's a better way to do this already, I am not seeing it. Thanks!

**Comment by brynnb** [comment]
Alternatively, a minImageWidth etc options would also fix this issue. This was discussed in #201 but it was closed without actually being implemented. 

To clarify, minContainerWidth does not work for me purposes because the user can zoom in - minContainerWidth does not account for this, it only displays the width of the cropping box visible to the user.

**Comment by brynnb** [comment]
Also to clarify further, I am not using `minCropBoxWidth` because the user is editing very large images. If the minimum image size is 2000px across, the cropper tool would have to be tremendous and probably cause horizontal scrolling (and make them zoom out in their browser to even see the entire image).

**Comment by fengyuanchen** [comment]
Use the `zoom` event is enough:
```js
var minImageWidth = 100;
var minImageHeight = 100;

$().on('zoom.cropper', function (e) {
  var imageData = $(this).cropper('getImageData');

  // Zoom out
  if (e.ratio < e.oldRatio) {

    // Prevent zoom out again
    if (imageData.width < minImageWidth || imageData.height < minImageHeight) {
      e.preventDefault();
    }
  }
});
```

**Comment by brynnb** [comment]
Did you mean to include a line like `$().cropper('zoom', 0.1);` after `if (e.ratio < e.oldRatio) {`? I am not sure how your example would run after the zoom event is complete otherwise.

**Comment by brynnb** [comment]
Thanks - to make sure I understand, any logic I need to run *after* the zoom event has finished I would include before `e.preventDefault()`?

**Comment by fengyuanchen** [comment]
`e.ratio` is the new ratio when zoom end, `e.oldRatio` is the current ratio, when call the `e.preventDefault()` in zoom event, then the new ratio still is `e.oldRatio`

**Comment by brynnb** [comment]
Oh, okay - thank you. I deleted a couple of my comments because I realized I was misunderstanding and was trying to understand better first. I was under the impression that e.oldRatio was the ratio from the previous scroll event (which could have been minutes ago). Thank you. I guess a more accurate label would be `e.startingRatio` and `e.endingRatio`

**Comment by brynnb** [comment]
I would close this but not sure on your thoughts on updating to use `e.startingRatio` and `e.endingRatio`. Feel free to close if you disagree on that.

**Comment by fengyuanchen** [comment]
Just like `change` event, The new value is `this.value`, not `this.newValue` or `this.endingValue`.

**Comment by brynnb** [comment]
Fair enough, thanks for your help.
