### ISSUE TITLE
CropBoxWidth does not update when zooming

### ISSUE THREAD

**Issue by brynnb** [fengyuanchen/cropper#575]
http://jsfiddle.net/9r6czo65/122/

If you zoom in, then move the crop box, it will jump to a bigger size to attempt to reach its minCropBoxWidth. It seems like it should do this automatically on zooming (and not wait for the user to start moving the crop box).

**Comment by fengyuanchen** [comment]
I think it is unnecessary to support this as the crop box size is not based on the actual image size.

**Comment by brynnb** [comment]
You're right, it is not relevant for creating the actual image size, but more from a user interaction standpoint is it really jarring. It seems like it should auto-expand on zoom, or not auto-expand on moving/adjusting cropping. As in, it should not *attempt* (and fail) to enforce `minCropBoxWidth` until it is actually possible for the crop box to be the correct minimum width.
