### ISSUE TITLE
No feasible way to work with large images and require minimum image dimensions

### ISSUE THREAD

**Issue by brynnb** [fengyuanchen/cropper#576]
If a user uploads an image 5000 pixels wide, and I want the minimum width of a cropped image to be 2000 pixels, the only built-in way I know of to do this with default options is to use `minContainerWidth` set to 2000 pixels, which requires that the cropper tool be 2000+ pixels wide in order for it to fit. 

Another way to enforce a minimum image size was brought up in #339 - this involves getting the width from `getCropBoxData` and reverting the crop if it fell below the minimum pixel width. However, this ignores the zoom ratio. 

So my solution to do this was to get the width from `getCropBoxData` and divide it by the zoom ratio to get the calculated real cropped image size.

(**edited for clarification and better Fiddle**) [Here is the JSFiddle](http://jsfiddle.net/9r6czo65/152/) I put together that almost works for my purposes. Without this extra logic, the webpage would need to be at least 3000 pixels wide plus margins and whatever else if you wanted to ensure a real, non-upscaled image dimensions after cropping.

The use case for this extends beyond simply having huge images - it would allow something like cropping an image that is 1920px wide with a required cropped width of 700 pixels while using a browser that is taking up half a monitor without worrying about horizontal scrolling. 

Editing large images while enforcing large minimum dimensions at a minimum resolution seems like a fairly reasonable thing to want to do with this library. I was disappointed when @fengyuanchen said in #339 that he didn't feel this was needed. It took me (admittedly no JS pro) many hours to figure this out and create that JSFiddle.

Is there some other way to do this that I haven't thought of? If not, It would be really nice if there could be a `minImageWidth` option that handled all of this for future developers. @fengyuanchen, are you open to the idea of accepting a pull request adding this, having seen a reasonable use case for it demonstrating the need?

**Comment by brynnb** [comment]
@fengyuanchen [cleared up a misconception](https://github.com/fengyuanchen/cropper/issues/574#issuecomment-168878896) I had about wanting a `zoomend` event, so that part is not relevant anymore.

**Comment by fengyuanchen** [comment]
Use `$().cropper('getCroppedCanvas', {width: 3000})`, you can always get an image with `3000` pixels width no matter what the real width of the original width!!!

**Comment by brynnb** [comment]
@fengyuanchen the point is to prevent upscaling of an image, I don't think your solution would prevent that.

**Comment by fengyuanchen** [comment]
Still use the `zoom` event is enough:
```js
var minWidth = 100;
var minHeight = 100;

$().on('zoom.cropper', function (e) {

  // This data is based on actual image size
  var data = $(this).cropper('getData');

  // Zoom out
  if (e.ratio < e.oldRatio) {

    // Prevent zoom out again
    if (data.width < minWidth || data.height < minHeight) {
      e.preventDefault();
    }
  }
});
```

**Comment by brynnb** [comment]
@fengyuanchen I updated JSFiddle to use what you posted: http://jsfiddle.net/9r6czo65/137/

Ignoring zooming, there is still the issue of enforcing a minimum size when cropping. As you can tell with the Fiddle, it refuses to ever to be less than the maximum width and height. This is because the cropper is only actually a few hundred pixels wide and it's trying to be thousands of pixels wide. Hence the webpage would have to be thousands of pixels wide to accommodate this.

**Comment by fengyuanchen** [comment]
Maybe I don't really understand the **prevent upscaling of an image**.  What is the mean?

**Comment by brynnb** [comment]
Let's say this image was the result of what was inside the cropper:
![kitten1](https://cloud.githubusercontent.com/assets/1271817/12107225/8153c516-b32d-11e5-8b6b-bfa331c81edd.jpg)

You said I can use `$().cropper('getCroppedCanvas', {width: 500})` and always get an image that's 500 pixels. If you do that with an image that's starting off as maybe 100px, this is what it looks like:

![kitten2](https://cloud.githubusercontent.com/assets/1271817/12107234/a0926284-b32d-11e5-80c3-a07ce25baa77.jpg)

It simply takes the 100px image, crops the 50px part that the user specified, and blows it up to 500px. 

This doesn't solve the problem of requiring the user to crop an image that is truly 500px (at a zoomRatio of 1).

**Comment by fengyuanchen** [comment]
So why don't you filter the original image first? 

For example, if the image come from user upload, then when a user chosen a small image (width < 500px), then alert user that you app requires an image which width great than 500 pixels.

**Comment by brynnb** [comment]
I was just posting that to explain what I meant by upscaling. The same sort of function that would check to make sure the true image output is 500px in that example is the same function that would be required for this:

* You want a user to upload an image that is 6000px wide and you want them to crop it to 3000px wide

AND

* You do not want the webpage to be 3000px+ wide.

**Comment by brynnb** [comment]
Here's an example: http://jsfiddle.net/9r6czo65/139/

Zoom out in your browser as much as possible to make it somewhat fit (may or may not work depending on your monitor resolution). This is what is needed to crop a 6000px image down to 2000px. The webpage has to be enormous, super zoomed out, or have huge horizontal scroll bars.

**Comment by fengyuanchen** [comment]
...

**Comment by fengyuanchen** [comment]
On the your demo: http://jsfiddle.net/9r6czo65/137/, just remove `minCropBoxWidth/Height` options, then you will find everything works fine!!!

**Comment by fengyuanchen** [comment]
Also, please `return` after this line `$(this).cropper('zoomTo', 1)`

**Comment by brynnb** [comment]
Here's the update as you suggested: http://jsfiddle.net/9r6czo65/141/

The user can still crop the image to only be 100px by 100px or any very small size. If I take that cropped image and use `$().cropper('getCroppedCanvas', {width: 2000})` it will be upscaled, just like the kitten. This is what I am trying to avoid. I don't want to allow users to use poor quality images that have been upscaled like the kitten. 

Thanks for your patience in helping me out.

**Comment by fengyuanchen** [comment]
After so many explanation, I find that you really don't understand how the Cropper works.
Why not read the documentation carefully first?

**Comment by fengyuanchen** [comment]
In short:
- `getData` outputs **absolute** position and size pixels based on natural image size
- `getCanvasData` and `getCropBoxData` outputs **relative** position and size pixels based on webpage

**Comment by brynnb** [comment]
Thanks for your help, your most recent comment helped. I still do not believe what I want is possible with the default options, but I made the JSFiddle that handles it much more simply and (I think) bug free: http://jsfiddle.net/9r6czo65/150/ (It's been an 16 hour work day with very little sleep for me so please forgive any mistakes!)

Hopefully my fiddle helps anyone else who comes across this looking for a solution to enforce minimum image sizes when dealing with large images while also preventing upscaling. 

The way this is being handled in my JSFIddle different from how Cropper usually handles stuff, so I understand if it is not a feature you feel is appropriate for the Cropper project. Thanks again for all your work on Cropper and enduring my sleep deprived questions!

**Comment by boutell** [comment]
@brynnb thanks for your fiddle. However I note that with this fiddle, once you zoom out, you are unable to zoom in again. It would be better if it upsized the crop box to match (as long as it's possible...) rather than rejecting the zoom altogether. I will let you know if I have any luck with that, I think your code is very close to what I need. Thanks!
