### ISSUE TITLE
Integration with Kohana framework

### ISSUE THREAD

**Issue by Pantela777** [fengyuanchen/cropper#579]
How I can to integration plugin with Kohana framework, I see PHP class **CropAvatar** and I think can use as a framework helper...
When I try to add plugin and upload img I didn't see any XHR any request http://i.imgur.com/JdfeeAr.png

**Comment by fengyuanchen** [comment]
The Crop Avatar is just a simple example for using Cropper. Just customize a advanced one as you want.

**Comment by Pantela777** [comment]
Ok, but can you tell me which of problem I have...? That XHR is empty...

**Comment by fengyuanchen** [comment]
Sorry, I don't know how to use Kohana yet.
