### ISSUE TITLE
Title is wrong

### ISSUE THREAD

**Issue by KevinMcCoy** [fengyuanchen/cropper#580]
simple jQuery image cropping plugin - This title or any where in the document, it dose not mention PHP.

Take a look here:  cropper/examples/crop-avatar/crop.php

**Comment by jonblum** [comment]
That's just an example (in one language) of how you might store your cropped image server-side.

The cropper itself is client-side JS.

**Comment by KevinMcCoy** [comment]
Thanks yeah I noticed it later, that was the example I really wanted.  So I'm using th demo, and basically getting that one to do the same thing as the avatar doing but with out php (Since work wants it in CF)
