### ISSUE TITLE
Bug if try to upload same image again

### ISSUE THREAD

**Issue by Pantela777** [fengyuanchen/cropper#581]
I want to upload image in modal window...
I use https://github.com/fengyuanchen/cropper/tree/master/examples/crop-avatar now if I click to image and try upload http://i.imgur.com/UBk2Mgb.png uploaded good, then close window and without refresh page try to again upload image http://i.imgur.com/802Pmbw.png, I can't see him to preview place.

P.S. Important try to upload only the same image.

**Comment by fengyuanchen** [comment]
Before you choose the same image, you should clear the file input first, if not, a **change** event will not be triggered.

```js
$('input[type="file"]').val('');
```

**Comment by ottokupradze** [comment]
Ok, but maybe I upload img set crop param, close modal and again open modal, and now I didn't want to clear crop param...

**Comment by Pantela777** [comment]
Ok, but maybe I upload img set crop param, close modal and again open modal, and now I didn't want to lost my set crop param.
xz

**Comment by itsAkky** [comment]
> Before you choose the same image, you should clear the file input first, if not, a **change** event will not be triggered.
> 
> ```js
> $('input[type="file"]').val('');
> ```

It work perfectly fine... thank you very much.. You saved my time...
