### ISSUE TITLE
Saving the cropped image into mysql using php

### ISSUE THREAD

**Issue by Aggreyluts** [fengyuanchen/cropper#583]
After selecting image in the modal on .html page, form gets submitted on below crop.php page. Image gets successfully cropped and gets saved as a png image in the folder. But I also want to update (insert) cropped image name in database table (as shown in the coding), but everytime it is showing parsererror and image is not updated (inserted) in the table.
So please help me out, about how to update (insert) cropped image in database.

**Comment by fengyuanchen** [comment]
The **Crop Avatar** is a simple example for guiding how to use Cropper. You might need to customize or improve it if you need to use in your production.

**Comment by Aggreyluts** [comment]
For me to post this issue it means its hard to customize it in terms
of database link up.Please show us a way forward.

**Comment by ko-github** [comment]
Hi Aggreyluts

That's moreorless what I'm trying to do. Instead of opening the file, to then save it to your own hard drive, I'm wanting to click that button and
- the file is saved to a MySQL database as a blob
- the modal window closes and re-directs you to a previous page

Have you got any further since your post?

**Comment by dadixon** [comment]
I can't get the saving images example to work.

`$().cropper('getCroppedCanvas').toBlob(function (blob) {
  var formData = new FormData();

  formData.append('croppedImage', blob);

  $.ajax('/path/to/upload', {
    method: "POST",
    data: formData,
    processData: false,
    contentType: false,
    success: function () {
      console.log('Upload success');
    },
    error: function () {
      console.log('Upload error');
    }
  });
});`

I keep getting the error that says toBlob or toDataURL is not a function

**Comment by fengyuanchen** [comment]
@dadixon You may need to see #572, #612.
