### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by dangreen** [fengyuanchen/cropper#584]
`checkCrossOrigin` instead `checkImageOrigin`

**Comment by fengyuanchen** [comment]
As of [v2.0.0](https://github.com/fengyuanchen/cropper/releases/tag/v2.0.0), the `checkImageOrigin` option had been renamed to `checkCrossOrigin `.

**Comment by fengyuanchen** [comment]
As of [v2.0.0](https://github.com/fengyuanchen/cropper/releases/tag/v2.0.0), the `checkImageOrigin` option had been renamed to `checkCrossOrigin `.
