### ISSUE TITLE
Moving Canvas/image in Modal

### ISSUE THREAD

**Issue by Antquity** [fengyuanchen/cropper#586]
Im using the Change Avatar sample and added the move up and down button but they don't seem to move the image. The move right and left moves the image on a diagonal. I think I tracked it down to the data-second-option not getting through to the offsetY in the move function

Any one able to help ?

**Comment by fengyuanchen** [comment]
The main reason may be the problem of your code.

**Comment by Antquity** [comment]
All i did was add the up down buttons to the avatar example, doesnt seem to work

**Comment by fengyuanchen** [comment]
You also need to edit the **main.js** to make your changes effective.

**Comment by Antquity** [comment]
Isnt it the same main.js as uesd in the main site that has the up down and sideways buttons working ?

**Comment by fengyuanchen** [comment]
Can you put your own HTML and JS code here for preference?
