### ISSUE TITLE
Image resizes and moves off center with multiple crop instances

### ISSUE THREAD

**Issue by matthewdowney** [fengyuanchen/cropper#587]
Hi,

I have a page where users upload multiple photos which are cropped sequentially and then saved. I'm encountering an error where after the first image upload, the cropper appears not to reset properly. 

I have the default settings configured like so:
```
  var aspectRatio = {width: 16, height: 9}; // aspect ratio for uploaded images
  . . . 
  $.fn.cropper.setDefaults({
    autoCropArea: 0.85,
    aspectRatio: aspectRatio.width / aspectRatio.height,
    guides: false,
    movable: false,
    zoomable: false
  }); 
```
Then, when an image is uploaded, a modal containing the cropper element is shown, calling:
```
/**
 * EVENT: The crop modal is shown; use these settings, and set isCurrentlyCropping.
 */
$('#cropModal').on('shown.bs.modal', function () {
  if (DEBUG) console.log("[EVENT] crop modal shown");
  cropImageSource.cropper({
    built: function () {
      cropImageSource.cropper('setCropBoxData', cropBoxData);
      cropImageSource.cropper('setCanvasData', canvasData);
    }
  });
});
```
Finally, when the modal is closed I get the image, upload it, and destroy the cropper:
```
/**
 * EVENT: The crop is complete; upload the image and destroy the cropper.
 */
$('#cropModal').on('hidden.bs.modal', function () {
  if (DEBUG) console.log("[EVENT] crop modal closed");
  cropBoxData = cropImageSource.cropper('getCropBoxData');
  canvasData = cropImageSource.cropper('getCanvasData');

  // get the cropped image as a blob with our desired width/height (aspect ratio is gauranteed)
  if (DEBUG) console.log("[INFO] converting canvas to image blob");
  $(cropImageSource).cropper('getCroppedCanvas', {
         width: pixelDimensions.width, 
         height: pixelDimensions.height
   }).toBlob(function(imageAsBlob) {
         // convert the blob to a file
         var imageAsFile = fileFromBlob(imageAsBlob, "");
         uploadImage(imageAsFile); // upload the image
   });
  cropImageSource.cropper('destroy');
});
```

All of this works fine until the second iteration of this pattern. Even though I destroy the cropper when the modal is closed, upon opening it & reconstructing it I get a different result--the image is shrunk and off center. It's almost as if `cropImageSource.cropper('destroy');` doesn't completely destroy the cropper instance, and when the modal is shown again the new cropper is somehow tainted.

Check out these screenshots. The first iteration it works fine:
<img width="956" alt="cropperfirst" src="https://cloud.githubusercontent.com/assets/7322450/12380110/fc824c76-bd1e-11e5-969d-761c1d8455b3.png">
In the second, the image is shrunk and off center:
<img width="956" alt="croppersecond" src="https://cloud.githubusercontent.com/assets/7322450/12380111/fc84b6be-bd1e-11e5-8a4a-5eb354cd81d7.png">

**Comment by fengyuanchen** [comment]
If the image url is changed,  you should clear the cached data as well:
```js
...

if (imageURLChanged) {
  cropBoxData = null;
  canvasData = null;
}

...
```

**Comment by matthewdowney** [comment]
Thank you, works like a charm!
