### ISSUE TITLE
Long loading and not responding error with IE

### ISSUE THREAD

**Issue by fdkdervis** [fengyuanchen/cropper#588]
Hello,

Firstly, thanks for this excellent and jQuery plugin !

I encountered a strange problem, when I initialize a crop on a high resolution picture (more than 2500 pixels for the width), my Internet Explorer 11 freezes for about a minute and sometime more than a minute (depending on the resolution of the picture)

There is no response. After 15 seconds, I receive an error message from IE and it tell me there is no response from the website. But if I continue to wait, it load the page and the crop area.

But I had no problem with the same case with Chrome or Firefox. Also, when I tried to crop the same picture with the demo, I didn't encounter this problem.

Someone have an idea ?

**Comment by fdkdervis** [comment]
Apparently, I resolve this issues by putting the checkOrientation option to false. It takes a long time otherwise, maybe it will be good to have false as a default value ?

**Comment by fengyuanchen** [comment]
The `checkOrientation` option also fix issue on Safari, so it can't be set to `false` by default.
