### ISSUE TITLE
Too slow in Mobile

### ISSUE THREAD

**Issue by RempelOliveira** [fengyuanchen/cropper#590]
It is normal to so respond events slowly on mobile?

**Comment by fengyuanchen** [comment]
If you are cropping a huge image, it may require many memory. So you can limit the size and dimension of the image.

**Comment by RempelOliveira** [comment]
Is correct, testing found the same situation.
To solve this problem, I resize the image before applying the plugin, getting as below:

...

var img 	   = new Image;
	img.src    = e.target.result;

	img.onload = function()
	{
		if(img.width > 1200) //if img > 1200, resize proportionally
		{
			var canvas = document.createElement("canvas"),ctx = canvas.getContext("2d");

				canvas.width  = img.width  / (img.width / 1200);
				canvas.height = img.height / (img.width / 1200);

			ctx.drawImage		  	  (img, 0, 0, canvas.width, canvas.height);
			img.src = canvas.toDataURL();

		}

		$("img").attr("src", img.src);
		$cropper = $("img").cropper($cropper_options);

	};

...

Thanks!
