### ISSUE TITLE
How to change Ratio to crop area on dinamically

### ISSUE THREAD

**Issue by rbrahul** [fengyuanchen/cropper#592]
How to reload the crop canvas with different ratio for different dimension?

I want reload the plugin based on different ratio. It maintains the first ratio all time. I want to change it programmatic ally.

**Comment by fengyuanchen** [comment]
Why not try the `setAspectRatio` method?

**Comment by AspireToCodeBetter** [comment]
I just now did something like this. Does this help?
The values are got from the DOM elements
```js
aspectRatio: $('div.imagecropper').attr('resize_width') / $('div.imagecropper').attr('resize_height'),
```
