### ISSUE TITLE
Is there any way of disabling the creation of a new crop area?

### ISSUE THREAD

**Issue by WingmanImd** [fengyuanchen/cropper#593]
Hello,
I want the user to just be able to move and resive the CropBox but not to be able to click and drag outside the initial CropBox and in this way to destroy the previous CropBox and create a new one.

I hope I explained it well.

Thanks for the awesome plugin!

**Comment by fengyuanchen** [comment]
Just set the `dragMode` option to `'move'`.

**Comment by WingmanImd** [comment]
I guess I scrolled past that. Thanks. Awesome plugin!
