### ISSUE TITLE
Preserve source image aspect ratio

### ISSUE THREAD

**Issue by WingmanImd** [fengyuanchen/cropper#594]
Hello,
Is there any way of preserving the source image aspect ratio on the crop container?

Example: If I try to crop an 360x480 image the crop container get the height of 480px but the width of 100% the viewport. is there any way of getting it stay at 100% width but get the height to match it's aspect ratio?

Thank you for the awesome plugin!

**Comment by WingmanImd** [comment]
Ok, maybe this helps somebody else in the future.

The solution to do this is setting the block element surrounding the <img> to {max-width: 100%;width:100%;} and the <img> to {width:100%; height:auto;}

This way the image never get bigger than the viewport and the aspect ratio is preserved.

Very important: make sure you don't allow user to upload images with ridiculous aspect ratios (1:100 or even 1:10 or 1px 100px, you get the idea) as this will create a huge element on your page.

Have a good day!

**Comment by fengyuanchen** [comment]
https://github.com/fengyuanchen/cropper/blob/master/examples/responsive-container.html
