### ISSUE TITLE
Android native browser with cropper performance > slow

### ISSUE THREAD

**Issue by sctaix** [fengyuanchen/cropper#595]
I'm handling a image with cropper(v.jQuery) in android native browser.

Detail tested device spec at
http://pdadb.net/index.php?m=specs&id=5402&c=samsung_sm-g710s_galaxy_grand_2_lte-a

Image size is not that really big (500 * 500), but the cropperjs performance is not smooth.

Is that normal?

**Comment by fengyuanchen** [comment]
It is easy to debug this.

1. Check if the [official demo](http://cropperjs.com/) is slow in your Android native browser.
2. If not, check your own code to find the problem.
3. If still slowly, comment here (list your phone detail will be good).

**Comment by fengyuanchen** [comment]
BTW, you should open issue at Cropper.js repository: https://github.com/fengyuanchen/cropperjs/issues

**Comment by sctaix** [comment]
I just checked official demo with the android device but still slow.
I think that the device hardware not enough to handle cropper plugin.

Performance test video link: https://drive.google.com/open?id=0B4Dd52uYX9-1MkotRXpWbTlyaTA

[General native Browser info.]
chromium
Javascript: V8 webtech-jsengine: 3.19.18.24-F.2.40a-ss-m2

[Browser gpu support info.] -- Not really helpful for this issue I think
Graphics Feature StatusCanvas: Hardware accelerated
Compositing: Hardware accelerated on all pages and threaded
3D CSS: Hardware accelerated
CSS Animation: Accelerated and threaded
WebGL: Hardware accelerated
WebGL multisampling: Hardware accelerated
Flash 3D: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Texture Sharing: Hardware accelerated
Video Decode: Software only, hardware acceleration unavailable
Video: Hardware accelerated
Panel Fitting: Unavailable. Hardware acceleration disabled.
Rasterization: Software only, multi-threaded

[Device info.]
Model: Galaxy Grand2
Kernel: 3.4.0-3440063
Android Kitkat 4.4.4

[Hardware info.]
Embedded Operating System:	Google Android 4.3 (Just upgraded to 4.4.4)
CPU Clock: 1200 MHz
CPU: Qualcomm Snapdragon 400 MSM8926 (Browse devices based on this microprocessor)
RAM capacity: 1.5 GiB (accessible: 1.4 GiB)

more detail spec at http://pdadb.net/index.php?m=specs&id=5402&c=samsung_sm-g710s_galaxy_grand_2_lte-a

BTW, this issue was cropper with jQuery version. Sorry for the confusion.

Thank you!

**Comment by fengyuanchen** [comment]
Maybe it is the problem of memory size.

**Comment by fengyuanchen** [comment]
If it is slow only when initializing, you might set the `checkOrientation` option to `false`.

**Comment by sctaix** [comment]
yes, I think so too. memory size!

BTW, iphone6s has 2G memory but cropper works very smoooooth.

Thank you!
