### ISSUE TITLE
Image after crop change to image/png type

### ISSUE THREAD

**Issue by pmd30011991** [fengyuanchen/cropper#597]
How can I keep the old file extension because my server validate file type and it throw error with message file type does not match, after I crop the image, it change to .png file but in the header of file still keeping the old extension
Can we keep the extension as before cropping for consistence ?

Thanks

**Comment by fengyuanchen** [comment]
Are you talking about the [Crop Avatar](https://github.com/fengyuanchen/cropper/tree/master/examples/crop-avatar) example?
