### ISSUE TITLE
GetCroppedCanvas Not working as required on scale

### ISSUE THREAD

**Issue by sat2madgo** [fengyuanchen/cropper#598]
When we scale the image by some factor( say 2,2 ) and then crop a area towards any corner of the image. The get cropped canvas does not expected results.

Example: http://fengyuanchen.github.io/cropper/
1. open this url
2. set data : {"x":1276.377358490566,"y":-387.1698113207547,"width":559.0943396226417,"height":314.49056603773596,"rotate":0,"scaleX":2,"scaleY":2}
3. Zoom out so that entire image is visible.
4. Change crop box to select a corner.
![selection](https://cloud.githubusercontent.com/assets/7886967/12613231/56b28240-c51e-11e5-951c-b87df0657066.PNG)
5. Click GetCroppedCanvas
![output](https://cloud.githubusercontent.com/assets/7886967/12613230/5675e362-c51e-11e5-8823-6fb3d7b00831.PNG)

**Comment by fengyuanchen** [comment]
You are right. I don't know why. I suggest you only set `1` or `-1` to scaleX and scaleY at present.

**Comment by sat2madgo** [comment]
I know the reason partially...
If you check the getSourceCanvas function inside 'getCroppedCanvas'
function it returns source image, but uses the natural width and height of
the image to prepare the canvas. This causes clipping of source image on
scale.

I modified some part of this in runtime which gave appropriate scaled
source image. but still am not able to get required result. I know that we
also need to change the clipping x,y parameter (ie. srcX and srcY) but
amnot sure about the calculation.

Below is the modified method(Please verify once) I haven't considered
rotation. Hope so this helps :)



*Highlighted code is the modified
part_____________________________________________________________________*

*  function getSourceCanvas(image, data) {*

*    var canvas = $('<canvas>')[0];*

*    var context = canvas.getContext('2d');*

*    var x = 0;*

*    var y = 0;*

*    var width = data.naturalWidth;*

*    var height = data.naturalHeight;*

*    var rotate = data.rotate;*

*    var scaleX = data.scaleX;*

*    var scaleY = data.scaleY;*

*    var scalable = isNumber(scaleX) && isNumber(scaleY) && (scaleX !== 1
|| scaleY !== 1);*

*    var rotatable = isNumber(rotate) && rotate !== 0;*

*    var advanced = rotatable || scalable;*

*    var canvasWidth = width;*

*    var canvasHeight = height;*

*    var translateX;*

*    var translateY;*

*    var rotated;*



*    if (scalable) {*

* canvasWidth = width***scaleX **;*

* canvasHeight = height***scaleY**;*

*      translateX = **canvasWidth **/ 2;*

*      translateY = **canvasHeight **/ 2;*

*    }*


*    if (rotatable) {*

*      rotated = getRotatedSizes({*

*        width: width,*

*        height: height,*

*        degree: rotate*

*      });*


*      canvasWidth = rotated.width;*

*      canvasHeight = rotated.height;*

*      translateX = rotated.width / 2;*

*      translateY = rotated.height / 2;*

*    }*


*    canvas.width = canvasWidth;*

*    canvas.height = canvasHeight;*


*    if (advanced) {*

*      x = -width / 2;*

*      y = -height / 2;*


*      context.save();*

*      context.translate(translateX, translateY);*

*    }*


*    if (rotatable) {*

*      context.rotate(rotate * Math.PI / 180);*

*    }*


*    // Should call `scale` after rotated*

*    if (scalable) {*

*      context.scale(scaleX, scaleY);*

*    }*


*    context.drawImage(image, floor(x), floor(y), floor(width),
floor(height));*


*    if (advanced) {*

*      context.restore();*

*    }*


*    return canvas;*

*  }*
_________________________________________________________________________

You are right. I don't know why. I suggest you only set 1 or -1 to scaleX
and scaleY at present.

—
Reply to this email directly or view it on GitHub
<https://github.com/fengyuanchen/cropper/issues/598#issuecomment-175656775>.
