### ISSUE TITLE
Load images without xhr upon init

### ISSUE THREAD

**Issue by mike2410** [fengyuanchen/cropper#599]
I was wondering whether it would be possible to load the initial images without having to request them thru xhr upon initialization. In this example https://github.com/fengyuanchen/cropper/blob/master/examples/multiple-croppers.html the same images is requested twice. Should it not be possible to simply copy the url of the image element, since they are being loaded within the dom anyway, or am I missing something?

Anyway: thanks a bunch for sharing this awesome piece of software =)

**Comment by fengyuanchen** [comment]
Set the `checkOrientation` option to `false`, then the cropper will not load image by xhr again.

**Comment by mike2410** [comment]
awesome, working fine now! must have overlooked that one in the docs.
thanks!

**Comment by fengyuanchen** [comment]
You are welcome~
