### ISSUE TITLE
Problem with "rotate" method

### ISSUE THREAD

**Issue by oktapodia** [fengyuanchen/cropper#600]
Hello,

When I rotate my image, I would like to keep my canvas size (with my aspect ratio).

Before click on "rotate"
![screen](https://i.gyazo.com/97693ca770c04a62b3352cb837ecf23b.jpg)

After rotate 90deg
![screen](https://i.gyazo.com/88230602576c30e4cd29af7db47ec471.png)

How can I keep the proportions please ?

**Comment by fengyuanchen** [comment]
What you want only available in view mode 0 (set `viewMode` option to `0`).

**Comment by oktapodia** [comment]
Ok thanks for your answer, but the size of the canvas doesn't change, can we automatically switch this one ?

example : 

![screen](https://i.gyazo.com/5c1a9c73cae73522d9a6fc4a651c31ef.png)

**Comment by fengyuanchen** [comment]
Not support this.

**Comment by oktapodia** [comment]
Ok, can you give me some tips about this feature please ? I will make a PR

**Comment by fengyuanchen** [comment]
I think it is really unnecessary to do this as the cropper already supports zoom and move for viewing the whole image.

**Comment by penafo** [comment]
+1 for this issue.

Been a couple of hours working on Cropper ... I'm giving up because of this.

If it gets rotated, everything shoud rotate also.

**Comment by ndtreviv** [comment]
I agree with @fengyuanchen . You don't need this. Zoom out, adjust the crop box size to reflect this. I think the issue stems from the fact that you're trying to size the container to the same aspect ratio as your  picture.

**Comment by ajaykumarj53** [comment]
how can apply some condition to crop box on rotate it should rotate with actual size correct...!
other wise after rotating i am getting some part of the image as getting crop by default with rotate also
