### ISSUE TITLE
Zoom in & Zoom out with slide bar

### ISSUE THREAD

**Issue by Five-stars-Coffee** [fengyuanchen/cropper#601]
Hi, All
It might not be a proper place to have this question, but I still want to ask that if someone has experience to do zoom in & zoom out the image with slider bar. 

I just play around with $().cropper.(zoom, 0.1) function and it just supports wheel zoom in & zoom out.

Now, I am trying to use
`<input id="zoomslider" class="zoomslider" type="range" min="0" max="100.00" step="1" ng-model="selectedRange">` 
to control zoom in & zoom out.

![screen shot 2016-02-01 at 7 33 37 pm](https://cloud.githubusercontent.com/assets/3260442/12712229/0634fcd4-c91b-11e5-8f79-e3ba13e23ab8.png)

I grab value from the above and run in angular scope.$watch 

```
scope.$watch('selectedRange', function(delta){

     current_value.push( delta );      
     delta = current_value[current_value.length - 2] < delta ? -1 : 1;
     element.cropper('zoom', -delta * 0.1);
});
```

In the option, I put zoom function like below:

```
$().cropper({
  zoom: function (e) {

	var imageData = $scope.cropper.first('getImageData');
	var zoomLevel = e.oldRatio;

	if (e.ratio > 3) {
	     e.preventDefault();
	     $scope.cropper.first('zoomTo', 3);
	}

	if (e.ratio < 1) {
	        e.preventDefault();
		$scope.cropper.first('zoomTo', 1);
	}
    }
});

```
 
However, the result is not accurate. 

I put two images to show the ratio I get

![screen shot 2016-02-01 at 7 43 38 pm](https://cloud.githubusercontent.com/assets/3260442/12712406/3f912880-c91c-11e5-8fff-39f93828245f.png)

![screen shot 2016-02-01 at 7 44 05 pm](https://cloud.githubusercontent.com/assets/3260442/12712411/441e0e86-c91c-11e5-8134-0bcd818f6afa.png)

So, I am wondering that is there any better way to to this instead of using wheel and button to control zoom in & zoom out. Any helps or any hints would be appreciated.

Best regards

**Comment by fengyuanchen** [comment]
It seems nobody answer this. I suggest you to ask help on the StackOverflow.
