### ISSUE TITLE
get the full image as blob

### ISSUE THREAD

**Issue by macarthy** [fengyuanchen/cropper#602]
How can you get the full image as blob? Not the cropped image, the full image. Is there an event created when the image is changed ?

Thanks

**Comment by fengyuanchen** [comment]
Just use the `XMLHttpRequest` API to load blob:

```js
var xhr = new XMLHttpRequest();

xhr.onload = function () {
  var blob = this.response;
};

xhr.open('get', 'paht/to/image.jpg');
xhr.responseType = 'blob';
xhr.send();
```

> https://developer.mozilla.org/zh-CN/docs/Web/API/XMLHttpRequest
