### ISSUE TITLE
Reuse of image data instead of loading again

### ISSUE THREAD

**Issue by Ralphilius** [fengyuanchen/cropper#603]
Can we reuse image data in `img` object rather than re-downloading it again for `cropper` rendering? I have an image with very big size and I thought it would increase the speed if we can reuse the image data being loaded somehow. I am not a JS expert, so please let me know if this is not a feasible workflow. I dynamically appended image src as below.

    $('#the-picture').attr("src",url);
    $('#the-picture').imagesLoaded( function() {
        picture.cropper({
            aspectRatio: 1 / 1,
            viewMode: 3,
            scalable: false,
            checkCrossOrigin: false,
            crop: function(e){
            }
        });
    });

**Comment by fengyuanchen** [comment]
Maybe what you need is set the `checkOrientation` option to `false`.

**Comment by Ralphilius** [comment]
I checked Network in Chrome. It's still having 2 network calls. One after I set `src` image, one after `imagesLoaded` got called. Is there anyway we can utilize the data from 1st call so that we won't need to call it twice?

**Comment by fengyuanchen** [comment]
A cropper requires at least two images.
