### ISSUE TITLE
How to get teh cropped canvas toDataURL?

### ISSUE THREAD

**Issue by Win10Developer** [fengyuanchen/cropper#604]
I have a working WCF service in my ASP NET website which I can use to send a canvas 'toDataURL' image from my existing pages. Is it possible in javascript to turn a getCroppedCanvas into the same? 

        var service = new MYSERVICE.UploadService();
        var image = $().cropper('getCroppedCanvas').toDataURL("image/png");
        image = image.replace('data:image/png;base64,', '');
        service.GetData(image, onSuccess, null, null);

**Comment by Win10Developer** [comment]
function run() {
        var service = new CardsWCFAjax.UploadService();
        var canvas = $().cropper('getCroppedCanvas');
        alert('got here 2');
        var image = canvas.toDataURL('image/png');
        alert('got here 3');
        image = image.replace('data:image/png;base64,', '');
        alert('got here 4');
        service.GetData(image, onSuccess, null, null);
        alert('got here anyhoo');
    }

The code above runs to the line **'got here 2'** but doesn't get to the line **'got here 3'**
So the canvas variable canvas seems to be being set, but when I call **toDataURL('image/png')** 
the javascript doesn't work. Anybody used 'toDataURL' on the cropper yet? Thanks in advance for any help...

**Comment by fengyuanchen** [comment]
Read the note about how to call a method of Cropper first: https://github.com/fengyuanchen/cropper#methods

**Comment by Win10Developer** [comment]
Thanks for your reply, it still isn't making sense to me though (I'm more dot net than javascript I'm afraid). How can I put the 'toDataURL' string into a text box using javascript, do you have a simple example anywhere? When I debug my javascript and hover over the variable to which I have assigned canvas.toDataURL, it just shows '_proto_'. I know I'm missing something but if anyone has a simple javascript call to show how I can get the dataURL text into a text box I would be eternally grateful!
Thanks again

**Comment by Win10Developer** [comment]
Got it, I was using *png file extension, works now with jpeg. Many thanks
