### ISSUE TITLE
setData / initial crop incorrect if it is out of the bounds of the view

### ISSUE THREAD

**Issue by Manuel-S** [fengyuanchen/cropper#606]
A simple example:

    <div style="width: 600px;">
        <img style="max-width: 100%" src="image.jpg" alt="">
    </div>
    <script>
        var coords = {
            x: -100,
            y: 0,
            width: 800,
            height: 450
        };
        var cropper = new Cropper(document.getElementsByTagName('img')[0], {
            aspectRatio: 800 / 450,
            data: coords,
            built: function(){if(this.cropper.getData().x != coords.x) alert('crop has been altered');}
        });
    </script>

Cropper does not display that crop, instead it moves the crop box into the viewbox. Is this by design? My expectation was that after setData and getData, my data actually stays invariant.

**Comment by Manuel-S** [comment]
ugly workaround:

        function zoomCropIntoView(cropper){
                if(cropper.getData().x != coords.x) {
                    cropper.zoom(-0.1); cropper.setData(coords);
                    setTimeout(zoomCropIntoView, 1000 / 60, cropper);
                }
                else if(cropper.getData().y != coords.y) {
                    cropper.zoom(-0.1); cropper.setData(coords);
                    setTimeout(zoomCropIntoView, 1000 / 60, cropper);
                }
            }

I would really appreciate if cropper could handle this natively, though.

**Comment by semmais** [comment]
2.2.5 has the same bug

**Comment by fengyuanchen** [comment]
Just because the crop box always within the image container.
