### ISSUE TITLE
Allowing image to zoom out smaller than the crop box

### ISSUE THREAD

**Issue by Schlitzhor** [fengyuanchen/cropper#607]
By far the best cropper plugin I've found, but I am having trouble with image zooming. I can zoom in and out, but the image will never resize to be smaller than the crop box outline. I have gone through your example source code and can't figure out why my image has a minimum zoom size.

Is there a css property or cropper option I am missing?

```js
this.$profileImageCrop.cropper({
  aspectRatio: 1,
  minCropBoxWidth: 512,
  minCropBoxHeight: 512,
  guides: true,
  highlight: false,
  dragCrop: true,
  cropBoxMovable: true,
  cropBoxResizable: true,
  responsive: true,
  background: false,
  preview: '.img-preview'
});
```

**Comment by fengyuanchen** [comment]
As of v2.0.0, you can set the `viewMode` option to `0`.

BTW, The `minCropBoxWidth` and `minCropBoxHeight` are relative to the page, not the image.

**Comment by hanky** [comment]
But in `viewMode` 0 the cropbox does not snap to image borders. Is it possible to start resizing the cropbox when it becomes the same size as the image during zooming out in `viewMode` 1?

**Comment by fengyuanchen** [comment]
```js
absoluteCropBoxWidth = cropBoxData.width * (canvasData.width / canvasData.naturalWidth);
```

**Comment by AndyBaird** [comment]
I am having this issue in 3.0.0 with the viewMode set to 0. I cannot zoom out beyond the image size to reveal a transparent background.
