### ISSUE TITLE
Allowing a parameter within the `replace` method to rebuild cropper or not

### ISSUE THREAD

**Issue by zilions** [fengyuanchen/cropper#609]
Sometimes, rebuilding the entire cropper is not 100% nessesary when using the `replace` method. 

For example, if I wish to apply a filter to my image and then re-add that image back into the cropper, I do not want that user to lose their zoom, flip, crop settings that they had set.

Is it possible to currently do this without saving every single setting that they had set and then reapplying them all upon build?

**Comment by fengyuanchen** [comment]
Good idea. I will add this soon. Thanks~

**Comment by zilions** [comment]
Looks like your commit will only work if a preview is in use. What about for other situations where a preview is not in use at all for that particular cropper?

**Comment by fengyuanchen** [comment]
Please trust me if you don't know how jQuery works.

**Comment by zilions** [comment]
I understand jQuery perfectly well. I tested your master version (with your latest commit), and it did not work for my example. My cropper does not have a preview, therefore when trying to use `this.$preview.find('img')`, it throws an error since it cannot find `img` of `undefined`.

Every single cropper must have a container, therefore when trying to find `img` within `$container`, there will never be an error thrown.

Have tested it on my end with all the examples I could come up with, and it works perfectly.

**Comment by fengyuanchen** [comment]
I know why, you should call the `replace` method after built for this case. If not, `this.$preview` will be undefined.
