### ISSUE TITLE
Multiple croppers, one image object

### ISSUE THREAD

**Issue by mirago** [fengyuanchen/cropper#611]
Hi, I was wondering whether it's possible to have multiple croppers but with one image object?

What I mean by this is I have a photo uploader where a user can upload up to 10 images. Each image can be cropper. They select an image by clicking on it's thumbnail and on click it updates the image src with originals image src that they clicked. This leads to cropper not recognise which image it's editing and  therefore it doesn't work. 

The easiest way is probably to load all images and just hide/show the correct one, but I was wondering if there are any other ways?

Please let me know if you need any more information in order to understand what I'm trying to do.

**Comment by fengyuanchen** [comment]
It is possible to recognize the images by their indexes. This is not a problem of Cropper exactly.

**Comment by lithstud** [comment]
Ok, thanks. Happy to close this
