### ISSUE TITLE
Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by lithstud** [fengyuanchen/cropper#615]
Hi,

When I pass an image object which has its source a blob url, I get this error. "Offset is outside the bounds of the DataView"
I'm not sure whether this is issue with this plugin, but maybe you have an idea of what is going wrong? On the demo website I can see that you have blob example working..
![screen shot 2016-02-19 at 16 20 54](https://cloud.githubusercontent.com/assets/12952983/13181463/32bf2672-d725-11e5-83c0-19814d76992c.png)

**Comment by fengyuanchen** [comment]
I don't know why, you might have to set the `checkOrientation` option to `false`.

**Comment by lithstud** [comment]
Hmm, that removes this error. But what happens is that the cropper does not find the image now. If I do not activate cropper, and just display the image, it will display it as per the picture above with no problems. If I activate cropper, it will activate it, but the image will not be found and the cropper will be empty. Any ideas?
