### ISSUE TITLE
overriding SCSS variables

### ISSUE THREAD

**Issue by the-mo** [fengyuanchen/cropper#618]
Is there a reason why the _variables.scss isn't written in a way that makes it easier to simply change the variables in a project without having to override them after compilation?

It would make it so much easier if cropper's variables would have a _!default_ flag so that if someone loads the cropper scss files into their project, they only need to set the used variables (mainly $color-brand) if they want to simply change the color or media queries.

**Comment by fengyuanchen** [comment]
Thank you. I will add it soon.
