### ISSUE TITLE
Add the "destroy.cropper" event

### ISSUE THREAD

**Issue by troygrosfield** [fengyuanchen/cropper#620]
There are very reasonable cases where it would be nice to listen to the ``destroy.cropper`` event so the user can do additional cleanup when a cropper is destroyed.  Would be a trivial change.  Just trigger the ``destroy.cropper`` event after the ``.destroy()`` method is called.

**Comment by fengyuanchen** [comment]
I will think about this. Thanks~

**Comment by fengyuanchen** [comment]
It is unnecessary to add this as the destroy process is synchronistical。
