### ISSUE TITLE
zoomOnTouch not working

### ISSUE THREAD

**Issue by andreicek** [fengyuanchen/cropper#621]
We are experiencing problems while using cropper with [jquery/PEP](https://github.com/jquery/PEP). The versions used are `cropper 2.3.0` with `PEP 0.4.1`.

The cropper is initialized with `zoomOnTouch: true` option set but zoom on touch will not zoom on image. This did work with `cropper 0.9.3`. Other methods of zoom work on both the latest version and `0.9.3`.

cc @DarkoKukovec

**Comment by fengyuanchen** [comment]
Please check if it is a problem of your own code or the PEP or the Cropper.

**Comment by andreicek** [comment]
HI!

Thanks for your response.  After a few days (sorry for a delayed response) of debugging we came to the conclusion that indeed it was an error on our side - but the mystery still persists. Can you please explain how do you ignore `pointerdown` and `pointerup` when zooming since they don't have the `touches` property required for zooming in your implementation.

The issue we have is that both (touch and pointer) events get triggered and enter `cropStart`. Since `pointerdown` happens after the `touchstart` and it doesn't have `touches` property it falls back to the `ACTION_MOVE` action. This won't happen in the example in libs repo (we added jquery/PEP to the example and that works A-OK).

As a quick-fix we removed pointer event listeners. (line 49 to 52 in `dist/cropper.js`)

```JavaScript
  // Events
  var EVENT_MOUSE_DOWN = 'mousedown touchstart';
  var EVENT_MOUSE_MOVE = 'mousemove touchmove';
  var EVENT_MOUSE_UP = 'mouseup touchend touchcancel';
```

Thanks in advance.
