### ISSUE TITLE
With set movable: false, zoomable: false cropp box is moved outside image

### ISSUE THREAD

**Issue by grzesiekp1308** [fengyuanchen/cropper#622]
When I try to cropp image with set movable: false, zoomable: false cropp box is moved outside image. Returned width value is one pixel greather than image width. I used latest version of cropper.js 2.3.0 and construction:
```js
crop: function(e){console.log(e.x + ' ' + e.y + ' ' + e.width + ' ' + e.height) }
```
image resolution is: 
```xml
w: 3072 h: 2304
```
and cropped values:
```xml
-0.9400244798042685 548.8050917992658 3073.8800489596088 1229.5520195838435
```

**Comment by fengyuanchen** [comment]
Do you set the `viewMode` option to `1` or more?

**Comment by grzesiekp1308** [comment]
viewMode option change to 2 solved issue
