### ISSUE TITLE
Chrome 48: cropper('getCroppedCanvas').toDataURL is not a function

### ISSUE THREAD

**Issue by wcatron** [fengyuanchen/cropper#624]
I'm receiving an error with Chrome 48.0.2564 only and its saying toDataURL is not a function. I'm assuming this is an issue with the getCroppedCanvas although I'm not able to recreate this locally. Are others getting this kind of issue?

**Comment by fengyuanchen** [comment]
It is all fine in my Chrome 48, just check your own code to fix it.

**Comment by vinnymac** [comment]
@wcatron working fine for me. Make sure that when you call `$("#my_selector").cropper("getCroppedCanvas")` the return value is a `Canvas Element`

It should look like, `<canvas width="1024" height="576">`

If it really is your browser just do a test.
Open up your console and type `document.createElement("canvas").toDataURL`, the return value should be the specified function, or will throw an error as you say.

**Comment by ChillerPerser** [comment]
Had the same problem.
Changed "autoCrop" to true and it returns the canvas instead of an image.

**Comment by wcatron** [comment]
I finally figured out the underlying issue. `getCroppedCanvas` only works if you are actually cropping, which explains why setting "autoCrop" to true would fix the issue for some. However I wanted the user to be able to not crop their image if they wanted and used the "clear"/"crop" method to toggle the crop feature. Unfortunately that means you can't save the image if you're not cropping it.

**Comment by tingfeng-key** [comment]
I also encountered this problem, because the object is not to find the object Jquery
