### ISSUE TITLE
plaid man's shirt bug

### ISSUE THREAD

**Issue by siderisltd** [fengyuanchen/cropper#625]
This is very intersting. I've found incorrect behaviour when i tested the demo functionality with a personal image. When I crop the selected area from the image there is a strange effect only on the colors of the shirt. http://postimg.org/image/sso46son1/ this is a link to the picture i was testing. The issue appears while moving the selected area and when the area is placed with some delay it is fine. But when i try to get the cropped canvas the visualisation is still broken. I think it is okey when it is saved but i will be glad if I can help. 
PS: Your cropper is awesome thanks :)

**Comment by fengyuanchen** [comment]
This is not a problem as all images has this behavior when moving (browser render behavior).
