### ISSUE TITLE
Blank space randomly at top of cropper

### ISSUE THREAD

**Issue by mardanlin** [fengyuanchen/cropper#627]
On some images, the image goes to the top of the cropper. On some, it goes to the middle, and on others, there is just an unnecessary amount of blank space at the top of the cropper above the image.

I can provide screenshots if you need them, but I assumed other people had this problem and had developed workarounds.

**Comment by fengyuanchen** [comment]
Why not read the documentation first? 
Just set the `viewMode` option to `1`!
