### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by sctaix** [fengyuanchen/cropper#629]
![fullsizerender](https://cloud.githubusercontent.com/assets/15074386/13601297/5479a5a2-e572-11e5-99b4-fe02c40781eb.jpg)

Move cropbox makes strange line on image. It does not effect to cropping but so annoying.

Tested on iPhone 6s safari browser.

**Comment by fengyuanchen** [comment]
I think this may be the problem of your browser.
