### ISSUE TITLE
Preview isn't working

### ISSUE THREAD

**Issue by DonFelipe** [fengyuanchen/cropper#63]
I can't find any information about what bootstrap version may or may not be compatible with cropper but it seems like any version prior to Bootstrap 3.2 causes problems in terms of letting the preview image and/or containers move and disappear horizontally to the left ultimately changing its format (widescreen to square to portrait into nirvana). Any idea what styles may cause this?

You can easily test this setting up a very basic HTML file and then switching between the 2 different bootstrap css files.

**Comment by damienvaz** [comment]
Thanks for the information fengyuanchen ! :D
