### ISSUE TITLE
Minimum crop area option

### ISSUE THREAD

**Issue by Jordan4jc** [fengyuanchen/cropper#630]
Is there an option or set of options I can use so that if an image is larger than my minimum width for the crop I want that the user can then scale that crop box up but cannot scale it smaller than that minimum?

And if an image is smaller than my minimum width for the crop then it will just be full and the user can't scale at all forcing them to crop the entirety of the image?

When I set `minCropBoxWidth` the crop box is always as big as the image even if the image is way bigger than my crop width I want set.

**Comment by fengyuanchen** [comment]
Reference #589.

**Comment by sotebuy** [comment]
If you are presenting a responsive cropper widget it is not logical to give the minCropBoxWidth realtively to the page and not the image. As when you change the page size dynamicly u must generate a new image for every device which is a performance killer for the server-side application. A better approach is presented in Jcrop http://deepliquid.com/content/Jcrop_Sizing_Issues.html where u can give the real size of the image as parameter. Thanks to this the crop knows how to calculate width and height and the position of the crop area.
