### ISSUE TITLE
Image doesn't rotate while I fire the rotate event in andriod wap page

### ISSUE THREAD

**Issue by jacob-xie** [fengyuanchen/cropper#631]
Hello~Thanks for you great plugin!
Here I came to a problem: I'm using a mobile phone and set up the cropper, and there is a button to rotate the image, but when I click the button to rotate the image , the image just change its place or scale itself, not rotating itself. But when I crop the image and create a new one, it is an rotated image.That means it rotate successfully, but it would not rotate while editing.

Would you please solve the problem for me? Thanks a lot.

**Comment by fengyuanchen** [comment]
Any questions about how to use Cropper or any other open source projects, please follow the documentation or ask for help at StackOverflow.
