### ISSUE TITLE
Constraining crop box to within original image

### ISSUE THREAD

**Issue by cainy393** [fengyuanchen/cropper#635]
From what I can understand none of the options allow you to constrain the crop box to be within the original image. In my particular case I actually only want to constrain the bottom 3 sides and allow the top side to go higher than the image but this is a slightly more niche use case. I expected there to be an option to totally constrain the crop box within the image though. To not allow the crop box to be larger than the image and to not allow any transparent areas around the image.

Would there be much interest if I were to make a pull request to support this?

**Comment by islemaster** [comment]
I think [setting the option `viewMode` to 1 already does this](https://github.com/fengyuanchen/cropper/blob/v2.3.0/README.md#viewmode), although if you expose the image rotation controls the constraint no longer applies.

**Comment by wintondeshong** [comment]
I believe this item can be closed. Just verified that @islemaster is correct in viewMode=1 creating this behavior.

**Comment by cainy393** [comment]
Yes that behaviour is correct. Although in my use case rotation controls are exposed and so there is still an issue. 

There should be the ability to use viewMode=1 with rotation.
