### ISSUE TITLE
New in JavaScript want to implement cropper.js

### ISSUE THREAD

**Issue by MohammedJaved** [fengyuanchen/cropper#636]
Hi I am new in javascript i want to implement cropper.js in a modal pop. but I can't understand where to start to implement this plugin. I see examples in cropper.js bundle not understand which part of codding i need to implement and place in my website.

Can someone please explain how to do it or install it step by step. 

Please help me!!!

Thanks,
M

**Comment by fengyuanchen** [comment]
Why not follow the getting started guide first?
