### ISSUE TITLE
Cross origin error

### ISSUE THREAD

**Issue by vamsi0391** [fengyuanchen/cropper#640]
Hi, I'm using this cropping plugin in AngularJS, i made some changes and implemented in my controller in AngularJS the cropping is working fine,  but for some images I'm getting cross origin issues. I'm getting images from Amazon cloud services.

**Comment by vamsi0391** [comment]
How to solve cross origin issue

**Comment by SoundLogic** [comment]
This is a CORS issue and not a cropper issue - the proper place for this question is StackOverflow - I'm sure similar questions have been answered there before.

**Comment by vamsi0391** [comment]
yes, and I'm testing the cropping in safari browser then the cropper is moving quickly without control and cropping is not performing.

**Comment by fengyuanchen** [comment]
@vamsi0391 About your problem about Cropper, please provide an online demo for testing. If you can reappear it, then open a new issue and provide the demo URL.

**Comment by vamsi0391** [comment]
ok thank you
