### ISSUE TITLE
require Cropper.js with Webpack

### ISSUE THREAD

**Issue by FoxWhite** [fengyuanchen/cropper#641]
Hello! Has anyone managed to require cropper.js as a module using webpack? I'm quite new to webpack so the only way I managed to do this is by getting rid of the wrapping function and requiring cropper as ```var Cropper = require 'imports?$=jquery!exports?Cropper!cropper'```
but I obviously don't like how I did this as I don't want to change the vendor code

**Comment by fengyuanchen** [comment]
You can reference the line 40 of this file: https://github.com/fengyuanchen/photo-editor/blob/gh-pages/gulpfile.js

**Comment by renatoagomes** [comment]
Link is down :(

**Comment by fengyuanchen** [comment]
```js
import Cropper from 'cropperjs/dist/cropper.esm';
```
