### ISSUE TITLE
Issue with 'Latest Release' zip

### ISSUE THREAD

**Issue by kennmyers** [fengyuanchen/cropper#644]
I downloaded the latest release zipped files linked in the main README and tried to implement cropper on an image tag (basically ~~```$img = '<img ...>'```~~```$img = $('<img ...>')``` and then ```$img.cropper({...})```). I kept getting an error that said something like 'TypeError $img.cropper is not a function'.

I did some googling and found [this thread ](https://github.com/fengyuanchen/cropper/issues/516) where someone had a similar error and after they tried fengyuanchen's rawgit links their code worked fine. Same thing happened to me. The error went away. Everything works beautifully now. So I think there might be something wrong with the js files in the zip.

**Comment by kennmyers** [comment]
In that thread I linked, sbsomya speculates it was either his jquery or cropper. I tested it with the version of jquery fengyuanchen uses (1.11.3) as well as v2.2.2 and it continued to work for both of them so I do not think it is a jquery issue.

**Comment by fengyuanchen** [comment]
The `$img = '<img ...>'` is not equal to `$img = $('<img ...>')`.

**Comment by kennmyers** [comment]
My mistake, I've edited that in my above comment, my code did have ```$img = $('<img ...>')```

**Comment by fengyuanchen** [comment]
Were you include the cropper.js into your page and run the code after that?

**Comment by kennmyers** [comment]
I know what sbsomya and I were doing wrong >__< . I think we were both accidentally downloaded the cropperjs files and tried implement cropper(jquery). Until your comment I didn't even realize there were two distinct libraries. Sorry about all that
