### ISSUE TITLE
getCroppedCanvas + Google Nexus 6 issue

### ISSUE THREAD

**Issue by Nijagun** [fengyuanchen/cropper#645]
Hi,

A great plugin for cropping, thanks for that. But the issue I am facing is that I am unable to get the cropped image on Nexus 6 device (android 5.0 - google chrome browser). Modal appears with a white background without the cropped image. A quick help is needed.

Thank you,
Nijagun.

**Comment by fengyuanchen** [comment]
I have not idea about this. Maybe you should limit the size of your original image to avoid any memory overflow.
