### ISSUE TITLE
Constantly getting Offset is outside the bounds of the DataView error

### ISSUE THREAD

**Issue by canpoyrazoglu** [fengyuanchen/cropper#646]
Hello,

I've just downloaded the latest version of cropper. I've got a `div` and inside that I've got an `img` object that I want to crop. When I try to initialize cropper:

         `$(image).cropper({
                        aspectRatio: 1,
                        crop: function(e){
                            debugger;
                        }
                    });`

I'm getting `Uncaught RangeError: Offset is outside the bounds of the DataView` in my browser's console (latest Chrome). My image displays normally, with no cropping support as if there's no cropper.

How can I solve it?

**Comment by canpoyrazoglu** [comment]
Nevermind, it was an error at my side. Fixed it.

**Comment by ricpumanes** [comment]
hi @canpoyrazoglu , how were you able to fix this issue? I ran into a similar issue. I'm using the latest Firefox. It works great in Chrome though.

**Comment by canpoyrazoglu** [comment]
> hi @canpoyrazoglu , how were you able to fix this issue? I ran into a similar issue. I'm using the latest Firefox. It works great in Chrome though.

@ricpumanes I've quit that project long ago, but as far as I remember I ended up changing many things with the CSS, as the cropper area was breaking very easily.

**Comment by fengyuanchen** [comment]
Recommands to use [jquery-cropper](https://github.com/fengyuanchen/jquery-cropper) which may have not this problem.
