### ISSUE TITLE
Unable to initialize cropper when first tab is showed

### ISSUE THREAD

**Issue by maxi032** [fengyuanchen/cropper#647]
I know that this is not really an issue that has to to with the cropper but I am trying to initialize the cropper when the first bootstrap3 tab is showed and i am doing
<pre>
$(document).ready(function () {
		$('a[data-toggle="tab"]:first').on('shown.bs.tab', function (e) {
			mycrop(e, $(this));
			console.log("first");
		});
...
</pre>
the console.log is not reached. The initialization is done only when I click on the tab's link but I need the cropper visible when the tab is visible/active

**Comment by fengyuanchen** [comment]
As the first tab is shown by default, so the `shown.bs.tab` will not been triggered any more. You should initialize the cropper directly (outside of the `shown.bs.tab` event handler)
