### ISSUE TITLE
Changing aspect ratio removes upload image

### ISSUE THREAD

**Issue by boulepick** [fengyuanchen/cropper#648]
Good day all,
i'd like to report an issue that i came across testing one of your examples. the issue is when i switch the aspect ratio on an uploaded image from my computer, it removes the picture and reload any image source that was previously there. I looked at the code and i see that on switching aspect Ratio let's say from 2:3 to free hand it will destroy the canvas and reload with the option 2:3 but the problem it does not reload the image that i had uploaded so i have to re-upload that picture again.
Is there a way to implement the feature without destroying the current picture?

Great work

**Comment by fengyuanchen** [comment]
Example is just example. For you problem, just cache the url of your uploaded image, and restart the cropper with a new aspect ratio.
