### ISSUE TITLE
cropping lines missing 

### ISSUE THREAD

**Issue by vamsi0391** [fengyuanchen/cropper#649]
Hi, I'm using this cropping plugin in angular, my image view is in a modal. when i click a button then a modal with image will open but here i'm missing cropping lines, so that image is not cropping and saving. please give me any solution. I have included all css files and js files.

**Comment by vamsi0391** [comment]
![screen shot 2016-04-01 at 4 29 45 pm](https://cloud.githubusercontent.com/assets/16221924/14205191/00b943ba-f827-11e5-888e-8ad8183ffe1a.png)

**Comment by vamsi0391** [comment]
In this way it is not appearing lines

**Comment by vamsi0391** [comment]
I'm getting error as, TypeError: $image.on(...).cropper is not a function. please help to get out of this error.

**Comment by fengyuanchen** [comment]
I guess you were using a wrong lib. [Cropper](https://github.com/fengyuanchen/cropper) is not equal to [Cropper.js](https://github.com/fengyuanchen/cropperjs).

**Comment by vamsi0391** [comment]
Thanks for reply. Actually I'm implementing the same not a different one, I
found that when a page is initially loading with image it is working fine,
now I'm implementing it in angular. I have a scenario like this, my page
will load with 10-10 records, I click on one of the record then it is
redirected to other HTML page with image URL  in cookies then cropping is
working and saving fine. But now I'm implementing to show cropping in a
modal then the cropping lines are not loading, then I kept timeout function
at ($image.on(...).cropper(options)) to one second then the cropping lines
are visible and cropping is working, but if i click on another
image(another record) for cropping, the old one is remaining in cropping,
without changing to new image.

**Comment by fengyuanchen** [comment]
You should read this note if you are using cropper in a modal:

https://github.com/fengyuanchen/cropper#notes

**Comment by vamsi0391** [comment]
Hi, please help me how to avoid cross origin error in jquery plugin.

**Comment by fengyuanchen** [comment]
@vamsi0391 https://github.com/fengyuanchen/cropper#notes
