### ISSUE TITLE
window.resize event handling is not correctly removed after clear()

### ISSUE THREAD

**Issue by timing** [fengyuanchen/cropper#650]
In my usecase, when a user is done cropping, the result is saved on the server. After this the image element and all the related elements from cropper are removed. Before that I call .cropper('clear') on the image to clean up all the events etc. However when I resize my browser window after this I get the uncaught typeerror (as in issue: #292).

I looked at the source and I worked around this by calling $(window).off('resize.cropper'); manually before removing the elements.

**Comment by fengyuanchen** [comment]
The `clear` method just hide the crop box exactly. What you want may be the `destory` method.

**Comment by timing** [comment]
Ah you are right, sorry about that.
