### ISSUE TITLE
setCropBoxData on initialization problem

### ISSUE THREAD

**Issue by noatak** [fengyuanchen/cropper#651]
If i set the CropBox size on initialization like this:
```
$(function() {
  var $toCrop = $('.img-container > img');
	
  $toCrop.cropper({
    autoCrop: true,
	strict: true,
    guides: true,
    highlight: true,
    dragCrop: false,
    cropBoxMovable: true,
    cropBoxResizable: true,

    built: function () {
      $toCrop.cropper('setCropBoxData', { left: 1, top: 1, width: 300, height: 200 });
    },


    crop: function (e) {
    
        $dataX.val(Math.round(e.x));
        $dataY.val(Math.round(e.y));
        $dataHeight.val(Math.round(e.height));
        $dataWidth.val(Math.round(e.width));
        $dataRotate.val(e.rotate);
        $dataScaleX.val(e.scaleX);
        $dataScaleY.val(e.scaleY);
      }
  });
});
```

The initial Values of e.height and e.width are values that are always 80% of the original image - the default of autoCropArea. After moveing or resizing the CropBox the values are correct.

If i set autoCrop: true and autoCropArea: 0.5 the initial values of e.height and e.width are correct.

**Comment by fengyuanchen** [comment]
What the Cropper version you were talking about? The `strict` and `dragCrop` options had been removed on the latest version.

**Comment by noatak** [comment]
I'm using 2.3.0. You can easily reproduce the problem. Just set in your demo code on http://fengyuanchen.github.io/cropper/ the cropbox dimensions to absolute values on initialization and see what values are displayed for width and height on the right side of the demo picture.

**Comment by fengyuanchen** [comment]
1. The size of crop box should not large than the container.
2. Take care of the `viewMode` option's four available values.
