### ISSUE TITLE
Responsive option does not resize Cropper when window gets smaller.

### ISSUE THREAD

**Issue by Cabskee** [fengyuanchen/cropper#653]
CSS Code:
`

		#uploadPreviewParent {
			width:100%;
		}
		#uploadPreviewParent img {
			width:100%;
		}
`

HTML Code:
`<div id="uploadPreviewParent"><img id="uploadPreview" /></div>`

JS Code:
`

	$('#uploadPreview').cropper({
		aspectRatio:100/41,
		zoomable:false,
		rotatable:false,
		background:false,
		zoomOnTouch:false,
		zoomOnWheel:false,
		restore:false,
		responsive:true,
		built:setMaxWidth
	});
`

When the window is resized larger (960x540 -> 1920x1080), the Cropper properly resizes. When the window is resized smaller (1920x1080 -> 1080x720), the Cropper stays the original size.

Nothing changes if I set "restore" to true. If I turn responsive to false, the Cropper does not change size at all.

**Comment by fengyuanchen** [comment]
Maybe something was wrong in your code. I have not time to check it for you. Just the follow the [examples](https://github.com/fengyuanchen/cropper/tree/master/examples).

**Comment by Cabskee** [comment]
The supplied code is the only code on the page. I have checked all of the examples and my code is practically copy & pasted from there.

**Comment by fengyuanchen** [comment]
Add the `>` selector and try again:

```
#uploadPreviewParent > img {
    width:100%;
}
```
