### ISSUE TITLE
Prevent new crop-selection when clicking outside the selection, but within the image

### ISSUE THREAD

**Issue by Airrudi** [fengyuanchen/cropper#655]
I'm working with a fixed size crop selection, which initializes on load and is not resizable. 

When I click outside of the selection, My cursor changes to a crosshair and I can create a new crop selection. The dimensions of this new selection (I can resize it) can exceed the dimensions of the initial selection. I want to disable  the possiblity to create a new selection (only moving the initial selection is my goal) or the possiblity to resize the new selection.

Thnx!

**Comment by fengyuanchen** [comment]
Just set the `dragMode` option to `'move'`.

**Comment by ngochangjelly** [comment]
Hi @Airrudi  Could you solve this issue yet? I have the same issue but still haven't figured out
