### ISSUE TITLE
images with a long height get flipped 

### ISSUE THREAD

**Issue by o7abeeb** [fengyuanchen/cropper#657]
@fengyuanchen why images with long height get flipped ?? 

![2016-04-11_15-42-31](https://cloud.githubusercontent.com/assets/16590992/14427230/69020a9c-fffc-11e5-9353-d2b8dcfd5047.png)

![2016-04-11_15-43-13](https://cloud.githubusercontent.com/assets/16590992/14427235/6ed1818c-fffc-11e5-8257-181dcb9944b9.png)

**Comment by fengyuanchen** [comment]
Read this: https://github.com/fengyuanchen/cropper#checkorientation

**Comment by o7abeeb** [comment]
@fengyuanchen how can i use it ?
i tried checkOrientation: false and checkOrientation: true
and get the same issue !!

**Comment by fengyuanchen** [comment]
Set `checkOrientation: false` should work. If not, send me the image, I will test it on my browser.

**Comment by o7abeeb** [comment]
@fengyuanchen  here is the image 

![3](https://cloud.githubusercontent.com/assets/16590992/14492536/9c61bc7e-0188-11e6-9048-e9cbae64f67b.jpg)

**Comment by o7abeeb** [comment]
it flipped here too :/ , you can try with any image witch the height is more that the width

eg: width:400px; height: 1500px;

**Comment by fengyuanchen** [comment]
The Exif Orientation value of your image is `8`, which means the image rotate -90 degree. It is incorrect as the image never rotated. The correct value should be `0`.

- [here is a tool for checking Orientation](http://fengyuanchen.github.io/exif/))

**Comment by fengyuanchen** [comment]
You can try this image: http://fengyuanchen.github.io/loader/img/potala.jpg

**Comment by o7abeeb** [comment]
i dont really understand, how can i fix it now ??
your image get flipped too !

**Comment by fengyuanchen** [comment]
In one word, the image you provided has a wrong orientation value, just ignore it.

And in your app, just set the `checkOrientation` option to `false`, no need to do anything else.

**Comment by o7abeeb** [comment]
'' In one word, the image you provided has a wrong orientation value, just ignore it. ''

how can i do it ?

**Comment by o7abeeb** [comment]
hhhhh that will fix it on my pc, what about other user's images like it ??

**Comment by fengyuanchen** [comment]
I will add a note for incorrect Orientation value in the documentation.

**Comment by fengyuanchen** [comment]
Just added: https://github.com/fengyuanchen/cropper#checkorientation

**Comment by wcj343169893** [comment]
I upload a photo, the original vertical screen, but in the box becomes a horizontal screen, also squashed. As shown in Figure
![img_0462](https://cloud.githubusercontent.com/assets/502789/15845330/98daac86-2ca4-11e6-9547-6f85163d27fa.PNG)

**Comment by fengyuanchen** [comment]
@wcj343169893 see #120.
