### ISSUE TITLE
Manual "crop" parameters

### ISSUE THREAD

**Issue by MonteShaffer** [fengyuanchen/cropper#658]
Hi,

I am using the demo as the basic framework.  I enable cropping initially.  That is the original crop box is drawn with this "80%" default, now I want to modify it on the fly.

The object in the demo is $image.cropper ...

With the current zoom, I want to change the crop box by passing (x1,x2,y1,y2) or (x,w,y,h) into the "crop" method, something like this:

```$image.cropper('crop', 0,0,100,100);```

as in 

```$image.cropper('crop', x,y,w,h);```

or maybe 

```$("#image").cropper('crop', 0,0,100,100);```

I don't understand from the documentation how I would do this?  Any ideas?

This would enable me to slightly adjust the crop-box by changing the (x,y,w,h) parameters in the "text inputs" which would be more accurate than a mouse ...

**Comment by fengyuanchen** [comment]
If you want to change the size of crop box, you can try the `setCropBoxData` method.

**Comment by MonteShaffer** [comment]
I am still confused by your "methods"...

Which methods move the canvas?  Which move the cropbox?  "move" or "moveTo" in the documentation, it is unclear which it moves.  And by how much.  Does move/moveTo move the original image (background) in its original units, or based on some current scaling of the zoom and the container window?  This is unclear.

My situation, I have an image that I will do several sequential crops.  First, it is very important that the crop data I store is associated with the original data ... Currently, I am calling "getData" to get this information?  Is that correct?  Or should it be getCropBoxData?  Which one gives me the actual x,y,w,h for the original image?

Once I set the first crop and save the x,y,w,h I want to move the cropbox down to (x,y+h,w,h) which also requires that I move the background image / canvas data... It is unclear how to make this happen.

I see that getCanvasData has the naturalHeight/naturalWidth...

Do I getCanvasData, do some ratio_x and ratio_y manipulation of the naturalHieght/height and naturalWidth/width?  adn then reset the canvasData with set (different object format)?

**Comment by fengyuanchen** [comment]
Sorry for your confusing. Maybe I should improve the documentation to provide more details.

**Comment by tinybigideas** [comment]
+1 for extra documentation. I'm looking to do something similar without success at the moment

**Comment by MonteShaffer** [comment]
So here is my current hack...  notice I have to get the ratio and do some math... it isn't working exactly as expected, when I have some more time, I will hack more.

Hopefully the class can have better documentation and just take care of all of this.

moveWhat:  background-iamge, cropper-box
moveWhere:  x,y (w,h)
moveUnits:  scaled, original

```
var canvasData = $("#image").cropper('getCanvasData');
		//console.log(canvasData);
			var imageH = canvasData["naturalHeight"];
			var imageW = canvasData["naturalWidth"];
			var image_h = canvasData["height"];
			var image_w = canvasData["width"];
			var ratio_h = image_h/imageH;
			var ratio_w = image_w/imageW;

	
	//$("#image").cropper('zoomTo', 0.75);  // zoom level ... this is relative not absolute, 'zoom' is absolute
	//$("#image").cropper('moveTo', 0,0);

	// smart move
		var info = data["crop"];
		var newX = info["x"]-100; if(newX < 0) { newX = 0; }
		var newY = ratio_h * (info["y"]+info["height"]); // if(newX < 0) { newX = 0; }
		//console.log("y: "+info["y"] + " --> newY: "+newY);

//setCanvasData = {"left": canvasData["left"], "top": newY / ratio_h, "width": image_w, "height": image_h};
//console.log(setCanvasData);
		//$("#image").cropper('setCanvasData',setCanvasData);

	//$("#image").cropper('moveTo', 0,newY);
	//$("#image").cropper('move', 0,newY/ratio_h);
		// var nMove = -1*newY + 100;
		var nMove = -1*newY;
	//$("#image").cropper('move', 0,nMove);
		$("#image").cropper('move', 0,-1*info["height"]);
		$("#image").cropper('move', 0,50);
			info["y"] = newY;	
			info["height"] = 150;
		$("#image").cropper('setData',info);
```

**Comment by MonteShaffer** [comment]
The fundamental issue is "relative" vs. "absolute" values.

I can set the new data to one value 

```
$image.cropper('setCropBoxData',nData);

nData
		
left
	
	13.68
top
	
	354.54
width
	
	262.2
height
	
	440.04
```

And immediately after call get data and return an entirely different result.

```
var vData = $image.cropper('getCropBoxData');

vData
		
left
	
	13.68
top
	
	75.95999999999998
width
	
	262.2
height
	
	440.04

```

My container height is 750 x 500, and the crop area is "tall" so the zoom had to be resized.  It gets close, but not exact.  There has got to be some sort of math-calculation errors going on.


The "top" value has changes as the "zoom" level may necessitate this ... I believe this is some sort of bug.

Regardless, there should be some fundamental wrapper functions that give me what I want, and nothing else, regardless of where the current zoom, current canvas location is, if I setCrop to an absolute value based on the actual image, I don't care about the scaled container it is in, I just want it to draw boxes in the correct places.

moveTo and zoomTo are "absolute" values, and it appears all other methods are not.

The logic is mind-boggling.

**CORRECT**
![preview-correct-position](https://cloud.githubusercontent.com/assets/6663327/14967847/d04abcd2-1076-11e6-8614-35aec8d48e25.png)

**INCORRECT**
![preview-wrong-position](https://cloud.githubusercontent.com/assets/6663327/14967848/d04adf00-1076-11e6-8948-d4fff4d8f686.png)

**Comment by fengyuanchen** [comment]
@MonteShaffer Please pay attention to the `viewMode` option: https://github.com/fengyuanchen/cropper#viewmode.

In short, the crop box should always inside the container. In your code, 354.54(crop box's top) + 440.04(crop box's height) = 794.58 > container's height (500).
