### ISSUE TITLE
getCroppedCanvas function doesn't respect declared height

### ISSUE THREAD

**Issue by jexneedls** [fengyuanchen/cropper#662]
![image](https://cloud.githubusercontent.com/assets/14348836/14567144/bf0fc152-0300-11e6-92b6-275c46a9f19d.png)

**Comment by fengyuanchen** [comment]
The real height = width * aspectRatio

**Comment by fengyuanchen** [comment]
So set the `aspectRatio` option to `NaN` and then try again.

**Comment by jexneedls** [comment]
Sorry @fengyuanchen , still not working.

**Comment by fengyuanchen** [comment]
Be sure to keep the same aspect ratio as the crop box!

```
const cropBoxData = $().cropper('getCropBoxData');
const cropBoxAspectRatio = cropBoxData.width / cropBoxData.height;
```
