### ISSUE TITLE
The method “setCropBoxData” can not  set “height” value  bigger than  the Image size of height

### ISSUE THREAD

**Issue by maki077** [fengyuanchen/cropper#664]
When I user this option
               {
                  viewMode: 0,  
		  dragMode: 'none', 
		  autoCropArea: 1,  
		  restore: false,  
		  guides: false, 
		  highlight: false,  
		  cropBoxMovable: false,
		  cropBoxResizable: false,
		  zoomable:false,}

               $image.cropper('setCropBoxData',{
			"left":0,
			"top":0,
			"height":200,
			"width":200
		});
and I want to  use it to resize cropbox; But my image  size of height is 180 ,I could't  crop the canvas with 200*200 when the zoom was 1. Just only was 200*180 to crop.

 Also on the demo website http://fengyuanchen.github.io/cropper/  ,I couldn't drag the cropbox fill out the container with   method  zoomTo(1);

**Comment by fengyuanchen** [comment]
The crop box should inside the container. Isn't is?

Just increase the height of the image container.

**Comment by maki077** [comment]
Thanks, I just set the css properties to solve this problem.
The display was that  the cropper-box  was the same size as container. And the img was inside the container and cropper-box.

**Comment by fengyuanchen** [comment]
Crop box should inside the Container forever!!!
