### ISSUE TITLE
Don't go outside of the image

### ISSUE THREAD

**Issue by NathanVss** [fengyuanchen/cropper#665]
Hello, thank you for this great plugin.
I did'nt found any updated solutions for my problem. I want the cropbox to stay into the image, and never be able to go outside of it, even if the user try to. 
Screenshot : 

http://puu.sh/opcdg/a760679915.png

Any solutions ? 
Thank you.

**Comment by vinnymac** [comment]
Just make the image the size of the container. You can do this in the [demo](http://fengyuanchen.github.io/cropper/) by clicking VM3 (view mode 3).

**Comment by NathanVss** [comment]
Oh ! really great, thank you, it is perfect !
