### ISSUE TITLE
Better Avatar Upload

### ISSUE THREAD

**Issue by BolatovAlau** [fengyuanchen/cropper#667]
Hi all, is Here any examples which shows avatar upload such as in website https://allevents.in
This is the best example i found in internet which uses Cropper.Js 
This website has better functionality of uploading image than the avatar demo 

Here the steps:

1) Here is an input button
![1](https://cloud.githubusercontent.com/assets/14837842/14721095/68081da2-0826-11e6-9a0f-b8324e1c36a8.png)

2) When you click this it asks to choose an image from local files

3) After you choose an image an click 'Ok' button it opens new modal dialog with 'Crop' button
![1](https://cloud.githubusercontent.com/assets/14837842/14721142/a8686640-0826-11e6-9708-4746fd90577b.png)

4) When you click 'Crop' button it opens new Modal with new Buttons
![1](https://cloud.githubusercontent.com/assets/14837842/14721150/b8c984ba-0826-11e6-8c47-6d859da55f68.png)

It's possible to go back by clicking 'back' button

Best Regards

**Comment by daneesv** [comment]
http://stackoverflow.com/questions/12368910/html-display-image-after-selecting-filename
