### ISSUE TITLE
Did't check the checkCrossOrigin option when trying to send a crossOrigin Xhr?

### ISSUE THREAD

**Issue by JounQin** [fengyuanchen/cropper#669]
When I use a crossOrigin image,it works when I disable the browser cache.However, when I enable the browser cache, the xhr gets an error on the console although there's a `onerror` event.

[load xhr](https://github.com/fengyuanchen/cropper/blob/master/src/js/init.js#L70)

So why not pass a param like `checkXhrCrossOrigin` which is different from `checkCrossOrigin` because it has been used in function `clone` to check whether to `addTimestamp` to the url.

**Comment by fengyuanchen** [comment]
Add a timestamp to xhr url will resolve your problem?

**Comment by JounQin** [comment]
Yes,when the response status code was `200 OK (from cache)`,the response header `Access-Control-Allow-Origin` is `0` which was different from `location.hostname`.

**Comment by fengyuanchen** [comment]
I can't reproduce your problem. Maybe the cross-origin image I used was set to `Access-Control-Allow-Origin:*` in server side.
