### ISSUE TITLE
Preview with detach/attach option into a new external window

### ISSUE THREAD

**Issue by MonteShaffer** [fengyuanchen/cropper#671]
Hi,

This is an idea for the preview feature of your cropper.  Allow for the preview element to attach/detach into a new window.

monte

{x:

**Comment by fengyuanchen** [comment]
That is not the work of the Cropper, you can build another tool to implement it by yourself.

BTW, for custom preview, here is an example: https://github.com/fengyuanchen/cropper/blob/master/examples/customize-preview.html
