### ISSUE TITLE
Crop box fixed

### ISSUE THREAD

**Issue by Cirrusware** [fengyuanchen/cropper#672]
Hello,

I use your library and I have one problematic and I search help.

I wish to have a fixed crop with already the same width. When I zoom my cropbox must be stay with the same width (maybe like http://scottcheng.github.io/cropit/). In fact, this is disturbing when I zoom the width change and when I change the crop box width change too.

How have the good parameters to have the behaviors ?

Sorry for my english, I hope you understand my need.

Thanks

**Comment by fengyuanchen** [comment]
Please read the documentation to find a solution or ask help on StackOverflow.
