### ISSUE TITLE
ScaleX method - not working?

### ISSUE THREAD

**Issue by MarconiMedia** [fengyuanchen/cropper#673]
Hey,

I am trying to create a button that flips the image horizontally. In your example and documentation I saw the following methods:

    cropper.scaleX(-1);
    cropper.scale(-1, 1);

But they don't seem to work. cropper.zoomTo() works perfectly, so I am guessing I am using the right syntax. Could you enlighten me, what am I doing wrong?

Thanks in advance,
Cheers!
Matyas

**Comment by fengyuanchen** [comment]
Please try to check it yourself first, not just post a question to another one.

And if you real need help, please provide a online demo for your case.
