### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by haksim** [fengyuanchen/cropper#676]
Hello!
I need the cropped image size like my fix crop box. how can i do?

**Comment by fengyuanchen** [comment]
If your crop box is 400x300, then:
```js
$().cropper('getCroppedCanvas', {
  width: 400,
  height: 300,
});
```

**Comment by namnguyen2091** [comment]
I set getCroppedCanvas = { width: 200, height: 262 } but why I get image with size 295x368?
> var $image = $('#image');
>       var cropBoxData = { width: 200, height: 262 };
>       var getCroppedCanvas = { width: 200, height: 262 };
>       var canvasData;
> 	  var console = window.console || { log: function () {} };
> 	  var $image = $('#image');
> 	  var $download = $('#save-change');
> 
>       $('#changeImageModal').on('shown.bs.modal', function () {
>         $image.cropper({
>           autoCropArea: 0.65,
>           guides: false,
>           cropBoxResizable: false,
>           cropBoxMovable: false,
>           restore: false,
>           highlight: false,
>           viewMode: 1,
>           dragMode: 'move',
>           built: function () {
>             $image.cropper('setCanvasData', canvasData);
>             $image.cropper('setCropBoxData', cropBoxData);
>             $image.cropper('getCroppedCanvas', getCroppedCanvas);
>           }
>         });
>         // method
>         $('.docs-buttons').on('click', '[data-method]', function () {
> 		    var $this = $(this);
> 		    var data = $this.data();
> 		    var $target;
> 		    var result;
> 
> 		    if ($this.prop('disabled') || $this.hasClass('disabled')) {
> 		      return;
> 		    }
> 
> 		    if ($image.data('cropper') && data.method) {
> 		      data = $.extend({}, data); // Clone a new one
> 
> 		      if (typeof data.target !== 'undefined') {
> 		        $target = $(data.target);
> 
> 		        if (typeof data.option === 'undefined') {
> 		          try {
> 		            data.option = JSON.parse($target.val());
> 		          } catch (e) {
> 		            console.log(e.message);
> 		          }
> 		        }
> 		      }
> 
> 		      result = $image.cropper(data.method, data.option, data.secondOption);
> 
> 		      switch (data.method) {
> 		        case 'scaleX':
> 		        case 'scaleY':
> 		          $(this).data('option', -data.option);
> 		          break;
> 
> 		        case 'getCroppedCanvas':
> 		          if (result) {
> 
> 		            // Bootstrap's Modal
> 		            //$('#getCroppedCanvasModal').modal().find('.modal-body').html(result);
> 
> 		            if (!$download.hasClass('disabled')) {
> 		              //$download.attr('href', result.toDataURL('image/jpeg'));
> 		              console.log(result.toDataURL('image/jpeg'));
> 		            }
> 		          }
> 
> 		          break;
> 		      }
