### ISSUE TITLE
Highlighted image not shown | blob

### ISSUE THREAD

**Issue by T1k3-HU** [fengyuanchen/cropper#677]
The original image src is blob.
The highlighted image not shown (.cropper-view-box img).

![cropper](https://cloud.githubusercontent.com/assets/8018130/15074052/2285081c-139d-11e6-9b18-2ea1e0894619.png)

**Comment by fengyuanchen** [comment]
Image with Blob URL is supported, please check for other reason. You can try it on the [demo](https://fengyuanchen.github.io/cropper) page.

**Comment by T1k3-HU** [comment]
I converted to base64 and it's fine. So i didn't found any other reason - but still looking...
