### ISSUE TITLE
Is it possible to get data uri of the cropped area? 

### ISSUE THREAD

**Issue by varunbhuvanendran** [fengyuanchen/cropper#683]
Is there any method to get the data uri of the crop area of the image, so that it could be used for preview. And also used to send to server. I am trying to find out a way to upload an image, crop, preview it and then send it to server.

**Comment by fengyuanchen** [comment]
Of course! Please check out the [`getCroppedCanvas`](https://github.com/fengyuanchen/cropper#getcroppedcanvasoptions) method.
