### ISSUE TITLE
如何获取裁剪后的图片到img 的src呢

### ISSUE THREAD

**Issue by zhangwei900808** [fengyuanchen/cropper#687]
如何获取裁剪后的图片到img 的src呢

**Comment by fengyuanchen** [comment]
```
$().cropper('getCroppedCanvas').toDataURL('image/jpeg')
```
Doc: 
- https://github.com/fengyuanchen/cropper#getcroppedcanvasoptions
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL
