### ISSUE TITLE
replace图片后，有回调函数吗？怎么调用？

### ISSUE THREAD

**Issue by AliceSong1** [fengyuanchen/cropper#688]

**Comment by fengyuanchen** [comment]
After replace, these events will be called again: `build`, `built` and `crop`.

**Comment by AliceSong1** [comment]
Thanks for your reply. If I just want to reset the setCropBoxData after replaced. But I don.t know whenever the replace method is finished. As it is an asynchronous process. Also I use the build or built is not work.  Can you provide me a example. If there is a callback function after replaced. it will be good for i use the cropper.
