### ISSUE TITLE
viewMode: 1 image moves outside of container on rotate

### ISSUE THREAD

**Issue by ndtreviv** [fengyuanchen/cropper#689]
If you set viewMode to 1, so that the cropper stays within the image, then rotate to 90 degrees, the image  zooms in to fit to the crop box.
eg:
**Start:**
<img width="629" alt="screen shot 2016-05-12 at 16 21 07" src="https://cloud.githubusercontent.com/assets/1530653/15220017/d402fabc-185d-11e6-9bd5-3d6f78d1d297.png">
**Rotated:**
<img width="615" alt="screen shot 2016-05-12 at 16 21 18" src="https://cloud.githubusercontent.com/assets/1530653/15220030/e787d8b4-185d-11e6-8ad8-af0f7b652025.png">

But then if you rotate back, the image stays zoomed:
<img width="623" alt="screen shot 2016-05-12 at 16 21 43" src="https://cloud.githubusercontent.com/assets/1530653/15220056/04708fa2-185e-11e6-9117-1d528fa8b69b.png">

Sometimes, if you rotate all the way around, moving the cropbox up the zoomed image, and back again you end up with some of the image outside of the top of the container:
<img width="623" alt="screen shot 2016-05-12 at 16 25 06" src="https://cloud.githubusercontent.com/assets/1530653/15220084/26a298cc-185e-11e6-8c6f-8b6ada4d0060.png">

This is a real pain if you've set: movable: false and zoomable: false.

I'd actually prefer it if the container always contained the whole image and the cropbox reduced in size to be contained within the image. However, as a minimum, when the image is rotated all the way around, it shouldn't be moved outside of the container.

**Comment by ndtreviv** [comment]
Was there a solution? Or was it not considered an issue?

**Comment by fengyuanchen** [comment]
It is not an issue.

**Comment by ndtreviv** [comment]
I suppose it doesn't matter. I've worked around the fact that you lose visibility of the image when rotating by listening for the crop event and resizing the canvas so it fits inside the container.
