### ISSUE TITLE
Add it to cdnjs

### ISSUE THREAD

**Issue by ilovecoffee** [fengyuanchen/cropper#69]
It would be awesome if you add this library to http://cdnjs.com.

**Comment by drewfreyling** [comment]
@fengyuanchen we are looking at creating a rep on the future which just has `package.json` files in it and no assets. But for now you will have to put up with the size.

**Comment by drewfreyling** [comment]
@fengyuanchen https://github.com/cdnjs/cdnjs/commit/be6c2fe41e676f327455e0fc5229f7c4176347b8 fixes this issue.

**Comment by fengyuanchen** [comment]
@drewfreyling Great! Thank you very very much!

**Comment by fengyuanchen** [comment]
Hi, @drewfreyling 

Can you help me to update the Cropper's versions on CDNJS or make it update automatically? 

Thanks in advance.

**Comment by drewfreyling** [comment]
You can try adding git auto-update to the https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/cropper/package.json and as long as you continue to tag your releases it should update automatically. More info here -> https://github.com/cdnjs/cdnjs#enabling-gitrecommended-or-npm-auto-update

**Comment by fengyuanchen** [comment]
@drewfreyling Thank you! I have sent the PR: https://github.com/cdnjs/cdnjs/pull/4833

**Comment by drewfreyling** [comment]
https://github.com/cdnjs/cdnjs/pull/4835 fixes this.
