### ISSUE TITLE
Feature: Preview Image Update Event

### ISSUE THREAD

**Issue by ndtreviv** [fengyuanchen/cropper#690]
I want to update the preview image once it's been set. It would be really useful to have more events thrown by the cropper so that this is possible.

**Comment by fengyuanchen** [comment]
Why not just custom the preview?

> https://github.com/fengyuanchen/cropper/blob/master/examples/customize-preview.html

**Comment by ndtreviv** [comment]
Is the crop handler called after the preview images have been drawn up? I want to make use of the width/height that the cropper is setting on the preview image div containers. What I'm finding is that often I'm accessing the elements as they're still being changed. 

I'll give it a go.

**Comment by ndtreviv** [comment]
Hmm..it seems the problem is maybe elsewhere:

`$(".picture-frame-border .img-preview").width(); //357`
`$(".picture-frame-border .img-preview")[0].style.width; //"500px"`

**Comment by ndtreviv** [comment]
I've written a workaround:
`var width = parseInt($(".picture-frame-border .img-preview")[0].style.width, 10);`

I think this is a jQuery problem, not a cropper problem. Closing.
