### ISSUE TITLE
Why crop event binded after every event?

### ISSUE THREAD

**Issue by Amr-alshroof** [fengyuanchen/cropper#691]
after every event the crop event  is fired 
`   $image.on({
            'build.cropper': function (e) {
              console.log(e.type);
            },
            'built.cropper': function (e) {
              console.log(e.type);
            },
            'cropstart.cropper': function (e) {
              console.log(e.type, e.action);
            },
            'cropmove.cropper': function (e) {
              console.log(e.type, e.action);
            },
            'cropend.cropper': function (e) {
              console.log(e.type, e.action);
            },
            'crop.cropper': function (e) {
              console.log(e.type, e.x, e.y, e.width, e.height, e.rotate, e.scaleX, e.scaleY);
            },
            'zoom.cropper': function (e) {
              console.log(e.type, e.ratio);
            }
          }).cropper(options);`
this code will print *I am cropping now* on zoom,cropStart,cropEnd and crop

**Comment by ndtreviv** [comment]
@Amr-alshroof Are you sure that code is correct?

Anyway, +1 for this.

If I set `responsive: false` I still get a crop event for every window resize event (hundreds in one resize).

It's a bit too chatty at the moment.

**Comment by Amr-alshroof** [comment]
@ndtreviv  i have got this code from [https://github.com/fengyuanchen/cropper/blob/master/demo/js/main.js](Croppers Demo)
the main problem here that i can't call backend to crop image on every single action, i must only call the ajax crop on crop action only, that makes things very hard to handle.

**Comment by ndtreviv** [comment]
@Amr-alshroof I only asked about the code because your ticket states that:

> this code will print I am cropping now...

which it doesn't, as far as I can see.

As for the action problem - I understand that you wouldn't want to fire off that back-end action until the user was definitely done cropping. I'd suggest hanging that back-end call off of some other action - something more definite and user driven. It's hard to comment when I don't really know what you're trying to achieve.

Also, this isn't really my code :) It's @fengyuanchen s awesomeness.

**Comment by Amr-alshroof** [comment]
What i am trying to do is to make multiple image cropper, that act like demo in the project where a user setDragMode('crop') then when $().cropper('crop') it must bind crop event where i could make ajax call to handle crop.
`   'crop.cropper': function (e) {
                $.ajax({
                    url: "/image/crop",
                    type: "post",
                    success: function (response) {}
                  });
            },`

**Comment by fengyuanchen** [comment]
@Amr-alshroof Please don't send any ajax with in the `crop` event as it will be triggered many many many many many many many many times when wheeling. mouse moving, touch moving, and so on.
