### ISSUE TITLE
change dynamically the `minCropBoxWidth` option when changing image?

### ISSUE THREAD

**Issue by MadeInMoon** [fengyuanchen/cropper#692]
Is it possible to change **dynamically** the `minCropBoxWidth` when changing image? (without to re-create a cropper?)

I found a solution [stackoverflow](http://stackoverflow.com/questions/30051695/fengyuanchen-jquery-cropper-plugin-minimum-crop-validation) (with [fiddle](http://jsfiddle.net/dekkard/9r6czo65/12/)), but it doesn't assure any minimum width if the user drag (reducing crop box) to fast, and also has little pixel jump if you reach the minimum width and click out.

Thank U!

**Comment by fengyuanchen** [comment]
Not support this.
