### ISSUE TITLE
main.js TypeError: Cannot read property 'download' of undefined

### ISSUE THREAD

**Issue by BenjaminPiscart** [fengyuanchen/cropper#695]
Hi I'm having this type of error, seems $download[0] is undefined

`  // Download
  if (typeof $download[0].download === 'undefined') {
    $download.addClass('disabled');
  }`

**Comment by fengyuanchen** [comment]
Browser and version?

**Comment by apasho** [comment]
I'm getting this same error. I'm using Firefox 49.02.
