### ISSUE TITLE
How to hide crop border line?

### ISSUE THREAD

**Issue by jimliang** [fengyuanchen/cropper#696]
I did it like this:
```
.cropper-line {
    background-color: transparent;
}
```
But it show  padding on left and right(`element.cropper('getData').x == 0` is true)
![pic1](http://i4.buimg.com/c4460dca4294747f.png)
![pic2](http://i4.buimg.com/600c349473e640c1.png)

The same that when making line width/height 0px.

How I should do?

**Comment by fengyuanchen** [comment]
I have not idea about this. Please try to fix it by yourself.
