### ISSUE TITLE
Image blank Area background area turns black.

### ISSUE THREAD

**Issue by designskiller** [fengyuanchen/cropper#697]
Hi,

First this is awesome cropper. Using this cropper i have small issue when i crop an rectangular image in free form its blank background area turns into black. Like - 
https://slack-files.com/T0649C47R-F1AUFSQ81-14b7082048
Why is this happening? 

Thanks in advance.

**Comment by fengyuanchen** [comment]
Demo?

**Comment by LJSancibrian** [comment]
Hi. I have thi same problem... Im using the demo Crop-Avatar, and i like that if the selected area to crop are longer that the image, the background area do not turns black, or the user can not to select the area out of the image. ( Scuse my english... I do not know a lot...)

this is an example for the selected area...
http://i.imgur.com/T0oCqvP.jpg

and this is the final image...
http://i.imgur.com/p9oiMaT.jpg

Thanks.

**Comment by LJSancibrian** [comment]
hi. I agree  "viewMode: 1" on the avatar.js file, into the function "startCropper".
Great job.
Thanks for this awesome pulling.
