### ISSUE TITLE
Windows 10 - Edge ( IE ) 

### ISSUE THREAD

**Issue by Stephan213** [fengyuanchen/cropper#701]
On the demo page an our implementation of Cropper, saving/downloading the cropped image does not work, spinning wheel of death.

**Comment by Stephan213** [comment]
Seems like its only an issue with a slow connection ( .5mbs or less ) upload and larger files, the same file and connection on Chrome will work.

**Comment by fengyuanchen** [comment]
Please limit image size before start cropper.

**Comment by Stephan213** [comment]
Image size was quite small under 500KB during tests 

And same image size worked in Chrome and earlier versions of IE ( 10 )
