### ISSUE TITLE
ViewMode 1 issue with crop area going outside the container

### ISSUE THREAD

**Issue by dorzki** [fengyuanchen/cropper#705]
Hi there,
There is an issue when trying to enlarge the cropping area on ViewMode 1.
I've attached a video with a demonstration.

The issue is on Mac & PC chrome (tested on several computers).

https://vid.me/JG9m

![screen shot 2016-05-26 at 16 24 04](https://cloud.githubusercontent.com/assets/3604454/15575996/4ae5903a-235e-11e6-9ea2-2092624c7351.png)

**Comment by fengyuanchen** [comment]
Got it. Thanks for report this issue.
