### ISSUE TITLE
Zooming in built callback does not trigger crop event

### ISSUE THREAD

**Issue by carrieje** [fengyuanchen/cropper#706]
```
$(".img-container > img").cropper
  built: ->
    console.log 'built'
    $(this).cropper 'zoomTo', 1
  zoom: (e) ->
    console.log 'zoom'
  crop: (e) ->
    console.log 'crop'
```

The previous coffee code generate the following console log at document rendering :

> crop
built
zoom

Whereas each time I zoom in or out manually after that I get the following :

> zoom
crop

Should not the first output be :

> crop
built
zoom
**crop**

And thus, the zoom requested in `built` callback having triggered a `crop` event ?
About the `crop.cropper` event, I read in the Readme :

> This event fires when the canvas (image wrapper) or the crop box changed.

Which, in my sense, covers the `zoom` event.

**Comment by fengyuanchen** [comment]
There is a bug here: The `crop` event should come after the `built` event.

**Comment by carrieje** [comment]
Perfect :)
I have downloaded the current version of the lib and patched it with your fix.
Waiting for an official release with it included ;)

Thanks !
