### ISSUE TITLE
TypeError: $(...).cropper is not a function

### ISSUE THREAD

**Issue by gewuxy** [fengyuanchen/cropper#707]
when use cropper in modal ,I suffer "cropper is not a function" problem,below is my code:

![qq 20160529113905](https://cloud.githubusercontent.com/assets/8190691/15631256/fdb42b92-2591-11e6-9304-3456e3bae110.png)
 
anyone help?

**Comment by gewuxy** [comment]
I find a similar question https://github.com/fengyuanchen/cropper/issues/85
and I change my code below:
![1](https://cloud.githubusercontent.com/assets/8190691/15632832/7b1fa758-25d0-11e6-8bc4-595d6c9b4b59.png)
![2](https://cloud.githubusercontent.com/assets/8190691/15632833/81c204d4-25d0-11e6-9f2b-091ad23c45b3.png)
But I still suffer the same error.

**Comment by fengyuanchen** [comment]
I guess you are using the [Cropper.js](https://github.com/fengyuanchen/cropperjs), which is not a jQuery plubin at all.
