### ISSUE TITLE
Simple image crop without the cropper UI

### ISSUE THREAD

**Issue by razielin** [fengyuanchen/cropper#708]
Hello guys. I can't figure out how to select existing image in a page, crop it by using some predefined CropBox parameters and output the result into a <div> element.
So I don't need any input from the user - all I need is to output the cropped image after the page load.  
Cropper always creates crop UI for the specified image in the constructor - so I can't do this...
Thanks!

**Comment by ndtreviv** [comment]
Why not instantiate the cropper, call the getCroppedCanvas and then destroy the cropper straight away?

eg:

```
var canvas = $().cropper({ .. }).cropper('crop').cropper('getCroppedCanvas');
$().cropper('destroy');
```

**Comment by fengyuanchen** [comment]
You may try a server side cropper for this case.
