### ISSUE TITLE
Rotate and ScaleX doesn't works at the same time

### ISSUE THREAD

**Issue by david-de-malaga** [fengyuanchen/cropper#709]
Go to https://fengyuanchen.github.io/cropper/, click on Rotate -45, click on Scale X or Y, select an small area of the girl and check the result with get Cropped Canvas,  the cropper is not correct, is the cropper that you would get if the scaleX (or scaleY) was not applied. Please play with Rotate and Scale and you will see the issue.

**Comment by fengyuanchen** [comment]
This was caused by the improvement in #633.
