### ISSUE TITLE
What is the alternate of getDataURL in latest version?

### ISSUE THREAD

**Issue by chitrank-samaiya** [fengyuanchen/cropper#711]
After updating plugin to latest version, I could not use getDataURL function, Can anyone help me what is the alternate of that getDataURL?

**Comment by fengyuanchen** [comment]
Can you provide an online demo?

**Comment by MuratCool** [comment]
i need this information too.  getDataURL
Thanks.

**Comment by fengyuanchen** [comment]
The `getDataURL` method had been removed since [v0.9.0](https://github.com/fengyuanchen/cropper/releases/tag/v0.9.0).

**Comment by fengyuanchen** [comment]
Please use the `getCroppedCanvas` method now. Read more about it in the [documentation](https://github.com/fengyuanchen/cropper#getcroppedcanvasoptions).
