### ISSUE TITLE
$image.on(...).cropper(options); is not a function

### ISSUE THREAD

**Issue by timusiiit123** [fengyuanchen/cropper#712]
I am using the **Cropperjs** code in my modal as below even I put the the path correct.
I have only assets,demo,dist folders when I used it separately, it works but when I uesd it in project, it doesn't work.

`<html>
			<head>
			<link rel="stylesheet"
				href="../plugins/cropper/assets/css/font-awesome.min.css">
			<link rel="stylesheet"
				href="../plugins/cropper/assets/css/bootstrap.min.css">
				<script src="../plugins/cropper/dist/cropper.js"></script>
			<link rel="stylesheet" href="../plugins/cropper/dist/cropper.css">
			<link rel="stylesheet" href="../plugins/cropper/demo/css/main.css">
			
			
			
			</head>
			<body>
				
			
				
				<div class="container">
					<div class="row">
						<div class="col-md-9">
							<div class="img-container">
								<img id="image" src="../plugins/cropper/assets/img/picture-2.jpg" alt="Picture" />
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-9 docs-buttons">
							
							<div class="btn-group">
								<button type="button" class="btn btn-primary"
									data-method="setDragMode" data-option="move" title="Move">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-arrows"></span>
									</span>
								</button>
								<button type="button" class="btn btn-primary"
									data-method="setDragMode" data-option="crop" title="Crop">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-crop"></span>
									</span>
								</button>
							</div>
			
							<div class="btn-group">
								<button type="button" class="btn btn-primary" data-method="zoom"
									data-option="0.1" title="Zoom In">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-search-plus"></span>
									</span>
								</button>
								<button type="button" class="btn btn-primary" data-method="zoom"
									data-option="-0.1" title="Zoom Out">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-search-minus"></span>
									</span>
								</button>
							</div>
			
							<div class="btn-group">
								<button type="button" class="btn btn-primary" data-method="move"
									data-option="-10" data-second-option="0" title="Move Left">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-arrow-left"></span>
									</span>
								</button>
								<button type="button" class="btn btn-primary" data-method="move"
									data-option="10" data-second-option="0" title="Move Right">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-arrow-right"></span>
									</span>
								</button>
								<button type="button" class="btn btn-primary" data-method="move"
									data-option="0" data-second-option="-10" title="Move Up">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-arrow-up"></span>
									</span>
								</button>
								<button type="button" class="btn btn-primary" data-method="move"
									data-option="0" data-second-option="10" title="Move Down">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-arrow-down"></span>
									</span>
								</button>
							</div>
			
							<div class="btn-group">
								<button type="button" class="btn btn-primary" data-method="rotate"
									data-option="-45" title="Rotate Left">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-rotate-left"></span>
									</span>
								</button>
								<button type="button" class="btn btn-primary" data-method="rotate"
									data-option="45" title="Rotate Right">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-rotate-right"></span>
									</span>
								</button>
							</div>
			
							<div class="btn-group">
								<button type="button" class="btn btn-primary" data-method="scaleX"
									data-option="-1" title="Flip Horizontal">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-arrows-h"></span>
									</span>
								</button>
								<button type="button" class="btn btn-primary" data-method="scaleY"
									data-option="-1" title="Flip Vertical">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-arrows-v"></span>
									</span>
								</button>
							</div>
			
							<div class="btn-group">
								<button type="button" class="btn btn-primary" data-method="crop">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-check"></span>
									</span>
								</button>
								<button type="button" class="btn btn-primary" data-method="clear"
									title="Clear">
									<span class="docs-tooltip" data-toggle="tooltip"> <span
										class="fa fa-remove"></span>
									</span>
								</button>
							</div>
			
							<div class="btn-group">
								<button type="button" class="btn btn-primary" data-method="disable"
									title="Disable">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-lock"></span>
									</span>
								</button>
								<button type="button" class="btn btn-primary" data-method="enable"
									title="Enable">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-unlock"></span>
									</span>
								</button>
							</div>
			
							<div class="btn-group">
								<button type="button" class="btn btn-primary" data-method="reset"
									title="Reset">
									<span class="docs-tooltip" data-toggle="tooltip">
										<span class="fa fa-refresh"></span>
									</span>
								</button>
								<label class="btn btn-primary btn-upload" for="inputImage"
									title="Upload image file"> <input type="file"
									class="sr-only" id="inputImage" name="file" accept="image/*">
									<span class="docs-tooltip" data-toggle="tooltip"
									title="Import image with Blob URLs"> <span
										class="fa fa-upload"></span>
								</span>
								</label>
							</div>
			
							<div class="btn-group btn-group-crop">
								<button type="button" class="btn btn-primary"
									data-method="getCroppedCanvas">
									<span class="docs-tooltip" data-toggle="tooltip"> Get
										Cropped Canvas </span>
								</button>
							</div>
			
							
							<div class="modal fade docs-cropped" id="getCroppedCanvasModal"
								aria-hidden="true" aria-labelledby="getCroppedCanvasTitle"
								role="dialog" tabindex="-1">
								<div class="modal-dialog">
									<div class="modal-content">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal"
												aria-hidden="true">&times;</button>
											<h4 class="modal-title" id="getCroppedCanvasTitle">Peview</h4>
										</div>
										<div class="modal-body"></div>
										<div class="modal-footer">
											<button type="button" class="btn btn-default"
												data-dismiss="modal">Cancel</button>
											<a class="btn btn-primary" id="download"
												href="javascript:void(0);" download="cropped.jpg">Upload</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			
			
				
				<script src="../plugins/cropper/assets/js/jquery.min.js"></script>
				<script src="../plugins/cropper/assets/js/bootstrap.min.js"></script>
				<script src="../plugins/cropper/dist/cropper.js"></script>
				<script src="../plugins/cropper/demo/js/main.js"></script>
			</body>
					</html>`

**Comment by fengyuanchen** [comment]
Cropperjs is not a jQuery plugin at all...

**Comment by michl-in-pan** [comment]
I have a problem with the Download Button. The modal with Download and Close Button is not closed after pushing Download.  Is there a way to change this ? so that the download runs in background and the window disappears ?
