### ISSUE TITLE
 I can not change fillcolor

### ISSUE THREAD

**Issue by kaioskam** [fengyuanchen/cropper#714]
$image.cropper({
          aspectRatio: 16 / 16,
          width: 570,
          height: 570,
          dragCrop: false,
          zoomOnWheel: false,
          cropBoxMovable:true,
          cropBoxResizable: false,
          fillColor: "#FFFFF",
          crop: function(e) {
              $("#x").val(e.x);
              $("#y").val(e.y);
              $("#w").val(e.width);
              $("#h").val(e.height);
              $('#orient').val(rotateImg);
          }
        });

**Comment by fengyuanchen** [comment]
The `fillColor` is just a optinal property of the `options` parameter of the `getCroppedCanvas` method.

**Comment by pwsic** [comment]
Can you send an example of use?
