### ISSUE TITLE
Crop doesn't return equal images

### ISSUE THREAD

**Issue by tychovbh** [fengyuanchen/cropper#715]
I'm trying to get all the images the same height and width. My settings are:
````JS
$('#test .image').cropper({
    viewMode: 1,
    dragMode: 'move',
    restore: false,
    guides: false,
    highlight: false,
    cropBoxMovable: true,
    cropBoxResizable: false,
    width: 800,
    height: 1200
});

// Then I crop with this:
var result      = $('#test .image').cropper('getCroppedCanvas', {
     width: 800,
     height: 1200,
});
````
Im cropping with two different images:
3888 x 5184 after crop: 800 x 1066
1168 x 1653 after crop: 800 x 1132

What I don't understand is that the images are far bigger than the requested width and height, so why does the cropper doesn't return me two images of the same with and height?

**Comment by fengyuanchen** [comment]
Just because:

For image with size 3888 x 5184:
```
800 / 1066 === cropBox.width / cropBox.height
800 / 1200 !== cropBox.width / cropBox.height
```

For image with size 1168 x 1653:
```
800 / 1132 === cropBox.width / cropBox.height
800 / 1200 !== cropBox.width / cropBox.height
```

**Comment by fengyuanchen** [comment]
Just set the `aspectRaio` option to `800/1200` if you want to get an expected result.
