### ISSUE TITLE
HTTPS下访问http图片，设置cropper参数checkOrientation为true时报错。

### ISSUE THREAD

**Issue by haozzzzzzzz** [fengyuanchen/cropper#716]
我的https站点访问一张http站点的图片，当checkOrientation为true时，cropper报错,cropper不能正常使用。见图：
![_20160613124341](https://cloud.githubusercontent.com/assets/2825386/15997301/f60a8dbc-3164-11e6-98ec-0c9aa8d4436a.png)

当我把checkOrientation设为false时，可以正常使用。

**Comment by fengyuanchen** [comment]
It not an issue of the Cropper.
