### ISSUE TITLE
cropper-point.point-se style?

### ISSUE THREAD

**Issue by ypcyc** [fengyuanchen/cropper#717]
Is it a feature that righ bottom point (cropper-point.point-se) has different style options for 768, 992 and 1200px?

@media (min-width: 768px) {
  .cropper-point.point-se {
    width: 15px;
    height: 15px;
  }
}

@media (min-width: 992px) {
  .cropper-point.point-se {
    width: 10px;
    height: 10px;
  }
}

@media (min-width: 1200px) {
  .cropper-point.point-se {
    width: 5px;
    height: 5px;

    opacity: .75;

    filter: alpha(opacity=75);
  }
}

**Comment by fengyuanchen** [comment]
Just customize it by override the default styles.

**Comment by ypcyc** [comment]
Thank you for the info! I think it's worth to document it somewhere.
