### ISSUE TITLE
When using an image larger than the cropper, it reports irregular points

### ISSUE THREAD

**Issue by jessicamarx** [fengyuanchen/cropper#718]
See these images as an example:

http://screencast.com/t/YNXNdpVDpp
http://screencast.com/t/cN5SKgpn

**End Result**
http://screencast.com/t/jCZrPZw6

As you can see - it is reporting the dimensions completely incorrectly. This works fine if I use smaller images. It is almost as though the width and height are halved?

**Comment by jessicamarx** [comment]
![Output of getCropBoxData()](http://screencast.com/t/IbWOVrND)
![Output of getData()](http://screencast.com/t/cwcGsF2TkI)

**Comment by jessicamarx** [comment]
It appears that it is getting the smaller dimensions for the shrunken crop image - and when i pass those over to the source image (which is a lot larger when not scaled down) it is calculating the points erroneously.

Is there a way to fix this?

**Comment by fengyuanchen** [comment]
Can you provide an online demo with [CodePen](http://codepen.io/) or [JSFiddle](http://jsfiddle.net/)?

**Comment by rebellao** [comment]
I have same problem, when I use images bigger than crop the result image rotates!! Occurs too with big images in portrait mode.....the result image rotates and the selected area for crop changes....

**Comment by fengyuanchen** [comment]
Try the latest version plz.
