### ISSUE TITLE
I found a bug on the iOS when i select a vertical photo.

### ISSUE THREAD

**Issue by ruanhaojian** [fengyuanchen/cropper#720]
I found a bug on the iOS when i select a vertical photo.
If the picture is a vertical version of the film,the picture editor exception, cannot use the result.
So I got file after using Image new () to generate canvas.toDataUrl and then edit to normal. But it will slow down a bit.

**Comment by ruanhaojian** [comment]
Remark: my environment is ios9.3.* wechat browser.

**Comment by fengyuanchen** [comment]
Does this is the same issue as #120 ?
