### ISSUE TITLE
what dose Chrome (latest) in Browser support mean ?

### ISSUE THREAD

**Issue by aflext** [fengyuanchen/cropper#721]
What dose `Chrome (latest)` in `Browser support` means ? Does it means the plugin only supports the newest version ? I use Chrome  with version 51, does this plugin supports version 45 of chrome ?

**Comment by fengyuanchen** [comment]
Did not you see the `Internet Explorer 8+` in the support list? Do you know what that means?

**Comment by aflext** [comment]
@fengyuanchen I see the `Internet Explorer 8+`,but i don't see the smallest version of `Chrome` `Firefox` like `Chrome 45+` `Firefox 4.0+ `

**Comment by fengyuanchen** [comment]
May support, may not support in older browsers.
