### ISSUE TITLE
how to re-initialize cropper?

### ISSUE THREAD

**Issue by ypcyc** [fengyuanchen/cropper#722]
How can I re-initialize cropper if I dynamically include path to cropper.js with <script> inside <body> during the run-time?
(I want to load the script and initialize it only when certain button is clicked after page was loaded)

Currently I get "cropper is not a function" error.

**Comment by fengyuanchen** [comment]
Destroy it first, and then initialize again.

**Comment by ypcyc** [comment]
After the script reference is loaded into <body> I'm trying to initialize it, but I get this error that copper is not a function, so there is nothing to destroy and $('#image').cropper returns the error

**Comment by fengyuanchen** [comment]
I guess you loaded a wrong script. Which one you are using?
- https://github.com/fengyuanchen/cropper
- https://github.com/fengyuanchen/cropperjs

**Comment by ypcyc** [comment]
I was using jquery based cropper and everything was working fine when the link was present in html.
Than new requirement came to load script on button click and it stopped working.
Now I tried JS based cropperjs and was able to use it, just have to re-write some old jquery code now, so I was thinking if it was possible to initialize jquery cropper.

**Comment by milpas999** [comment]
There is no proper example for destroying the cropper session using jquery. In documentation it is written

`destroy()

Destroy the cropper and remove the instance from the image.`

But i don't understand where to write this code

**Comment by fengyuanchen** [comment]
@milpas999 `$('img').cropper('destroy')`

**Comment by kiarash3tar** [comment]
Hi...
And how destroy cropper using pure javascript?

**Comment by shoter** [comment]
If you have:
```
var cropper = new Cropper(image, {...});
```
Then you can destroy it by writing:
```
cropper.destroy();
```

**Comment by asifmushtaqse** [comment]
But how to reinit after the destroy?
It is removing the element from the DOM.
