### ISSUE TITLE
[Not an issue] - How to show only crop area in fixed mode?

### ISSUE THREAD

**Issue by agriz** [fengyuanchen/cropper#724]
It shows the complete image as well as cropping area. (Fixed Mode ) How do i hide all the part except the crop-box area?
![1](https://cloud.githubusercontent.com/assets/1437943/16170854/d3ab9974-357d-11e6-87fd-eb205bfea91f.png)

**Comment by fengyuanchen** [comment]
https://github.com/fengyuanchen/cropper/blob/master/examples/fixed-crop-box.html

**Comment by agriz** [comment]
Fixed and Full crop is not just showing the croppable area. It shows the complete image with crop area. I just want the visible part where the user should move the image.

**Comment by fengyuanchen** [comment]
Not support that.
