### ISSUE TITLE
Question: Is it possible to disable drag points?

### ISSUE THREAD

**Issue by ndtreviv** [fengyuanchen/cropper#726]
EG: If I wanted to only allow crop box resizing from the corners.

I can hide the NORTH/EAST/SOUTH/WEST drag points using CSS, but you can obviously still drag in those directions.

is there anyway to disable that?

**Comment by fengyuanchen** [comment]
Just set `cropBoxResizable` option to `false`.

**Comment by ndtreviv** [comment]
I want to resize on the corners though. It doesn't matter - I'll just hide them for now.
