### ISSUE TITLE
Cropper does not allow scroll when dragMode is "none" on touch screens

### ISSUE THREAD

**Issue by ndtreviv** [fengyuanchen/cropper#727]
Steps to reproduce:

Load the cropper with the following options and browser with a mobile device:
```
{
  dragMode: "none",
  background: false,
  zoomOnWheel: false,
  zoomOnTouch: false,
  autoCropArea: 1,
  responsive: true,
  toggleDragModeOnDblclick: false
}
```

Swipe the screen to scroll. In responsive mode, the cropped takes almost full width of the screen (depending in CSS layout), but when you swipe up/down over the cropper it doesn't scroll.

Ideally it would defer the swipe action to scroll if dragMode was "none".

**Comment by ndtreviv** [comment]
Solved in my fork. Review the referenced commit for the solution.

**Comment by fengyuanchen** [comment]
Are you sure you had solved it?

**Comment by fengyuanchen** [comment]
Thanks for report this.
