### ISSUE TITLE
Enhancement: view mode where cropbox should be within the image and the image should be within the canvas.

### ISSUE THREAD

**Issue by ndtreviv** [fengyuanchen/cropper#728]
Let me start by saying that this plugin is fantastic. It's got _almost_ everything we need for our site. I personally am happy to help in supporting the plugin by resolving issues that people raise here. This is open source afterall.

However, we have a few use cases that aren't being solved, and that currently generate a lot of support issues on our current cropper, and that _could_ be solved really easily with your plugin.

We'd really like to replace our current cropped with this one, but we have to solve those problems first.

These problems are:

1. When the image rotates, it must be totally visible within the container - no part of it should "disappear" (via overflow) outside of the container. 
ie: `$().cropper('clear').cropper('rotateTo', 35).cropper('crop');` should result in the image being scaled so that all corners are still visible within the container.

2. When an image is rotated, the cropbox should be restricted to the *image*, not the *canvas*. 
For example, at 45deg rotation, the cropbox should not be able to overflow the image area, but should be restricted to within the bounds of the image - all four corners of the cropbox should be within the rotated image. This is similar, _but not the same_ as viewMode 1, which currently lets the cropbox overflow a rotated image.

I've previously solved these problems by implementing them as a new view mode, as together they change the way that the canvas and the cropbox behaves, and how the image looks on rotation, which _by your convention_ is determined by which viewMode you choose.

My pull request was rejected because you want to keep cropper simple and don't want to add a new viewmode - fair enough. It's your plugin afterall.

I want to make this work. So:

1. Are you ever going to consider adding functionality to solve the above 2 points into your plugin?

2. If so, how would you expect these options to be set? In particular consider point 2 above, which is currently, _by your convention_, determined by viewMode setting.

Thanks.

**Comment by ndtreviv** [comment]
I've assumed that this is never going to happen, so we'll continue developing our fork to do what we need it to do, especially as we've recently folded in memory-use fixes for low memory devices and getCroppedCanvas with tiling.

**Comment by galvarez421** [comment]
FWIW, I still think #2 would be a useful option. It's already essentially partially supported, but only for 0, 90, 180, and 270 degrees (and their negative counterparts), i.e., images whose edges are parallel to the edges of the canvas.

**Comment by ndtreviv** [comment]
@galvarez421 My fork of this project has that functionality in it, but it's quite out of date now. The codebase has moved on quite a bit, and I currently don't have the time to bring it back up to speed.
