### ISSUE TITLE
Incorrect zoom and/or size when initializing a cropper

### ISSUE THREAD

**Issue by PeeHaa** [fengyuanchen/cropper#730]
I want to have the cropper the size of the image on initialization. This works great for one image (300x250), but for some reason it seems like the image is zoomed for another image (235x48).

My reduced test case:

    <div style="width: 300px; height: 250px;">
        <img class="cropper1" name="background_1" src="bg.jpg" style="max-width: 100%;">
    </div>
    <div style="width: 235px; height: 48px;">
        <img class="cropper2" name="background_2" src="cta-button.png" style="max-width: 100%;">
    </div>
    <script>
      $('.cropper1').cropper({
        aspectRatio: 300 / 250,
        viewMode: 4,
        dragMode: 'move'
      });

      $('.cropper2').cropper({
        aspectRatio: 235 / 48,
        viewMode: 4,
        dragMode: 'move'
      });
    </script>

Which results in:

![cropper-bug](https://cloud.githubusercontent.com/assets/1330296/16308767/96705fc6-3966-11e6-9980-5135f827015a.png)

As you can see the first image has the correct dimensions and zoom, but the second looks zoomed in and has the wrong dimensions.

Original images:

![bg](https://cloud.githubusercontent.com/assets/1330296/16308731/746ee51e-3966-11e6-9406-50081b5d1eab.jpg)

![cta-button](https://cloud.githubusercontent.com/assets/1330296/16308714/6c24ba3c-3966-11e6-8317-ac8ac4fb235b.png)

I also tried disabling zooming `zoomable: false`, but that didn't make any difference. I also tried different viewmodes without any success.

[Self contained repro archive using the latest release (v2.3.2)](https://github.com/fengyuanchen/cropper/files/330295/repro-case.zip)

**Comment by fengyuanchen** [comment]
The min height of the cropper container is 100:
https://github.com/fengyuanchen/cropper#mincontainerheight

**Comment by PeeHaa** [comment]
I somehow missed that one. Thanks! :yellow_heart:
