### ISSUE TITLE
rotateTo: is not working 

### ISSUE THREAD

**Issue by agriz** [fengyuanchen/cropper#733]
I tried to give rotateTo: 180 
But it is showing the normal image instead of rotating the image.

However if i add rotate function, it works.

**Comment by agriz** [comment]
..?
What do you mean by closing it?
Can you please tell me what is wrong? I was waiting for your reply in the last three days

**Comment by fengyuanchen** [comment]
Are you sure it is a problem of the Cropper, not yourself?

**Comment by agriz** [comment]
Sir, 

$('.img-crop').cropper({
    aspectRatio: $('#ratio').val(),
    viewMode: 1,
    movable: false,
    minCropBoxWidth: 100,
    zoomable: true,
    fitCanvasToContainer: true,
    autoCropArea: 0.3,
    rotateTo: 180,

This is what i am using. But nothing happens. Everything else works. I dont see any warning or error in the console. I tried few browser. It is not working in anything. 

$().cropper('clear').cropper('rotate', 90).cropper('crop'); is working.
I use two cropper in a page, one after another.

**Comment by fengyuanchen** [comment]
The `rotateTo` is **not** an option at all...

**Comment by agriz** [comment]
While i load the photo, how to rotate it?
