### ISSUE TITLE
A bug found on some mobile when I load a picture

### ISSUE THREAD

**Issue by luochris** [fengyuanchen/cropper#739]
I can not sure is that a bug or a  misstake by my self.  I used cropper in my App running on a mobile with android os. and then I load a picture, when it done, the picture is not showing, there is only a background with translucent.  but on some android mobile it worked well, and ios it worked well too.

Looking forward to your reply， thanks！

**Comment by fengyuanchen** [comment]
#294, #577

**Comment by luochris** [comment]
You help me so much,thanks a lot!
