### ISSUE TITLE
Orientations are not read correctly.

### ISSUE THREAD

**Issue by jasollien** [fengyuanchen/cropper#740]
I solved it by changing some of the value inside the switch. This worked fine for me. Hope you can add this to the next release. 

Works for these images: https://github.com/recurser/exif-orientation-examples.

`switch (orientation) {

          // flip horizontal
          case 2:
            scaleX = -1;
            scaleY = 1;
            break;

          // rotate left 180°
          case 3:
            rotate = -180;
            break;

          // flip vertical
          case 4:
            scaleX = 1;
            scaleY = -1;
            break;

          // flip vertical + rotate right 90°
          case 5:
            rotate = -90;
            scaleX = 1;
            scaleY = -1;
            break;

          // rotate right 90°
          case 6:
            rotate = 90;
            break;

          // flip horizontal + rotate right 90°
          case 7:
            rotate = -90;
            scaleX = -1;
            scaleY = 1;
            break;

          // rotate left 90°
          case 8:
            rotate = -90;
            break;
        }
      }`

**Comment by fengyuanchen** [comment]
Thanks for report this.
