### ISSUE TITLE
jQuery Version

### ISSUE THREAD

**Issue by dolfvdberg** [fengyuanchen/cropper#741]
Do we need a specific version of JQuery for this to work?

**Comment by fengyuanchen** [comment]
jQuery 1.9+
jQuery 2.0+
jQuery 3.0+

All works~

**Comment by dolfvdberg** [comment]
Thanks

Where can I find an example to save cropped image using MVC c#

**Comment by superlbr** [comment]
is there a ZeptoJs version? Just replace Zeptojs with JQuery, is it ok? I just do this,but don't know whether works fine

**Comment by roberkules** [comment]
I think the minimum required jquery version should be mentioned in the installation guide. We just tried to add the cropper to our legacy app (using jquery 1.7.x) and where wondering why it wasn't working.

**Comment by fengyuanchen** [comment]
@roberkules The required jquery version list in the repo's **package.json** file:
```json
"dependencies": {
  "jquery": ">= 1.9.1"
},
```

**Comment by roberkules** [comment]
touché

(but not everybody might look there)
