### ISSUE TITLE
Adding re sizable Logo to existing wallpaper Generator

### ISSUE THREAD

**Issue by devbikshu** [fengyuanchen/cropper#744]
Hi,

I have a requirement that i need to add re sizable logo to my existing wallpaper generator before it gets Cropped.

My Site Url : http://cricmovie.com/bb-imagecrop/

My target is to build site like : http://apps.warnerbros.com/pacificrim/wallpapergenerator/

The main difference in both is adding logo before wallpaper gets cropped. i need to add logo to this.

I am very new to programming. Any Help will be grateful.

**Comment by fengyuanchen** [comment]
The Cropper does not support this.

> You can try the native [Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) to draw logo image over another image.

**Comment by devbikshu** [comment]
Thanks for the replay 

I tried to draw logo using Canvas API as you have suggested but how to capture canvas with logo and with the same dimensions??
