### ISSUE TITLE
Cropper upload is not working on IE

### ISSUE THREAD

**Issue by rakeshmobileprogramming** [fengyuanchen/cropper#745]
Hi,
I am using cropper in on of my project. Cropper is working fine on Firefox and Chrome and still not working on IE browser. Please help.

**Comment by fengyuanchen** [comment]
Upload? Are you sure it is an issue of Cropper?

**Comment by rakeshmobileprogramming** [comment]
It's not working on IE 9 and working on IE 10 later.
