### ISSUE TITLE
Behavior within scaled container

### ISSUE THREAD

**Issue by dtgeorge** [fengyuanchen/cropper#748]
Before today I had jquery 1.12 and lates cropper.js.
Today I updated jquery to latest 3.1 and found issue.

I digged a bit and here are results.
Let say we have construction:
`<div id="container">`
`          <div id="preview_container">blablabla</div>`
`          <div id="operation_container">blablabla</div>`
`</div>`
and CSS:
`===== skipped`
`	#container{`
`		transform-origin:left top;`
`		transform:scale(1);`
`		width:100%;`
`		@media @crop_treshhold_size {`
`			transform:scale(1.5);`
`			width: 66%;`
`		}`
`               > div {`
`                       width:200px;`
`             }`
`===== skipped`

That specific scaling is for different screen sizes. I decided to not make separate calculations for cropper init on different screen widths, but just scale a bit a whole container ;) 
'#operation_container' and '#operation_container' is that where we placing cropper preview and cropper canvas for cropping....

Withing cropper.js there are some lines of code, like:
`      $cropper.css((this.container = {`
`        width: max($container.width(), num(options.minContainerWidth) || 200),`
`        height: max($container.height(), num(options.minContainerHeight) || 100)`
`      }));`

Lets say $container is $('#preview_container') and CSS scaling (transform 1.5) is active.
In this case issue is that 
under jquery 1.12 $container.width() == 200
under jquery 3.1 $container.width() == 300

So, under 3.1, cropper sets custom style attr width and height to 300 and then browser scale it 1.5 times... ((

Browser Chrome 51

I googled a bit and found that .width() function at old versions of jquery didn't affected by scale. And there are many people who searched for workaraound to get 300 not 200 )))))) But in my case that jquery issue was for good )))))

Thats it...

**Comment by dtgeorge** [comment]
under jquery 2.2.4 $container.width() == 200

**Comment by fengyuanchen** [comment]
My suggestion is not to use `transform` css style on the container.
