### ISSUE TITLE
Either the library file or the CSS file is not present in the directory //dist/ - Drupal

### ISSUE THREAD

**Issue by frazerf** [fengyuanchen/cropper#752]
I'm trying to add cropper's CDN links in to drupal image widget crop settings but I keep on getting hit with this error - Either the library file or the CSS file is not present in the directory //dist/ - even though when I visit the links they show the minified css and js files.

Does anyone know how to fix this? 

Using Drupal 8
![screen shot 2016-08-02 at 15 49 48](https://cloud.githubusercontent.com/assets/892617/17333041/c5798708-58c8-11e6-92a5-f53550ea4619.png)

**Comment by kierenj** [comment]
With "npm install react-cropper", there's no cropper.css anywhere in the package either as far as I can see

**Comment by kierenj** [comment]
Indeed the "dist" folder only has "react-cropper.js" (not cropper.js, cropper.css and the minified versions).  So either docs are wrong or npm package is wrong I think..

**Comment by fengyuanchen** [comment]
```
npm install cropper
```

**Comment by kierenj** [comment]
Thanks for the thoughtful, considerate reply.

Who knows if this fixed frazerf's issue.. let's close it anyway.

I also see that my issue is with `react-cropper`, so will raise an issue there.
