### ISSUE TITLE
Any way to fit the cropper container to the image size ?

### ISSUE THREAD

**Issue by Wharenn** [fengyuanchen/cropper#755]
Hi,

I'm trying to use this plugin to crop images on my website. However, I don't see how to force an exact fit of the cropper container to the format of my images. There is always a space at the left and right of the image that can be cropped on :

![capture d ecran 2016-08-06 a 12 47 26](https://cloud.githubusercontent.com/assets/276784/17456326/5b722dce-5bd4-11e6-9936-fc062d6e55f1.png)

The ``cropper-wrap-box`` seems always slightly larger than the ``cropper-canvas`` one.
This lead to allow crop outside of the image which is what I don't want.

Am I missing an option or something ?

(I didn't forget to add the ``max-width: 100%`` directive)

Thank you :)

**Comment by fengyuanchen** [comment]
https://github.com/fengyuanchen/cropper/blob/master/examples/responsive-container.html

**Comment by Wharenn** [comment]
I'm sorry to say this still does not work.

**Comment by OKNoah** [comment]
I don't see how that helps either.

**Comment by pedromamede** [comment]
Have the same "problem" and the responsive-container sample did not solve it.

**Comment by kamal0808** [comment]
Is there a solution to this?

**Comment by Wharenn** [comment]
Hi, I found a workaround for the unwanted spaces by increasing the size of the copper container (with the same ratio). This is still not a fix for me as I am not sure how it will behave on smaller screens. However I still had other issues with negative coordinates (-1;-1) for the crop top left coordinate when the selection is stretched to the borders. Had to handle it server side to force it to 0.

**Comment by Necare** [comment]
Probably you don't need this anymore, but I was working on a project which integrate this library and dropzone.js and I just developed yesterday what you are asking for.

In my case, I needed to set a fixed values for width (900px) and height (600px) properties, for make sure the image is not too large and ruin my layout. First thing I do is to get the size (width and height) of the original image. After that I compare both values to obtain which is higher (width or height) so I can calculate the coefficient to re-scale the image to my stated values (900/600px).

```
var img = new Image(); 
img.src = dataURL; //dataURL is a base64 image data code previusly obtained.
img.onload = function(){
	//This is only for load the original image into my modal window, no real deal for this example.
	$("#crop_image").attr('src', dataURL);

        //When the image is loaded I get all the data of original image so I can compare and calculate the coeff.
	var coef = 0;
	img.width>img.height ? coef = calculateCoeff(img.width,"width") : coef = calculateCoeff(img.height,"height");
		
       	//When I finally have the coefficient, then I create and load the cropper library.
	createCropper((coef*img.width),(coef*img.height));
}
```

This is the function to calculate the coefficient of reduction (just a simple rule of three):

`function calculateCoeff(image_value, property){
	var x = 0;
	property=="width" ? x=900 : x=600;
	return ((x*100)/image_value)*0.01;
}`

And this is the function to inicializate cropper library:

`
function createCropper(width, height){
	var image = document.getElementById('crop_image');
	var cropper = new Cropper(image, {
		viewMode: 2,
		aspectRatio: 2 / 3,
		movable: false,
		zoomable: false,
		minContainerHeight: height,
		minContainerWidth: width,
		minCanvasHeight: height,
		minCanvasWidth: width,
		preview: ".crop_preview",
		crop: function(e) {
			    console.log(e.detail.x);
			    console.log(e.detail.y);
			    console.log(e.detail.width);
			    console.log(e.detail.height);
			    console.log(e.detail.rotate);
			    console.log(e.detail.scaleX);
			    console.log(e.detail.scaleY);
			    //console.log("-> Crop box is moving! "+e.detail.x+" / "+e.detail.y);
		}
	});
}
`

I hope this can help to you!

**Comment by fengyuanchen** [comment]
In short: 

```css
.container {
  max-width: 100%;
  margin: 0 auto;
}

.container img {
  /* This is important */
  width: 100%;
}
```

**Comment by mortal-fighter** [comment]
if it's still important for somebody setting viewMode: 1 in options helped me

**Comment by acelot** [comment]
**Do not place any sibling elements to image container!**
```
<div class="img-container">
    <img src="..."/>
    <!-- DO NOT PLACE ANYTHING HERE -->
</div>
```
If you want to place any controls, place them into another div like this:
```
<div class="my-cropper">
    <div class="img-container">
        <img src="..."/>
    </div>
    <div class="controls">
        <!-- CONTROLS -->
    </div>
</div>
```

**Comment by BugDroid-Duarte** [comment]
I stil couldn´t apply any solution to my project, nothing works, any tip of something that i could be missing ?

**Comment by wsauvage** [comment]
Hi,
If somebody is still interested.
`viewMode : 2`
solve my problem.

**Comment by adnanganie** [comment]
Use this
 cropper = new Cropper(image, {
         viewMode:2,
          aspectRatio: 2,
}

**Comment by yethuaungptu** [comment]
Please how to fix it @fengyuanchen 
![screenshot from 2018-06-07 18-26-28](https://user-images.githubusercontent.com/25340840/41099859-cbc00a26-6a85-11e8-9610-af6129c85694.png)

**Comment by u2u4u** [comment]
view this link:
[https://stackoverflow.com/questions/42377243/how-to-set-crop-box-to-full-width-and-full-height-of-the-container-previewcropp](url)
Put:
`var contData = cropper.getContainerData(); //Get container data
cropper.setCropBoxData({ height: contData.height, width: contData.width  }) //set data`
in `crop` event

**Comment by Rushanf** [comment]
Set the image width as 
```
.img-container img {
  /* This is important */
  width: 100%;
}
```
And Set 

`cropper = new Cropper(image, {
viewMode:3,
aspectRatio: 1
}`

**Comment by kramsram** [comment]
> Set the image width as
> 
> ```
> .img-container img {
>   width: 100%;
> }
> ```
> And set options as followed
> 
> `cropper = new Cropper(image, { viewMode: 3, aspectRatio: 1 }`

ViewMode 3 and aspect ratio seems to have an impact on how the image fills the canvas. Most others seem to not do much at all.

**Comment by pero5ar** [comment]
if it's a full sized image `autoCropArea: 1` should do the trick, although it depends on your specific scenario.

**Comment by help-me-help-you** [comment]
> https://github.com/fengyuanchen/cropper/blob/master/examples/responsive-container.html

https://fengyuanchen.github.io/cropperjs/examples/responsive-container.html

Updated link

**Comment by ashrafali-v** [comment]
I think viewMode: 0 will help to fit any image inside the cropper.

**Comment by ivansergeevichlobodyuk** [comment]
> if it's a full sized image `autoCropArea: 1` should do the trick, although it depends on your specific scenario.

good solution!!! without any hard codes and calculation sizes

**Comment by ncjoshi** [comment]
In coropper.js there is a variale
autoCropArea which is set to 80% 
you can set it to 100%

**Comment by fengyuanchen** [comment]
@ncjoshi Just set the `autoCropArea` option to `1` (100%), default to `0.8` (80%).

**Comment by lingtalfi** [comment]
For me, what worked was to zoom out inside the ready event (https://github.com/fengyuanchen/cropperjs#ready-1). I wish there was an initial zoom level option by the way (would have been simpler).

```js
// ...
var cropper;
image.addEventListener("ready", function(){
    cropper.zoom(-100);
});
cropper = new Cropper(image);
// ...
```

**Comment by jeromesheerin** [comment]
I just edited the cropper.css file that is included as part of the plugin. and changed the css line as following:

Changed it from:
.cropper {
  max-width: 700px;
}

to this:

.cropper {
  max-width: 100%;
}

Fixed my problem straight away. 

Make sure your surrounding divs are not restricting the width of the inner divs. (Use chrome/firefox inspect mode to see this)

**Comment by ozairasmat** [comment]
i think you should try like this 



cropper = new Cropper(image, {

      viewMode: 2,
      autoCropArea: 1,
      center: true,
      restore: false,
      zoomOnWheel: false

  });
