### ISSUE TITLE
How can i get cropped data as base64 format?

### ISSUE THREAD

**Issue by MuratCool** [fengyuanchen/cropper#757]
Hi everybody,

I downloaded the latest version 2.3.3 of cropper plugin.
But i don't understand how can i get cropped image as base64 format.
Could you give me an example without model window?.

Thank you.

**Comment by fengyuanchen** [comment]
`$().cropper('getCroppedCanvas').toDataURL()`

> Docs: https://github.com/fengyuanchen/cropper#getcroppedcanvasoptions
