### ISSUE TITLE
Fit canvas to fixed container

### ISSUE THREAD

**Issue by ver1000000** [fengyuanchen/cropper#761]
Hello.

I have fixed container 600*600.
Is there way to load canvas with max container width and height?

Now it resize container height according image aspect:
![screenshot_1](https://cloud.githubusercontent.com/assets/3034821/17678204/62d2842c-6360-11e6-96e7-9d01980a2975.jpg)

I need to fit canvas of 600px max height:
![screenshot_2](https://cloud.githubusercontent.com/assets/3034821/17678213/679c5294-6360-11e6-8b0e-18843d576a3f.jpg)

**Comment by fengyuanchen** [comment]
```css
.image-container {
  width: 600px;
  height: 600px;
}
```

**Comment by ver1000000** [comment]
Great. Thank you!
However, be noted that .image-container should be an immediate parent of image
