### ISSUE TITLE
Setting cropBoxResizable to false doesn't work if you click and drag anywhere outside the crop box

### ISSUE THREAD

**Issue by mrj365** [fengyuanchen/cropper#762]
Chrome 52.0.2743.116 m

Steps to reproduce 
Go to: https://fengyuanchen.github.io/cropperjs/
Toggle cropBoxResizableOption to off
Click outside of the crop box and drag.
The crop box is resized
This also happens in chrome on android.

**Comment by fengyuanchen** [comment]
You also need to set the `dragMode` option to `'none'` for this case.

**Comment by egemenu** [comment]
@fengyuanchen didn't work for me.

i have an aspectRatio and as you said the settings are: 
dragMode: 'none',
cropBoxResizable: false,

but when you click outside of "cropbox" its still resizeable that i don't want. tested in firefox and chrome. its closed topic but hopefully still you re gonna see that issue.

**Comment by fengyuanchen** [comment]
You may need to set the `toggleDragModeOnDblclick` option to 'false' too.
