### ISSUE TITLE
Exif orientation change

### ISSUE THREAD

**Issue by mattjs** [fengyuanchen/cropper#764]
When reading the exif headers to handle orientation changes, the user options should not affect wether or not the image is oriented properly.

```javascript
// in Cropper.prototype.read

//if (options.rotatable) {
  image.rotate = rotate;
//}

//if (options.scalable) {
  image.scaleX = scaleX;
  image.scaleY = scaleY;
//}
```

I think the if statements should be removed here, unless I misunderstand this block of code.

**Comment by fengyuanchen** [comment]
Read the docs: https://github.com/fengyuanchen/cropper#checkorientation
