### ISSUE TITLE
Incorrect check for 90 degrees rotation after browser resize

### ISSUE THREAD

**Issue by OlenaPianykh** [fengyuanchen/cropper#765]
I found a bug with image rotation and updating canvas after that. Canvas gets incorrect size after image rotation on 270 degrees and resizing browser after that.

I'm using cropper with viewMode = 1, and I have rotation functionality. I'm rotating image with each user's click on 90 degrees.

```
        this.degrees += 90;
        if (this.degrees >= 360) {
            this.degrees -= 360;
        }
        this.refs.cropper.clear();
        this.refs.cropper.rotateTo(this.degrees);
        this.refs.cropper.crop();
```
So when image was rotated on 270 degrees (or -270deg) and then browser window  was resized, there is canvas updating is performed in functions:
- resize
- render
- initCanvas
And in function initCanvas there is check-flag       
`var is90Degree = abs(image.rotate) === 90;`
Using this flag, these values are swapped:
```
  var naturalWidth = is90Degree ? imageNaturalHeight : imageNaturalWidth;
  var naturalHeight = is90Degree ? imageNaturalWidth : imageNaturalHeight;
```
270 degrees causes the problem, because image values also need to be swapped (as in case of 90 or -90 degrees) and in this case they are not swapped that's why canvas gets incorrect size values.  And position of image becomes incorrect too. 
In my case, when viewMode is set to 1, crop-box are moving in small area inside the image, but it should be movable inside all image.

For resolve this issue I put condition inside my code: 
```
if (this.degrees === 270) {
            this.refs.cropper.rotate(-90);
        } else {
            this.refs.cropper.rotate(this.degrees);
        }
```
But it would be great if this issue is fixed.
Thank's.

**Comment by fengyuanchen** [comment]
It might be a problem of your own logic code.
