### ISSUE TITLE
2.3.3 with webpack

### ISSUE THREAD

**Issue by breslavsky** [fengyuanchen/cropper#767]
Hello! Thanks for good work.

I use  cropper 2.3.2 with webpack 1.13.1.
I set global jquery in webpack.common.js
```
new webpack.ProvidePlugin({
    jQuery: 'jquery',
    $: 'jquery',
    jquery: 'jquery'
})
```

Next in vendor.ts I add:
```
import 'jquery';
import 'cropper';
```

Then in my code I use:
```
declare var $:any;
$(this.target.nativeElement).cropper(...);
```

all works fine.
But when I updated cropper to 2.3.3 I catch in console "cropper is undefined".

Please help. Thanks.

**Comment by fengyuanchen** [comment]
Are you sure you were using the Webpack in a correct way?

**Comment by breslavsky** [comment]
I use https://github.com/AngularClass/angular2-webpack-starter in my project.

Another plugins: selectize, slick works fine and cropper 2.3.2 too. Problem only with 2.3.3.

**Comment by fengyuanchen** [comment]
Remove the `dependencies` from the **package.json** and try again.

**Comment by erikwestlund** [comment]
I use webpack through Laravel Elixir. 2.3.2 works fine. 2.3.3 breaks.  I specified 2.3.2 in package.json -- all good.

I don't get any compile errors. It just doesn't load the cropper as expected.

**Comment by fengyuanchen** [comment]
Try the latest version please.
