### ISSUE TITLE
Cursor outside of rectangle

### ISSUE THREAD

**Issue by strohhut** [fengyuanchen/cropper#768]
When you draw a rectangle on the demo page the cursor is not aligned with the corner that lies opposite of the starting point. I think when drawing a rectangle the end point should be where the cursor is currently.

Here on the image I'm currently drawing a rectangle and when I move the mouse the rectangle still changes its size but the endpoint isn't where it should be. This happens when you don't move the move in an exact diagonal way.

![temp](https://cloud.githubusercontent.com/assets/15095059/18027947/4434b1ec-6c71-11e6-9f53-c9ac9db5eb39.JPG)

Tested in latest Firefox and Chrome.

**Comment by fengyuanchen** [comment]
Just because the aspect ratio in the demo is 16:9.
You can try to set the `aspectRatio` option to `NaN`.

**Comment by strohhut** [comment]
@fengyuanchen This fixes it when the cursor always stays on the image but when it leaves the image while keeping the mouse pressed and then reenters the image area I think the problem still exists.

![temp](https://cloud.githubusercontent.com/assets/15095059/18066738/fb897962-6e39-11e6-9082-f6c6e851b3b7.JPG)
