### ISSUE TITLE
Image Size issue : POST Content-Length of 3587824 bytes exceeds the limit...

### ISSUE THREAD

**Issue by p6naveen** [fengyuanchen/cropper#769]
Hi,

I have integrated this plugin to my application, I have selected 886KB (2880x1800) image to upload. But at the server end its showing the actual size of the image.

3587824 bytes = 1.24 MB.

**below are the configuration details.**

`$('#image').cropper({
    viewMode: 1,
    dragMode: 'move',
    restore: false,
    guides: false,
    highlight: false,
    movable: false,
    cropBoxMovable: true,
    cropBoxResizable: false,
    zoomable: false,
    preview: '.img-preview',
    built: function() {
        // Width and Height params are number types instead of string
        $image.cropper("setCropBoxData", {
            width: 200,
            height: 200
        });
        //$image.cropper("setCanvasData", {width: 300, height: 300});
    },
});`

**Jquery AJAX code**

`var imageData = $($image).cropper("getCroppedCanvas").toDataURL();
formData.append('avatar_data', imageData);
$.ajax("<?php echo base_url() . 'index.php/upload_avatar'; ?>", {
    method: 'POST',
    data: formData,
    processData: false,
    contentType: false,
    success: function(data) {
        console.log(data);
        alert("Image uploaded successfully");
    },
    error: function() {
        alert("Error: Please try again");
        location.reload(true);
    }
});`

**PHP Server Side Script**

echo $size = (int) $_SERVER['CONTENT_LENGTH'];

**Error I am receiving in console.**
<b>Warning</b>:  POST Content-Length of 3587824 bytes exceeds the limit of 3145728 bytes in <b>Unknown</b> on line <b>0</b><br />

Could you please suggest me, if any configurations to be updated.

Thanks,
Naveen

**Comment by fengyuanchen** [comment]
Are you sure this is an issue of the Cropper?

**Comment by p6naveen** [comment]
Hi,

This the image I used to test.

https://s11.postimg.org/8mtzrv0df/gorgeous_new_bmw_i8_2880x1800_wallpaper_18528.jpg
