### ISSUE TITLE
When will `setCanvasData` or `setCropBoxData` do not work?

### ISSUE THREAD

**Issue by HellenDu** [fengyuanchen/cropper#770]
I'm using `setCanvasData` and `setCropBoxData` on the built hook, but it doesn't work, then I try to use `moveTo` to change to offset of canvas, but it doesn't work either.

So, my question is that when will `setCanvasData` or `setCropBoxData` do not work?

By the way, is there any option to initialize the cropper without setting the canvas middle of the container?

**Comment by fengyuanchen** [comment]
https://github.com/fengyuanchen/cropper/blob/master/examples/cropper-in-modal.html
