### ISSUE TITLE
How to save images after user finish manipulating it

### ISSUE THREAD

**Issue by VCardWEb** [fengyuanchen/cropper#775]
Hi, more than an issue I'd like to know how do I save the generated images, yes imageS, I need to upload the original image and the cropped images, so total images to be saved are 3 from the original,
1.- **Original image**
2.- **Cropped Canvas**: the data from getCroppedCanvas,
3.- **Specific Crop area**: data from data-option="{ "width": 800, "height": 600 }"  Data-method="getCroppedCanvas"
Do once the use click on a button named "Done" I'd like to save that information on the server so the images can be use latter. how do I do that?
Thanks in advance.

**Comment by chrisribe** [comment]
I agree with VCardWEb,

It's not clear how to save the data once done. There are so many button examples...

I figured out that getCroppedCanvas opened a popup with the cropped image data on the download button (data:image base64). But maybe some example in the docs or on the [demo website](https://fengyuanchen.github.io/cropper/) on how to pass that to your server.

Chris

**Comment by fengyuanchen** [comment]
Here is a complete example for cropping image and save it in the server side with PHP: https://github.com/fengyuanchen/cropper/tree/master/examples/crop-avatar

**Comment by Brisingr97** [comment]
Page not available anymore^

**Comment by fengyuanchen** [comment]
@Brisingr97 https://github.com/fengyuanchen/cropper/tree/v3.1.6/examples/crop-avatar
