### ISSUE TITLE
Event when the image is successfully loaded

### ISSUE THREAD

**Issue by NovaDev94** [fengyuanchen/cropper#780]
For some reason, I need to call `getCroppedCanvas` on event `crop.cropper`. However, the returned canvas is always blank at the first call, and `crop.cropper` is called even when the image is loading into the cropper.  

I've setup something like this

```js
$(img).cropper({
  built: function() {
    console.log('built');
    $(img).on('crop.cropper', function() {
      console.log('cropped');
      $(img).cropper('getCroppedCanvas');  // return a blank image at first run
    });
  }
});

// The log is printed even the image hasn't finished loading yet
// built
// cropped
```

So is there anyway to overcome this or get an event when the image is successfully loaded into the cropper?

**Comment by fengyuanchen** [comment]
```js
$(img).cropper({
  built: function() {
    console.log('built');
    $(img).cropper('getCroppedCanvas');
  }
});
```

**Comment by NovaDev94** [comment]
@fengyuanchen As I explained in the issue. The problem is when `built` is raised, the image still not loaded fully yet, so `getCroppedCanvas` returns a blank image.

**Comment by fengyuanchen** [comment]
Check the source code, you will find that the `built` event is triggered after the `load` event of the image triggered.
