### ISSUE TITLE
Feature request: disable X or Y in cropper

### ISSUE THREAD

**Issue by webtrix** [fengyuanchen/cropper#781]
Hi,

I was wondering if it would be possible to add a small new feature to the cropper. Now you can disable the cropper or enable it. When it's enabled, you can scale the cropper to what ever format you like, that's nice.. but in some cases that's also a drawback.

If it would be possible to set a fixed `width` or `height` on the cropper, so that in case of a fixed `width` the height could still be changed, or the other way around. Now this isn't possible, and I think it would really be a cool feature to have.

**Comment by fengyuanchen** [comment]
You can limit it in the `cropmove` event by `event.preventDefault()`.
