### ISSUE TITLE
minContainerHeight and minContainerWidth are not working properly in live.

### ISSUE THREAD

**Issue by s-sk** [fengyuanchen/cropper#782]
minContainerHeight and minContainerWidth are not working properly in live.

In local environment it is working properly but in live custom minContainerHeight and minContainerWidth values are not reflated. It set container height same as image (original height) height. Although resized image is displaying is properly in modal.

what i want is both canvas size and container size should be same.
var $image = $("#image);
                       originalData = {};
$image.cropper({
                     minCanvasHeight:750,
                     minCanvasWidth:c1000,
                     minContainerHeight:750,
                     minContainerWidth:1000,
                     aspectRatio: 100/100,
                     resizable: true,
                     zoomable: false,
                     rotatable: false,
                     multiple: true,
                     responsive:true,
                     minCropBoxWidth:120,
                     minCropBoxHeight:120,
                  crop: function(data){
                            var json = [
                                '{"x":' + data.x,
                                '"y":' + data.y,
                                '"height":' + data.height,
                                '"width":' + data.width + '}'
                            ].join();
                            $('#cropImage').val(json);
                   }
             })

**Comment by s-sk** [comment]
Please help me @fengyuanchen

**Comment by forest-devil** [comment]
2 weeks passed, did you solve it your self? if so please close this issue yourself.
If not solved yet, I think by now you might have been fired.

**Comment by fengyuanchen** [comment]
There is a similar example in the repository already: https://github.com/fengyuanchen/cropper/blob/master/examples/full-crop-box.html
