### ISSUE TITLE
Feature Request: Make Cropped Area Sticky i-e follow image when rotated / scaled

### ISSUE THREAD

**Issue by omeryousaf** [fengyuanchen/cropper#783]
The user should not have to manually reselect the part of the image previously selected (i-e inside cropbox) after a rotation or scaling is applied. The motivation is described in a bit more detail at https://stackoverflow.com/questions/39672960/fengyuanchen-cropper-keep-the-same-part-of-image-selected-in-cropping-area-af.

**Comment by forest-devil** [comment]
You've forgot rotating is not restricted to 90° only, what are you expecting when you rotate the image by only 1°? 
You should save the crop data before rotating, after you flip the image, you should calculate the new crop area data and set it via method call. This logic is so specific that it should be implemented by you, not the plugin it self.

**Comment by forest-devil** [comment]
You've forgot rotating is not restricted to 90° only, what are you expecting when you rotate the image by only 1°? 
You should save the crop data before rotating, after you flip the image, you should calculate the new crop area data and set it via method call. This logic is so specific that it should be implemented by you, not the plugin it self.

**Comment by omeryousaf** [comment]
@forest-devil hmm, you have a point. Btw, the way plugin currently specifies cropped area (using location of top left corner, and width and height of cropped area) it seems there is no way of displaying cropbox (even if i can calculate the four vertices of the cropbox after a rotation) unless the rotation is in multiples of 90°. So the specification of cropbox needs to change in order to support the sticky cropbox with respect to image rotations, right ? May be specification should comprise locating each of the four vertices of the cropbox rather than only top left vertex and magnitudes of width and height.

For 90 degree rotations, though, I have implemented the sticky cropbox with cropper for our application. Our application involves simple left/right 90° image rotations and cropping.

**Comment by forest-devil** [comment]
> So the specification of cropbox needs to change in order to support the sticky cropbox with respect to image rotations

> specification should include/comprise locating each of the four vertices of the cropbox rather than only top left vertex and magnitudes of width and height

Yep, that's the reason, changing the spec will change the plugin's underlying data structure, which is not likely affordable. For 90° situation, the plugin has provided enough events and methods, so you can insert your logic. For other angles this plugin simply can't handle.

The current logic is the crop area will stick to the whole canvas, not the image being cropped, which also makes sense, but in further will there be an option to make the center point of the crop box stick to the source image? I've not read the code thoroughly, so I can't say if it is difficult. The only thing bothers me is when you call `'setAspectRatio' ,`the plugin doesn't maintain the crop area's size, it simply re-initialize the cropper with the new aspect ratio. I think it would be better if it only do a 90° rotation for the crop box, maintaining the center, just like the `rotate and `rotateTo do. If this plugin can provide more handy functions like `getCropAreaCenter and `setCropAreaCenter it would be even better, but I think maybe I'm asking too much...

**Comment by chaoaretasty** [comment]
I agree that a selection shouldn't be sticky with respect to rotation but should be sticky with respect to zoom. As well as being the more expected behaviour (a rotation naturally feels like an edit to the image, a zoom feel like an edit to my view of a worksapce) this is also the common behaviour in a variety of image editing software.
