### ISSUE TITLE
Unable to restore cropped area after zooming

### ISSUE THREAD

**Issue by renspoesse** [fengyuanchen/cropper#784]
I'm trying to save the cropped area data (from getData) and the zoom factor of the image (canvas.width / canvas.naturalWidth) and then restore it after the cropper has been rebuilt.

_(I'm rebuilding in the example. In reality, data will be stored on a server and the cropper will be rebuilt later when the user wants to change the image again)._

As can be seen in my [test case](http://tinyurl.com/z2l9t75), this doesn't go well when:

1. Zooming in
2. Dragging the crop box and,
3. Dragging the image and,
4. Clicking Restore Crop Box

This is what I'm basically doing in the code:

```
var d = $image.cropper("getData");
var c = $image.cropper("getCanvasData");

var restoreData = {

    x: d.x,
    y: d.y,
    width: d.width,
    height: d.height,
    zoom: c.width / c.naturalWidth
};

# (Code to rebuild the cropper. After it has been built:)

$image.cropper("zoomTo", restoreData.zoom);
$image.cropper("setData", _.extend(_.clone(restoreData), {

     rotate: 0,
     scaleX: 1,
     scaleY: 1
}));
```

I'm not sure if I'm missing something or if this is a bug in the cropper plugin!

**Comment by forest-devil** [comment]
why not call `setData to restore what you saved from `getData , then use `setCanvasData to set what you got from `getCanvasData ? your data structure is weird

**Comment by fengyuanchen** [comment]
@renspoesse for you case, you need to save both data get from `getCanvasData` and  `getCropBoxData`, and then restore it with the `setCropBoxData` and  `setCanvasData`.

Note: you should call the  `setCropBoxData` before `setCanvasData`.

Similar example: https://github.com/fengyuanchen/cropper/blob/master/examples/cropper-in-modal.html
