### ISSUE TITLE
custom image aspect ratio

### ISSUE THREAD

**Issue by emrahlok** [fengyuanchen/cropper#785]
I want to make custom image aspect ratio. I examined your code. I can't find it. Is it possible? Please help me.

**Comment by forest-devil** [comment]
Can't get your point, i guess you can describe it in Chinese?

**Comment by fengyuanchen** [comment]
@emrahlok Are you want something like the [`aspectRaio`](https://github.com/fengyuanchen/cropper#aspectratio) option?
