### ISSUE TITLE
$(...).cropper(...).toBlob is not a function

### ISSUE THREAD

**Issue by cschoeni** [fengyuanchen/cropper#786]
Failure in the Developer view in Chrome. When i have that, give me the Feedback below.
 
// Upload cropped image to server if the browser supports "HTMLCanvasElement.toBlob"
`
    $().cropper("getCroppedCanvas").toBlob(function (blob) {

      var formData = new FormData();

      formData.append('croppedImage', blob);

      $.ajax("/test", {
        method: "POST",
        data: formData,
        processData: false,
        contentType: false,
        success: function () {
          console.log("Upload success");
        },
        error: function () {
          console.log("Upload error");
        }
      });
    });`

**Comment by omhybrid** [comment]
yes right is not working

**Comment by fengyuanchen** [comment]
See the [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob#Browser_compatibility) of `HTMLCanvasElement.toBlob()`.
