### ISSUE TITLE
.toBlob() not working on any mobile browser on iPhone.

### ISSUE THREAD

**Issue by rgins16** [fengyuanchen/cropper#788]
I am building a web app using MEAN.JS and OnsenUI. Latest version of everything. 
For Desktop: I am testing in Chrome.
For Mobile: iPhone 5C on Chrome/Safari, latest version of all software.

WHAT I HAVE SUCCESSFULLY DONE (on Desktop Browser):
Pretty much everything. I can upload a file, crop it, and upload it to my server. Everything works wonderfully, and as expected. 

PROBLEM (on mobile): 
The exact same code does not work on mobile. After some alert messages and try/catch, I narrowed the problem down to this line:
`$('#image').cropper('getCroppedCanvas' , {width: 200, height: 200}).toBlob(function (blob) {`

I stuck a try/catch around this and displayed an alert in the browser. Here is screenshot of the alert message taken on my phone:
![image1](https://cloud.githubusercontent.com/assets/16677164/19204237/a1e5330e-8ca9-11e6-9efe-e2e72f613e05.PNG)

It appears your .toBlob function does not work on mobile.

**Comment by fengyuanchen** [comment]
See the [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob#Browser_compatibility) of `HTMLCanvasElement.toBlob()`.
