### ISSUE TITLE
UI for rotating the image

### ISSUE THREAD

**Issue by forest-devil** [fengyuanchen/cropper#789]
Firstly, this plugin is really amazing, it works like a charm in practice.

However, the default cropping UI can do everything except for **rotating**, like the demo on the [website](https://fengyuanchen.github.io/cropper/), the rotating is done by toolbar buttons, not so much WYSIWYG.

Is it possible to add a "handle" or something alike to respond to mouse dragging, but instead of rotating the cropping box, it rotates the original image instead? I think the UI of PowerPoint may be a good reference.
![image](https://cloud.githubusercontent.com/assets/941314/19300563/8fc1ffee-908d-11e6-9f90-c9979d14d53f.png)

**Comment by fengyuanchen** [comment]
You can customize a toolbar for these actions by your self. Here is a similar [example](https://fengyuanchen.github.io/photo-editor/).
