### ISSUE TITLE
autoCrop: false not working

### ISSUE THREAD

**Issue by The-Nutty** [fengyuanchen/cropper#790]
I will attach my code bellow but even with autoCrop: false,. The method crop: function(e) { is being called when ever the crop box is resized/moved.

I could be using the wrong method but any help is appreciated. 

Thanks

Code:
https://gist.github.com/The-Nutty/23e76fd53aa75f8095874ff3717abf5f

**Comment by kiarash3tar** [comment]
I have same issue too

**Comment by fengyuanchen** [comment]
@all Works as expected. Check your own code carefully.
