### ISSUE TITLE
Multiple crops from single photo?

### ISSUE THREAD

**Issue by dakipro** [fengyuanchen/cropper#791]
Hi,
fantastic script, exactly what I need for a project. I was just wondering if it is possible to have multiple crops from the single photo?
For example, if there are two (or more) elements on the single photo that would be saved in two separate cropped images?
Say there is a dog and a cat on one photo, could you crop dog in one photo, and cat into the another photo, both from single uploaded image?

Thanks in advance

**Comment by fengyuanchen** [comment]
You can move the crop box over the dog and crop it by call the `getCroppedCanvas`, then move the crop box over the cat and crop it again.
