### ISSUE TITLE
UI for resizing (zooming) the image

### ISSUE THREAD

**Issue by cryve** [fengyuanchen/cropper#793]
This peace of software looks really promising and I'd love to use it, but I'm missing a way to resize/zoom the image like in Photoshop or Powerpoint. Currently this can only be done by the mouse wheel, but this lacks precision/usability as I have a non movable cropbox.

Basically, it should be like resizing the cropbox, i.e. with resize handles which you can click and drag. This is already proposed for rotation in issue #789 and could be combined somehow by enable toggling rotation/resize mode.

**Comment by forest-devil** [comment]
+1 for this.
In practice, I'm handling both rotation and zooming with additional sliders to make it more precisely. but if the plugin's UI can support these in the canvas area, it will be fantastic.

**Comment by fengyuanchen** [comment]
You can customize a toolbar for these actions by your self. Here is a similar [example](https://fengyuanchen.github.io/photo-editor/).

**Comment by aykinlowi** [comment]
hello fengyuanchen. good day. i wonder how did you do the "OK" function after the crop in that example you've posted above.. im very new to programming and i need the code that is exactly how you did it in that example above this post.. i want to add a "OK" button after the user (system user) crop the image.. thank you so much fengyuanchen..
![cropper](https://cloud.githubusercontent.com/assets/25896237/23117017/76017e0a-f702-11e6-9f5c-736e8f5e7831.png)

**Comment by fengyuanchen** [comment]
@aykinlowi Here is the source code: https://github.com/fengyuanchen/photo-editor/tree/gh-pages/src

**Comment by aykinlowi** [comment]
thank you so much sir. i really really appreciated it. im using your
cropper plugin in my school project. thanks

**Comment by cryve** [comment]
@fengyuanchen You closed this issue, does that mean you decided against image resizing by dragging the image vertices (handles)? 

What I actually meant was an UI without additional toolbars/sliders, which becomes handy, when dealing with fixed cropboxes for stuff like profile images etc... Just like this:
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/5485480/23650099/3faa505e-0321-11e7-832b-97ae9ea54e5a.gif)

**Comment by fengyuanchen** [comment]
@cryve We will not support this.
