### ISSUE TITLE
maxCropImageWidth not working.I had to limit the highest crop box width and height

### ISSUE THREAD

**Issue by afzydev** [fengyuanchen/cropper#794]
Hello

I had to fixed the size of the crop box to maximum level.But i am not able to achieve.Please suggest me.I need urgent help.

Thanks

**Comment by afzydev** [comment]
hii

please suggest me how to do this i am unable to do that.

Thanks

**Comment by fengyuanchen** [comment]
What the `maxCropImageWidth` is? I don't know it at all.
