### ISSUE TITLE
Multiple cropper in the same page

### ISSUE THREAD

**Issue by juanmarinelli** [fengyuanchen/cropper#795]
Hello fengyuanchen ! the example is fantastic! but i have a problem when i have two croppers in the same page
i have one in a modal and the other in an other modal, the first charging works well but no the second
how is the problem? I must be rename de functions? 
thanks

**Comment by hotNoder** [comment]
@juanmarinelli how did you initialize the cropper ? I have faced some problems too when I have mutiple coppers at the same page. I initialize the copper using $('.copper').copper(..)。Then I found when I $().cropper('getData')，it would always return the data of the first $('.cropper')。
Hope this makes sense for you.

**Comment by juanmarinelli** [comment]
I solved at the moment with ajax. when I click on the button initialize the main_cropper.js but I think it is not the best solution
