### ISSUE TITLE
Javascript:void(0); error while downloading image in safari browser

### ISSUE THREAD

**Issue by devbikshu** [fengyuanchen/cropper#796]
Hi,

I am getting **Failed to load resource: unsupported URL**   **Error loading javascript:void(0);** in my safari browser console while downloading image through getCroppedCanvas. this is happening only with safari browser.

any help in this regards will be greatful?

thanks

**Comment by fengyuanchen** [comment]
Safari does not support the `download` attribute: http://caniuse.com/#feat=download.
