### ISSUE TITLE
Fixed crop-box, drag image

### ISSUE THREAD

**Issue by ext** [fengyuanchen/cropper#8]
Feature request: I would like to have a fixed crop-box and drag the image around instead of moving the crop-box.

**Comment by boblikesoup** [comment]
This feature is broken for me.  I'm using all the same attributes as the demo and the crop box isn't fixed:

$('.cropper-example-1 > img').cropper({
  aspectRatio: 16 / 9,
  autoCropArea: 0.65,
  strict: false,
  guides: false,
  highlight: false,
  dragCrop: false,
  cropBoxMovable: false,
  cropBoxResizable: false
});

**Comment by Ice32** [comment]
I'm looking for the same feature, @fengyuanchen could you let us know what are the attributes needed to accomplish it (drag only the image, while having fixed crop box)?
