### ISSUE TITLE
Image compression

### ISSUE THREAD

**Issue by hemaxox** [fengyuanchen/cropper#800]
Hi,

I am using your wonderful library but I have a question. When I use the cropper code below
dataURL = $(".uploaded-tile-holder>span>img").cropper("getCroppedCanvas", {   width  : 640 }).toDataURL();
imagejpeg($image, $source_url, $quality);

Is there a way I can control compression ratio before running imagejpeg function. 

Thanks,

**Comment by fengyuanchen** [comment]
```js
dataURL = $(".uploaded-tile-holder>span>img").cropper("getCroppedCanvas", { width : 640 }).toDataURL('image/jpeg', 0.8);
```

> Spec: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL
