### ISSUE TITLE
about the preview pics getting smaller

### ISSUE THREAD

**Issue by amilyxy** [fengyuanchen/cropper#803]
Hello 
I ‘m troubled by a problem that  i preview in a fixed size container through { preview:document.getElementById('large') } and when each change of image the preview size will reduce 2px it’s the element.style changes the css Weights;
It may my problem but i want to ask for help ;
this is my container css
#large {
      float: left;
      width: 200px ;
      height: 200px ;
      margin: 10px 0 0 20px;
      border: 1px solid rgb(98, 98, 95);
      overflow: hidden;
}

thank you

**Comment by amilyxy** [comment]
Is there a good solution except : width: 200px！important ; height: 200px ！important   ??? ;

**Comment by fengyuanchen** [comment]
The reduced 2px may be the border width of the container, so set:
```css
#large {
  width: 202px ;
  height: 202px ;
}
```

**Comment by amilyxy** [comment]
sorry ，I got a try just now，but it seems can't work ,and when the crop box changes ,the size no longer reduce 2px,it's change with the crop box，and i have learn the cropper demo，but still can‘t find the reason....

each confirm or close the modal or change the photo ，the preview does’nt smaller but the picture smaller 
e...（it's the element.style change）
