### ISSUE TITLE
Cropper in Boostrap Modal - Small image/cropper preview

### ISSUE THREAD

**Issue by hpolonkoev** [fengyuanchen/cropper#806]
Hello @fengyuanchen ,
Thanks for cropper script. Really helpful one.

I have an annoying issue with the cropper inside modal. 

The modal show event is triggered on input upload form. So if I select a file from PC a modal shows up. The issue is that the preview doesn't fit the modal box. The image/cropper is to small. 

![modal_cropper_small](https://cloud.githubusercontent.com/assets/17225291/19813341/933f9416-9d39-11e6-90a1-64a3630c3015.PNG)

On the other hadn if I change the browser size it automatically fit the modal.

![modal_cropper_fit](https://cloud.githubusercontent.com/assets/17225291/19813365/aee92f88-9d39-11e6-8274-f78eebfc1e61.PNG)

 I tried the stuff from https://github.com/fengyuanchen/cropper/issues/85 but don't understand where the `data: originData` comes from. Even using the example from https://github.com/fengyuanchen/cropper/blob/master/examples/cropper-in-modal.html  doesn't work.

Would really appreciate your help.

**Comment by fengyuanchen** [comment]
You **must** initialize the cropper only when the modal has been shown completely!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by hpolonkoev** [comment]
@fengyuanchen Thanks a lot. This actually helped.

**Comment by MironD** [comment]
cant u please show me our solution?, I have the same issue

**Comment by hpolonkoev** [comment]
@MironD sorry mate. 
It has been a year and a half since I worked on the project. Don't have the code and I am not working for this client/company anymore.
Maybe you could create a new issue and post you code.

**Comment by dr-code1996** [comment]
You just set "backdrop: false" in bootstrap modal and find :)
