### ISSUE TITLE
it's about rotate and crop question.

### ISSUE THREAD

**Issue by xflife** [fengyuanchen/cropper#808]
FIrst，thanks for you script,But I have some question: 
drag crop box :
![image](https://cloud.githubusercontent.com/assets/1779757/19928183/581c8ef4-a138-11e6-9ecd-9236fff585de.png)
then,i rotate 90:
![image](https://cloud.githubusercontent.com/assets/1779757/19928216/80bdd8cc-a138-11e6-89a7-eff7fa0805da.png)
it's not what I expect.
may,this last image is my expect:
![image](https://cloud.githubusercontent.com/assets/1779757/19928319/edec90c8-a138-11e6-8245-928c67eb2bec.png)
can u help me?

**Comment by fengyuanchen** [comment]
Before rotate: 

```js
$().cropper('clear')
```

After rotate: 

```js
$().cropper('crop')
```

**Comment by xflife** [comment]
Can I setting crop box after rotation?

**Comment by xflife** [comment]
Can I setting crop box after rotation?

I try use function setCropBoxData or setData,but it does’t not work

**Comment by mirkochan** [comment]
Try to use
`$().cropper("setCropBoxData", { left: 0, top: 0, width: 500, height: 500 });`
or
`$().cropper("setData", {"x":0,"y":0,"width":500,"height":500,"rotate":0,"scaleX":1,"scaleY":1});`

**Comment by xflife** [comment]
I use setCropBoxData or setData before crop,it’s not work,Another,after crop,it’s right.But have some question. crop box size is’t last time size.
