### ISSUE TITLE
Feature request: shift-click an anchor to change crop size symetrically

### ISSUE THREAD

**Issue by cadilhac** [fengyuanchen/cropper#811]
It would be great, like in so many drawing programs, to be able to change the current selection in a symetrical way (relatively to the center) by shift-clicking and moving an anchor.

Thanks

**Comment by fengyuanchen** [comment]
Already support this: https://github.com/fengyuanchen/cropper#faq

**Comment by cadilhac** [comment]
No this is not what I meant. I am not in free ratio mode. I wanted Shift to allow me to move 2 opposite corners symetrically, around the center.
