### ISSUE TITLE
Controling canvas size?

### ISSUE THREAD

**Issue by neotropic2023** [fengyuanchen/cropper#812]
Is there any way to control how big the canvas size is?

I have tried all of these:
minContainerWidth, minContainerHeight, minCanvasWidth, minCanvasHeight
The only change I see in this is the images are greatly enlarged within the copper while the canvas remains the same size.

Ultimately, would be nice to get the cropper and canvas the same size.

Also, when I set the crop box width/height, why is it always 5px smaller?
It also does not center properly.
These do not work properly (Not using all a he same time, used separately. Just adding all the code here)

```
minCropBoxWidth:300,
minCropBoxHeight:300,
built: function () {
	var container = $(this).cropper('getContainerData');
	var cropBoxWidth = 300;
	var cropBoxHeight = 300;
	$(this).cropper('setCropBoxData', {
		width: cropBoxWidth,
		height: cropBoxHeight,
		left: (container.width - cropBoxWidth) / 2,
		top: (container.height - cropBoxHeight) / 2
	});
	$image.cropper('getCroppedCanvas', {fillColor: '#ffffff'});
	$image.cropper("setCropBoxData", { width: 300, height: 300 });
}

```
The cropper is all off center. Not at the top but off the the left and down some. And always random.
The cropper randomly loads images full size in the canvas area. Then decides to load the image at like 25% in size centered at the top.

![capture](https://cloud.githubusercontent.com/assets/2349937/20225072/4af9888e-a7f6-11e6-8395-4bf43094c79a.PNG)
![capture2](https://cloud.githubusercontent.com/assets/2349937/20225076/4ea25682-a7f6-11e6-888a-69966aa52ac2.PNG)

**Comment by fengyuanchen** [comment]
Why control it? Is it necessary?

**Comment by neotropic2023** [comment]
Um, yes? Because that image above is NOT the second size? And the canvas in the first image is to big and a waste of space?

**Comment by hengsoheak** [comment]
http://stackoverflow.com/questions/41002081/fengyuanchen-cropper-typeerror-url-createobjecturl-is-not-a-function

**Comment by kamal0808** [comment]
@fengyuanchen  why did you close this issue? Is it resolved? I am facing a similar issue, but can't find a solution

**Comment by edisonskiploop** [comment]
@fengyuanchen Same issue!

**Comment by mtx-z** [comment]
@fengyuanchen same issue here. It seems to handle correctly the width resize if the image CSS is correctly set. But changing the viewport height is not rightly handled. Resize is then broken on both width/height.
