### ISSUE TITLE
not bug, but performane, slow when using with large image(1M)

### ISSUE THREAD

**Issue by Nomia** [fengyuanchen/cropper#813]
When I save a cropped or rotated image using cropper, cropper will get the datauri of that image/canvas, it will be a very slow process if the image is 1M or more. Small img is ok.

Hope u could improve the performance of this great plugin :>

**Comment by Rituba** [comment]
The same to me, when i upload an image more than 1MB, the preview of the cropped image turns out it has 11MB! But when i upload an image of 705kb nothing wrong happens.

I love this plugin! I dont want to change it :(

**Comment by fengyuanchen** [comment]
The only way is to limit the size of the image for cropping.
