### ISSUE TITLE
Initialization bugs out on dynamically loaded image

### ISSUE THREAD

**Issue by sjilo** [fengyuanchen/cropper#814]
I load a page's content with jQuery's load function:

`      $('#content').load(hash + ' #content >*');
`
And I get this:

![issue5](https://cloud.githubusercontent.com/assets/10420730/20282428/505260ca-aabd-11e6-8e1e-fc7ff6b3dc4c.png)

So far so good, but when I try to initialize the cropper on my image, this happens:

![issue7](https://cloud.githubusercontent.com/assets/10420730/20282449/5f201156-aabd-11e6-9273-0bf534ba3c68.png)

I found out that the images stacked on top of each other are the canvas, crop box, etc.
Ideally, when I don't use dynamic load, the cropper looks like this and works correctly:

![issue4](https://cloud.githubusercontent.com/assets/10420730/20282461/6afb373a-aabd-11e6-861e-0686f03a3c95.png)

Event listener for picture upload: 

`    $(document.body).on('change', '#cover-picture-input, function(){...});
`
After it's uploaded I change my img's src to the uploaded's src and initialize the cropper:

![issue9](https://cloud.githubusercontent.com/assets/10420730/20282798/ee8c8c06-aabe-11e6-9b27-9c769a757966.png)
Thanks!

**Comment by georgikoyrushki95** [comment]
Hey @sjilo , did you find out how to solve this? I am having the same problem.
