### ISSUE TITLE
在Chrome54下，上传图像时，需要10秒左右才能显示出选择文件框

### ISSUE THREAD

**Issue by shun634501730** [fengyuanchen/cropper#820]
并不是所有的Chrome54都存在此问题，我有两个同事都存在这个问题，但是有一个同事却不存在此问题。我是使用最新版的demo，没有修改任何代码。

**Comment by fengyuanchen** [comment]
This problem is caused by the `accept="image/*"` attribute of the file input. Just fixed it with `accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff"`.
