### ISSUE TITLE
Touch zoom chrome issue

### ISSUE THREAD

**Issue by Mafial** [fengyuanchen/cropper#824]
It seems the cropper doesn't work with the latest version of chrome on mobile devices.
The image literally disappears when trying to zoom or unzoom.

Can someone help me?
Many thanks in advance!

**Comment by DarkxKen** [comment]
Hi, I have the same issue with ionic on Android devices. I guess it use Chrome too.
I can zoom in/out just with the inspector of remote devices in my computer, but in the phone the image just disappears. Tablets and iOS works perfectly.
I'm using the settings of "fixed-crop-box".

Thanks.

**Comment by Mafial** [comment]
@DarkxKen 
Good to know: the old version v0.7.9 still works but it is very slow...
https://fengyuanchen.github.io/cropper/v0.7.9/

**Comment by fengyuanchen** [comment]
Works fine in Chrome for Android 55.0.2883.91. Check if it is just a problem of your own code.

**Comment by xe21500** [comment]
Hi, I can reproduce the error notified by @DarkxKen on your [sample page](https://fengyuanchen.github.io/cropper/), on Android 5.1 with Chrome 55.0.2883.91 (also happens on my application). It works correctly on Chrome 54.

**Comment by fengyuanchen** [comment]
As of version 55, Chrome starts to support [Pointer Events](http://caniuse.com/#feat=pointer) which causes this problem. I will resolved this soon.

**Comment by fengyuanchen** [comment]
I cannot fixed this right now, recommend to use the non-jQuery version as this issue had been fixed in that.

> - [Cropper.js](https://github.com/fengyuanchen/cropperjs) - the non-jQuery version of Cropper (**recommended**).

**Comment by fengyuanchen** [comment]
This has been fixed in v3.0.0-alpha.

**Comment by ellej16** [comment]
Hi @fengyuanchen! Tried updating Cropper to v3.x.x (3.0.0-rc1 in this case) and it does fix the issue **but** the responsive: true stopped working. I tried manually trigerring the window resize event to no avail.

Any advice on how we should go about the issue?

Thanks!
