### ISSUE TITLE
An uploaded image reverts to original if aspect ratio is changed.

### ISSUE THREAD

**Issue by chrisloughnane** [fengyuanchen/cropper#825]
Windows 10 v1607 b14393.576
Chrome v55.0.2883.87 m (64-bit)
Test Case: Use the demo https://fengyuanchen.github.io/cropper/

After you upload an image file change  to any other aspect ratio and the original image will restore. I think the desired* use would be to upload an image and it remain after a change of aspect ratio.

I attempted to persist the blob of the image and do a check in the aspect ratio function if an image has been loaded but I end up getting another instance of the canvas (above the previous image)

Excellent library, thank you.

*my desired use  :)

**Comment by chrisloughnane** [comment]
My HTML Set Ratio : note - I found if I just passed an aspect ration value I would get more final image resolutions out by 1px than when I was the desired x and y.

`<button data-toggle="tooltip" data-placement="bottom"  title="Set Joomla 600x400" type="button" id="crop-joomla-article" class="btn btn-primary btn-lg change-crop-size active" data-cropped-width="600" data-cropped-height="400"><i class="fa fa-crop" aria-hidden="true"></i> Joomla 600x400</button>`

My HTML Upload file, basically what you have in the demo

`            <label class="btn btn-primary btn-upload" for="inputImage" title="Upload image file" id="uploadImageCropWrapper">
                <input type="file" class="sr-only" id="inputImage" name="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">
                <span class="docs-tooltip" data-toggle="tooltip" title="" data-original-title="Import image with Blob URLs" data-placement="bottom">
                    <span class="fa fa-upload"></span>
                </span>
            </label>`

MY JS for changing ratio

` $(".change-crop-size").click(function () {
        var $this = $(this);
        $this.parent().parent().find(".change-crop-size").removeClass("active");
        $this.addClass("active");
        croppedImageHeight = $this.data("cropped-height");
        croppedImageWidth = $this.data("cropped-width");
        var cropBoxData = $cropThis.cropper('getCropBoxData');
        var canvasData = $cropThis.cropper('getCanvasData');
        options.built = function () {
            $cropThis.cropper('setCropBoxData', cropBoxData);
            $cropThis.cropper('setCanvasData', canvasData);
        };
        options['aspectRatio'] = croppedImageWidth / croppedImageHeight;
        $cropThis.cropper('destroy').cropper(options);
        console.log("aspect " + $this.val());
    });`

"My" JS for importing image (Your code)
`   var $inputImage = $('#inputImage');
    var URL = window.URL || window.webkitURL;
    var blobURL;
    if (URL) {
        $inputImage.change(function () {
            var files = this.files;
            var file;
            if (!$cropThis.data('cropper')) {
                return;
            }
            if (files && files.length) {
                file = files[0];
                if (/^image\/\w+$/.test(file.type)) {
                    blobURL = URL.createObjectURL(file);
                    $cropThis.one('built.cropper', function () {
                        // Revoke when load complete
                        URL.revokeObjectURL(blobURL);
                    }).cropper('reset').cropper('replace', blobURL);
                    $inputImage.val('');
                } else {
                    window.alert('Please choose an image file.');
                }
            }
        });
    } else {
        $inputImage.prop('disabled', true).parent().addClass('disabled');
    }`

Apologies for the code formatting

**Comment by JSteunou** [comment]
Use triple ``` for code formatting or button shortcuts above ;)

**Comment by chrisloughnane** [comment]
Hi JSteunou, 
 Thanks for the tip with ```
I was using the code button but I treated it as text quotes wrapping my code.

**Comment by fengyuanchen** [comment]
Just a problem of the demo, not the library. Already fixed this at 88abaa252031ee6e342b4171ab5b1b6f4af0c239
