### ISSUE TITLE
Idea to make cropper work from within an iframe

### ISSUE THREAD

**Issue by raphaelokon** [fengyuanchen/cropper#828]
Hi there.
We have a special use case (CMS) where we are _initialising_ the cropper is from within an iframe's script, but _rendering_ it into the window.parent (dynamically in a modal UI). We observed that the bindings to `$(document)` get out of sync. The iframe's `#document` becomes the cropper document binding resulting in `$document.on(EVENT_MOUSE_MOVE, …);`not being triggered or yielding false values.

We know this is an edge case, but thought we will share our solution to this problem:

```js
var $document = $(window === window.parent ? document : window.parent.document);
```

/cc @helhum

**Comment by fengyuanchen** [comment]
Just include the cropper script in the top window.
