### ISSUE TITLE
Failed to response

### ISSUE THREAD

**Issue by femarschall** [fengyuanchen/cropper#83]
Actually it isn't an issue to cropper itself but to the example which is bundled with the release.
First I tested it on my home server and it worked fine:

http://marschall.neon.org:88/cipoh/crop-avatar/crop-avatar.html

but then I moved it to a server on the web, withou making any changes, and it returns "Failed to response":

http://cipoh.com.br/crop-avatar/crop-avatar.html

the only explanation I can think of is some missing php module.
here are the two phpinfo:
http://marschall.neon.org:88/cipoh/crop-avatar/info.php
http://cipoh.com.br/crop-avatar/info.php

could you give me a hint?

**Comment by nivram-gt** [comment]
Hi, a question, how do I upload multiple images?

**Comment by peterchibunna** [comment]
@nivram-gt, this is not a plugin for uploading images. There are tutorials to help you learn how to do that.

**Comment by fengyuanchen** [comment]
@peterchibunna It's what I want say. Thanks!
