### ISSUE TITLE
preview width and height error

### ISSUE THREAD

**Issue by wolfboys** [fengyuanchen/cropper#834]
The first, you plugins really help me, thanks you very much.
the code of 1589 lines have bug,your source code: 
  $this.data(DATA_PREVIEW, {
      width: $this.width(),
      height:  $this.height(),
      html: $this.html()
 });
 my ${DATA_PREVIEW} element class name is "avatar-preview " ,this is style code:
  .avatar-preview {
  border: **10px** solid rgba(200, 220, 220, 0.35);
  **border-radius: 50% !important;**
  float: left;
  overflow: hidden;
}
if  ${DATA_PREVIEW}' width is 180px height is 180px,
then first run copper uploaded ${DATA_PREVIEW}' width changed 160px,height changed 160px; 
second run copper uploaded  ${DATA_PREVIEW}' width changed 140px,height changed 140px; 
....
now code:
 $this.data(DATA_PREVIEW, {
          width: $this.outerWidth(),
          height: $this.outerHeight(),
          html: $this.html()
   });
this bug fixed!

搞了半天发现好像作者是中国人,我还苦逼哈哈的写一堆英文的bug反馈,是这样的,在我的项目里,用于显示上传之后的那个预览的元素的样式定义如下:
.avatar-preview {
  border: **10px** solid rgba(200, 220, 220, 0.35);
  **border-radius: 50% !important;**
  float: left;
  overflow: hidden;
}
本身这个avatar-preview 元素的宽和高都是180px,
但是我第一次点击上传之后,avatar-preview宽和高自动缩小20px变成160px,刚好是border定义的宽度的两倍,
再次点击又在上次的基础上再次缩小border的两倍变成140px...
经过我反复的尝试才发现这个bug(源码examples下的crop-avatar里就有这个bug),后来我改了源码:
$this.data(DATA_PREVIEW, {
          width: $this.outerWidth(),
          height: $this.outerHeight(),
          html: $this.html()
   });
bug修复了,这里要取 DATA_PREVIEW这个元素的外宽度和外高度.

**Comment by fengyuanchen** [comment]
你可以在预览元素外面再包一层div，然后在该div上设置border.
