### ISSUE TITLE
Bug - Canvas has 10 times the size of the original photo

### ISSUE THREAD

**Issue by Rituba** [fengyuanchen/cropper#838]
Hi, 

When i upload an image less than 1MB it doesnt change the file size but, when i upload an image that has More than 1MB is multiplied by 10 times the size, because of this, i cant upload the image to my server.

Im trying to see where is located this "bug" on my files.

I use Windows 7 Proffesional
Google Chrome version : 55.0.2883.87 m

Thank you.

**Comment by atfa** [comment]
The same situation on my server. Hope we can find the way to fix it.

**Comment by JounQin** [comment]
If you are using `toDataURL`, try to add `toDataURL('image/jpeg')`, default output seems to be 'image/png.'

**Comment by atfa** [comment]
thanks, it works.

**Comment by Rituba** [comment]
The thing is that im actually working with `toDataURL('image/jpeg')` but its like it doesnt work.

Here is the piece of the code that i use to get the data of the canvas.

```
var canvas = document.getElementById('canvas');
var canvasData = canvas.toDataURL('image/jpeg');
```

I really dont know whats happening.

**Comment by fengyuanchen** [comment]
If your original photo is a JPEG image, the call `toDataURL('image/jpeg')`, if your original photo is a PNG image, the call `toDataURL('image/png')`, etc.
