### ISSUE TITLE
Fill color to transparent background within cropbox.

### ISSUE THREAD

**Issue by mikelyc** [fengyuanchen/cropper#839]
Hi, I want to crop all size image into square.

However, some of the images are rectangle so that I allow user to zoom in & out the image.

After that, I will get the cropped x, y, width, height from cropper("getData") and crop it at server side.

Is there any way to fill color into the transparent background?

For example:
![image](https://cloud.githubusercontent.com/assets/22939197/22140037/fafd41d4-df24-11e6-905f-1cb46d0cdee6.png)

The transparent area in the crop box will filled with white color.

**Comment by fengyuanchen** [comment]
```css
.cropper-crop-box {
  background-color: white;
}
```

**Comment by mikelyc** [comment]
The background will not append to the photo right? 

After I set to white, but the cropped image doesn't include the background also, it shows as transparent..

**Comment by fengyuanchen** [comment]
```js
$().cropper('getCroppedCanvas', { 
  fillColor: '#fff' 
})
```

**Comment by karaagacylmaz** [comment]
how to do this in Angular 4+? @fengyuanchen

**Comment by Supriya-bansal** [comment]
I am getting similar issue, when I upload a png cropper adds black background. Any idea how can i fix this in Angular 8?

I uploaded: 

![PNG_transparency_demonstration_1](https://user-images.githubusercontent.com/35838777/77763756-dc528b80-703b-11ea-8a6a-65903e633c4b.png)

And i got this after crop:

![PNG_transparency_demonstration_1 (1)](https://user-images.githubusercontent.com/35838777/77763807-ebd1d480-703b-11ea-8a32-151f2ccc7343.png)

**Comment by Usama4745** [comment]
> I am getting similar issue, when I upload a png cropper adds black background. Any idea how can i fix this in Angular 8 @fengyuanchen ?
> 
> I uploaded:
> 
> ![PNG_transparency_demonstration_1](https://user-images.githubusercontent.com/35838777/77763756-dc528b80-703b-11ea-8a6a-65903e633c4b.png)
> 
> And i got this after crop:
> 
> ![PNG_transparency_demonstration_1 (1)](https://user-images.githubusercontent.com/35838777/77763807-ebd1d480-703b-11ea-8a32-151f2ccc7343.png)

same issue with me

**Comment by Supriya-bansal** [comment]
> > I am getting similar issue, when I upload a png cropper adds black background. Any idea how can i fix this in Angular 8 @fengyuanchen ?
> > I uploaded:
> > ![PNG_transparency_demonstration_1](https://user-images.githubusercontent.com/35838777/77763756-dc528b80-703b-11ea-8a6a-65903e633c4b.png)
> > And i got this after crop:
> > ![PNG_transparency_demonstration_1 (1)](https://user-images.githubusercontent.com/35838777/77763807-ebd1d480-703b-11ea-8a32-151f2ccc7343.png)
> 
> same issue with me

This was quite simple. I did a mistake while specifying the format. Just mention it as png and the cropper wont add default background.

<image-cropper
      #imageCropper
      [imageChangedEvent]="imageChangedEvent"
      **format="png"**
      outputType="file"
      autoTriggerCrop="false"
      autoCrop="false"
      [aspectRatio]="aspectRatio"
      [maintainAspectRatio]="true"
      (imageCropped)="imageCropped($event)"
      (imageLoaded)="imageLoaded()"
    ></image-cropper>

**Comment by Usama4745** [comment]
> > > I am getting similar issue, when I upload a png cropper adds black background. Any idea how can i fix this in Angular 8 @fengyuanchen ?
> > > I uploaded:
> > > ![PNG_transparency_demonstration_1](https://user-images.githubusercontent.com/35838777/77763756-dc528b80-703b-11ea-8a6a-65903e633c4b.png)
> > > And i got this after crop:
> > > ![PNG_transparency_demonstration_1 (1)](https://user-images.githubusercontent.com/35838777/77763807-ebd1d480-703b-11ea-8a32-151f2ccc7343.png)
> > 
> > 
> > same issue with me
> 
> This was quite simple. I did a mistake while specifying the format. Just mention it as png and the cropper wont add default background.
> 
> <image-cropper
> #imageCropper
> [imageChangedEvent]="imageChangedEvent"
> **format="png"**
> outputType="file"
> autoTriggerCrop="false"
> autoCrop="false"
> [aspectRatio]="aspectRatio"
> [maintainAspectRatio]="true"
> (imageCropped)="imageCropped($event)"
> (imageLoaded)="imageLoaded()"
> >

Can we also specify format while adding cropper in javascript

**Comment by Usama4745** [comment]
> > > > I am getting similar issue, when I upload a png cropper adds black background. Any idea how can i fix this in Angular 8 @fengyuanchen ?
> > > > I uploaded:
> > > > ![PNG_transparency_demonstration_1](https://user-images.githubusercontent.com/35838777/77763756-dc528b80-703b-11ea-8a6a-65903e633c4b.png)
> > > > And i got this after crop:
> > > > ![PNG_transparency_demonstration_1 (1)](https://user-images.githubusercontent.com/35838777/77763807-ebd1d480-703b-11ea-8a32-151f2ccc7343.png)
> > > 
> > > 
> > > same issue with me
> > 
> > 
> > This was quite simple. I did a mistake while specifying the format. Just mention it as png and the cropper wont add default background.
> > <image-cropper
> > #imageCropper
> > [imageChangedEvent]="imageChangedEvent"
> > **format="png"**
> > outputType="file"
> > autoTriggerCrop="false"
> > autoCrop="false"
> > [aspectRatio]="aspectRatio"
> > [maintainAspectRatio]="true"
> > (imageCropped)="imageCropped($event)"
> > (imageLoaded)="imageLoaded()"
> > >
> 
> Can we also specify format while adding cropper in javascript

Sorry my question was related to cropperjs
