### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by Jonatthu** [fengyuanchen/cropper#840]
Is there a plan for make directives for angular 2?
Or should I work on it?

**Comment by fengyuanchen** [comment]
No plan yet.

**Comment by whyboris** [comment]
I had no trouble getting it to work in an angular 4 project (after enough research time and enough attempts). 
I created a repo that works out of the box: https://github.com/whyboris/cli106/tree/cropperjs
Notice what changed compared to baseline angular project started with angular/cli106: 
https://github.com/whyboris/cli106/compare/cropperjs

I owe a great debt to StackExchange ;)
