### ISSUE TITLE
Version beta - the cropper frame no correspond at the avatar

### ISSUE THREAD

**Issue by helinW** [fengyuanchen/cropper#842]
I use Windows 7 and Chrome v55

I use the avatar cropper and I just have changed the code from the v.2.3.4 to the v3.0.0-alpha.1.
I havn't change my code for the avatar cropper. 

The older version is correct, from the cropper to the avatar.
The new version show a difference between the image cropped and the avatar.

Old version correct :
![cropper-oldjs](https://cloud.githubusercontent.com/assets/14940480/22296873/83742b64-e2e9-11e6-925f-b07ee5b36362.png)

New version with a difference :
![cropper-newjs](https://cloud.githubusercontent.com/assets/14940480/22296872/836eb09e-e2e9-11e6-84bb-26a6bf1c9f09.png)

Hope it can help you to correct it or maybe I have to change something in the cropper avatar code ?

**Comment by fengyuanchen** [comment]
I don't know why. Please check your own code fisrt.
