### ISSUE TITLE
Cropper issue with Bootstrap v3.* Tabs

### ISSUE THREAD

**Issue by AdrianKuriata** [fengyuanchen/cropper#843]
Hi, i have a problem with cropping image:

[http://i.imgur.com/0Yvfnsy.png](http://i.imgur.com/0Yvfnsy.png)

Here is image how it displaying, i can't set it for displaying on 100% width, but when i resize my browser this is changing width and height for good displaying. Could someone help me with that? I tried set width for 100% on cropp container, but this didn't help me, because height container is not changed and image is still little, just helping resize browser window.

Here is my code:
`var cropper = new Cropper(faceImg, {
	aspectRatio: 4 / 3,
	autoCropArea: 0,
	movable: false,
	rotatable: false,
	scalable: false,
	zoomable: false,
	viewMode: 3,
	crop: function(e) {
		console.log(e.detail);
	}
});`

I set `max-width:100%` for image.

Sorry for my English.

I found the problem, problem is when we insert cropper into Tabs from Bootstrap. I mean if we inner cropper into tab, which is displaying first(like active class) everything working perfectly, but when we insert it into other tab and change on it it will display like in photo which i included.

**Comment by JoelSParker** [comment]
Having the same issue when trying to display in Bootstrap Modals

**Comment by AdrianKuriata** [comment]
Yea, i did it the same day when i wrote this "issue".
