### ISSUE TITLE
Selection with aspectRatio issue

### ISSUE THREAD

**Issue by fedot01** [fengyuanchen/cropper#844]
I have a problem when aspectRatio is set and I'm trying to change size of selection with dragging corner.
If I move one selection corner with hold mouse button from one corner to opposite everything seems to be OK. But if I still hold it and try to move mouse to the opposite corner on same edge then selection collapsing.

**Comment by fengyuanchen** [comment]
Cannot reproduce. More detail is needed.

**Comment by fedot01** [comment]
Video record of issue http://dropmefiles.com/pzjmo
With default settings here https://fengyuanchen.github.io/cropper/

**Comment by fengyuanchen** [comment]
If you move the northeast corner, please just move it to the southwest side (only support this), not to northwest or southeast.
