### ISSUE TITLE
Cropper image scale backroud black

### ISSUE THREAD

**Issue by fayas668** [fengyuanchen/cropper#845]
![my restaurant](https://cloud.githubusercontent.com/assets/5784765/22582311/228f5056-ea0c-11e6-9e18-c343fd6686d1.png)

why am getting this result... i need white background or only the image not black bg

**Comment by fengyuanchen** [comment]
```js
$().cropper('getCroppedCanvas', {
  fillColor: ‘#fff’
}).toDataURL('image/jpeg')
```
