### ISSUE TITLE
cropBox orientation switch

### ISSUE THREAD

**Issue by jousch** [fengyuanchen/cropper#846]
Hi,

I'm using cropper within TYPO3 CMS, where cropper is used for image manipulations within the TYPO3 backend. Editors can crop images when adding images to content elements. TYPO3 CMS actually uses just a bunch of the cropper's feature. At first, thanks for such a great tool!

What I actually miss is the possibility to switch/toggle the actual cropBox orientation between landscape/portrait.
For example, this could be an image like the one of google chrome's responsive toolbar
![image](https://cloud.githubusercontent.com/assets/2861556/22772344/6675abdc-ee9c-11e6-909c-50405f540b2f.png)
The location of the toggle/button could be placed within the crop area. For example 
![image](https://cloud.githubusercontent.com/assets/2861556/22772448/fccaddb4-ee9c-11e6-9380-15bb3694fd9e.png)

After thinking about, there are some open questions:

- If you give an editor some cropRatios, basically a orientation change of the cropBox means different cropRatio. If you want to only offer a cropRatio "3:2" (because this image is used for a landscape image as fullwidth sujet image at the top of a website) in some situations it must be possible to disable/activate such a "cropBox orientation switch".
- Maybe something like if there's an available cropRatio `3:2` && `2:3` a cropBox orientation switch can be activated..

What do you think about such a builtin feature?

**Comment by fengyuanchen** [comment]
Just use the methods to customize it. 

> If every feature build in the core cropper code, then it will be becoming more and more bloated, then it will be hard to maintain and dead at the end.

**Comment by jousch** [comment]
Many thanks!
