### ISSUE TITLE
Selector handle problem

### ISSUE THREAD

**Issue by xie-yang** [fengyuanchen/cropper#847]
I have tested cropper in Chrome 53 in Windows 7.
it work well in desktop but in mobile I found an issue.
Right bottom handle of selector is bigger than others.
I think this is small issue but has to be removed.
Here is url of screenshot .
http://prntscr.com/e8h2vj
Regards.

**Comment by tilocgn** [comment]
![68259600](https://cloud.githubusercontent.com/assets/11157110/22922036/515856a6-f29c-11e6-90eb-02694f80247b.jpg)

**Comment by xie-yang** [comment]
Oh. That so?
Thanks for your reply.

**Comment by xie-yang** [comment]
I have another trouble. cropper container had not full width. I have copied and change some part of demo.
Looks it like this.
http://prntscr.com/e8w6f9
But container of demo works with full width .
I can not find reason.
Thanks

**Comment by fengyuanchen** [comment]
@tilocgn Thanks for helping to reply this.
@xie-yang The container can be controled by CSS completely.
