### ISSUE TITLE
base64 doesn't seem to work

### ISSUE THREAD

**Issue by rwwagner90** [fengyuanchen/cropper#849]
I set a base64 image and the image shows up, but the crop box does not. It does not seem to be actually initializing the cropper instance when I use a base64 image instead of a url to a hosted image somewhere.

Any ideas?

**Comment by schuylr** [comment]
This was solved in #180 (so others who find this page can find that issue)

**Comment by fengyuanchen** [comment]
@rwwagner90 You can try the latest version.
