### ISSUE TITLE
Doesn't Display in Bootstrap Modal

### ISSUE THREAD

**Issue by redstar504** [fengyuanchen/cropper#85]
The HTML below should display the cropper inside the bootstrap modal, but this doesn't happen.  The cropper stays hidden and the modal dialog appears empty when opened.

``` html
<html>
<head>
    <title>Crop Me Baby</title>
    <script type="text/javascript" src="/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="/cropper/dist/cropper.js"></script>
    <script type="text/javascript" src="/bootstrap/dist/js/bootstrap.js"></script>
    <link href="/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
    <link href="/cropper/dist/cropper.css" rel="stylesheet">
    <style type="text/css">
        .modal-dialog {
            width: 800px;
        }
    </style>
</head>
<body>
<div class="container">
    <h1>Crop Me Baby</h1>

    <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        Launch demo modal
    </button>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                </div>
                <div class="modal-body">
                    <img src="http://baconmockup.com/700/400">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("img").cropper({
        aspectRatio: 16 / 9,
        done: function (data) {
            console.log(data);
        }
    });
</script>
</body>
</html>
```

**Comment by 3ncrypter** [comment]
@fengyuanchen consider me a noob in Javascript, I am facing same issue, How to do the same if I am using cropper.js (the one without jquery).

**Comment by gurnay1973** [comment]
When using modal with the function :

$(".modal").on("shown.bs.modal", function() {
  $("img").cropper({
    multiple: true,
    data: originalData,
    done: function(data) {
      console.log(data);
    }
  });
})
the cropper works, but the action buttons (rotation, zoom, etc.) stop working, as would be the correct way to create the buttons ???.
I am trying to create the instance by clicking on a photo.

**Comment by fengyuanchen** [comment]
@gurnay1973 Please read the docs about how to use methods carefully!

> https://github.com/fengyuanchen/cropper#methods

**Comment by o15a3d4l11s2** [comment]
@fengyuanchen I have a scenario where the user can show the modal dialog multiple times and adjust the crop area. To do so, I always reuse the same modal with the initialised cropper in it.

I experience the same issues (the small modal), because I start the cropper before the modal is shown.
Is there a nice way to do what I am trying - allowing the user to call the cropper modal multiple times, while keeping the last-cropped area where the user left it?

**Comment by fengyuanchen** [comment]
@o15a3d4l11s2 You can follow this example: https://github.com/fengyuanchen/cropper/blob/v3.1.6/examples/cropper-in-modal.html
