### ISSUE TITLE
Crop-avatar example image is not loading in Editor

### ISSUE THREAD

**Issue by Hsidhu** [fengyuanchen/cropper#854]
hello,
I tried crop-avatar from examples folder. 
When I click on image it opened up a model and I can see image in right side in preview
But I can't see any image in left side for edit

![cropper](https://cloud.githubusercontent.com/assets/6515812/23269176/ae3d5efc-f9bd-11e6-824d-eac022799a8a.PNG)

Thanks in advance

**Comment by fengyuanchen** [comment]
It is an example of how to update an old avatar. So just choose a new avatar from the file input on the upper left corner.
