### ISSUE TITLE
Poor Performance In Large Images

### ISSUE THREAD

**Issue by breeswish** [fengyuanchen/cropper#856]
1. `newImage.src = image.src` is slow in Chrome. Can be optimized by directly passing data url.

2. `$('<img....>')` is slow. Can be optimized by direct DOM operations.

**Comment by rodrigograca31** [comment]
I also would like to see some performance related changes...
I was even pondering hanging to the Alpha release to see if it would make it faster/better... :smile:

**Comment by rodrigograca31** [comment]
Awesome!
@fengyuanchen any idea when V3 will be released?

**Comment by fengyuanchen** [comment]
@rodrigograca31 v3 is preview release now, but is mostly stable, and will be finally release soon.

**Comment by rodrigograca31** [comment]
@fengyuanchen awsome! I will try to keep an eye on it! :)
