### ISSUE TITLE
Let options be changed outside of Cropper

### ISSUE THREAD

**Issue by snizek** [fengyuanchen/cropper#861]
I would like to suggest feature to let the options be changed outside of Cropper. I needed this when I had a request to perform "faster" scrolling when user holds the CTRL button. I added method to prototype:

```javascript
/**
 * Get the options of cropper
 * @returns {Object} options
 */
getOptions: function() {
  return this.options;
},
```
and then did 

`$().cropper("getOptions").wheelZoomRatio = XX;`
in my JavaScript file.

IMHO more people would need this.

Would this be good feature for more people? Should I make a pull request with this piece of code?

David

**Comment by fengyuanchen** [comment]
Just fork one and implement it in your own branch. We don't need this exactly as it is not very useful for most people.
