### ISSUE TITLE
Prevent zooming for small images

### ISSUE THREAD

**Issue by amitava82** [fengyuanchen/cropper#864]
If I load a small image it scales up to fill the canvas area (tried on the demo as well). How do I prevent zooming if image is smaller than canvas area?

**Comment by fengyuanchen** [comment]
Why? If you do this, then when you choose an small image as 10 x 10 pixels, you will be hard to see it.

**Comment by amitava82** [comment]
What's the point of seeing a 10x10 image zoomed in to 1000x1000? You'll be seeing pixels. There are use causes and these things should be configurable.
