### ISSUE TITLE
Rotating (-)270 degrees gives strange results

### ISSUE THREAD

**Issue by Venorcis** [fengyuanchen/cropper#865]
I make the following calls (with viewmode 1, background false, movable false):
```
$(img).cropper('rotate', 90);
 $(img).cropper('build');
```

On 0, 90, and 180 degrees, the image is correctly displayed (i.e. fully visible within the canvas). However, at 270 degrees, only a small fraction of the image is visible (i.e. it suddenly fills).
The same is true but then in reverse when using rotate with -90; it goes well at 0, -90, and -180, but not at -270. So very strange that 90 is correct, and then -270 is not (and the other way around).

Edit: this is with 3.0.0-rc

**Comment by fengyuanchen** [comment]
`build` is not a public method...

**Comment by Venorcis** [comment]
How do I ensure the image fits in the viewscreen and the cropbox is reset after rotation otherwise? And again the problem seems unrelated to calling build, because it goes fine only besides two notable (strange) exceptions.
