### ISSUE TITLE
Crop area isn't aligned to cursor if cursor leaves the boundaries

### ISSUE THREAD

**Issue by johnBrink** [fengyuanchen/cropper#866]
Tested on Chrome 56 on Windows 10. This happens in my app and in the cropper demo page.

If I drag the crop selection around, and my cursor leaves the cropper boundary, then the selection will continue to move around in the same direction as the cursor. If I move the cursor back over the cropper's boundary, then the selection will still be offset from the cursor.

Rather than moving in the same direction as the cursor is moving, can the selection area instead try to stay underneath the cursor (while still being constrained by the image's boundaries)?

![drag issue](https://cloud.githubusercontent.com/assets/7257437/24625762/a6b2e658-1875-11e7-8b16-5665882f9754.gif)

**Comment by fengyuanchen** [comment]
It is designed as this.
