### ISSUE TITLE
Pixelated getCroppedCanvas

### ISSUE THREAD

**Issue by darkfrog26** [fengyuanchen/cropper#867]
I'm using the cropper to constrain the aspect ratio of the images, but then I call `getCroppedCanvas({ width: 240, height: 180 });`.  This works, but very often the resulting image is somewhat pixelated.  I presume it's because of the scaling that's occurring but was hoping there might be some way for the cropper to do a better job of scaling the image and perhaps using antialiasing?

**Comment by fengyuanchen** [comment]
1. If the target image is too small, ask your user to upload a big one.
2. Limit the zoom out level by the `zoom` event to avoid **pixelated**.
