### ISSUE TITLE
cropper js is increasing size of the file

### ISSUE THREAD

**Issue by errakeshpd** [fengyuanchen/cropper#871]
The cropper js is increasing the file size drastically . let say if 1 MB file is processed and send as 2-3 MB size file.

**Comment by fengyuanchen** [comment]
If your original imaeg is JPEG, then when call `canvas.toDataURL`, you should pass in the same image type:

```html
<img src="example.jpg">
```
```js
$('img').getCroppedCanvas().toDataURL('image/jpeg');
```
