### ISSUE TITLE
to blob function error

### ISSUE THREAD

**Issue by tainaml** [fengyuanchen/cropper#874]
Does anyone know why this message appears?

TypeError: $(...).cropper(...).toBlob is not a function
$('#canvas').cropper('getCroppedCanvas').toBlob(function (blob) {

**Comment by Alexbeis** [comment]
Which browser are you using? I faced with this problem on IOS safari as it does not support. I have solved it by sending the canvas and processing  the file on server side. Hope it helps. Regards

**Comment by tainaml** [comment]
Alex, firstly thank you for your fast reply.
I am using chrome browser but I tried the same action with  firefox as well and it appeared the same error.

Thank you

**Comment by Alexbeis** [comment]
I recommend you to send the cropped canvas to the server side and convert there to the MIME type you want. 
For me worked perfectly. Regards

**Comment by tainaml** [comment]
How can I do this?  :S

**Comment by tainaml** [comment]
I am already doing this!

**Comment by tainaml** [comment]
I will send you the print screen!

**Comment by tainaml** [comment]
I will send you my script by gist.

**Comment by tainaml** [comment]
may you look here?
https://gist.github.com/tainaml/5f2a029f92632172f3a8ff355c7336a5

is there something wrong?

thank you!

**Comment by dcy** [comment]
@Alexbeis Can you show your example code?

**Comment by fengyuanchen** [comment]
For browser which does not support canvas.toBlob, include this lib: https://github.com/blueimp/JavaScript-Canvas-to-Blob
