### ISSUE TITLE
How to make the image fit the original size

### ISSUE THREAD

**Issue by FIERMAND** [fengyuanchen/cropper#878]
NOT LIKE THIS
![7](https://cloud.githubusercontent.com/assets/22112876/25469066/36e075ca-2b44-11e7-8132-a0e7e8460418.png)

**Comment by LANSELOT** [comment]
How did you solve this problem?

**Comment by FIERMAND** [comment]
I can not solve this problem, 
So, I use another CropJS

**Comment by Felipesdeveloper** [comment]
Has anyone solved this problem?
