### ISSUE TITLE
cropper/examples/crop-avatar demo, set aspectRatio not 1, crop and show image isn't same size

### ISSUE THREAD

**Issue by mqy1023** [fengyuanchen/cropper#881]
when i use  cropper/examples/crop-avatar, change aspectRatio value not 1, 
image can't show normaly. the crop image is not as the same size as the show image.

使用 cropper/examples/crop-avatar 例子时，当改变aspectRatio的值不为1后，运行代码，返回的剪裁的图片无法正常显示，显示出来的图片和当时裁剪图片尺寸对不上。

**Comment by fengyuanchen** [comment]
The `aspectRatio` option in this example must be `1`, any other values are not available.

**Comment by mqy1023** [comment]
any other example recommend? about crop-avatar can be cropped any size and upload and show normally，thanks !
