### ISSUE TITLE
Feature Request : resizing handle on the image, not a crop box.

### ISSUE THREAD

**Issue by leesc81** [fengyuanchen/cropper#883]
I was running a "cropper with fixed cropr box" example.
All is good.
But I would like to have a resizing handle on the image, not a crop box.
Attach the image below.

Thank you for your efforts.
![2017-05-11 1 25 45](https://cloud.githubusercontent.com/assets/16448526/25909655/cf4251ea-35e8-11e7-9bea-672b8eeef2e2.png)

**Comment by fengyuanchen** [comment]
Not support this.
