### ISSUE TITLE
IE: issue wile croping and saving

### ISSUE THREAD

**Issue by atuleshK** [fengyuanchen/cropper#884]

**Comment by atuleshK** [comment]
I have implemented cropper into my project, it's working fine with firefox as well as chrome but when I try to run in IE... doesnt save and preview image at all.

**Comment by stevaras** [comment]
Be a little more specific please. Does the component get "rendered"? Do you see it?

**Comment by atuleshK** [comment]
@stevaras thanx for the reply.. yup it gets render, still trying to figure it out... Now, I am trying to find out if its IE's or Cropper's problem. Thanx again for your reply.
