### ISSUE TITLE
Responsive: true stopped working

### ISSUE THREAD

**Issue by ellej16** [fengyuanchen/cropper#886]
Hi, first of all thanks for this wonderful library!

I came across this issue https://github.com/fengyuanchen/cropper/issues/824 and updated my cropper version accordingly to fix the said issue (v3.x.x rc1 if I'm not mistaken via bower). However, a new issue arose: `responsive:true` doesn't work, even if I manually trigger the window resize event.

Is the `responsive:true` option dropped for v3, and are there any new ways to go about this?

Thanks again!
Paul

**Comment by fengyuanchen** [comment]
Cannot reproduce. Please check your own code first.

**Comment by ellej16** [comment]
Hi, this snippet was working well on `v2.3.2`:

```
 $('#cover-crop-image').cropper({
                    aspectRatio: 1 / 1,
                    autoCropArea: 1,
                    minCropBoxWidth: 300,
                    minCropBoxHeight: 300,
                    checkOrientation: true,
                    strict: false,
                    guides: true,
                    highlight: false,
                    dragCrop: true,
                    responsive: true,
                    restore: false,
                    zoomable: true,
                    movable: true,
                    center: true,
                    cropBoxMovable: true,
                    cropBoxResizable: true
                }).cropper("crop");
  $('#cover-crop-image').cropper("reset", true).cropper("replace", this.result);
  setTimeout(function () {
                    $(window).trigger('resize');
                    console.log("triggered resize event")
                }, 300);
```

So I was confused when I upgraded to `v3.0.0-rc.1` it just stopped working. I tried triggering the `resize` event manually on the browser but to no avail.

![image](https://cloud.githubusercontent.com/assets/6106749/26282510/5f81a058-3e45-11e7-9465-bf17f21b83ed.png)

**Comment by ellej16** [comment]
It did fix https://github.com/fengyuanchen/cropper/issues/824 's issue (image disappears when zooming in on chrome android) though. Any idea what happened here?

**Comment by ellej16** [comment]
Same code snippet on `v2.3.2`:
![image](https://cloud.githubusercontent.com/assets/6106749/26282771/96fce45c-3e4a-11e7-897f-1b0b681a9be0.png)

**Comment by fengyuanchen** [comment]
Please the [description](https://github.com/fengyuanchen/cropper#methods) about how and when to call the methods carefully!

**Comment by ellej16** [comment]
Missed that one, sorry. Would try it out later. I deeply apologize. Thanks a lot!
