### ISSUE TITLE
Wrong crop box behavior when you move mouse very fast

### ISSUE THREAD

**Issue by dmytrostrembetskyi** [fengyuanchen/cropper#888]
When you try to change size of crop box, and move your mouse very fast
Crop box change it's coordinates

Chrome
![issue](https://cloud.githubusercontent.com/assets/15861246/26123250/e4a4ba3e-3a82-11e7-8f1e-7a69674cb74f.gif)

Firefox
![issue3](https://cloud.githubusercontent.com/assets/15861246/26141888/a9d43f42-3ae6-11e7-9f27-f2861c4401b9.gif)

**Comment by fengyuanchen** [comment]
So how to fix this. Do you have any suggestions?

**Comment by dmytrostrembetskyi** [comment]
Nope
