### ISSUE TITLE
Unable to Download Cropped Image

### ISSUE THREAD

**Issue by sarathi125** [fengyuanchen/cropper#891]
I have downloaded/cloned the source and trying from my development system, upon clicking on the 'Download' button in the cropped image popup, getting failed network error in both IE & Chrome.

From Developer tools seen this 

`<a class="btn btn-primary" id="download" href="javascript:void(0);" download="cropped.jpg">Download</a>`

Please advise me to resolve this issue.`

**Comment by fengyuanchen** [comment]
More detail? Browser version?

**Comment by sarathi125** [comment]
Hi, 

Thank you for your resposne, 

Chrome Version 58.0.3029.110 (64-bit), Windows 10 & Windows 7 as well with the same version of Chrome browser.

I have downloaded the plugin source from Github and tried with a HTML page, when I click download I am getting this error.

**Comment by sarathi125** [comment]
Hi,

Any update please.

**Comment by fengyuanchen** [comment]
Works fine in the [official demo](https://fengyuanchen.github.io/cropper)? If so, it may be your own problem.

**Comment by sarathi125** [comment]
Yes, official site working online. But offline it is not working
