### ISSUE TITLE
How destgroy cropper using pure javascript

### ISSUE THREAD

**Issue by kiarash3tar** [fengyuanchen/cropper#894]
Before opening an issue:I want to read an image from input type file and add it to a cropper, but I have another cropper instance before..

this is my code:

    $(document).on('change', '#avatarInput', function () {
            var file = document.getElementById('avatarInput').files[0];
            var reader = new FileReader();
            document.getElementById('cropperImage').src = '';
            //$(this).cropper('destroy');
            reader.onload = function(e) {
                log(reader.result);
                document.getElementById('cropperImage').src = reader.result;
                $().cropper('destroy');
            }
            reader.readAsDataURL(file);
        });

it seems some thing is wrong in my code...
Would you let me know what is my problem?

**Comment by fengyuanchen** [comment]
For your case, just use the `replace` method to update the image.
