### ISSUE TITLE
unwanted crop image using replace method

### ISSUE THREAD

**Issue by kiarash3tar** [fengyuanchen/cropper#896]
Hi again and thanks for your greate plugin;

This is my cropper

            $cropperImage.cropper({
                aspectRatio: 'free',
                autoCropArea: false,
                strict: false,
                guides: false,
                highlight: false,
                dragCrop: false,
                cropBoxMovable: true,
                cropBoxResizable: false,

                minContainerWidth: width,
                minContainerHeight: height,
                minCropBoxWidth: width,
                minCropBoxHeight: height,
                cropBoxResizable: false,

                built: function () {
                    $cropperImage.cropper("setCropBoxData", {width: width, height: height});
                }

            });

And this is for select another picture from input field:

            $('#avatarInput').on('change', function (eve) {

                var file = document.getElementById('avatarInput').files[0];

                var reader = new FileReader();
                reader.onload = function (e) {
                    //$cropperImage.attr('src', e.target.result);
                    $cropperImage.cropper('replace', e.target.result, true);
                };

                reader.readAsDataURL(file);

            });

The problem is the cropper will compress image without respect to aspect ratio.

please look at these pictures:

![cropperissue01](https://cloud.githubusercontent.com/assets/4986757/26792172/cad7ff06-4a2e-11e7-9fd1-aecd31b3d92c.png)

![cropperissue02](https://cloud.githubusercontent.com/assets/4986757/26792185/daf3615a-4a2e-11e7-8053-581d1690f792.png)

**Cropper work fine on initialze and the issue will appear after replace method**

**Comment by fengyuanchen** [comment]
It is the right behaviour for your case. Please read [the docs about the `replace` method](https://github.com/fengyuanchen/cropper#replaceurl-onlycolorchanged) carefully.
