### ISSUE TITLE
什么破文档啊，到底怎么用啊

### ISSUE THREAD

**Issue by aviggngyv** [fengyuanchen/cropper#897]
$().cropper 这是什么鬼，

例子里又是这种

<script>
          window.addEventListener('DOMContentLoaded', function () {
            var image = document.querySelector('#image');
            var cropper = new Cropper(image, {
              movable: false,
              zoomable: false,
              rotatable: false,
              scalable: false,
              rotatable: true
            });

            document.getElementById('rotate').onclick = function () {
              cropper.cropper('rotateTo', 90);
            };
          });
        </script>

没一个可用的，就不能简单化文档吗

**Comment by fengyuanchen** [comment]
看清楚有如下两个版本：
- jQuery版: https://github.com/fengyuanchen/cropper
- 原生JS版: https://github.com/fengyuanchen/cropperjs
