### ISSUE TITLE
How can I create multiple instances of the cropper?

### ISSUE THREAD

**Issue by bilalghalayini** [fengyuanchen/cropper#898]
Hello,

I want to create multiple instances of the cropper. 
How can I achieve this?

Thank you,
Bilal

**Comment by fengyuanchen** [comment]
https://github.com/fengyuanchen/cropper/blob/master/examples/multiple-croppers.html

**Comment by bilalghalayini** [comment]
I'm asking for multiple instance in the same image.

**Comment by fengyuanchen** [comment]
It's impossible to do that...
