### ISSUE TITLE
Add Min Zoom

### ISSUE THREAD

**Issue by razor-rich** [fengyuanchen/cropper#90]
Not really and issue more of an added feature. Would it be possible to add a minimum zoom level?

**Comment by fengyuanchen** [comment]
@trickpattyFH20 [v0.8.0](https://github.com/fengyuanchen/cropper/releases/tag/v0.8.0) had be released, and it supports to zoom out past the original image dimensions.

**Comment by trickpattyFH20** [comment]
@fengyuanchen wow.... amazing. thank you. <3 this pluggin so much.
looks absolutely amazing in chrome.
It's pretty buggy in iOS, I can try to help write a fix for that soon if you'd like.

Is this zoom out feature using canvas/svg? both?

**Comment by fengyuanchen** [comment]
@trickpattyFH20 Thank you! Zoom in / out just changes the styles (size and position) of the image, doesn't use canvas. Only the `getDataURL` method use canvas.
