### ISSUE TITLE
set background image when drop

### ISSUE THREAD

**Issue by tanvan81** [fengyuanchen/cropper#900]
Hi

When I crop image, background auto set black, how to I set white background

tks

**Comment by shankarThiyagaraajan** [comment]
@tanvan81 ,
There are two ways to done this,
1. Use as option "`fillColor`", while you initiate your cropper. 
2. In **main.js**,
 try this `fillColor: '#fff'` on **options** .
Here, you can set whatever the colour you want.

This second option will set the background as default.

Thank you !

**Comment by tanvan81** [comment]
tks so much

I've config success

2017-06-29 12:12 GMT+07:00 Shankar Thiyagaraajan <notifications@github.com>:
