### ISSUE TITLE
.cropper-container inline styles width: 200px and height: 100px 

### ISSUE THREAD

**Issue by NicolasVanhecke** [fengyuanchen/cropper#901]
Why is it that the `.cropper-container` is always set to 200x100 px? I cannot style it so it scales properly. I can see the styles are set inline to the element itself (meaning it is set in JS?).

This is how small it looks when simply initialising the cropper without any settings. I have not added any css to interfere with anything. 

![screen shot 2017-06-27 at 13 21 11](https://user-images.githubusercontent.com/9153781/27585305-0143a806-5b3c-11e7-8ec5-3e8565de9246.png)

**MORE INFO:**
To be clear, I have also tried `minCanvasWidth` and `minCanvasHeight`, which partly solves the problem. I now have a bigger image, but the cropper still can't size bigger than 200x100 px.. Meaning this is not the solution (this is the max side of the cropped area, I cant drag it any bigger)
![screen shot 2017-06-27 at 13 31 55](https://user-images.githubusercontent.com/9153781/27585608-41d4f784-5b3d-11e7-9967-660a44d310d6.png)

**Comment by fengyuanchen** [comment]
Please read the docs about the `minContainerWidth` and `minContainerHeight` options:

```js
$('img').cropper({
  minContainerWidth: 800,
  minContainerHeight: 600
})
```

**Comment by 1v** [comment]
In my situation the solution was to apply cropper on image load:
```js
$('img').load(function() {
  $('img').cropper();
});
```
