### ISSUE TITLE
how to fix the  Container Width and Height

### ISSUE THREAD

**Issue by wblbird** [fengyuanchen/cropper#906]
when I upload new image ,the new image is higher than the previous picture，then the height of the container has also changed，but i need a fix width and height。
can you help me ？

**Comment by dariopm** [comment]
Perhaps using 'setCanvasData'?

**Comment by dariopm** [comment]
Or destroying the current object and creating a new one for the new image. This way is working.

**Comment by wblbird** [comment]
thank you ， Let me have a try
