### ISSUE TITLE
I have crop_avtar folder cropping image using modal,but its not working on windows in chrome and mac in chrome. 

### ISSUE THREAD

**Issue by jayslktechlabs** [fengyuanchen/cropper#914]
I have download folder in example crop_avatar folder cropping image using modal,but its not working on windows in chrome and mac in chrome.

Can you please help anyone?

**Comment by jayslktechlabs** [comment]
I have download folder in example crop_avtar folder cropping image using modal,but its not working on windows in chrome and mac in chrome.

Can you please help anyone?

**Comment by fengyuanchen** [comment]
I just test it, it works fine. Did you read the [README.md](https://github.com/fengyuanchen/cropper/blob/master/examples/crop-avatar/README.md)? Maybe it is your PHP config problem.
