### ISSUE TITLE
[Bug] Rotate bug with photo taken in portrait on iPhone

### ISSUE THREAD

**Issue by hungdo89** [fengyuanchen/cropper#915]
OS: iOS version 8.1.2 ~ 9.3.2 (and I think below iOS 10 will has the same bug)
Browser: Safari

When I take a photo in portrait and rotate it, the cropper canvas will display wrong. At first I think there are something wrong with my configs so I come to your site and try. Well, it's the same. Please check below image.
![img_2566](https://user-images.githubusercontent.com/12625380/29402524-711bb3c6-835f-11e7-9e8d-ec1b9d5b6ffe.PNG)

I have spent 2 days trying to fix this bug but no luck.

**Comment by Anderson-Vasques** [comment]
No sure if it can help you @hungdo89 
https://github.com/fengyuanchen/cropper#checkorientation

PS: I am not an expert. I just started using this nice plugin :P

**Comment by hungdo89** [comment]
@Anderson-Vasques I don't change any option so it will be default value. As you can see, checkOrientation will be true and the bug is still there.

**Comment by fengyuanchen** [comment]
The checkOrientation option requires [Typed Array support (iOS Safari 9.3+)](http://caniuse.com/#feat=typedarrays)!

**Comment by hungdo89** [comment]
@fengyuanchen Don't you see that I have mentioned iOS 9.3.2 in my first post?

**Comment by fengyuanchen** [comment]
@hungdo89 I said **iOS Safari**. Are you sure they are the same?

**Comment by hungdo89** [comment]
@fengyuanchen http://caniuse.com/#feat=typedarrays as mentioned in this link, Typed Array is avaiable in Safari & Chrome for iOS 9.3+, not iOS Safari. Please hover to see more detail.

**Comment by fengyuanchen** [comment]
@hungdo89 Can you provide the `window.navigator.userAgent` of your iOS Safari?

**Comment by hungdo89** [comment]
![img_2577](https://user-images.githubusercontent.com/12625380/29757017-e916827c-8bd2-11e7-8a4c-b5749621c826.PNG)
@fengyuanchen

**Comment by fengyuanchen** [comment]
I saw `Safari/601.1`, which is nearly the same as Safari 9.0.

> You can detect Typed Array support in your iPhone quickly with this way: `alert(window.ArrayBuffer)`
