### ISSUE TITLE
Bottom or right 1px black line

### ISSUE THREAD

**Issue by Samuel91** [fengyuanchen/cropper#918]
Using the fixed crop box some images are uploaded with 1px of the fillcolor on the bottom or on the right. Maybe it's a problem with the approximation of subpixels. I'm uploading images using HTMLCanvasElement.toBlob() and then php.

This is the code I'm using:
```js
var image_cropper = croppedImg.cropper({
            viewMode: 1,
            dragMode: 'move',
            autoCropArea: 0.85,
            wheelZoomRatio: 0.02,
            restore: false,
            guides: false,
            highlight: false,
            cropBoxMovable: false,
            cropBoxResizable: false,
            aspectRatio: aspectRatio,
            zoom: function (e) { // function to allow maxZoom to max size
                if (e.ratio > 1) {
                    e.preventDefault();
                    $(this).cropper('zoomTo', 1);
                }
            }
 });
```

**Comment by LonerKO** [comment]
Yes, have same problem.

**Comment by fengyuanchen** [comment]
Which version of Cropper? Any screenshots?

**Comment by Samuel91** [comment]
Same issue with the v.3.0.0-rc.3 which I'm using now and with v.2.3.2 which I used time ago. What kind of screenshot do you need?

**Comment by LonerKO** [comment]
View
https://prnt.sc/gwf0a4
Cropped image
https://prnt.sc/gweznw
GetImage
```
var imageData = $('.cropper-example-1 > img').cropper('getCroppedCanvas', {
                width: 123,
                height: 92,
                imageSmoothingQuality: 'high'
            }).toDataURL('image/jpeg');
```

**Comment by Tomefa** [comment]
Yes same problem here with v3.1.1

**Comment by fengyuanchen** [comment]
The core problem is the same as http://0.30000000000000004.com/

**Comment by nag5000** [comment]
Could you please release a new version with that fix?

**Comment by fengyuanchen** [comment]
v3.1.2 has been released for this.

**Comment by joostdr** [comment]
@fengyuanchen We are encountering this issue by using the javascript version of the cropper (https://github.com/fengyuanchen/cropperjs). Is it possible that the same bug is still present there?

**Comment by Dimchao** [comment]
@fengyuanchen this is still very much an issue using both the cropper.js and jQuery cropper tools. Could you point us in the right direction to fix this issue? It appears that it can be easily resolved by forcing INT numbers for the image dimensions when resizing.

Thank you.

**Comment by nugoo1** [comment]
Is there a fix? Why is this closed
