### ISSUE TITLE
 Problem when cropper in modal.

### ISSUE THREAD

**Issue by yimik** [fengyuanchen/cropper#921]
Operating system : windows10
Browser : Chrome 61.0.3163.100

When I run /examples/cropper-in-modal.html ,there's a problem like this picture
It's worked well in the old version of Chrome。

![image](https://user-images.githubusercontent.com/7576454/30954846-4d166cc0-a464-11e7-8782-a2523d327fee.png)

**Comment by allanchao** [comment]
Seconding this bug, seems to be a very new bug. happening on 
OS: windows 8 
browser: 61.0.3163.100 (Official Build) (64-bit)

**Comment by fengyuanchen** [comment]
It seems to be a bug of the new Chrome browser.

**Comment by LonerKO** [comment]
Yep, It's chrome bug.

**Comment by mrbraca15** [comment]
same issue here, any suggestion?

**Comment by DenisKolpakov** [comment]
Have same issue. So, when I remove `background-color: #fff;` or `border: 1px solid rgba(0, 0, 0, .2);` or `border-radius: 6px;` from `.modal-content` style everythings become fine.

**Comment by DenisKolpakov** [comment]
On the other hand if I add `border-radius: 6px;` to `<div class="cropper-drag-box cropper-modal cropper-move"></div>` (as style) everything is getting right too.

**Comment by yimik** [comment]
@DenisKolpakov Thanks ,you are right. `border-radius`>0px could fix.

**Comment by tjamescouch** [comment]
This css rule seems to fix the issue without causing any visual changes:
div.cropper-drag-box.cropper-modal {
    opacity:1;
    background-color: rgba(0,0,0,0.5);
}

**Comment by yimik** [comment]
Chrome 62 has fixed the problem
