### ISSUE TITLE
Uploading cropped image

### ISSUE THREAD

**Issue by FlyingFlo86** [fengyuanchen/cropper#922]
Hi,
I want to upload a cropped image to the file server.
-----------------------
**1st trial:** 

- process.php contains code for uploading the image
- Problem: console says "Upload success", but process.php is not even executed, and I don't know why

        'croppedCanvas = $image.cropper('getCroppedCanvas', {
			width: 320,
			height: 320, 
		});
	
		
		croppedCanvas.toBlob(function (blob) {
				var form_data = new FormData();
  				form_data.append('croppedCanvas', blob);
			
				$.ajax('process.php', {
					type: "POST",
					data : form_data,
					contentType: false,
					cache: false,
					processData:false,
					mimeType:"multipart/form-data"
				}).done(function(res) {
					console.log('Upload success');
				});
			});'
---------------------
2nd trial:
- direct upload to the upload directory
- Problem: upload doesn't work

        'croppedCanvas = $image.cropper('getCroppedCanvas', {
			width: 320,
			height: 320, 
		});
	
		
		croppedCanvas.toBlob(function (blob) {
				var form_data = new FormData();
  				form_data.append('croppedCanvas', blob);
			
				$.ajax('\uploads', {
					type: "POST",
					data : form_data,
					contentType: false,
					cache: false,
					processData:false,
					mimeType:"multipart/form-data"
				}).done(function(res) {
					console.log('Upload success');
				});
			});'

**Comment by fengyuanchen** [comment]
1. Help yourself.
2. Ask help on search engine or StackOverflow.com
