### ISSUE TITLE
dragCrop: false is not works on latest version

### ISSUE THREAD

**Issue by LonerKO** [fengyuanchen/cropper#925]
$('.cropper-example-1 > img').cropper({
  aspectRatio: 16 / 9,
  autoCropArea: 0.65,
  strict: false,
  guides: false,
  highlight: false,
  dragCrop: false,
  cropBoxMovable: false,
  cropBoxResizable: false
});
version 1.0 - works perfect
latest version - not works. 
I can still create a new crop.

**Comment by fengyuanchen** [comment]
The old `dragCrop` option had renamed to `dragMode` as of [v2.0.0](https://github.com/fengyuanchen/cropper/releases/tag/v2.0.0).
