### ISSUE TITLE
Get cropped canvas problem with result of the picture size, 20% of last result is missing

### ISSUE THREAD

**Issue by dhanyn10** [fengyuanchen/cropper#930]
hello, i have problem when i trying getting result as image in canvas. here're the screenshot
![screenshot-2017-10-22 alpha cv 1](https://user-images.githubusercontent.com/11478316/31857435-ccce3fc2-b708-11e7-9482-869b00b5e9e6.png)
i'm use latest version of cropper
here're result so you can check it:
[jsbin](http://jsbin.com/nojoyalero/edit?output)

**Comment by fengyuanchen** [comment]
You just draw the output cropped canvas into a smaller canvas!
