### ISSUE TITLE
Set container data without destroying and reinitializing

### ISSUE THREAD

**Issue by kevingelion** [fengyuanchen/cropper#934]
Whenever rotating an image, this changes the container's size and ratio. When a user rotates an image, I'd like to have cropper re-calculate all of the values of the container on the new size.

My setup looks like this:  
```
<div style="height: 400px; width: 500px;">
    <img src="..." class="cropper"/>
</div>
```

When the image is rotated by 90 degrees:
```
<div style="height: 500px; width: 400px;">
    <img src="..." class="cropper"/>
</div>
```

I need to set the container and have all internal values respect the new height and width of my defined container without calling `destroy` and reinitializing. This causes a flash on the screen and seems unnecessary in terms of processing to do this.

**Comment by fengyuanchen** [comment]
After change the size of the container, you can trigger resize event on the window to force re-render the cropper:

```js
$(window).trigger('resize');
```
