### ISSUE TITLE
Problem with the cropper rotating.

### ISSUE THREAD

**Issue by web42** [fengyuanchen/cropper#938]
Hi!
There is a problem with the cropper rotating.
On DEMO page:
1 - press "rotate" button
2 - press GET DATA
3 - change the rotation from 45 "rotate":45 to "rotate":92
4 - press SET DATA

After that, the image you'll see, won't be full-sized.
![2017-11-17 14 59 18-fullpage](https://user-images.githubusercontent.com/20476741/32948489-0885129e-cba8-11e7-8795-539fbc7bfa1f.png)

**Comment by fengyuanchen** [comment]
Can't reproduce. What's your browser and version?

**Comment by web42** [comment]
firefox, chrome, opera... All latest versions. See the issue of "cropper JS" - https://github.com/fengyuanchen/cropperjs/issues/260
Im not alone with this problem))
