### ISSUE TITLE
Unable to control the max height of the container.

### ISSUE THREAD

**Issue by FritzTGreen** [fengyuanchen/cropper#940]
After two hours trying, I am unable to find a way to control the height or max height of a container.

![2017-12-06_1738](https://user-images.githubusercontent.com/7661816/33691150-70b45592-daac-11e7-92eb-1653c1bc25bf.png)

**Comment by ToDarkClown** [comment]
cropper only had minheight and minwidth,I can't find maxwidth and height too

**Comment by fengyuanchen** [comment]
Check out #833

**Comment by chungnd10** [comment]
I solved this problem by adding width and height to the img tag!
<img width="402" alt="Ảnh chụp Màn hình 2019-11-03 lúc 20 57 48" src="https://user-images.githubusercontent.com/51743940/68086281-b0f8b580-fe7c-11e9-90c4-12ce9edf1f91.png">
