### ISSUE TITLE
Problem with image size horizontal/vertial, error automatic scale container

### ISSUE THREAD

**Issue by quanghuygit** [fengyuanchen/cropper#941]
My config:
```
var configs = {
        viewMode: 1,
        movable: false,
        zoomable: false,
        rotatable: false,
        scalable: false,
}
```

I have input select file, but when i change file, the cropper re-render fail with nature size of image.
[Codepen](https://codepen.io/quanghuy1294/pen/RxbGGx)
![](http://i.imgur.com/HnLWudQ.png)
Why? and how to fix it.

**Comment by fengyuanchen** [comment]
```css
.modal-body img {
  width: 100%;
}
```

**Comment by quanghuygit** [comment]
ok thanks you so much

2017-12-11 21:12 GMT+07:00 Chen Fengyuan <notifications@github.com>:
