### ISSUE TITLE
Does not work with CSP img-src where data: sources are blocked

### ISSUE THREAD

**Issue by codemasterover9000** [fengyuanchen/cropper#943]
The problem occurs when selecting images with non default orientation (from camera for example). Cropper tries to rotate the image for viewing. Probably rendering the image to a rotated canvas and making an image from the canvas using a data: url. 

**To reproduce**
To reproduce open the following image https://github.com/recurser/exif-orientation-examples/blob/master/Portrait_7.jpg on the demo in the main page with CSP header as img-src 'self' blob:;

You can use this plugin for quick testing from the browser: https://chrome.google.com/webstore/detail/csp-tester/ehmipebdmhlmikaopdfoinmcjhhfadlf

**Possible solution**
Instead of producing an intermediate image, rendering the source (blob:) image directly rotated onto the target canvas would probably fix the problem. Basically setting the initial rotation config derived from the orientation meta data of the image.

**Comment by fengyuanchen** [comment]
You may need to set `checkOrientaion` option to `false`.

**Comment by codemasterover9000** [comment]
I know that is what I use now. But then the user needs to manually rotate. 

Seems like a simple and usefull fix. Just set the rotation config based on the orientation and its working and CSP approved. Which seems like a big+

**Comment by fengyuanchen** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-crossorigin

**Comment by codemasterover9000** [comment]
I dont get how this will solve anything? 

This problem is fixable for me by reading the orientation externally and setting rotation and scaling accordingly with checkOrientation set to false for cropper. Would be nice if cropper could do that though.

**Comment by fengyuanchen** [comment]
Can you just provide an online demo on CodePen? I think I don't really understand what you are meaning...

**Comment by codemasterover9000** [comment]
Hi. 

A codepen would also need the chrome plugin activated as described in my original post. It can be reproduced on the demo page also. See below

**To reproduce**
- Download and install csp tester plugin https://chrome.google.com/webstore/detail/csp-tester/ehmipebdmhlmikaopdfoinmcjhhfadlf
- Configure the csp tester plugin: Go to simple mode. Enter  "https://fengyuanchen.github.io/*" in the url box. Enter "'self' blob:" without the double quotes into the img-src box. Check the active checkbox.
- Go to the demo page https://fengyuanchen.github.io/cropperjs/
- Open image https://github.com/recurser/exif-orientation-examples/blob/master/Portrait_7.jpg (download first)

Now you will see a broken image icon instead of the image. This is because of the intermediate image that is created by doing orientation correction which results in a data:base64 image source.

**Comment by fengyuanchen** [comment]
Why not use `Content-Security-Policy: img-src data: blob: 'self'`?

**Comment by codemasterover9000** [comment]
Not possible for us. This might not be a common case though.

I solved it for our case by doing the rotation on the server side.
