### ISSUE TITLE
Do not permit crop-area enters at empty-canvas

### ISSUE THREAD

**Issue by priMo-ex3m** [fengyuanchen/cropper#944]
I've tried all options, events, methods, but I can't achieve my goal : So, user with cropped box to can't enter out of the image (to omit the possibility that user can cut the image a little bit crookedly, and saved image in .png will have empty spaces.
P.S. There is a way how to select saving format of file before upload it to the server?

**Comment by fengyuanchen** [comment]
`viewMode: 1`
