### ISSUE TITLE
Canvas height too long

### ISSUE THREAD

**Issue by priMo-ex3m** [fengyuanchen/cropper#946]
Hello, dude. First, thank you for a great lib.
I am using ur example with "Modal".
I did in the next order : I have a input type file, so when I upload a image, with some JS I display it like User Avatar. Next, user has a "Modal button from ur example". And when clicked on it, it opens the modal dialog with this image in canvas. The problem is in : When I upload a full hd photo, this canvas area became extra-long, and I can't fix it with either css rule.
It is possible to set a fixed, or maximum height/width for canvas area?

[Image](https://imgur.com/IlIHBU2)

**Comment by fengyuanchen** [comment]
#833
