### ISSUE TITLE
There is a way of saving image in specific sizes?

### ISSUE THREAD

**Issue by priMo-ex3m** [fengyuanchen/cropper#947]
Hello, dude! I know that question probably is more for back-end part, but may be you have implemented in your plugin smth that can solve it in front end : 
If user uploads a full hd image, I fixed the minimum width and height of crop-box as 200x200, and disabled resize of the box. I also set img#image as max-width: 100%; So, when I upload a photo full hd photo, it opens in a modal like thumbnail of 468x263. And with my "200x200 crop-box" after crop, uploaded image has size of 863x863px. Is there a way how can I trick it to achieve output as images of 200x200 px?
Thank you!

**Comment by fengyuanchen** [comment]
Please check out the docs of [`getCroppedCanvas`](https://github.com/fengyuanchen/cropper#getcroppedcanvasoptions) method.

In short:

```js
$().cropper('getCroppedCanvas', {
  width: 200,
  height: 200,
}); // Generate a image with 200 * 200 px
```

**Comment by priMo-ex3m** [comment]
It works. Thanks!
