### ISSUE TITLE
getCroppedCanvas returns incorrect results with rotated orientation on iOS with checkOrientation = false

### ISSUE THREAD

**Issue by codemasterover9000** [fengyuanchen/cropper#948]
Really like this cropper but cant seem to use it correctly in my use case (nog data: scheme based url's). In a previous issue #943 it was suggested to use checkOrientation = false. But this results in the issue as described below.

**Description**
Using checkOrientation = false results in a correctly rendered cropper and preview (using the preview option) but incorrect the result of getCroppedCanvas on iOS. The problem is that on iOS/Safari with an image that has a rotated orientation Safari automatically corrects the orientation in the img tag thus rendering the image in the correct orientation as intended by the user. But when the cropped image is rendered to a canvas using the API getCroppedCanvas() the internal canvas.drawImage() call does not auto correct the orientation and the resulting canvas contains an image based on the original unrotated image producing an incorrrect result.

**To reproduce**
This is reproducable in the demo on the main page using an iOS device an the camera in portrait mode.

Thanks

**Comment by fengyuanchen** [comment]
The `checkOrientation` should be set to `true` if you want to fix the cropping result in iOS!

**Comment by codemasterover9000** [comment]
Then should #943 be reopened?
