### ISSUE TITLE
cropper({ready : function}) not working?

### ISSUE THREAD

**Issue by DanielEberl** [fengyuanchen/cropper#952]
Hi, first of all, thank you so much for developing Cropper!
I tried various cropping/upload plugins, but this is the only one that works for me!

When i call 
`
$("#target").cropper('moveTo',0,0); `

from a button click or inside the 
`on('ready')` Event

The Canvas DOES move to the top-left corner.

But calling the 'moveTo' function from inside an Event-Handler of Cropper,
nothing actually happens.

Does someone have a solution for this?

I'm trying to keep the Image/Canvas always fixed to the top-left corner.

Any help is highly appreciated!

**Comment by fengyuanchen** [comment]
After try, it works as expected with the following code:

```js
$('#image').cropper({
  ready: function(event) {
    $(this).cropper('moveTo', 0, 0);
  }
});
```
