### ISSUE TITLE
Adapt cropper area/img container to mobile resolutions 

### ISSUE THREAD

**Issue by BugDroid-Duarte** [fengyuanchen/cropper#960]
Hello,

I sucessfully implement the cropper on my project but its not usable on mobile because the image is always bigger than the modal container (the cropper is inside a modal) andi cannot see all the image on mobile res.

I tried several combinations of max-widths, widths, on cantainers, on the img tag but cannot do it, i have set:

minContainerWidth: 568,
minContainerHeight: 320

If i remove it, it works but then its too small on mobile and super small on PC

Heres my setup:

reader.onloadend = function () {
                        $cropperModal.find('.image-container').html($img);
                        $img.attr('src', reader.result);
                        $img.cropper({
                            preview: '.image-preview',
                            aspectRatio: 16 / 11,
                            autoCropArea: 1,
                            movable: false,
                            cropBoxResizable: true,
                            minContainerWidth: 568,
                            minContainerHeight: 320
                        });
                    };

MODAL:

 var modalTemplate = '' +
        '<div class="modal fade" tabindex="-1" role="dialog" style="z-index: 99999;">' +
        '<div class="modal-dialog" role="document">' +
        '<div class="modal-content-recorte widthimage">' +
        '<div class="modal-header">' +
        '<h4 class="popup_title"> @lang('popups.crop_img') </h4>' +
        '<p class="popupcontent"> @lang('popups.crop_img_desc') </p>' +
        '</div>' +
        '<div class="modal-body">' +
        '<div class="image-container""> </div>' +
        '</div>' +
        '<div class="modal-footer" style="text-align:center">' +
        '<button type="button" class="btn btn-primary crop-upload">Upload</button>' +
        '</div>' +
        '</div>' +
        '</div>' +
        '</div>' +
        '';

i want to set like a max size, and that the cropper stuff adapts to the screen, sorry to ask here but i am trying for hours and still couldnt do it.

Thanks

**Comment by fengyuanchen** [comment]
You need a responsive container: https://github.com/fengyuanchen/cropper/blob/master/examples/responsive-container.html
