### ISSUE TITLE
Issue with crop destroy

### ISSUE THREAD

**Issue by tunglt** [fengyuanchen/cropper#962]
Sorry for my bad english
Please take a look at my site:
http://test.brite.vn/cropbug/
- with normal internet speed everything works perfectly fine.
But I test with slow internet speed and it have bug like this image below
https://imgur.com/Nk3iADY
I think that
`cropper('destroy');` 
not working in this situation.
Please see the video 
https://youtu.be/c2rh8cQwXkQ
I'm using Windows 10, chrome 64.0.3282.140 (64bit).

**Comment by fengyuanchen** [comment]
Please upgrade to v4.0.0 and try again or try to use the [`jquery-cropper`](https://github.com/fengyuanchen/jquery-cropper).
