### ISSUE TITLE
is this support php 7.0 or not

### ISSUE THREAD

**Issue by infuginindia** [fengyuanchen/cropper#963]
Hello Author,

Do this php script support PHP 7.0 or not.

Regards
Infugin

**Comment by jonasva** [comment]
It's a javascript cropper library which runs on the client (browser). The result can be uploaded to any type of back end afterwards.

**Comment by infuginindia** [comment]
in examples folder there is a folder crop-avatar which contain crop.php file, i have implemented this on php version 5.5 but on above version its not working

**Comment by jonasva** [comment]
What error are you getting?

**Comment by infuginindia** [comment]
i am getting no error as php is called in another file

**Comment by jonasva** [comment]
You don't have an nginx/apache error log?

**Comment by amandeep1995** [comment]
This is the php code i have changed , its working on php 5.5 but on above version its not working 
<?php include "include/header.php"; ?>
<?php
class CropAvatar {
  private $src;
  private $data;
  private $dst;
  private $type;
  private $extension;
  private $msg;

  function __construct($src, $data, $file) {
    $this -> setSrc($src);
    $this -> setData($data);
   // $this -> setFile($file);
    $this -> crop($this -> src, $this -> dst, $this -> data);
  }
  private function setSrc($src)
  {
    if(empty($src)) 
    {
    $file_name = $_FILES['avatar_file']['name'];
    $file_temp =$_FILES['avatar_file']['tmp_name'];
    $file_type=$_FILES['avatar_file']['type'];
    $img = explode(".",$file_name );
    $imgname=$img[0];
    $imgtype=$img[1];  
    if ($file_temp)
      {
       $image_type_to_mime_type= $img[1];
       $type=$image_type_to_mime_type;
      $src = '../uploads/sitelogos/' . date('YmdHis') . '_original' . '.'. $image_type_to_mime_type; 
      if ($image_type_to_mime_type == "png" || $image_type_to_mime_type == "jpg" || $image_type_to_mime_type == "jpeg") 
      {
        if (file_exists($src)) {
          unlink($src);
        }

        $result = move_uploaded_file($file_temp, $src);
        if ($result) {
          $this -> src = $src;
          $this -> type = $type;
          $this -> extension = image_type_to_extension($type);
          $this -> setDst();
        } else {
           $this -> msg = 'Failed to save file';
          }
      } 
      else 
      {
        $this -> msg = 'Please upload image with the following types: JPG, PNG, GIF';
      }

      }
     
    }
    else
    {
      print "File not uploaded succesfully!";
      exit;
    }
  }
  private function setData($data) {
    if (!empty($data)) {
      $this -> data = json_decode(stripslashes($data));
    }
  }

  private function setDst() {
   $new= $this -> dst = '../uploads/sitelogos/' . date('YmdHis') . '.png';
   $profile_pic=substr($new,21);
            $insert_load_step = array(
                        "site_logo" => $profile_pic
                        );
            $insert6 = dbRowUpdate("sites_tbl", $insert_load_step, "site_id = '".$_SESSION['siteid']."' " );
  }

  private function crop($src, $dst, $data) {
    if (!empty($src) && !empty($dst) && !empty($data)) {
      switch ($this -> type) {
        case png:
          $src_img = imagecreatefrompng($src);
          break;

        case jpg:
          $src_img = imagecreatefromjpeg($src);
          break;

        case jpeg:
          $src_img = imagecreatefromjpeg($src);
          break;
      }

      if (!$src_img) {
        $this -> msg = "Failed to read the image file";
        return;
      }

      $size = getimagesize($src);
      $size_w = $size[0]; // natural width
      $size_h = $size[1]; // natural height

      $src_img_w = $size_w;
      $src_img_h = $size_h;

      $degrees = $data -> rotate;

      // Rotate the source image
      if (is_numeric($degrees) && $degrees != 0) {
        // PHP's degrees is opposite to CSS's degrees
        $new_img = imagerotate( $src_img, -$degrees, imagecolorallocatealpha($src_img, 0, 0, 0, 127) );

        imagedestroy($src_img);
        $src_img = $new_img;

        $deg = abs($degrees) % 180;
        $arc = ($deg > 90 ? (180 - $deg) : $deg) * M_PI / 180;

        $src_img_w = $size_w * cos($arc) + $size_h * sin($arc);
        $src_img_h = $size_w * sin($arc) + $size_h * cos($arc);

        // Fix rotated image miss 1px issue when degrees < 0
        $src_img_w -= 1;
        $src_img_h -= 1;
      }

      $tmp_img_w = $data -> width;
      $tmp_img_h = $data -> height;
      $dst_img_w = 220;
      $dst_img_h = 220;

      $src_x = $data -> x;
      $src_y = $data -> y;

      if ($src_x <= -$tmp_img_w || $src_x > $src_img_w) {
        $src_x = $src_w = $dst_x = $dst_w = 0;
      } else if ($src_x <= 0) {
        $dst_x = -$src_x;
        $src_x = 0;
        $src_w = $dst_w = min($src_img_w, $tmp_img_w + $src_x);
      } else if ($src_x <= $src_img_w) {
        $dst_x = 0;
        $src_w = $dst_w = min($tmp_img_w, $src_img_w - $src_x);
      }

      if ($src_w <= 0 || $src_y <= -$tmp_img_h || $src_y > $src_img_h) {
        $src_y = $src_h = $dst_y = $dst_h = 0;
      } else if ($src_y <= 0) {
        $dst_y = -$src_y;
        $src_y = 0;
        $src_h = $dst_h = min($src_img_h, $tmp_img_h + $src_y);
      } else if ($src_y <= $src_img_h) {
        $dst_y = 0;
        $src_h = $dst_h = min($tmp_img_h, $src_img_h - $src_y);
      }

      // Scale to destination position and size
      $ratio = $tmp_img_w / $dst_img_w;
      $dst_x /= $ratio;
      $dst_y /= $ratio;
      $dst_w /= $ratio;
      $dst_h /= $ratio;

      $dst_img = imagecreatetruecolor($dst_img_w, $dst_img_h);

      // Add transparent background to destination image
      imagefill($dst_img, 0, 0, imagecolorallocatealpha($dst_img, 0, 0, 0, 127));
      imagesavealpha($dst_img, true);

      $result = imagecopyresampled($dst_img, $src_img, $dst_x, $dst_y, $src_x, $src_y, $dst_w, $dst_h, $src_w, $src_h);

      if ($result) {
        if (!imagepng($dst_img, $dst)) {
          $this -> msg = "Failed to save the cropped image file";
        }
      } else {
        $this -> msg = "Failed to crop the image file";
      }

      imagedestroy($src_img);
      imagedestroy($dst_img);
    }
  }

  private function codeToMessage($code) {
    $errors = array(
      UPLOAD_ERR_INI_SIZE =>'The uploaded file exceeds the upload_max_filesize directive in php.ini',
      UPLOAD_ERR_FORM_SIZE =>'The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form',
      UPLOAD_ERR_PARTIAL =>'The uploaded file was only partially uploaded',
      UPLOAD_ERR_NO_FILE =>'No file was uploaded',
      UPLOAD_ERR_NO_TMP_DIR =>'Missing a temporary folder',
      UPLOAD_ERR_CANT_WRITE =>'Failed to write file to disk',
      UPLOAD_ERR_EXTENSION =>'File upload stopped by extension',
    );

    if (array_key_exists($code, $errors)) {
      return $errors[$code];
    }

    return 'Unknown upload error';
  }

  public function getResult() {
    return !empty($this -> data) ? $this -> dst : $this -> src;
  }

  public function getMsg() {
    return $this -> msg;
  }
}

$crop = new CropAvatar(
  isset($_POST['avatar_src']) ? $_POST['avatar_src'] : null,
  isset($_POST['avatar_data']) ? $_POST['avatar_data'] : null,
  isset($_FILES['avatar_file']) ? $_FILES['avatar_file'] : null
);

$response = array(
  'state'  => 200,
  'message' => $crop -> getMsg(),
  'result' => $crop -> getResult()
);

echo json_encode($response);

**Comment by infuginindia** [comment]
This is the php code i have changed , its working on php 5.5 but on above version its not working 
[crop.zip](https://github.com/fengyuanchen/cropper/files/1689199/crop.zip)

**Comment by fengyuanchen** [comment]
The Crop Avatar example was built in PHP 5.5, I don't know if it works fine in PHP. Just debug it by yourself.
