### ISSUE TITLE
Image colors change in cropper window

### ISSUE THREAD

**Issue by jonasva** [fengyuanchen/cropper#964]
When viewing an image in cropper, I've noticed the colors are a bit different from the original. 

See image below of the difference (left is the original, right is cropperJS):
<img width="969" alt="screen shot 2018-02-02 at 15 51 19" src="https://user-images.githubusercontent.com/8156732/35722551-c01fe724-0831-11e8-8b5d-7cbbedd4ed27.png">

After saving and uploading to the server, the color difference is also there (left original, right manipulated with cropperJS):
![screen shot 2018-02-02 at 16 05 25](https://user-images.githubusercontent.com/8156732/35722850-efc73152-0832-11e8-93a2-4a8f6f6e510b.png)

My HTML:

```
<div class="js-cropper-wrapper cropper__wrap">
    <img class="js-image-preview cropper__img" src="/images/huge-2.jpg">
</div>
```
JS:

`$('.js-image-preview').cropper();`

Cropper version: cropper@3.1.4
Browser: Chrome 63
OS: OSX 10.13

[Source image file](https://we.tl/WUy2yjFEAT)

**Comment by fengyuanchen** [comment]
You are viewing the image in two different applications which have different image rendering engines. 
Just open your original image in chrome tab to compare!!!

**Comment by jonasva** [comment]
Yeah I kinda figured you would say something like that. That's why I included the second image as well (both in the same application)

**Comment by fengyuanchen** [comment]
I mean the browser will change the color. Open your original image in a browser tab and compare to cropping image.

**Comment by jonasva** [comment]
Oh I see what you mean. Ok, thx for elaborating.
