### ISSUE TITLE
Recreate Image cropped Images on editing.

### ISSUE THREAD

**Issue by mustanish** [fengyuanchen/cropper#965]
First of all thankyou for this plugin.I am trying to make an online image editor using this plugin, but I am stuck at one point.This application has functionality of re-edit, but How do I recreate the last edited version of image using this plugin.

**Comment by fengyuanchen** [comment]
You should save both the canvas data and crop box data for restore, here is a similar example:
https://github.com/fengyuanchen/cropper/blob/master/examples/cropper-in-modal.html
