### ISSUE TITLE
Issue with maxWidth and maxHeight on getCroppedCanvas

### ISSUE THREAD

**Issue by BGitlin337** [fengyuanchen/cropper#966]
Hey Fengyuanchen,
I am having issues with maxWidth and maxHeight. The cropper works totally fine with width and height set, but if I want to include max width and height, the image renders mostly black
![image](https://user-images.githubusercontent.com/6411276/35893537-8434b23c-0b7c-11e8-87ff-b678d9c05861.png)

Then, without maxWidth and maxHeight:

![image](https://user-images.githubusercontent.com/6411276/35893596-c4687122-0b7c-11e8-8b64-593ab734e2fc.png)

**Comment by fengyuanchen** [comment]
This is a bug and will be fixed in next version.

**Comment by fengyuanchen** [comment]
The same as #953.

**Comment by BGitlin337** [comment]
Hey thanks for the quick response. Any idea on time frame for that release?

**Comment by BGitlin337** [comment]
@fengyuanchen I've been working with the updated version and am still having issues. It seems like this update only fixes the issue with landscape images. If I add the maxWidth and maxHeight attributes and then crop a landscape image above the max width and height, I again get a distorted crop with black bars on the sides. If I rotate the image to be oriented as landscape, it works perfectly.
