### ISSUE TITLE
Cropped image is shifted related to the selection

### ISSUE THREAD

**Issue by lexiv0re** [fengyuanchen/cropper#969]
Hi @fengyuanchen! First of all, thanks for the cropper.

- Operating system and version: macOS Sierra v10.12.6
- Browser and version: Chrome 63.0, Firefox 58.0.1

Was testing in https://fengyuanchen.github.io/photo-editor/:
Selecting
![selection](https://user-images.githubusercontent.com/20221821/36087597-cd63cfe6-1005-11e8-85e5-2cb37622e56e.png)
results in
![result](https://user-images.githubusercontent.com/20221821/36087601-d3a786f4-1005-11e8-919e-7b7b9d111e3a.png)
which is cut on the right and bottom sides.

The cropped area is very small (about 16x16px) so probably it's a rounding issue?

Source image:
![shifts](https://user-images.githubusercontent.com/20221821/36087683-38d1f41a-1006-11e8-9693-f59ed5a97f98.png)

**Comment by fengyuanchen** [comment]
All decimals will be ignored (floored) when apply to canvas element to crop. It is the default behaviour of canvas element.

**Comment by lexiv0re** [comment]
Are there any good known workarounds for this? Maybe there is a way to apply some restrictions to crop area to prevent this?

**Comment by fengyuanchen** [comment]
Maybe send both the data and image to server to crop it.

**Comment by lexiv0re** [comment]
Yes, that's an option.
Is it possible to show `preview` container (not the crop area) with the rounding already applied? If not, do you have an idea if it will be hard to apply such an enhancement?

**Comment by fengyuanchen** [comment]
You can fork one and try to round all size related values for your expectation if you have interest.
