### ISSUE TITLE
裁剪参数和七牛图片高级处理参数的映射关系

### ISSUE THREAD

**Issue by lanhouzi** [fengyuanchen/cropper#974]
作者能提供一份cropper裁剪参数和七牛图片高级处理参数的映射关系表么

[七牛-图片高级处理](https://developer.qiniu.com/dora/manual/1270/the-advanced-treatment-of-images-imagemogr2)

**Comment by fengyuanchen** [comment]
两者并无关系，何来映射关系？

**Comment by lanhouzi** [comment]
因为七牛中存的图片比较大（一般都在10M以上），
为了节省流量，通过七牛取到瘦身后的图片（几百K左右），
再通过Cropper处理得到需要的裁剪图片，
然后把Cropper裁剪参数通过映射处理之后传给七牛（不用把裁减后的原图在上传至七牛），
七牛再处理原图，这样就可以节省相当可观的流量，以及加快批量处理的速度

---

## 可付费
