### ISSUE TITLE
GIF Image's only first frame is stored

### ISSUE THREAD

**Issue by girishsalaskar** [fengyuanchen/cropper#978]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Steps:
1. Upload GIF
2. Rotate GIF to left/right
3. Export rotated GIF

Result:
As original GIF shows all frames, new GIF does not display all frames

## Expected behavior

After rotating, the new GIF should display all frames with rotation effect.

## Environment

<pre><code>
Cropper version: v3.0.0-rc.3

Browser: All browsers supporting cropper plugin

</code></pre>

**Comment by fengyuanchen** [comment]
The `getCroppedCanvas` method use the `canvas.drawImage` API to crop image in browser, `canvas.drawImage` only draw the first frame image into a canvas. So you may have to upload the GIF image to server and crop it by yourself.

In short, Cropper does not support this.

**Comment by girishsalaskar** [comment]
Thanks for the description :+1:
