### ISSUE TITLE
blob is not defined error

### ISSUE THREAD

**Issue by joeljfernandes** [fengyuanchen/cropper#979]
Dear Fengyuanchen,
I have checked in the console the value blob is not defined.Moreover reader.onloadend is not called..So I am not able to get the cropped image in base64.Please help me.Below is the code I used to create cropping canvas and save image.

<pre><code>
import Cropper from 'cropperjs'

ionViewDidLoad() {
    console.log('ionViewDidLoad Crop');
    var image = document.getElementById('image');
    this.cropper = new Cropper(image, {
      aspectRatio: 1 / 1
    });

  }

savePicture() {

    this.cropper.getCroppedCanvas().toBlob((blob) => {
     console.log('blob'+blob); //blob is undefined
      var reader = new FileReader();
      reader.readAsDataURL(blob);
   
      reader.onloadend = () => {
//moreover this function is not called
        let base64data = reader.result;
 console.log('data'+base64data);

        var base64result = base64data.split(',')[1];

        this.viewCtrl.dismiss({
          croppedImage: base64result
        });
        
      }

    });
  }
</code></pre>

## Current behavior

When I click the save button after selecting area to be cropped I call savePicture().

## Expected behavior

I am expecting blob variable to be defined .

I have used cropper * Cropper.js v1.0.0-rc.3

**Comment by fengyuanchen** [comment]
What is your browser and version?

**Comment by xiefangzhenz** [comment]
I solved it by change method.

var canvas = $('#photo').cropper('getCroppedCanvas',{width:145, height:185})
//如果太大可以换成jpeg
var dataURL=canvas.toDataURL('image/png');
var blob = dataURLtoBlob(dataURL);

**Comment by joeljfernandes** [comment]
In my app $('#photo').cropper('getCroppedCanvas',{width:145, height:185}) not working since I am not using jquery

Moreover this.cropper.getCroppedCanvas() reverts {}  when I try to 
alert JSON.stringify(this.cropper.getCroppedCanvas())

I am using the cropper in an ionic 3 app 
As far as I know the app uses the native browser on the device.

The Cropping function is working sometimes and sometimes it does not work.Please advice me an alternative way to get the cropped Canvas.Thanks

**Comment by fengyuanchen** [comment]
1.  Check if your browser support [canvas.toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob#Browser_compatibility).
2. Polyfill for canvas.toBlob: https://github.com/blueimp/JavaScript-Canvas-to-Blob

PS: The `getCroppedCanvas` will return a `<canvas>` element.
