### ISSUE TITLE
On cropping of second Image it is always showing at the first place 

### ISSUE THREAD

**Issue by atishay-khare** [fengyuanchen/cropper#981]
## I'm submitting a...

<pre><code>
 <div class="container">
    <h1>Upload cropped image to server</h1>
    <label class="label" data-toggle="tooltip" title="Change your avatar">
      <img class="rounded" id="showbox" src="https://avatars0.githubusercontent.com/u/3456749?s=160" alt="showbox">
      <input type="file" class="sr-only" id="des" name="image" onclick="crop('des','showbox');" accept="image/*">
    </label>
    <label class="label" data-toggle="tooltip" title="Change your avatar">
      <img class="rounded" id="showboxa" src="https://avatars0.githubusercontent.com/u/3456749?s=160" alt="showboxa">
      <input type="file" class="sr-only" id="dess" name="image" onclick="crop('dess','showboxa')" accept="image/*">
    </label>
   
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="modalLabel">Crop the image</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="img-container">
              <img id="image" src="https://avatars0.githubusercontent.com/u/3456749">
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="button" class="btn btn-primary" id="crop">Crop</button>
          </div>
        </div>
      </div>
    </div>
  </div>
 <script>
   function crop(res , pict) {
      var avatar = document.getElementById(pict);
      var image = document.getElementById('image');
      var input = document.getElementById(res);
     var $modal = $('#modal');
      var cropper;
      $('[data-toggle="tooltip"]').tooltip();
      input.addEventListener('change', function (e) {
        var files = e.target.files;
        var done = function (url) {
          input.value = '';
          image.src = url;
          $modal.modal('show');
        };
        var reader;
        var file;
        var url;
        if (files && files.length > 0) {
          file = files[0];
          if (URL) {
            done(URL.createObjectURL(file));
          } else if (FileReader) {
            reader = new FileReader();
            reader.onload = function (e) {
              done(reader.result);
            };
            reader.readAsDataURL(file);
          }
        }
      });
      $modal.on('shown.bs.modal', function () {
        cropper = new Cropper(image, {
          aspectRatio: 1,
          viewMode: 3,
        });
      }).on('hidden.bs.modal', function () {
        cropper.destroy();
        cropper = null;
      });
      document.getElementById('crop').addEventListener('click', function () {
        var initialAvatarURL;
        var canvas;
        $modal.modal('hide');
        if (cropper) {
          canvas = cropper.getCroppedCanvas({
            width: 160,
            height: 160,
          });
          initialAvatarURL = avatar.src;
          avatar.src = canvas.toDataURL();
          canvas.toBlob(function (blob) {
            var formData = new FormData();
            formData.append('avatar', blob); 
          });
        }
      });
    };
  </script>
</code></pre>

## Current behavior

i am trying to show two images on the same page after cropping but both the images are showing at only first div and a error is also generated in console that the canvas is Null

## Expected behavior

second image to be shown in the second div

**Comment by fengyuanchen** [comment]
Just check it in your own code.
