### ISSUE TITLE
MaxWidth and MaxHeight issue with portrait images

### ISSUE THREAD

**Issue by BGitlin337** [fengyuanchen/cropper#984]
I've been working with build release 4.0.0-beta and am having issues using maxWidth and maxHeight. It seems like this update fixes the functionality of this feature but only with landscape images. If I add the maxWidth and maxHeight attributes and then crop a portrait image above the max width or height, I get a distorted crop with black bars on the sides. If I rotate the image to be oriented as landscape, it works perfectly. This is an extension of issue #966 that I previously reported.

**Comment by fengyuanchen** [comment]
Try the [`jquery-cropper`](https://github.com/fengyuanchen/jquery-cropper) package please.
