### ISSUE TITLE
Remove Extra Background

### ISSUE THREAD

**Issue by mzubairharoon** [fengyuanchen/cropper#987]
Hi, this is a great tool for cropping, I'm using it in Vue there is a small problem or I am missing something in it, when I use it, it displays a lot of extra backgrounds which I can't remove as it is set by the container.

https://www.screencast.com/t/dUi4GekOr

<pre><code>
 let cropper = new Cropper(this.$refs.editImage, {
            //aspectRatio: 16 / 9,
            //autoCropArea: 1,
            background: false,
            viewMode: 1
          })
          this.cropper = cropper
        })
</code></pre>

Can you please tell me what I'm missing?

Thank you

**Comment by fengyuanchen** [comment]
Place you image correctly first before start a cropper on it.

In short, limit the max width of the image,:

```css
img {
  max-width: 100%;
}
```
