### ISSUE TITLE
setCropBoxData not working

### ISSUE THREAD

**Issue by julian0852** [fengyuanchen/cropper#990]
I cannot get setCropBoxData to work, even on the demo page
https://fengyuanchen.github.io/cropper/
Clicking on "Get Crop Box Data" shows the data. Then I change the width and height, Then Click "Set Crop Box Data"
It seems the width figure is accepted but the height figure is ignored - the crop box is always shown in landscape mode? How can I set this to portrait mode?

**Comment by jcmckay** [comment]
Do you need to use setCropBoxData?  I had inconsistent results with that.  Instead I used .setData().

**Comment by jcmckay** [comment]
Sorry I think I see the issue, did you select 'Free' for the ratio?
![image](https://user-images.githubusercontent.com/1891757/40446243-6a2ef4a6-5e83-11e8-9031-71e7d75948d1.png)

**Comment by julian0852** [comment]
Thank you, I'll try this when im back in my office

**Comment by lrh454830526** [comment]
i have met the seem probleam,and I choose the ratio 'free' ,both of 'setCropBoxData' and 'setData' dont work

**Comment by lrh454830526** [comment]
ok! I hava realized my fault！the parameter "width" and "height" must be float type ,so, I just convert my width and height parameter to float ,and the code worked.  

ps: parseFloat(width); parseFloat(height);

**Comment by nelsonblaha** [comment]
I'm getting the same width-only behavior with both `setData` and `setCropBoxData`, using `parseFloat` or `parseInt`, using `aspectRatio: 'free'`

**Comment by fengyuanchen** [comment]
If you set the `aspectRatio` option to a positive number, then call the `setCropBoxData` method, you only need to provide a `width` or `height` value (the other value will be computed by the `aspectRatio` automatically).
