### ISSUE TITLE
Regarding mincropboxwidth

### ISSUE THREAD

**Issue by developerrito** [fengyuanchen/cropper#992]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Cropper version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by developerrito** [comment]
I have a requirement where i want to restrict the min image size to be 600x600 px. After research I found out that so many people are asking for this support. May be its time you should consider giving this. 

I had to use some rcrop(which is not as good as this one) instead of this one because of this issue.

**Comment by fengyuanchen** [comment]
You can control it with `zoom` event (`event.preventDefault()`).
