### ISSUE TITLE
Cross-origin image can not to be loaded

### ISSUE THREAD

**Issue by Viioir** [fengyuanchen/cropper#994]
These are some cross-origin images can't be loaded. The request status is canceled in Chrome. Below is a case:

`<div class="crop-container">`
`<img id="crop-image" src="https://prodcmscdn.azureedge.net/careerconnectresources/p/MICRUS/en_us/desktop/assets/images/home_talent_community_full_width_office.jpg" />`
`</div>`

**Comment by Viioir** [comment]
I tried this image with cropperjs, another issue occured. The image was displayed, but the div.cropper-container was not created.

**Comment by fengyuanchen** [comment]
You should set a `crossorigin` attribute to the image element, here is an example:

> https://github.com/fengyuanchen/cropperjs/blob/master/examples/crop-cross-origin-image.html

**Comment by Viioir** [comment]
Thank you. I got it. That image server doesn't present response header with Access-Control-Allow-Origin: *.
