### ISSUE TITLE
images disappear when refresh the page

### ISSUE THREAD

**Issue by imedev2** [fengyuanchen/cropper#995]
## Current behavior

hi
i'm using cropper in laravel, every things is perfect and i want to store the image in database and that working perfectly. 
my problem is that i want to show all the cropped images from database but when i refresh the page, all images disappear with get error in console.

## Expected behavior

page should include all cropped images from database

Browser:
- [ ] Chrome (desktop) version XX

**Comment by fengyuanchen** [comment]
I think this is not an issue about Cropper.js itself.
