### ISSUE TITLE
How to add white background and paste only the cropped part on top of that ?

### ISSUE THREAD

**Issue by vikaschauhan17** [fengyuanchen/cropper#997]
Hi,

Suppose I have a input image of width=500px ,height=500px and I want to crop a portion where width is 200px , height is 200px. 
Now after crop I am getting the output document of height 200px and width 200px. 
Is it possible to get the cropped document size same as of that of original document size, which is, 500X500  with cropped content on 200X200 area and rest should be white background. ? That way cropped output document will not be stretched. 

Any pointer will be of great help.

**Comment by vikaschauhan17** [comment]
I have images with white background and I want cropped document also to have the white background and should have size equal to that of original document.

**Comment by fengyuanchen** [comment]
After get the cropped image with size of 200x200px from Cropper, just draw it into the center of a new `<canvas>` element with the size of 500x500px.

**Comment by vikaschauhan17** [comment]
Thank you for the response. May I know how to do this- "just draw it into the center of a new <canvas> element with the size of 500x500px." What is the syntax for the same ? Sudo code will work.

Thanks

**Comment by fengyuanchen** [comment]
```js
const cropper = new Cropper(targetImage, {
  ready() {
    const croppedCanvas = cropper.getCroppedCanvas();
    const canvas = document.createElement('canvas');
    const context = canvas.getContext('2d');

    canvas.width = 500;
    canvas.height = 500;
    context.fillStyle = 'white';
    context.drawImage(croppedCanvas, 125, 125);
    canvas.toDataURL();
  },
});
```

> https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

**Comment by vikaschauhan17** [comment]
fengyuanchen : I have invested lot of time in this project and now this is the only issue left. If this doesn't work out my project will not be accepted. I request you to please have a look at my code and let me know what I am doing wrong. Thanks :)

**Comment by vikaschauhan17** [comment]
Hey, could you please let me know what am I missing here. ?

**Comment by vikaschauhan17** [comment]
I have tried this as well, But it is not working. Could you please tell me what I am missing here. ?

var cropcanvas = $('#'+imageName).cropper('getCroppedCanvas');
                    var croppng = cropcanvas.toDataURL("image/png");
                    const canvas = document.createElement('canvas');
                    const context = canvas.getContext('2d');
                    canvas.width = 1000;
                    canvas.height = 1000;
                    var image = new Image();
                    image.onload = function() {
                        context.fillStyle = 'white';
                        context.drawImage(image, 200, 200);
                    };
                    image.src = croppng;
                    payload.croppedImg = image.src;
