### ISSUE TITLE
setCropBox depends on the width of the container.

### ISSUE THREAD

**Issue by fabianrios** [fengyuanchen/cropper#998]
<pre><code>
[x] Bug report 
[x] Feature request
</code></pre>

## Current behavior

If I try to resize an image inside a small container adjusting the setCropBoxData to a size that it´s bigger than the container itself it will not do it, it will stop in the maxim width of the container

<code>
built: function () {
    var w = "a value bigger than the container width"
    var h = "a value bigger than the container height"
    let to_this = {width:w,height:h};
    $(this).cropper('setCropBoxData', to_this);
  },
</code>
## Expected behavior

the image would scale and the cropbox itself too to allowing this to happen

## Minimal reproduction of the problem with instructions

here I show the problem
https://codepen.io/anon/pen/djprKo

## What is the motivation / use case for changing the behavior?

 to allow to setCropBox at any size that fits the image independently of the container
## Environment

<pre><code>
Cropper version: 2.3.4

Browser:
- [X] Firefox version 60
- [X] Chrome
</code></pre>

**Comment by fengyuanchen** [comment]
Not support that.
